### DISCUSSION TITLE
Prisma client not generated on serverless webpack - edit: solved

### DISCUSSION THREAD

**Discussion by afcode123** [prisma/prisma#10278] [Q&A]
Hi!

EDIT: solved, answer below

My api suddenly stopped generating prisma client when deploying to aws with serverless-webpack, even though it has worked previously.  I am getting error "@prisma/client did not initialize yet. Please run "prisma generate" in lambda but not when running the api in serverless offline. If I understood correctly from prisma documentation, the client is generated whenever @prisma/client is installed. Webpack includes this package correctly but it does not create the prisma client. I tried with versions 2.3.0 (previously it worked with this one) and 3.4.2
Glad if someone could take a look if I am missing something.

I have the following configs: 

webpack.config.js and serverless.yml
```js
const nodeExternals = require("webpack-node-externals");
const serverlessWebpack = require("serverless-webpack");

module.exports = {
  devtool: "inline-cheap-module-source-map",
  entry: serverlessWebpack.lib.entries,
  mode: serverlessWebpack.lib.webpack.isLocal ? "development" : "production",
  module: {
    rules: [
      {
        exclude: /node_modules/,
        test: /\.ts$/,
        use: "ts-loader",
      },
    ],
  },
  experiments: {
    topLevelAwait: true,
  },
  node: false,
  externals: [nodeExternals()],
  optimization: {
    minimize: false,
  },
  resolve: {
    extensions: [".ts", ".js"],
  },
  target: "node",
};
```
```yml
service: <api>
provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  lambdaHashingVersion: 20201221
useDotenv: true
functions:
  graphql:
    handler: src/apollo-server.graphqlHandler
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get
          cors: true

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-dotenv-plugin
custom:
  webpack:
    includeModules: true
    
    
```
sls deploy --stage dev
  ```
  asset src/apollo-server.js 206 KiB [emitted] (name: src/apollo-server)
orphan modules 85.5 KiB [orphan] 45 modules
runtime modules 937 bytes 4 modules
built modules 86 KiB [built]
  ./src/apollo-server.ts + 45 modules 85.9 KiB [not cacheable] [built] [code generated]
  external "fs" 42 bytes [built] [code generated]
  external "util" 42 bytes [built] [code generated]
webpack compiled successfully in 4771 ms
Serverless: WARNING: Could not determine version of module jsonwebtoken
Serverless: Package lock found - Using locked versions
Serverless: Packing external modules: reflect-metadata@^0.1.13, apollo-server-lambda@^3.3.0, graphql@^15.5.3, type-graphql@^1.1.1, class-validator@^0.13.1, jsonwebtoken, jwks-rsa@^2.0.5, @prisma/client@^2.30.0, graphql-fields@^2.0.3, dayjs@^1.10.7, axios@^0.21.4
Serverless: WARNING: Could not determine version of module jsonwebtoken
Serverless: Copying existing artifacts...
Serverless: Packaging service...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service <api> file to S3 (47.33 MB)...
Serverless: Validating template...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
Serverless: Stack update finished...
Service Information
```

**If anyone ends up with the same issue, here is how it can be solved.** 
1. npm install copy-webpack-plugin
2. Add following line to your webpack.config.js (notice that the filepath must point to your prisma schema): 
```js  
plugins: [new CopyWebpackPlugin({ patterns: ["./prisma/schema.prisma"] })]
```
3. Edit your serverless.yml with following: 
```
custom:
  webpack:
    includeModules: true
    packagerOptions:
      scripts:
        - prisma generate
```
4. For some previous steps might do the trick, but in my case I ended up with a serverless package with a size of 130MB, this of course is too large to be deployed and serverless throws an error " Unzipped size must be smaller than 262144000 bytes." You can fix this by adding following lines after the prisma generate: 

```
custom:
  webpack:
    includeModules: true
    packagerOptions:
      scripts:
        - prisma generate
        - rm -R node_modules/@prisma/engines
        - rm -R node_modules/@prisma/engines-version
        - rm node_modules/prisma/libquery_engine-darwin.dylib.node
        - rm -R node_modules/prisma/engines
```
        
Removing unneeded prisma engines etc of course depends which one you need in your production  package. In my case those were not needed since I was running with serverless AWS lambda. Also depending on which prisma version you are using, those rm commands can make the serverless deploy command fail if the files are not found in nodemodules. In that case you should check your zip package and see where the unneeded files are located and which can be removed and then update the rm commands accordingly.
For example in my case package size dropped from 130MB to 59MB.
