### DISCUSSION TITLE
Undefined models after running a migration using Docker

### DISCUSSION THREAD

**Discussion by uncvrd** [prisma/prisma#10280] [Q&A] [answered]
Hi! I have been using Prisma for a while, and just moved to containerizing my dev environment. I've run in to an issue when I try and add / update a model in my schema, and I think it has to do with how files are copied from my local environment to my container (since `.prisma` is found in `node_modules`). I was wondering what the best way would be to re-generate my Prisma models so that I don't run in to an error such as:

`Cannot read property 'create' of undefined` when running a query?

For example, in my `docker-compose.yaml`, I have:

```
  prisma:
    build:
      context: .
      dockerfile: ./app/graphql/src/Dockerfile
      target: development
    depends_on:
      - db
    ports:
      - '4001:4001'
    restart: always
    volumes:
      - ./app/graphql/src:/workspace
      - /workspace/node_modules/
 ```

The volumes attached, move all files over from host machine to my container...except the `node_modules` so that my dev server doesn't track file changes in that directory. When I run a `prisma migrate` on my host machine, my database is updated, but I run in to issues where I receive the error message listed above when running a query on a new table like:

```
return await ctx.db.address.create({})
```

The only way I can fix this problem at the moment is by destroying my docker container and forcing a rebuild. 

I'm like 99% certain this is because I'm blocking `node_modules` from my volume, so I was wondering what is the best way to fix this?

I've tried running `npx prisma generate` on both my host machine and inside my docker container with no luck. Any suggestions?

Thanks!
