### DISCUSSION TITLE
Prisma not connecting to postgres docker container in the same network. It gets connected using pg

### DISCUSSION THREAD

**Discussion by ghost** [prisma/prisma#10631] [Q&A] [answered]
### Bug description

I have two docker containers one with postgres and other with nodejs backend. They are under same external docker network.
Prisma is not getting connected when I run npx prisma db push in Dockerfile for pushing database tables.

### How to reproduce

docker-compose file of postgres:
``` 
version: '3.8'
services:
 postgres:
    image: postgres:latest
    container_name: postgresfe
    ports:
      - 5430:5432
    restart: always
    environment:
      - PGHOST=postgres
      - POSTGRES_PASSWORD=fe@2021
      - POSTGRES_DB=freshdb
    expose:
      - 5432

networks:
  default:
    external : true
    name: webnet

``` 

docker-compose file of backend:
```
version: '3.8'

services:
  backend:
    build: ./
    hostname: backend
    container_name: backend
    ports:
      - 5000:5000
    environment:
      - DATABASE_URL=postgres://postgres:fe@2021@postgres:5432/freshdb
    
networks:
  default:
    external : true
    name: webnet
```

Dockerfile of backend:
```
FROM node:17-alpine

WORKDIR /app

COPY package*.json /app

RUN npm install



COPY . .

RUN npx prisma generate

RUN npx prisma db push --accept-data-loss

CMD [ "npm" ,"start"]
``` 

### Prisma information

Version : 3.6.0

### Environment & setup

Windows

### Prisma Version

```
3.6.0
```

Get connected using this:
![image](https://user-images.githubusercontent.com/62518496/144709601-8764d488-6842-429b-8569-3de58695748e.png)

Prisma Error:
![image](https://user-images.githubusercontent.com/62518496/144709615-be8b14bd-c2fa-4818-b910-08edb794b220.png)

**Comment by piotr-chowaniec** [comment, marked as answer]
Hi There! I have a similar issue with Prisma `3.6.0`. 
I can't connect to Postgres from inside the docker container in order to set up DB at startup.
OS: mac os 11.6
docker version: `20.10.11, build dea9396`

`dockerfile` definition of my `events-board` service:
```
FROM node:16.10

WORKDIR /app

COPY package*.json ./
COPY ./client/package*.json ./client/
COPY ./server/package*.json ./server/
COPY ./commonPackages ./commonPackages

RUN npm run install:all

```

`docker-compose.yml`:

```
version: '3.8'

services:
  events-board:
    container_name: events-board
    restart: on-failure
    build: .
    command: npm run dev
    volumes:
      - .:/app
      - /app/node_modules
      - /app/client/node_modules
      - /app/server/node_modules
    ports:
      - 3000:3000
    depends_on:
      - events-db

  events-db:
    container_name: events-db
    restart: always
    image: postgres:14
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB

volumes:
  postgres:
```

I've tried to run `npx prisma migrate dev` from within `events-board` container.
I've accessed it by `docker exec -it events-board sh`
However, what I'm seeing is the following error:
![Screenshot 2021-12-06 at 21 22 43](https://user-images.githubusercontent.com/45924475/144916829-05afd989-7040-4c9e-90ff-bffbd6321ab9.png)

It's also possible to ping that `events-db` container:
![Screenshot 2021-12-06 at 21 29 15](https://user-images.githubusercontent.com/45924475/144917734-6492fc97-82fb-44d4-982e-8a012c9ee7c5.png)


Changing host from service name `events-db` to IP address `172.25.0.2` solves the issue, however, it makes it unusable from the containerized perspective.

**Reply by piotr-chowaniec** [reply]
It turned out to be mac M1 issue.
The quick solution was to add `connect_timeout` param to connection string as advised [here](https://stackoverflow.com/questions/68476229/m1-related-prisma-cant-reach-database-server-at-database5432)

**Reply by ghost** [reply]
@piotr-chowaniec Thanks for the suggestion. I will try this solution.

**Reply by khuezy** [reply]
Thanks @piotr-chowaniec ! I was scratching my head all day why it couldn't connect.

**Reply by peter-gy** [reply]
Thank you for sharing your findings, @piotr-chowaniec!

**Reply by ael-bagh** [reply]
FOR M1 setting **connect_timeout=60** worked just fine
`DATABASE_URL="postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?schema=public&connect_timeout=60"`

**Comment by milon27** [comment]
## solved the issue by waiting for few seconds before run the api container


my server dockerfile

in CMD command: **sleep 20 &&...**

```Dockerfile

FROM node:16.3.0-alpine as build
RUN npm install -g pnpm

WORKDIR /app

COPY package.json .
COPY pnpm-lock.yaml .

RUN pnpm install

COPY . .

RUN npm run p-gen
RUN npm run build

# # ------------------production -------------------

FROM node:16.3.0-alpine as production
RUN npm install -g pnpm

WORKDIR /app

COPY --from=build /app/.env.docker ./.env
COPY --from=build /app/package.json .
COPY --from=build /app/pnpm-lock.yaml .
COPY --from=build /app/prisma ./prisma
COPY --from=build /app/node_modules/ ./node_modules/
COPY --from=build /app/dist/ ./dist/

# migrate db to production
# run the app
# without seed:npm run p-mg-prod && node dist/app.js
# with seed: npm run p-mg-prod && npm run p-gen && npm run seed && node dist/app.js
CMD ["/bin/sh", "-c", "sleep 20  && npm run p-mg-prod && npm run p-gen && npm run seed && node dist/app.js"]
```



my docker compose file: 

```yml
version: '3.9'
services:
  mariadb:
    container_name: mariadb
    image: mariadb:10.7
    restart: always
    environment:
      - MARIADB_USER=milon27
      - MARIADB_PASSWORD=YourPassWord
      - MARIADB_ROOT_PASSWORD=YourPassWord
      - MYSQL_DATABASE=DB_NAME
    volumes:
      - db_vol:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 7070:8080

  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    links:
      - mariadb
    depends_on:
      - mariadb
      - adminer
    ports:
      - 2727:2727

#volumes(root label)
volumes:
  db_vol: {}

```
