### DISCUSSION TITLE
How to migration on k8s using initContainers?

### DISCUSSION THREAD

**Discussion by cucaixanh** [prisma/prisma#11048] [Q&A] [answered]
Hello.
I am trying to set up migration on k8s, using `initContainers` to migrate before starting the service.
So I'm having an error but haven't been able to fix it? Can anyone help me?

I have build container for using migration like:
```
project-be/prisma/

├── Dockerfile
├── migrations
│   ├── 20220108130032_
│   │   └── migration.sql
│   └── migration_lock.toml
├── schema.prisma
└── seed
    ├── seed.js
    └── userLists.js

```
My Dockerfile:

```
FROM prismagraphql/prisma:1.34

COPY . .

CMD [""]
```

My manifest:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: be-service
  namespace: default
  labels:
    app: be-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: be-service
  template:
    metadata:
      labels:
        app: be-service
    spec:
      terminationGracePeriodSeconds: 30
      initContainers:
      - name: data-migrations
        image: registry/data-migrations:latest
        command: [ 'prisma', 'migrate', 'dev' ]
        env:
          - name: DATABASE_URL
            value: mysql://root:pass_change_me@MY_IP:3306/DB_test
      containers:
        - name: be-service
          image:  registry/be-service:latest
          ports:
            - name: http
              containerPort: 3000
```

I had error when run cmd `kubectl describe pods my_pods_be_service`

```
    Command:
      prisma
      migrate
      dev
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       StartError
      Message:      failed to create containerd task: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "prisma": executable file not found in $PATH: unknown
      Exit Code:    128
```
