### DISCUSSION TITLE
Prisma Migrate and CICD

### DISCUSSION THREAD

**Discussion by danielyogel** [prisma/prisma#11131] [Q&A] [answered]
Hi!
Anyone has a basic repo or tutorial that teaches how to implement CICD with Prisma Migrate (or something similar)? 
Thanks.

**Comment by samrathchadha** [comment]
Running migrations in CI/CD isn't exactly advisable(since you need to change the migration name every single time in the file, but if your use case could be solved by `prisma generate` this would be what a workflow looks like(note: this workflow uses pnpm and will fail if you don't use pnpm too, update it with instructions for your package manager)

```
name: CI
on: [push, pull_request]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"

      - name: Install pnpm 
        run: npm i -g pnpm

      - name: Install dependencies 🔧
        run: pnpm install

      - name: Lint 🖊
        run: pnpm run check-lint

      - name: Set environment variables 🔏
        run: |
          touch .env
          echo NEXT_PUBLIC_CLERK_FRONTEND_API=clerk.8bqex.mkl5j.lcl.dev >> .env
      - name: Build ✅
        run: pnpx prisma generate && pnpm run build
```
