### DISCUSSION TITLE
Integration with GraphQL Code Generator

### DISCUSSION THREAD

**Discussion by ivandotv** [prisma/prisma#11642] [Q&A] [answered]
Has anyone managed to integrate https://www.graphql-code-generator.com/ with prisma generated types?

**Comment by austincrim** [comment]
Hey @ivandotv 👋 ,

We don't have an official plugin for GraphQL Code Generator and I couldn't find a community one on their website either.

We would love to see someone give it a shot!

**Comment by notrab** [comment, marked as answer]
@ivandotv can you explain a little bit more about the expected outcome here, and what you'd like to codegen?

I would take a guess you're looking to automatically create a GraphQLSchema from the Prisma datamodel?

If not that, you can today already use `mappers` to map GraphQL types to Prisma types, for example:

```yml
    config:
      # These mappers result in `import { Cart as CartModel, CartItem as CartItemModel } from '@prisma/client';`
      # Added sufix so Database types don't clash with GraphQL types
      mapperTypeSuffix: Model
      mappers:
        Cart: "@prisma/client#Cart"
        CartItem: "@prisma/client#CartItem"
```
