### DISCUSSION TITLE
Unable to seed MongoDB database

### DISCUSSION THREAD

**Discussion by quinnjr** [prisma/prisma#11659] [Q&A] [answered]
Hello,

So I seem to be having a problem with seeding my database when MongoDB is set as the database type. The connection to the database seems to be working correctly otherwise in my application, but seeding is failing due to an authentication error:

```sh
/app $ prisma db seed
Environment variables loaded from .env
Running seed command `pnpm run ts-node prisma/seed.ts` ...

> pluma-online@0.1.0 ts-node /app
> ts-node --compiler-options "{\"module\":\"commonjs\"}" "prisma/seed.ts"

PrismaClientUnknownRequestError: 
Invalid `prisma.plugin.upsert()` invocation:


  Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: AuthenticationFailed { user: "SCRAM failure: Authentication failed." } })
    at cb (/app/node_modules/.pnpm/@prisma+client@3.9.1_prisma@3.9.1/node_modules/@prisma/client/runtime/index.js:38707:17)
    at async PrismaClient._request (/app/node_modules/.pnpm/@prisma+client@3.9.1_prisma@3.9.1/node_modules/@prisma/client/runtime/index.js:40853:18)
    at async seed (/app/prisma/seed.ts:15:15) {
  clientVersion: '3.9.1'
}
```

My Docker configuration for the database:

```yaml
  database:
    container_name: pluma-online-database
    image: mongo:latest
    command: ["--keyFile", "/etc/mongodb.key", "--replSet", "dbrs", "--bind_ip_all"]
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    networks:
      - web
    ports:
      - 27017:27017
    volumes:
      - database:/data/db
      - ./mongodb/initdb:/docker-entrypoint-initdb.d/
    restart: unless-stopped
```

My `DATABASE_URL`:

```sh
DATABASE_URL=mongodb://pluma:IAMASUPERSECRETPASSWORD@database:27017/pluma?authSource=admin
```

My seed file:

```ts
import { PrismaClient } from '@prisma/client';

import { Plugin } from '../server/@generated/prisma-graphql/plugin/plugin.model';
import { Pipeline } from '../server/@generated/prisma-graphql/pipeline';

import { Plugins } from './plugins';
import { Pipelines } from './pipelines';

const prisma = new PrismaClient();

async function seed() {
  for (const plugin of Plugins) {
    const p = await prisma.plugin.upsert({
      where: {
        name: plugin.name
      },
      update: plugin,
      create: plugin
    });
  }

  console.log(`Seeded ${Plugins.length} plugins`);

  for (const pipeline of Pipelines) {
    const p = await prisma.pipeline.upsert({
      where: {
        name: pipeline.name
      },
      update: pipeline,
      create: pipeline
    });
  }

  console.log(`Seeded ${Pipelines.length} pipelines`);

  let anonUser = {
    name: 'Anonymous',
    email: 'anonymous@local.domain',
    passwordHash: '0000000'
  };

  const _anonymous = await prisma.user.upsert({
    where: {
      email: 'anonymous@local.domain'
    },
    update: anonUser,
    create: anonUser
  });
}

seed()
  .catch(console.error)
  .finally(() => {
    prisma.$disconnect();
  });
```
