### DISCUSSION TITLE
Is there a need to run `migrate dev` from `PrismaClient`?

### DISCUSSION THREAD

**Discussion by buschco** [prisma/prisma#11786] [Q&A] [answered]
I like to test my stuff as realistic as possible on the CI, so I have a `docker-comose.test.yml` with my node app and a postgres service.

To run my tests I will `deploy` my stack with `docker stack deploy -c docker-compose.test.yml test` and run some test I another script.

The problem I am facing, is a primsa client complaining:
```
test_nodejs.2.iln3jwuqgjsb@docker-desktop    | [container] The table `public.User` does not exist in the current database.
test_nodejs.1.ukan9ad590iz@docker-desktop    | [container] The table `public.User` does not exist in the current database.
```

The workaround I came up with is a copy of my node app Dockerfile, with this entrypoint:
```
CMD ["yarn", "workspace", "server", "prisma", "migrate", "dev"]
```
and another service in the compse file:
``` 
 init-tests:
    image: init-tests
    depends_on:
      - postgres
    environment:
      - POSTGRES_URL=postgres://postgres:pgpass@postgres/dev
    deploy:
      replicas: 1
      restart_policy:
        condition: none
    networks:
      - app-network
```

A simpler way to do this would be the possibility do call `migrate dev` I the node app code like this:

```
if(process.env.NODE_ENV === 'test') await prisma.migrateDev()
```

Is there a simpler solution?
