### DISCUSSION TITLE
Error: MongoDB error Server selection timeout: No available servers.

### DISCUSSION THREAD

**Discussion by BEDIRHANSAMSA** [prisma/prisma#11929] [Q&A] [answered]
Hi, I tried to run mongo on Docker, but when I type prisma db push I get this error, can you help?

Connectiong String: 
```txt
mongodb://username:password@localhost:27017/akillisatici?authSource=admin&retryWrites=true&w=majority
```

docker-compose.yml
```yaml
version: "3.8"

networks:
  akillisatici-net:
    name: akillisatici-net

volumes:
  akillisatici-2.mongo:
  akillisatici-1.mongo:
  akillisatici-0.mongo:

services:
  akillisatici-2.mongo:
    hostname: akillisatici-2.mongo
    container_name: akillisatici-2.mongo
    image: mongo
    entrypoint:
      [
        "/usr/bin/mongod",
        "--keyFile",
        "/data/file.key",
        "--replSet",
        "rs",
        "--journal",
        "--bind_ip_all",
      ]
    ports:
      - "27018:27017"
    restart: always
    networks:
      - akillisatici-net
    volumes:
      - "akillisatici-2.mongo:/data/db"
      - "./.docker/file.key:/data/file.key"

  akillisatici-1.mongo:
    hostname: akillisatici-1.mongo
    container_name: akillisatici-1.mongo
    image: mongo
    entrypoint:
      [
        "/usr/bin/mongod",
        "--keyFile",
        "/data/file.key",
        "--replSet",
        "rs",
        "--journal",
        "--bind_ip_all",
      ]
    ports:
      - "27019:27017"
    restart: always
    networks:
      - akillisatici-net
    volumes:
      - "akillisatici-1.mongo:/data/db"
      - "./.docker/file.key:/data/file.key"

  akillisatici-0.mongo:
    hostname: akillisatici-0.mongo
    container_name: akillisatici-0.mongo
    image: mongo
    command: bash -c "/usr/bin/mongod --keyFile /data/file.key --replSet rs --journal --bind_ip_all"
    ports:
      - "27017:27017"
    links:
      - akillisatici-1.mongo:akillisatici-1.mongo
      - akillisatici-2.mongo:akillisatici-2.mongo
    restart: always
    networks:
      - akillisatici-net
    volumes:
      - "akillisatici-0.mongo:/data/db"
      - "./.docker/setup.sh:/scripts/setup.sh"
      - "./.docker/file.key:/data/file.key"

```

setup.sh
```shell
#!/bin/bash

mongo <<EOF
   var cfg = {
        "_id": "rs",
        "version": 1,
        "members": [
            {
                "_id": 0,
                "host": "akillisatici-0.mongo:27017",
                "priority": 2
            },
            {
                "_id": 1,
                "host": "akillisatici-1.mongo:27017",
                "priority": 0
            },
            {
                "_id": 2,
                "host": "akillisatici-2.mongo:27017",
                "priority": 0
            }
        ]
    };
    rs.initiate(cfg, { force: true });
    //rs.reconfig(cfg, { force: true });
    rs.status();
EOF
```

After prisma db push command:
```
Error: MongoDB error
Server selection timeout: No available servers. Topology: { Type: ReplicaSetNoPrimary, Servers: [ { Address: akillisatici-1.mongo:27017, Type: Unknown, Error: No such host is known. (os error 11001) }, { Address: akillisatici-2.mongo:27017, Type: Unknown, Error: No such host is known. (os error 11001) }, { Address: akillisatici-0.mongo:27017, Type: Unknown, Error: No such host is known. (os error 11001) }, ] }
   0: migration_core::state::SchemaPush
             at migration-engine\core\src\state.rs:274
```
