### DISCUSSION TITLE
Docker restart fails after creating a prisma connection

### DISCUSSION THREAD

**Discussion by alexsro** [prisma/prisma#13208] [Q&A]
Hello, I am just starting to use prism and I face a problem when I save my file and my containers are restarted, if the connection to prism has not been established yet everything is fine, otherwise the container cannot restart.
Obs. The connection with database and the requests work well.

message:
![Captura de tela de 2022-05-05 21-02-33](https://user-images.githubusercontent.com/65572080/167045818-8e62d73d-eb1b-4121-9aaa-0b7ade26beca.png)

My docker-compose.yml:
```
version: "3"

services:
  postgres:
    image: postgres
    container_name: postgres-auth-api
    environment:
      - POSTGRES_USER=User
      - POSTGRES_PASSWORD=Pass
    ports:
      - 6432:5432
    volumes:
      - data_postgres

  data_postgres:
    image: cogniteev/echo
    command: echo 'Data Container for Postgres'
    volumes:
      - /var/lib/postgresql/data

  app:
    build: .
    command: yarn dev:server
    container_name: auth-api
    ports:
      - 3334:3334
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    links: 
      - data_postgres
      - postgres
    restart: always
```
my database url : 
```
DATABASE_URL="postgresql://User:Pass@172.25.0.2:5432/postgres?schema=public"
```
I created a network for communication between the containers with the following commands:
```
docker network create auth-api-network
docker network connect auth-api-network auth-api
docker network connect auth-api-network postgres-auth-api
```
