### DISCUSSION TITLE
prisma generate on azure app service

### DISCUSSION THREAD

**Discussion by MauroMontan** [prisma/prisma#13409] [Q&A]
Hello, im having a problem with prisma when i'm deploying on azure app service. the problem is this:
`Error: @prisma/client did not initialize yet. Please run "prisma generate" and try to import it again.`

i know this problem can be solved by running: `npx prisma generate`, this command fix it perfectly locally. but i have no idea of how to run that command on the azure app service, or even if it can be solved from the github workflow. If anyone has a solution I would greatly appreciate it.

this is my workflow
```
name: Build and deploy Node.js app to Azure Web App - demoexpress

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: npm install, generate prisma
        run: |
          npm install

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'demoexpress'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_D63015789E8D400C9F857EB8ABDE6512 }}
          package: .
```
