### DISCUSSION TITLE
Prisma Studio + Docker Postgres Container

### DISCUSSION THREAD

**Discussion by tomwray13** [prisma/prisma#13626] [Q&A] [answered]
Hey there!

I'm running my project locally via Docker compose and 2 services running: 
- NestJS service  
- Postgres service

When I fire up prisma studio locally with `npx prisma studio`, it throws this database connection error:

<img width="515" alt="image" src="https://user-images.githubusercontent.com/24568306/171692293-53716acb-3566-4ec1-b78c-25c432779fa3.png">

Worth noting that the local postgres server (via Docker) is defo running - I'm doing crud operations locally in the nestJs service which is persisting to the database.

What's strange is if I remove the NestJS service from the docker compose, keep the postgres service running, and then run the NestJS project in my local machine (with `npm run start:dev`) - prisma studio opens up with no issues and connects to the Postgres Docker service.

So the issue seems to happen when the Postgres service is running in Docker alongside the NestJs service? 🤔

Not sure if it's helpful but here's my `docker-compose.yml` file:

```
version: "3.9"
services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
      # Only will build development stage from our dockerfile
      target: development
    # TBC
    volumes:
      - .:/usr/src/app
      - ./usr/src/app/node_modules
    # Run in dev Mode: npm run start:dev
    command: npm run start:dev
    depends_on: 
      - postgres
    env_file:
    - .env
    ports:
      - 3000:3000
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_NAME: nest-twitter-db
      POSTGRES_USER: nest-twitter
      POSTGRES_PASSWORD: password
    ports: 
      - '5432:5432'
    volumes:
      - nest-twitter-db:/var/lib/postgresql/data

volumes:
  nest-twitter-db:
```

And the DATABASE_URL in my env file (which is what I assume Prima studio is trying to use to connect to the postgres instance):

```env
DATABASE_URL="postgresql://nest-twitter:password@localhost:5432/nest-twitter-db?schema=public"
```

Thank you for you help in advance! Love the prisma community 💜

**Comment by tomwray13** [comment, marked as answer]
Looks like someone had a similar question recently https://github.com/prisma/prisma/discussions/13012 which helped me solve the above issue!

Basically, in the local env file, ensure you use `localhost` as the hostname

```
DATABASE_URL="postgresql://nest-twitter:password@localhost:5432/nest-twitter-db?schema=public"
```

This means when you run `npx prisma studio` it connects to the local postgres instance in Docker with no issues.

However, this will then break the Docker services from working together as you need to use `postgres` as the hostname.

So what you can do in the `docker-compose.yml` file is define an overriding `DATABASE_URL` environment variable, using `postgres` as the hostname

```
version: "3.9"
services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
      # Only will build development stage from our dockerfile
      target: development
    # TBC
    volumes:
      - .:/usr/src/app
      - ./usr/src/app/node_modules
    # Run in dev Mode: npm run start:dev
    command: npm run start:dev
    depends_on: 
      - postgres
    env_file:
    - .env
    environment:
    - DATABASE_URL=postgresql://nest-twitter:password@postgres:5432/nest-twitter-db?schema=public
    ports:
      - 3000:3000
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_NAME: nest-twitter-db
      POSTGRES_USER: nest-twitter
      POSTGRES_PASSWORD: password
    ports: 
      - '5432:5432'
    volumes:
      - nest-twitter-db:/var/lib/postgresql/data

volumes:
  nest-twitter-db:
```
