### DISCUSSION TITLE
Prisma migrate doesn't work on Mysql port 3307 in Docker

### DISCUSSION THREAD

**Discussion by dagistan-tuncbilek** [prisma/prisma#14133] [Q&A] [answered]
### Bug description

I am running a local database on 3306 and another in docker container on 3307. On 3306 everything is working well. When i want use 3307, migrate commands cant find the database. 
```
MySQL database xxx created at localhost:3307
Error: P1003
Database `xxx` does not exist on the database server at `localhost:3307
````

I am creating database on 3306 and copy it to 3307, then application works as expected and Prisma works perfect. 
Problem is only related to migrate commands.
Only for this reason i used Laravel to migrate and seed in my last project.

### How to reproduce

Run a mariadb or mysql container and open port 3307.

### Prisma information

Not important

### Environment & setup

- OS: Ubuntu 22.04
- Database: MariaDB
- Node.js version: 16.15.1

### Prisma Version

```
4.0
```

**Comment by austincrim** [comment, marked as answer]
Hey @dagistan-tuncbilek 👋,

Could you share your relevant `Dockerfile` or `docker-compose.yml` files as well as your Prisma Schema?

**Reply by dagistan-tuncbilek** [reply]
Hi austincrim, here is my dockerfile. But i think it is not so important. I use mariadb in docker container in my developments. Because i am using docker as my development envirenment, it is useful especially working with php. I can access and migrate database for example with Laravel without any problem. And i have no problem if i use postgresql with prisma. But problem is only with mysql/mariadb. Application itself  running and accesing database, but migrate command not.
```
version: "2.1"
services:
  mariadb:
    image: lscr.io/linuxserver/mariadb:10.5.16
    container_name: mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      -  /home/docker_data/mysql_data:/config
    ports:
      - 3307:3306
    restart: unless-stopped
```
