### DISCUSSION TITLE
Prisma support: 8.0.22-13 Percona Server (GPL) ?

### DISCUSSION THREAD

**Discussion by obzenner** [prisma/prisma#14156] [Q&A]
Dear Prisma team!

When running `DEBUG=* npx prisma migrate resolve --applied xxxxxxx_baseline_migration` against a remote db that is a `8.0.22-13 (Percona Server (GPL), Release 13, Revision 6f7822f) support` we're getting this error:

```
  prisma:migrateEngine:rpc  SENDING RPC CALL {"id":1,"jsonrpc":"2.0","method":"markMigrationApplied","params":{"migrationsDirectoryPath":"/Users/obzenner/stuff/repo_repo/prisma/migrations","migrationName":"xxxxxxx_baseline_migration"}} +12ms
  prisma:migrateEngine:stderr  {"timestamp":"2022-07-05T13:45:31.036595Z","level":"INFO","fields":{"message":"Starting migration engine RPC server","git_hash":"da41d2bb3406da22087b849f0e911199ba4fbf11"},"target":"migration_engine"} +0ms
  prisma:migrateEngine:rpc  {
  jsonrpc: '2.0',
  error: {
    code: 4466,
    message: 'An error happened. Check the data field for details.',
    data: {
      is_panic: false,
      message: 'Server has closed the connection.',
      meta: null,
      error_code: 'P1017'
    }
  },
  id: 1
} +345ms
Error: Error: P1017

Server has closed the connection.
```

Locally when running with docker-compose everything works fine, but the difference is that our local dbs are running a `8.0.29 (MySQL Community Server - GPL)`

Have you encountered issues with Percona Server?

We are using the latest Prisma 4.0.0

P.S. Same happens for `npx prisma migrate dev` commands as well, however the db pull/push commands work fine (i.e. `npx prisma db pull`)

**Comment by obzenner** [comment]
FYI, tried running percona locally and it worked as a charm:
```
  keyword_content_db:
    image: percona/percona-server:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db_init:/docker-entrypoint-initdb.d
    ports:
      - "13033:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=user_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=test
    healthcheck:
      test: out=$$(mysqladmin ping -h localhost -P 3306 -u root --password=root 2>&1); echo $$out | grep 'mysqld is alive' || { echo $$out; exit 1; }
      interval: 20s
      timeout: 30s
      retries: 10
    env_file:
      - .env.test
```
