### DISCUSSION TITLE
Can't reach database server at `postgres`:`5432`

### DISCUSSION THREAD

**Discussion by gabriel-frattini** [prisma/prisma#14187] [Q&A] [answered]
### Bug description

I have a docker container running with postgres but prisma cant find the database server when i run ```npx prisma migrate dev```

In my docker GUI it says that I have a running container with a name of postgres on PORT:5432

The error i get is 
```
Error: P1001: Can't reach database server at `postgres`:`5432`

Please make sure your database server is running at `postgres`:`5432`.
```

### How to reproduce

1. Install ```prisma``` and ```@prisma/client```
2. run ```npx prisma init``` to get the following schema
```
generator client {
   provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url = env("DATABASE_URL")
}
```
3. add the docker-compose.yml file

```
version: "3.8"
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  postgres:
```

5. Add database string to .env 

```
DATABASE_URL="postgresql://postgres:postgres@postgres:5432/mydb?schema=public"
```

7. run ```docker compose up ```
8. run `npx prisma migrate dev`

### Expected behavior

Succesful migration from prisma

### Prisma information

"@prisma/client": "^3.5.0"
 "prisma": "^3.15.2"

### Environment & setup

- OS: Windows

### Prisma Version

```
3.15.2
```

**Comment by sabinadams** [comment, marked as answer]
Hey @gabriel-frattini, I believe the issue here is your connection string.

```
DATABASE_URL="postgresql://postgres:postgres@postgres:5432/mydb?schema=public"
```

The format of the connection string should be:
```
postgresql://<USER>:<PASSWORD>@<HOST>:<PORT>/<DATABASE>?schema=<SCHEMA>
```

Yours is mostly correct, except the `HOST` shouldn't be `"postgres"`, but instead `"localhost"`.

```
DATABASE_URL="postgresql://postgres:postgres@localhost:5432/mydb?schema=public"
```

**Reply by Tunji17** [reply]
I am facing the same issue, I think `"postgres"` in this case is referencing the docker container in his docker-compose file, although @gabriel-frattini I think you should check that the container is actually created using the `"postgres"` name or explicitly state it in your compose file like so 
```
version: "3.8"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  postgres:
```

**Reply by spencerxiao** [reply]
I faced the same issue . My case is that I passed the postgres container name as build-args for the docker file of my application and in the docker file, it sets the environment variable `DATABASE_URL` as the following:
```
ARG POSTGRES_HOST
ARG POSTGRES_PWD
ENV DATABASE_URL="postgresql://postgres:${POSTGRES_PWD}@${POSTGRES_HOST}:5432/mydb?schema=public"
```
But after checking several times and the problem is solved. My current docker compose file looks like the following:
```
services:
    app:
        image: "app-server"
        container_name: app-backend
        build: 
            context: .
            args:
               - POSTGRES_HOST=app-postgres
               - POSTGRES_PWD=postgrespw
    postgres:
         image: "postgres:latest"
         container_name: app-postgres
         restart: always
         ports:
             - "5432:5432"
         environment:
             - POSTGRES_PASSWORD=postgrespw
             - POSTGRES_HOST_AUTH_METHOD=trust
```
The important thing to note is that do not put double quotes around the value for the build args `POSTGRES_HOST`.

**Reply by maxganiev** [reply]
how to proceed without doker? i got same error for the server, on my local machine everything works as expected though:
```
Listening on 0.0.0.0:3000                                                                                              
 PrismaClientInitializationError:  Invalid `prisma.category.findMany()` invocation: 
Can't reach database server at `localhost`:`3306`  
Please make sure your database server is running at `localhost`:`3306`. 
```

completely stucked here

3000 is just a proxy, db itself lives on localhost:3306

**Reply by Suniron** [reply]
Same error here :'(

**Reply by maxganiev** [reply]
here I described the solution I'd managed to find https://github.com/prisma/prisma/discussions/15005
hope it will help out

**Reply by bablukpik** [reply]
I'm getting the same error :(

Here is the error: 

> Error: P1001: Can't reach database server at `postgres`:`5432`

While running `npx prisma migrate dev` to perform Prisma migrations locally.

Again if I replace the value of `POSTGRES_HOST` with `localhost` and run `docker compose up` then it shows this error:

> PrismaClientInitializationError: Can't reach database server at `localhost`:`5432`

**Reply by 99lalo** [reply]
Were you able to find the solution?

**Reply by kejlerj** [reply]
I had the same error and this fixes it : 
[https://stackoverflow.com/a/77822758/10661841](https://stackoverflow.com/a/77822758/10661841)

I had to use the name container as HOST in the db url, then my app works fine, but not the migrations commands. To do so I had to execute the commands from inside the container.

**Reply by noobpiyush** [reply]
hey @sabinadams . i was also facing the same issue. i am using windows your solution worked thanks. i wan using this string -> DATABASE_URL="postgresql://piyush:piyuush@localhost:5432/postgres".  but i then saw you answer and modified it to  DATABASE_URL="postgresql://piyush:piyuush@localhost:5432/postgres?schema=public". it worked

**Reply by blavikensbutcher** [reply]
@kejlerj yass it works for me. thnx man

**Reply by bablukpik** [reply]
@99lalo I made custom npm script commands like so:
```
  "migrate:dev": "cross-env POSTGRES_HOST=localhost prisma migrate dev --skip-seed",
  "migrate:prod": "prisma generate && prisma migrate deploy",
  "migrate:reset": "cross-env POSTGRES_HOST=localhost prisma migrate reset --skip-seed",
  "studio": "cross-env POSTGRES_HOST=localhost prisma studio",
  "seed:dev": "cross-env POSTGRES_HOST=localhost prisma db seed -- --environment development",
  "seed:prod": "prisma db seed -- --environment production",
```
And the `.env` like so:
```
POSTGRES_HOST=postgres
POSTGRES_USER=admin
POSTGRES_PASSWORD=admin
POSTGRES_DB=project_db
DATABASE_URL="postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/${POSTGRES_DB}?schema=public"
```
And here is the `docker-compose.yml`:
```
version: '3.8'

services:
  backend_app:
    build: . # Dockerfile's path
    container_name: backend_app
    restart: always
    depends_on:
      - postgres
    ports:
      - 9000:9000
    networks:
      - vb
    volumes:
      - ./:/app
    env_file:
      - .env

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - vb
    env_file:
      - .env

volumes:
  postgres_data:

networks:
  vb:
    name: vb
```
But remember @kejlerj 's answer should also work

**Reply by lohnsonok** [reply]
added `?schema=public` worked for me psst 👍

**Comment by sonnyiosa** [comment]
I'm faced same issue but this worked for me: https://stackoverflow.com/questions/68476229/m1-related-prisma-cant-reach-database-server-at-database5432

Just need to add **?connect_timeout=300** with nodejs-16 (need someone to explain for me how this work)

Second way without adding anything to DATABASE_URL is upgrade nodejs to 18 .

**Reply by gmcouto** [reply]
Thank you. It seems that docker hostname resolving might be a little bit slow. Will keep that in mind.

**Reply by usmansbk** [reply]
This fixed my issue but why?

**Reply by MobinAskari** [reply]
I'm on Node 24.11.1 and Prisma 7.1.0 and this somehow did the trick!.
It took 21 seconds to update the database.

**Comment by zhoou** [comment]
If you have created a "newuser" to log in and this issue occurs，
like this:
`postgresql://newuser:password@localhost:5432/mydb?schema=public`
maybe you need to check if “newuser” can log in！！

**Comment by erik-metz** [comment]
How could this error be handled in the backend, when for example the database is really down?

**Comment by MarchenkoVL05** [comment]
I was facing the same problem and changing the port from "5432:5432" to "5434: 5432" solved it. So the docker-compose is: 
```
version: '3.8'
services:
  postgres:
    image: postgres:13.5
    restart: always
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5434:5432'

volumes:
  postgres:
```

and .env:
`DATABASE_URL="postgres://myuser:mypassword@localhost:5434/median-db"
`
Dunno why, but it works

**Reply by Rormea** [reply]
Esto me resultó!!!

**Reply by Lepaic6969** [reply]
¡Funciona!, hay que resaltar que ahora el puerto que debemos poner en DATABASE_URL es el 5434 como lo sugiere @MarchenkoVL05

**Reply by AlexandrDyagel** [reply]
It worked for me!

**Reply by Aleydon** [reply]
Thanks, bro. its work for me.

**Comment by jziggas** [comment]
I am having the same problem. Nothing makes sense!

```.env
# Environment variables declared in this file are automatically made available to Prisma.
# See the documentation for more detail: https://pris.ly/d/prisma-schema#accessing-environment-variables-from-the-schema

# Prisma supports the native connection string format for PostgreSQL, MySQL, SQLite, SQL Server, MongoDB and CockroachDB.
# See the documentation for all the connection string options: https://pris.ly/d/connection-strings

POSTGRES_DB=foo
POSTGRES_USER=bar
POSTGRES_PASSWORD=baz
POSTGRES_SCHEMA=public
POSTGRES_PORT=5432
POSTGRES_HOST=localhost
DATABASE_URL="postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?schema=${POSTGRES_SCHEMA}"
APOLLO_PLAYGROUND=true
JWT_SECRET="qux"
```

```Dockerfile
###################
# BUILD FOR LOCAL DEVELOPMENT
###################

FROM node:18-alpine As development

# Create app directory
WORKDIR /usr/src/app

# Copy application dependency manifests to the container image.
# A wildcard is used to ensure copying both package.json AND package-lock.json (when available).
# Copying this first prevents re-running npm install on every code change.
COPY --chown=node:node package*.json ./

# Install app dependencies using the `npm ci` command instead of `npm install`
RUN npm ci

# Bundle app source
COPY --chown=node:node . .

# Generate Prisma database client code
RUN npm run prisma:generate

EXPOSE 3000

# Use the node user from the image (instead of the root user)
USER node

###################
# BUILD FOR PRODUCTION
###################

FROM node:18-alpine As build

WORKDIR /usr/src/app

COPY --chown=node:node package*.json ./

# In order to run `npm run build` we need access to the Nest CLI.
# The Nest CLI is a dev dependency,
# In the previous development stage we ran `npm ci` which installed all dependencies.
# So we can copy over the node_modules directory from the development image into this build image.
COPY --chown=node:node --from=development /usr/src/app/node_modules ./node_modules

COPY --chown=node:node . .

# Run the build command which creates the production bundle
RUN npm run build

# Set NODE_ENV environment variable
ENV NODE_ENV production

# Running `npm ci` removes the existing node_modules directory.
# Passing in --only=production ensures that only the production dependencies are installed.
# This ensures that the node_modules directory is as optimized as possible.
RUN npm ci --only=production && npm cache clean --force

USER node

###################
# PRODUCTION
###################

FROM node:18-alpine As production

# Copy the bundled code from the build stage to the production image
COPY --chown=node:node --from=build /usr/src/app/node_modules ./node_modules
COPY --chown=node:node --from=build /usr/src/app/dist ./dist

# Start the server using the production build
CMD [ "node", "dist/main.js" ]
```

```docker-compose.yml
version: '3.8'
services:
  postgres:
    image: postgres:15.3-alpine
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    environment:
      # You'll notice the DATABASE_URL variable in the docker-compose.yml file is the same as the DATABASE_URL variable in the .env file - except the host has been updated to postgres instead of localhost.
      # This will prevent you from getting the error: Error: Can't reach database server at localhost:5432
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/${POSTGRES_DB}?schema=${POSTGRES_SCHEMA}
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - nestjs
  api:
    build:
      dockerfile: Dockerfile
      context: .
      # Only will build development stage from our dockerfile
      target: development
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/${POSTGRES_DB}?schema=${POSTGRES_SCHEMA}
    # Run a command against the development stage of the image
    command: npm run start:dev
    ports:
      - 3000:3000
    depends_on:
      - postgres
volumes:
   postgres:
      name: nestjs-postgres

networks:
   nestjs:
```

No matter what I do it's either `Error: Can’t reach database server at localhost:5432` or `Error: Can’t reach database server at postgres:5432`

**Reply by jziggas** [reply]
Ugh. Had to add the network to the api service just like the postgres service :(
```
networks:
      - nestjs
```

Now it works. In any case, I hope my docker files serve as a template for others.

**Reply by gabbrieu** [reply]
Thank you so much man! You reply was the only one that did the job.

**Reply by yassinesaindou** [reply]
I was having this problem, I just changed the internet provider. I was using a WiFi and it did not work then I switched to mobile data and it started working.

**Comment by dev-sumanaditya** [comment]
@jziggas 
Replacing host in the DATABASE_URL with **"host.docker.internal"** also works but is not recommended.
link - [Docker Docs](https://docs.docker.com/desktop/networking/#i-want-to-connect-from-a-container-to-a-service-on-the-host)

final code looks like this.
`DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@host.docker.internal:5432/${POSTGRES_DB}?schema=public`

**Comment by welcomemonth** [comment]
我是在运行这个npm run migrate:dev命令的时候一直提示Error: P1001: Can't reach database server at `postgres`:`5432`，上面的办法我都试过了，但是都不行，当我直接在数据库中创建了一个《POSTGRES_DB》表的之后再运行就不报错了

**Reply by lili21** [reply]
怎么建的

**Comment by fazil-softprodigy** [comment]
If you encounter the same issue, it is essential to ensure that Docker is running correctly. In my case, I experienced a similar problem, and upon investigation, I found that the PostgreSQL server was not accessible because Docker was not up and running.

To avoid facing this problem, please make sure that you have Docker up and operational before attempting to connect to the PostgreSQL database. Docker plays a crucial role in providing the necessary environment for the database server to function correctly.

**Reply by solutionsSlayer** [reply]
captain obvious

**Reply by NielsCodes** [reply]
You're telling me I can't connect to the database if there is no database? I am shocked!

**Comment by anasdevv** [comment]
if you encounter same issue and your url is also in correct format try replacing 
DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@host.docker.internal:5432/${POSTGRES_DB}?schema=public
with
DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@localhost:5432/${POSTGRES_DB}?schema=public

**Reply by anasdevv** [reply]
if you are using docker windows

**Comment by AprajitKatiyar** [comment]
Adding `schema=public&connect_timeout=30&pool_timeout=30&socket_timeout=30` to the connection string worked for me.
Also make sure you don't have a VPN enabled. (Struggled with Zscaler in my case)

**Reply by kelokchan** [reply]
This has fixed my issue. Thanks!

**Reply by trishan9** [reply]
this fixed my issue

**Reply by udddo2** [reply]
thanks

**Reply by mischulz14** [reply]
Had this issue today at work and this worked like a charm. Thanks @AprajitKatiyar ! 🚀 

I only used the string after `schema=public`

**Reply by lil-id** [reply]
thank you, it works for me.

**Reply by fredlemieux** [reply]
Worked for me, but can you explain why this worked to fix the issue?

**Comment by IkeCairns** [comment]
I have been facing the same problem for a week, and have tried every advice above, but unfortunately, it is still not solved.

**Comment by IkeCairns** [comment]
When I hit the command below on my terminal, problem has been solved!
$ sudo docker compose run app npx prisma migrate dev

ChatGpt 3.5 advised me to do so.

**Reply by slarkvan** [reply]
it works

**Comment by 1qh** [comment]
[This solution](https://stackoverflow.com/questions/72889810/docker-compose-prisma-cannot-connect-with-database-nestjs) works for me

**Comment by Anhdao153** [comment]
i resolved
This is my step
i added this key to .env
PRISMA_SCHEMA_DISABLE_ADVISORY_LOCK=false
then i execute my container
```
docker exec -it your-application-container bash
```
and finally, run command migrate
```
npx prisma migrate dev --name init-source
or 
npx prisma migrate dev
```
it worked to me
i spent more than 2 hours because this issue T_T

my docker compose

```yml
version: '3.9'
services:
  
  api:
    container_name: portfolio-api
    build:
      dockerfile: Dockerfile
      context: .
    env_file: .env
    ports:
      - "5050:5050"
    networks:
      - portfolio
    depends_on:
      - database

  database:
    container_name: postgres
    image: postgres:15.6-alpine3.19
    restart: unless-stopped
    ports:
      - '5432:5432'
    networks:
      - portfolio
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin

    ports:
      - "${PGADMIN_PORT:-8080}:80"
    networks:
      - portfolio
    restart: unless-stopped

networks:
  portfolio:
    driver: bridge
  
volumes:
  postgres:
  pgadmin:
```
