### DISCUSSION TITLE
Getting PrismaClientInitializationError in my app tests (I don't test any prisma stuff)

### DISCUSSION THREAD

**Discussion by beshur** [prisma/prisma#14242] [Q&A]
Hello.

My app uses prisma, but it does not appear in tests - everything is mocked, using `jest`.

When I run tests locally I have no issues.

But when I try to the tests on github I get the prisma error after the tests are completed.

I tried to remove my local config files to reproduce this, but to no success.

See this piece of log:

```
Test Suites: 5 passed, 5 total
Tests:       14 passed, 14 total
Snapshots:   0 total
Time:        4.38 s
Ran all test suites.
/home/runner/work/app/app/node_modules/@prisma/client/runtime/index.js:36174
            throw new PrismaClientInitializationError(error2.message, this.config.clientVersion, error2.error_code);
                  ^
PrismaClientInitializationError: error: Environment variable not found: DATABASE_URL.
  -->  schema.prisma:10
   | 
 9 |   provider = "mysql"
10 |   url      = env("DATABASE_URL")
   | 
Validation Error Count: 1
    at Object.loadEngine (/home/runner/work/app/app/node_modules/@prisma/client/runtime/index.js:36174:19)
    at Object.instantiateLibrary (/home/runner/work/app/app/node_modules/@prisma/client/runtime/index.js:36103:5) {
  clientVersion: '3.8.1',
  errorCode: 'P1012'
}
Error: Process completed with exit code 1.
```

Github workflow:

```yaml
name: Node.js CI

on:
  push:
    branches: ['*']

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - uses: bahmutov/npm-install@v1
      - run: npm test
```

**Comment by beshur** [comment]
Okay, this was a fast one.

Fixed with dummy env vars in workflow file.

But why it even gets triggerred?

```YAML
name: Node.js CI

on:
  push:
    branches: ['*']

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - uses: bahmutov/npm-install@v1
      - run: npm test
        env:
          DATABASE_URL: 'mysql://localhost'
          SHADOW_DATABASE_URL: 'mysql://localhost'
```
