### DISCUSSION TITLE
Docker prisma can't reach database server

### DISCUSSION THREAD

**Discussion by pierColo** [prisma/prisma#15023] [Q&A]
Hi, i build a simple crud project with next.js and prima and i'm trying to dockerize everything up and run it. But it seems the docker version can't reach the db server even if the server is up.
The logs
```
postgres-db | 2022-08-26 10:36:16.081 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres-db | 2022-08-26 10:36:16.081 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgres-db | 2022-08-26 10:36:16.085 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres-db | 2022-08-26 10:36:16.109 UTC [26] LOG:  database system was shut down at 2022-08-26 10:32:09 UTC
postgres-db | 2022-08-26 10:36:16.135 UTC [1] LOG:  database system is ready to accept connections
poke-project | 
poke-project | > poke-project@0.1.0 start /app
poke-project | > next start
poke-project | 
poke-project | ready - started server on 0.0.0.0:3000, url: http://localhost:3000
poke-project | info  - Loaded env from /app/.env
poke-project | PrismaClientInitializationError: Can't reach database server at `0.0.0.0`:`5432`
```

My docker-compose file :
```
version: '3.3'
services:
  db:
    image: postgres
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: pokemon
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  next-app :
    image: nextjs-app
    container_name: poke-project
    build: .
    ports:
    - '3000:3000'
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./styles:/app/styles
    depends_on:
      - db
```
env file with database url 
```
DATABASE_URL="postgres://postgres:admin@0.0.0.0:5432/pokemon?schema=public"
```
dockefile
````
FROM node:14.19.3

RUN mkdir -p /app
WORKDIR /app

EXPOSE 3000

COPY src /app/src
COPY public /app/public
COPY styles /app/styles
COPY package.json ./
COPY prisma ./prisma
COPY jsconfig.json ./
COPY .env ./

RUN npm install

RUN npx prisma generate

RUN npm run build
CMD ["npm","run", "start"]

````
