### DISCUSSION TITLE
AWS Lambda Deployment Guide broken

### DISCUSSION THREAD

**Discussion by ThaFishDance** [prisma/prisma#15057] [Q&A] [answered]
### Bug description

While following the AWS Lambda deployment guide [Deploying to AWS Lambda
](https://www.prisma.io/docs/guides/deployment/deployment-guides/deploying-to-aws-lambda), the guide works until the webpack section. Once I included the webpack information, the deployment failed to a ""Unzipped size must be smaller than 262144000 bytes " error

### How to reproduce

1. Go to [Deploying to AWS Lambda
](https://www.prisma.io/docs/guides/deployment/deployment-guides/deploying-to-aws-lambda) and follow instructions.

2. See error logs when deploying once webpack information is included

### Expected behavior

UPDATE_FAILED: GetPostsLambdaFunction (AWS::Lambda::Function)
Resource handler returned message: "Unzipped size must be smaller than 262144000 bytes 

### Prisma information

generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["native", "rhel-openssl-1.0.x"]
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model Post {
  id        Int      @id @default(autoincrement())
  title     String   @db.VarChar(255)
  createdAt DateTime @default(now()) @db.Timestamp(6)
  content   String?
  published Boolean  @default(false)
  authorId  Int
  author    User     @relation(fields: [authorId], references: [id], onDelete: NoAction, onUpdate: NoAction)
}

model Profile {
  id     Int     @id @default(autoincrement())
  bio    String?
  userId Int     @unique
  user   User    @relation(fields: [userId], references: [id], onDelete: NoAction, onUpdate: NoAction)
}

model User {
  id      Int      @id @default(autoincrement())
  name    String?  @db.VarChar(255)
  email   String   @unique @db.VarChar(255)
  posts   Post[]
  profile Profile?
}

### Environment & setup

- OS: Windows - Deploying to AWS Lambda
- Database: Heroku Postgres
- Node.js version: v16.14.0

### Prisma Version

```
prisma                  : 4.2.1
@prisma/client          : 4.2.1
Current platform        : windows
Query Engine (Node-API) : libquery-engine 2920a97877e12e055c1333079b8d19cee7f33826 (at node_modules\@prisma\engines\query_engine-windows.dll.node)
Migration Engine        : migration-engine-cli 2920a97877e12e055c1333079b8d19cee7f33826 (at node_modules\@prisma\engines\migration-engine-windows.exe)
Introspection Engine    : introspection-core 2920a97877e12e055c1333079b8d19cee7f33826 (at node_modules\@prisma\engines\introspection-engine-windows.exe)
Format Binary           : prisma-fmt 2920a97877e12e055c1333079b8d19cee7f33826 (at node_modules\@prisma\engines\prisma-fmt-windows.exe)
Default Engines Hash    : 2920a97877e12e055c1333079b8d19cee7f33826
Studio                  : 0.469.0
```

**Comment by ThaFishDance** [comment]
This is my current serverless.yml file. Can any one help?
Serverless.yml

```
service: prisma-aws-lambda-example
plugins:
  - serverless-webpack
  - serverless-webpack-prisma

provider:
  name: aws
  region: us-east-1
  runtime: nodejs14.x

custom:
  webpack:
    includeModules: true

functions:
  status:
    handler: handlers/status.handler
    events:
      - http:
          method: GET
          path: /
  seed:
    handler: handlers/seed.handler
    events:
      - http:
          method: GET
          path: /seed
  getUsers:
    handler: handlers/users.handler
    events:
      - http:
          method: GET
          path: /users
  createUser:
    handler: handlers/create-user.handler
    events:
      - http:
          method: POST
          path: /users
  getPosts:
    handler: handlers/posts.handler
    events:
      - http:
          method: GET
          path: /posts

# removed when serverless-webpack included
# # only include the Prisma binary required on AWS Lambda while packaging
# package:
#   patterns:
#     - "!node_modules/.prisma/client/libquery_engine-*"
#     - "node_modules/.prisma/client/libquery_engine-rhel-*"
#     - "!node_modules/prisma/libquery_engine-*"
#     - "!node_modules/@prisma/engines/**"

```

**Comment by ThaFishDance** [comment, marked as answer]
**SOLUTION**
Serverless.yml
```
service: prisma-aws-lambda-example
plugins:
  - serverless-dotenv-plugin
  - serverless-bundle

package:
  individually: true

custom:
  bundle:
    packagerOptions:
      scripts:
        - npx prisma generate
    copyFiles:
      - from: "node_modules/.prisma/client/libquery_engine-rhel-openssl-1.0.x.so.node"
        to: "handlers/libquery_engine-rhel-openssl-1.0.x.so.node"
      - from: "node_modules/.prisma/client/schema.prisma"
        to: "handlers/schema.prisma"
        
        ^^^^^^^Magic happens here

....etc
```
Using serverless-bundle plugin, and explicitly moving the desired engine and schema to where your handlers are packaged.
ASIDE: Serverless-bundle is for TS files, you might have to mess with some configs or look at their docs to use only JS files
