### DISCUSSION TITLE
No available servers

### DISCUSSION THREAD

**Discussion by ariran5** [prisma/prisma#15288] [Q&A]
### Bug description

I use mongodb with docker image bitnami/mongodb:latest and prisma can't pull database on first steps

### How to reproduce

1. create nodejs project
2. use this database (docker-compose up)
```yaml
version: "3.9"

services:
  db:
    image: bitnami/mongodb:latest
    environment:
      MONGODB_REPLICA_SET_MODE: primary
      ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "27018:27017"
    volumes:
      - ./data/db:/data/db

```
3. prisma init
4. past mongodb://localhost:27018/qwe url to env
5. npx prisma db pull -> error 
```
Error: Error in connector: Error querying the database: Server selection timeout: No available servers. Topology: { Type: ReplicaSetNoPrimary, Servers: [ { Address: 172.19.0.2:27017, Type: Unknown, Error: timed out }, ] }
```

### Prisma information

```prisma
datasource db {
  provider = "mongodb"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}
```

```ts
```

### Environment & setup

- OS: Mac OS
- Database: bitnami/mongodb:latest (mongo 5.0.6) 
- Node.js version: 16.11 

### Prisma Version

```
4.3.1
```

(This setup works fine with server and mongo compass, but not work with prisma)
