### DISCUSSION TITLE
Migration Engine error:

### DISCUSSION THREAD

**Discussion by gscorrea10** [prisma/prisma#16139] [Q&A] [answered]
### Im trying to create a container for testing in my project, but i'm facing a lot problems recently to implement. I have a db local (mysql) and im not sure if is a future problem with a container to connect on prisma.

**error:**
```
gabriel@gabriel-Nitro-AN515-54:~/Desktop/my projects/omicron-backend$ dotenv -e .env.test -- npx prisma migrate deploy
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": MySQL database "mydb", schema "public" at "localhost:3306"

Error: Migration engine error:
Error querying the database: Unknown authentication plugin `sha256_password'.
```

Some infos:

**Environment & setup**
OS: Ubuntu 20.04
Database: mysql  Ver 8.0.31-0ubuntu0.20.04.1 for Linux on x86_64 ((Ubuntu))
Node.js version: v14.20.1

**schema.prisma:**

```
generator client {
  provider = "prisma-client-js"
}

generator erd {
  provider = "prisma-erd-generator"
}

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}
```

**docker-compose.yml:**

```
version: "3"

services:
  redis:
    image: 'bitnami/redis:latest'
    restart: always
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'redis_data:/bitnami/redis'
  test-db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '3308:3306'
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=mydb
      - MYSQL_ALLOW_EMPTY_PASSWORD=1

volumes:
  redis_data:
    driver: local

```

**.env.test:**

```DATABASE_URL="mysql://user:password@localhost:3306/mydb?schema=public"```

**.env**

```
DATABASE_URL="mysql://root:password@127.0.0.1:3306/omicron?schema=backend"
NODE_ENV="local"
```
I face some erros before like P1000 (authentication failed against database server) and P1017 (server has closed the connection).
I'm still "newbie" and learning how to use several environment variables with docker but I've already tried most of the solutions I found on the forums, but this error now is something I don't know how to deal with because in my local db it never happened before.

**Comment by pantharshit00** [comment]
Hello @gscorrea10 

Can you please try with the following `docker-compose.yml`:
```
version: "3"

services:
  redis:
    image: 'bitnami/redis:latest'
    restart: always
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'redis_data:/bitnami/redis'
  mysql:
    image: mysql:latest
    restart: always
    ports:
    - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql:/var/lib/mysql
volumes:
  redis_data:
    driver: local
  mysql:
  ```
  
  We currently don't support `sha256_password` authentication method for MySQL: https://github.com/prisma/prisma/issues/14417
  
  So you will need to omit the parameter that you setting and try again here.

**Comment by gscorrea10** [comment, marked as answer]
hi @pantharshit00 , i actually fix follow the prisma [github example](https://github.com/prisma/prisma/blob/main/docker/docker-compose.yml)

docker-compose.yml:
```
version: "3"

services:
  redis:
    image: 'bitnami/redis:latest'
    restart: always
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'redis_data:/bitnami/redis'
  test-db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password --lower_case_table_names=1
    restart: always
    ports:
      - '3307:3306'
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=mydb
      - MYSQL_ALLOW_EMPTY_PASSWORD=1

volumes:
  redis_data:
    driver: local
```

and my .env.test
```
DATABASE_URL="mysql://user:password@localhost:3307/mydb?schema=public"
```

idk why is working now because before the update i try using on .env.test the port 3306(same as local), and the port 3308. Now i just change the 3308 for 3307 (for me should be not something relevant to make changes) and i pass that flag on mysql image and everything is working perfectly. i will try later with this docker-compose example and see if works too.
Thanks for the support!
