### DISCUSSION TITLE
How to connect to DB using system environment variables?

### DISCUSSION THREAD

**Discussion by code-raisan** [prisma/prisma#17709] [Q&A] [answered]
I have looked for a way to connect to the DB with a system environment variable for use with Docker, but I can't find it, so I would appreciate it if you could tell me how to do this.

*We use DeepL translation

**Comment by nurul3101** [comment]
Hello @code-raisan 👋 

Can you have a look at this [example](https://www.prisma.io/docs/guides/testing/integration-testing#add-docker-to-your-project) that demonstrates how to connect to a database running in a docker container? 

Let me know in case you run into any issues.

**Comment by code-raisan** [comment]
I would like to set and use environment variables as follows.

```yml
version: '3.9'

services:
  db:
    image: postgres:13
    restart: always
    container_name: integration-tests-prisma
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: tests
  app:
      build: .
      environment:
        POSTGRES_USER: prisma
        POSTGRES_PASSWORD: prisma
        POSTGRES_DB: tests
```

How do I change the connection point or user by doing something like this?
