### DISCUSSION TITLE
error: Environment variable not found: DATABASE_URL.

### DISCUSSION THREAD

**Discussion by Helios69** [prisma/prisma#17731] [Q&A]
### Bug description

Hello. I'm struggling with connecting to a database running in the docker container alongside my main app (nestjs+prisma).
I'm getting the following error:

```
#0 9.627 Prisma schema loaded from prisma/schema.prisma                                                                                                
#0 9.646 Datasource "db": PostgreSQL database                                                                                                          
#0 9.652                                                                                                                                               
#0 9.654 Error: Prisma schema validation - (get-config wasm)                                                                                           
#0 9.654 Error code: P1012
#0 9.654 error: Environment variable not found: DATABASE_URL.
#0 9.654   -->  schema.prisma:10
#0 9.654    | 
#0 9.654  9 |   provider = "postgresql"
#0 9.654 10 |   url      = env("DATABASE_URL")
#0 9.654    | 
#0 9.654 
#0 9.654 Validation Error Count: 1
#0 9.654 [Context: getConfig]
#0 9.654 
#0 9.654 Prisma CLI Version : 4.9.0
```

Here is my docker-compose.yml file:

```
version: "3.8"
services:
  api:
    platform: linux/amd64
    container_name: api
    build: 
      context: ./api
      dockerfile: ./Dockerfile
      target: development
    command: npm run start:debug
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - PORT=4000
      - DATABASE_URL="postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@db:5432/${DATABASE_NAME}?schema=public"
    ports:
      - ${PORT}:${PORT}
      - 9229:9229
    volumes: 
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
  db:
    image: postgres
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
```

Dockerfile:

```
FROM node:14-alpine AS development

WORKDIR /usr/src/app

COPY package*.json ./
COPY prisma ./prisma/

RUN npm ci

RUN npx prisma generate
RUN npx prisma migrate deploy

COPY . .

RUN npm run build

FROM node:14-alpine AS production

ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm ci

COPY . .

COPY --from=development /usr/src/app/dist ./dist

CMD ["node", "dist/main"]

```

.env

```
PORT=4000

DATABASE_USER=username
DATABASE_PASSWORD=password
DATABASE_NAME=database

```

And that's my directory structure: 
```
├── Jenkinsfile
├── .env
├── api
│   ├── Dockerfile
│   ├── nest-cli.json
│   ├── package-lock.json
│   ├── package.json
│   ├── prisma
│   │   ├── migrations
│   │   └── schema.prisma
│   ├── src
│   │   ├── app.controller.ts
│   │   ├── app.module.ts
│   │   ├── app.service.ts
│   │   └── main.ts
│   ├── tsconfig.build.json
│   ├── tsconfig.json
│   └── yarn.lock
└── docker-compose.yml
```

note: my app is nested inside root directory, where i placed docker-compose and .env file 

### Prisma information

```
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model User {
  id    Int    @id @default(autoincrement())
  email String @unique
}

```

### Environment & setup

- OS: macOS
- Database: Postgres
- Node.js version: node:14-alpine

### Prisma Version

```
4.9.0
```

**Comment by Helios69** [comment]
Other than that, I think it wouldn't work anyway, because Prisma is trying to connect to the Postgres database before the container is actually initialized.

So my question is: is it possible to use Prisma in this case? With a database running in the same docker environment?

**Reply by atalayozmen** [reply]
Late reply, but I hope it will be helpful to others: 

I run a separate service in docker compose for the migration. It depends on db and backend, and also waits until database is initialized, using a script. Something like this:

```
version: '3.9'
services:

..other services

  devdb:
    image: postgres:13
    container_name: devdb
    ports:
      - '5432:5432'

  db-migration:
    build: .
    depends_on:
      - "devdb"
      - "backend"
    environment:
      DATABASE_URL: postgres://postgres:postgres@devdb:5432/devdb
    command: bash -c './wait-for-it.sh -h devdb -p 5432 && npx prisma migrate dev'
```

It uses the wait-for-it.sh script which you can find on GitHub. I used bash -c to execute multiple commands.

**Comment by Helios69** [comment]
I figured out how to solve the missing env variable issue, by passing it as build arg to the container, but the problem now, as I expected, Prisma cannot connect to the database server, as it is not running yet. Any suggestions, please? 

```
#0 9.353 Prisma schema loaded from prisma/schema.prisma                                                                                                
#0 9.369 Datasource "db": PostgreSQL database "database", schema "public" at "db:5432"                                                                 
#0 9.892                                                                                                                                               
#0 9.895 Error: P1001: Can't reach database server at `db`:`5432`
#0 9.895 
#0 9.895 Please make sure your database server is running at `db`:`5432`.
```

**Reply by nurul3101** [reply]
I believe this is related to this GitHub Discussion that is resolved now
- https://github.com/prisma/prisma/discussions/17735#discussioncomment-4867081

**Comment by ZhaoKunLong** [comment]
I have a similar problem with you. My database is locally and already running. There is no problem when I use the. env. File to develop in dev Mode. However, I encountered a problem when using docker-compose for injection.


```env
# .env  file
# DATABASE
DATABASE_URL="postgresql://root:root123@localhost:5432/test-dev"
```
When use the env file it works fine
When I use docker compose deploy it.

```yml
# docker compose file
version: "3" # optional since v1.27.0
services:
  app:
    image: test-image:latest
    ports:
      - "5050:3030"
    environment:
      - DATABASE_URL="postgresql://root:root123@my-ip:5432/test-dev"
```
It showed me the issue. DATABASE_URL does not validate the issue. as this 
```shell
PrismaClientInitializationError: error: Error validating datasource `db`: the URL must start with the protocol `postgresql://` or `postgres://`.
->  schema.prisma:10
    | 
 9 |   provider = "postgresql"
10 |   url      = env("DATABASE_URL")
    | 
```

After I tried so many times, finally I found it. `Double quotation marks` should be removed from environment variables. What a funny question, recorded here, to prevent others from encountering this problem.

```yml
# changed docker-compose file
version: "3" # optional since v1.27.0
services:
  app:
    image: test-image:latest
    ports:
      - "5050:3030"
    environment:
      - DATABASE_URL=postgresql://root:root123@my-ip:5432/test-dev
```
