### DISCUSSION TITLE
Cannot run prisma migrate in a Jenkins pipeline

### DISCUSSION THREAD

**Discussion by Helios69** [prisma/prisma#17735] [Q&A] [answered]
Hello.
I'm trying to run npx prisma migrate inside a Jenkins pipeline, but the job fails with the following error:
```
+ docker exec api yarn migrate:prod
yarn run v1.22.19
$ prisma migrate deploy
Prisma schema loaded from prisma/schema.prisma
Datasource "db": PostgreSQL database "database", schema "public" at "db:5432"

Error: P1001: Can't reach database server at `db`:`5432`

Please make sure your database server is running at `db`:`5432`.
```

Locally it works just fine with docker.
Here is my Jenkinsfile:
```
pipeline {
    agent any

    stages {
        stage('SCM Checkout'){
            steps {
                git branch: ...
            }
        }

        stage('Run Docker Compose') {
            environment {
                PORT = "4000"
                DATABASE_USER = "username"
                DATABASE_PASSWORD = "password"
                DATABASE_NAME = "database"
            }

            steps {
                sh 'docker-compose down --rmi all'
                sh "docker-compose up -d"
            }
        }

        stage('Run migrations') {
            steps {
                sh 'docker exec api yarn migrate:prod'
            }
        }
    }
}
```
package.json script:
```
"scripts": {
   ...
    "migrate:prod": "prisma migrate deploy"
}
```

docker-compose:
```
version: "3.8"
services:
  api:
    container_name: api
    build: 
      context: ./api
      dockerfile: ./Dockerfile
      target: development
      args:
        - DATABASE_USER=${DATABASE_USER}
        - DATABASE_PASSWORD=${DATABASE_PASSWORD}
        - DATABASE_NAME=${DATABASE_NAME}
    command: yarn start:debug
    restart: unless-stopped
    environment:
      - PORT=${PORT}
    ports:
      - ${PORT}:${PORT}
      - 9229:9229
    depends_on:
      db:
        condition: service_started
  db:
    image: postgres
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
```

Both docker and Jenkins are running on my local machine (Macbook Pro M1 Pro).
