### DISCUSSION TITLE
Google Cloud Build keeps on giving me 'Can't reach database server at'

### DISCUSSION THREAD

**Discussion by bowis** [prisma/prisma#17748] [Q&A]
So I have been at this for days now almost and it is driving me crazy. Based on other posts here and on stackoverflow, I have set up the following `cloudbuild.yaml` :

```
steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - gcr.io/${INSTANCE_NAME}
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - gcr.io/${INSTANCE_NAME}
  - name: 'gcr.io/${INSTANCE_NAME}'
    entrypoint: sh
    env:
      - DATABASE_URL=postgresql://USER:PASSWORD@localhost/DATABASE?host=/cloudsql/CONNECTION_NAME
    args:
      - -c
      - |
        wget https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64 -O cloud_sql_proxy
        chmod +x cloud_sql_proxy
        ./cloud_sql_proxy -instances=CONNECTION_NAME=tcp:5432 & sleep 3
        npx prisma migrate deploy
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - backend
      - --image
      - gcr.io/${INSTANCE_NAME}
      - --region
      - europe-west1
images:
  - gcr.io/${INSTANCE_NAME}
```

When running this, I am greeted by: 

```
Step #2: 2023/02/05 13:00:49 Listening on 127.0.0.1:5432 for CONNECTION_NAME
Step #2: 2023/02/05 13:00:49 Ready for new connections
Step #2: 2023/02/05 13:00:49 Generated RSA key in 118.117245ms
Step #2: npm WARN exec The following package was not found and will be installed: prisma@4.9.0
Step #2: Prisma schema loaded from prisma/schema.prisma
Step #2: Datasource "db": PostgreSQL database "develop", schema "public" at "localhost"
Step #2: 
Step #2: Error: P1001: Can't reach database server at `/cloudsql/CONNECTION_NAME`:`5432`
Step #2: 
Step #2: Please make sure your database server is running at `/cloudsql/CONNECTION_NAME`:`5432`.
```

So even with using the database url hardcoded and with the Cloud SQL proxy working, i am STILL getting this error. What am I missing?
