### DISCUSSION TITLE
Solved: prisma 4.10 (mongodb) in docker container: server selection timeout

### DISCUSSION THREAD

**Discussion by mpgalaxy** [prisma/prisma#17833] [Q&A] [answered]
Hi,
I adapted the graphql-nexus example from prisma-examples to mongodb, provided our database as replica set (mongodb and keycloak running in docker-compose with ports exposed to localhost) and running the service from localhost everything is working perfectly fine (yarn dev as well as start), I can access and use the db without any problems.
As soon as I put this prisma 4.10 service into a docker container prisma runs into timeout trying to connect to the mongo container. I can access the mongo container without any problems from nosqlbooster on localhost and in our large dev environment the old prisma1 and python services also connect to this mongo replica set without any problems, so I suspect this to be a bug in prisma client, but maybe I made a mistake I didn't see....here some facts:

- graphql-nexus example with graphql 16
- prisma 4.10
- prisma client 4.10
- docker image based on node:16.1.0-alpine3.13
- linux system of localhost: arch linux x64
- Docker version 20.10.23, build 715524332f
- Docker Compose version 2.15.1

Running a test query on the service in docker container it takes about 30 seconds then resulting in this error:
`Invalid 'ctx.prisma.form.findMany()' invocation in\n/usr/src/app/src/schema.ts:274:34\n\n  271 },\n  272 resolve: (_parent, args, ctx: Context) => {\n  273   return {\n→ 274     forms: ctx.prisma.form.findMany(\nRaw query failed. Code: 'unknown'. Message: 'Server selection timeout: No available servers. Topology: { Type: ReplicaSetNoPrimary, Servers: [ { Address: localhost:27017, Type: Unknown, Error: Address not available (os error 99) }, ] }`

Somehow prisma or the rust mongo connector falls back to default ( ` localhost:27017` ) although `DATABASE_URL` is provided correctly to the docker contrainer:
```
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mongodb"
  url      = env("DATABASE_URL")
}
....
```
`DATABASE_URL` in .env file:
`DATABASE_URL=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_HOST}:${MONGO_PORT}/formdb_default?retryWrites=true&w=majority&authSource=admin`

with env variables provided via docker-compose.
The connection information in the docker container are correct, debug output gives me
```
🚀 Test-Service ready at: http://localhost:4003/
Prisma DATABASE_URL: mongodb://admin:admin@mongo:27017/formdb_default?retryWrites=true&w=majority&authSource=admin
```
Strange thing is that somehow the rust mongo connector tries to connect on a different port:
```
mongo  | {"t":{"$date":"2023-02-09T08:34:55.056+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn24","msg":"Connection ended","attr":{"remote":"192.168.123.12:50824","connectionId":24,"connectionCount":16}}
```
192.168.123.12 is the IP of the prisma docker container which is fine, but it tries to connect on port 50824, not 27017 which is strange.

The error message from the prisma service in docker logs is:
```
test-service  | 2023-02-09T08:34:54.946Z prisma:client:request_handler  PrismaClientInitializationError: Raw query failed. Code: `unknown`. Message: `Server selection timeout: No available servers. Topology: { Type: ReplicaSetNoPrimary, Servers: [ { Address: localhost:27017, Type: Unknown, Error: Address not available (os error 99) }, ] }`
test-service  |     at startFn (/usr/src/app/node_modules/@prisma/engine-core/src/library/LibraryEngine.ts:380:17)
test-service  |     at Gt.getDmmf (/usr/src/app/node_modules/@prisma/engine-core/src/library/LibraryEngine.ts:438:5)
test-service  |     at /usr/src/app/node_modules/@prisma/client/src/runtime/getPrismaClient.ts:1117:22
test-service  |     at /usr/src/app/node_modules/@prisma/client/src/runtime/getPrismaClient.ts:1127:24
test-service  |     at t._executeRequest (/usr/src/app/node_modules/@prisma/client/src/runtime/getPrismaClient.ts:1046:33)
test-service  |     at t._request (/usr/src/app/node_modules/@prisma/client/src/runtime/getPrismaClient.ts:1021:14) {
test-service  |   clientVersion: '4.10.0',
test-service  |   errorCode: 'P2010'
test-service  | }
```
Minimal docker-compose:
```
version: '3.5'
services:
  mongo:
    hostname: mongodb
    container_name: test-mongo
    image: mongo:4.4
    restart: always
    volumes:
      - ../scripts:/docker-entrypoint-initdb.d/
      - ${LOCAL_MONGO_DIR}:/data/db
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    ports:
      - "27017:27017"
    networks:
      - mytest_intern
  postgres:
    container_name: postgres-keycloak
    restart: always
    image: postgres:11-alpine
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ${LOCAL_POSTGRES_DIR}:/var/lib/postgresql/data
    networks:
      - mytest_intern
  auth:
    container_name: auth-test
    restart: always
    image: quay.io/keycloak/keycloak:19.0.2
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      PROXY_ADDRESS_FORWARDING: "true"
      KC_HOSTNAME_STRICT: "false"
      KC_HTTP_ENABLED: "true"
      KC_PROXY: "edge"
    entrypoint: /opt/keycloak/bin/kc.sh start-dev
    depends_on:
      - postgres
    ports:
      - ${KEYCLOAK_PORT}:8080
    networks:
      - mytest_intern
  sometest:
    container_name: test-service
    restart: always
    image: test-service:0.1
    environment:
      NODE_OPTIONS: ${NODE_OPTIONS}
      # NODE_ENV: production
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      KEYCLOAK_HOST: ${KEYCLOAK_HOST}
      KEYCLOAK_SCHEME: ${KEYCLOAK_SCHEME}
      KEYCLOAK_PORT: ${KEYCLOAK_PORT}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      IS_KEYCLOAK_QUARKUS : ${IS_KEYCLOAK_QUARKUS}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
      TEST_PORT: 4003
    depends_on:
      - mongo
    links:
      - mongo
    ports:
      - ${TEST_PORT}:${TEST_PORT}
    networks:
      - mytest_intern
networks:
  mytest_intern:
    name: mytest_intern
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.123.0/24
```
As mentioned above the mongo replica set works perfectly fine, I can access it from localhost and other dev services (provided in dev docker-compose, but this compose has the minimal most important stuff), only prisma can't connect to it.

Dockerfile:
```
ROM node:16.1.0-alpine3.13

RUN yarn global add prisma && yarn cache clean
WORKDIR /usr/src/app

COPY package.json ./
COPY yarn.lock ./
COPY startup.sh ./

RUN apk update && apk upgrade --no-cache && apk add --no-cache bash less curl ca-certificates nano iputils
RUN yarn install \
      --prefer-offline \
      --frozen-lockfile \
      --non-interactive && yarn cache clean

COPY . .
RUN chmod +x ./wait-for-it.sh
RUN chmod +x ./startup.sh

RUN npx prisma generate

EXPOSE 4000
CMD ["sh", "startup.sh"]
```
with startup.sh
```
export DEBUG="*" && update-ca-certificates
./wait-for-it.sh -t 0 ${MONGO_HOST}:${MONGO_PORT} -- yarn dev
```

Even if I remove the custom network from docker-compose the error stays the same, makes no difference. Prisma service connects perfectly fine to the mongo replica set from localhost, but fails in docker container.

I event tried with different params in the connection string, but the error stays the same:
```
DATABASE_URL=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_HOST}:${MONGO_PORT}/formdb_default?authSource=admin&directConnection=true
```
The prisma docker service starts in dev mode and I can access the graphql sandbox via localhost, but running the test query in the sandbox results in the same error (which is consistent).

Any ideas ? I think this is a bug in prisma client....

**I found the reason:** In our dev-compose I provided the DATABASE_URL via docker-compose environment and in the .env of the service. The string is the same, but this seems to confuse prisma, after removing the env variable from compose env it worked. 

I'll leave the information in here, maybe it helps some people regarding mongo replica set, docker-compose or keycloak. ;)
