### DISCUSSION TITLE
prisma-client.js and postgres under docker (I see a lot of issues about this but they  can't fix it(or I don't understood something))

### DISCUSSION THREAD

**Discussion by Perry-chouteau** [prisma/prisma#17888] [Q&A] [answered]
Hey I'm using prisma and want to make simple call with client.js and db under docker:

The error is:

```sh
docker-sign     | PrismaClientInitializationError: 
docker-sign     | Invalid `this.prisma.user.create()` invocation in
docker-sign     | /app/prisma-client.js:10:40
docker-sign     | 
docker-sign     |    7 
docker-sign     |    8 async signUp(username, password) {
docker-sign     |    9     console.log('>' + username.toString() + ' ' + password.toString());
docker-sign     | → 10             await this.prisma.user.create(
docker-sign     | Can't reach database server at `localhost`:`7000`
docker-sign     | 
docker-sign     | Please make sure your database server is running at `localhost`:`7000`.
docker-sign     |     at Kr.handleRequestError (/app/node_modules/@prisma/client/runtime/library.js:163:19773)
docker-sign     |     at Kr.handleAndLogRequestError (/app/node_modules/@prisma/client/runtime/library.js:163:19031)
docker-sign     |     at /app/node_modules/@prisma/client/runtime/library.js:173:282
docker-sign     |     at async /app/node_modules/@prisma/client/runtime/library.js:173:397
docker-sign     |     at async t._executeRequest (/app/node_modules/@prisma/client/runtime/library.js:173:9985)
docker-sign     |     at async t._request (/app/node_modules/@prisma/client/runtime/library.js:173:9714)
docker-sign     |     at async AreaPrismaClient.signUp (/app/prisma-client.js:10:17) {
docker-sign     |   clientVersion: '4.10.1',
docker-sign     |   errorCode: undefined
docker-sign     | }
docker-sign     | 
docker-sign     | Node.js v19.6.0
docker-gateway  | 1 CANCELLED: Call cancelled
docker-sign exited with code 0
```

and need some help:

## prisma.js
```js
const { PrismaClient } = require('@prisma/client');

class AreaPrismaClient {
    constructor () {
        this.prisma = new PrismaClient();
    }

    async signUp(username, password) {

                    await this.prisma.user.create({
                        data: {
                          email: username,
                          password: password,
                        },
                    })
    }
}

module.exports = AreaPrismaClient;
```
## shema.prima
```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

// @description User
model User {
  id            Int         @id @unique @default(autoincrement())
  createdAt     DateTime    @default(now())
  updatedAt     DateTime    @updatedAt

  email         String      @unique
  password      String
  name          String?
  token         String?
  tokenTime     DateTime?
}
```

## env
```sh
DATABASE_URL="postgresql://user:password@localhost:7000/db?schema=public"
```

## dockerfile
```dockerfile
FROM node:19-alpine3.16

WORKDIR /app

COPY package*.json ./
COPY prisma ./prisma/
COPY .env  ./.env

RUN npm install
RUN npm install prisma
RUN npx prisma migrate
RUN npx prisma generate
RUN npm install prisma --save-dev
RUN npx prisma migrate
RUN npm install @prisma/client

COPY . .

EXPOSE 7001

CMD [ "node", "server.js" ]
```
yes I've over test combination

## docker-compose
```yml
version: '3'

services:
  sign:
    container_name: docker-sign
    build:
      context: ./services/sign
      dockerfile: Dockerfile
    ports:
      - "7001:7001"
    networks:
      - sign-tier
#      - database-tier
    restart: unless-stopped

# https://hub.docker.com/_/postgres
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "7000:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - sign-tier
    restart: unless-stopped

networks:
  sign-tier:


volumes:
  pgdata:
```

I runing container wich test it under docker 

If you need more information to help me or to explain better what I've done.. ask me ..
I'm locked for  7 days  in the prisma understanding
