### DISCUSSION TITLE
Struggling with Nest.js Serverless Deploy | Error: Cannot find module '.prisma/client/index'

### DISCUSSION THREAD

**Discussion by SendDerek** [prisma/prisma#18722] [Q&A] [answered]
I have a Nest.js + Prisma application successfully running locally via `prisma generate` and `npm run start:dev`.  I'm able to use serverless to deploy the .zip package to S3 and get a Lambda function working.  However, when I attempt to open a "Hello world" page, I'm met with:

```
{
"message": "Internal server error"
}
```

Digging into the error logs, I see:
```
message:"Error: Cannot find module '.prisma/client/index'
Require stack:
- /var/task/node_modules/@prisma/client/index.js
- /var/task/dist/src/prisma/prisma.service.js
- /var/task/dist/src/users/users.service.js
- /var/task/dist/src/users/users.module.js
- /var/task/dist/src/app.module.js
- /var/task/dist/src/lambda.js
- /opt/sls-sdk-node/wrapper.js
- /var/runtime/index.mjs"
name:"Runtime.ImportModuleError"
type:"ERROR_TYPE_UNCAUGHT"
}
```

There are a few bug reports that look familiar, but none of them have resolved my issue:
https://github.com/prisma/prisma/issues/5266
https://github.com/prisma/prisma/issues/10813
https://github.com/prisma/prisma/discussions/10787

This has been a road blocker for me, so I'm hoping somebody will be kind enough to help me through it.  Please let me know what you need to see as far as configuration files.  I'm sure you'd like to see my serverless.yml file, so here we are:

```
service: backend
frameworkVersion: '3'

plugins:
  - serverless-jetpack
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs16.x
  region: us-west-2

functions:
  api:
    handler: dist/src/lambda.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'
```

Thanks in advance. 🙏 😄
