### DISCUSSION TITLE
When connect to mysql, prisma thow: P1017: Server has closed the connection.  please help

### DISCUSSION THREAD

**Discussion by wine-fall** [prisma/prisma#18805] [Q&A] [answered]
my docker-compose.yml
```yml
version: '3.8'
services:
  dev-db:
    image: mysql:latest
    container_name: nest-dev
    environment:
      - "MYSQL_ROOT_PASSWORD=123"
      - "MYSQL_DATABASE=mysql"
      - MYSQL_USER=prisma
    ports:
      - 5434:5432
```
my .env file
```env
DATABASE_URL="mysql://mysql:123@localhost:5434/nest-dev?schema=public"
```

my schema.prisma file 
```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}

model User {
  id        Int      @id @default(autoincrement())
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt

  email String @unique()
  hash  String

  firstName String?
  lastName  String?

  bookmarks Bookmark[]

  @@map("users")
}
```

I run the sql sever successfully using this two commands
```
pnpm docker compose rm dev-db -s -f -v
pnpm docker compose up dev-db -d
```
here is when I run `docker ps`

![image](https://user-images.githubusercontent.com/62830944/232794604-0684bddc-643e-40dc-9d64-ded6b10c887d.png)

and I run
```
pnpm prisma migrate dev
```

here is all the output
![image](https://user-images.githubusercontent.com/62830944/232795621-afc88d0b-761d-4c13-94fd-a1f81325093a.png)

please help me!

**Comment by ludralph** [comment]
Hi @wine-fall 

Shouldn't `MYSQL_USER=prisma` be in quotes in your docker-compose.yml file

**Reply by wine-fall** [reply]
Hi @ludralph :

thank u for reply, and I just update my `docker-compose.yml` to be
```yml
version: '3.8'
services:
  dev-db:
    image: mysql:latest
    container_name: nest-dev
    environment:
      - "MYSQL_ROOT_PASSWORD=123"
      - "MYSQL_DATABASE=mysql"
      - "MYSQL_USER=prisma"
    ports:
      - 5434:5432
```

However, it doesn't work.

**Reply by ludralph** [reply]
for your ports, can you please show what happens if you set it to
 ```yml
ports:
    - 5432:5432
```
Also, can you verify that the MySQL port is 5434 or 3306?

**Reply by wine-fall** [reply]
Here are the latest file

docker-compose.ym
```yml
version: '3.8'
services:
  dev-db:
    image: mysql:latest
    container_name: nest-dev
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_DATABASE=mysql
      - MYSQL_USER=prisma
    ports:
      - 3306:3306
```
.env
```env
DATABASE_URL="mysql://mysql:123@localhost:3306/nest-dev?schema=public"
JWT_SECRET="JWT_SECRET"
```

I have run the sql sever by docker and when I run `docker ps`, you can see the result:
![image](https://user-images.githubusercontent.com/62830944/232951685-f794e633-9637-4f24-a7cc-544f504bbb4d.png)
