### DISCUSSION TITLE
Prisma error P1001 on server after migrate deploy

### DISCUSSION THREAD

**Discussion by Xazgl** [prisma/prisma#19960] [Q&A]
I have several subdomains on the server with next.js and prism where everything works as it should, but I added radish to one of them and now I can't do migrations, and when I try to do them manually, I get the error:

data source "DB": PostgreSQL DB "db-arkont", schemes "Public" to "db-arkont:5432"

Error: P1001: Unable to contact database server at `db-arkont':`5432`

Please make sure that your database server is running at `db-arkont`:`5432'.
Help me understand what the reason is, not installing redis migrations took place on this subdomain, as they should, that's why I associate this error with my incorrect tincture of content after installing redis

My docker-compose: version: '3.4'

  ```yml
app-arkont:
    container_name: app-arkont
    image: arkont-image
    build:
      context: arkont
      dockerfile: Dockerfile
    restart: always
    environment:
      NODE_ENV: production
    networks:
      - arkont-net
    env_file: 
      - arkont/.env
    ports:
      - 7000:3000
    depends_on:
      - "db-arkont"
    command: sh -c "sleep 13 && npx prisma migrate deploy && npm start"
    links:
      - redis:redis   
 
  redis:
    container_name: redis
    image: redis:latest
    restart: always
    environment:
      NODE_ENV: production
      REDIS_HOST: my host
      REDIS_PORT: 6379 
    ports:
      - 6379:6379
    command: redis-server start
    networks:
      - arkont-net
      
  db-arkont:
    container_name: db-arkont
    env_file:
      - arkont/.env
    image: postgres:latest
    restart: always
    volumes:
      - db-arkont-data:/var/lib/postgresql/data
    networks:
      - arkont-net

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      - PMA_ARBITRARY=1
    networks:
      - arkont-net


volumes:
  db-arkont-data: {}
networks:
  arkont-net:
    name: arkont-net
```

Dockerfile:

```docker
FROM node:lts-alpine AS builder


# Create app directory
WORKDIR /app

# A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY package*.json ./
COPY prisma ./prisma/
COPY next.config.js ./

# Install app dependencies
RUN npm install
RUN npx prisma generate


COPY . .

RUN npm run build

FROM node:lts-alpine

WORKDIR /app

COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public
COPY --from=builder /app/prisma ./prisma
COPY --from=builder /app/next.config.js ./


# Install Redis
RUN apk add --update redis


# # Stop Redis service
# RUN pkill redis-server && redis-cli shutdown

# Copy Redis configuration file
COPY redis.conf /usr/local/etc/redis/redis.conf  


# Set ownership and permissions for Redis configuration file
RUN chown redis:redis /usr/local/etc/redis/redis.conf

# Set Redis configuration
ENV REDIS_HOST=https://test.opel-arkont-volgograd.ru
ENV REDIS_PORT=6379

ENV NODE_ENV=production



EXPOSE 3000

    
 CMD ["npx", "prisma", "migrate", "deploy", "--preview-feature"]
```
env:
```

POSTGRES_USER=User
POSTGRES_PASSWORD=password
POSTGRES_DB=arkont-db
HOST=https://myhost.com

REDIS_HOST=https://myhost.com
REDIS_PORT=6379

DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db-arkont:5432/${POSTGRES_DB}?schema=public

```
