### DISCUSSION TITLE
Enums are undefined - cannot read properties of undefined

### DISCUSSION THREAD

**Discussion by t3bld** [prisma/prisma#20575] [Q&A]
### Bug description

I would like to use enums in my Prisma model. Unfortunately, I get an error when I want to access the enum. I already run Prisma generation, there is no import issue.

```js
import {$Enums, BlogStateType} from "@prisma/client";
...
console.log(BlogStateType.generating);
```

> TypeError: Cannot read properties of undefined (reading 'BlogStateType').

### How to reproduce

**schema.prisma**
```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mongodb"
  url = env("DATABASE_URL")
}

model Blog {
  id String @id @default(auto()) @map("_id") @db.ObjectId
  blogType BlogStateType
}

enum BlogStateType {
  generating
  errorDuringGeneration
  generated
}
```

**tsconfig.json**
```json
{
    "compilerOptions": {
      "target": "es2020",
      "strict": true,
      "preserveConstEnums": true,
      "experimentalDecorators": true,
      "noEmit": true,
      "sourceMap": false,
      "module":"commonjs",
      "moduleResolution":"node",
      "esModuleInterop": true,
      "skipLibCheck": true,
      "forceConsistentCasingInFileNames": true,
      "isolatedModules": true
    },
    "exclude": ["node_modules"]
  }
```

### Prisma information

```prisma
// Add your schema.prisma
```

```ts
// Add your code using Prisma Client
```

### Environment & setup

macOS
MongoDB
Node 18.16.0

### Prisma Version

"@prisma/client": "^5.1.1"

**Comment by ludralph** [comment]
Hi @ArkasDev 👋 

Did you run `npx prisma generate` to generate the Prisma client?

Also, to use enums, you can import it and use it as shown below:

```ts
import { PrismaClient, BlogStateType  } from '@prisma/client';

const prisma = new PrismaClient();

const blog = await prisma.blog.create({
    data:{
      blogType: BlogStateType.generated
    }
  });
```

This should now create the record in the database as shown with this output:
```js
{ id: '64d0a00703518e92e151013e', blogType: 'generated' }
```

If this answers your question, it would be great if you could **mark this Discussion as answered** to indicate that it has been resolved. 

Otherwise please let us know how else we can help you further or close the Discussion if it was resolved in some other way 🙏

**Reply by t3bld** [reply]
The problem is that I can't use the enum in my code because all enums are undefined. E.g. I cannot check the type using the enum via Prisma. 

```
import { PrismaClient, BlogStateType  } from '@prisma/client';

if(type === BlogStateType.generated) {
}
```

I already run `npx prisma generate`. 

I am deploying the code in an AWS Lambda function. I am not sure, but maybe there is a problem with this combination. My deploying info below:

**template.yaml**
```
Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 900
      MemorySize: 512
      CodeUri: .../generate-blog-post-v1
      Handler: index.handler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /generate-blog-post-v1
            Method: post
    Metadata:
      SamResourceId: Function
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - index.ts

```
