### DISCUSSION TITLE
Dockerize Prisma : Prisma Client was generated for "windows"

### DISCUSSION THREAD

**Discussion by r4ch1d76** [prisma/prisma#20747] [Q&A]
### Question

Bonjour,

When I execute my container using docker compose up, I receive the message: "Prisma Client was generated for 'windows', but the actual deployment required 'debian-openssl-1.1.x'." This error occurs when I try to docker compose up.

### Expected behavior (optional)

Consequently, I added binaryTargets = ["native", "debian-openssl-1.1.x", "linux-musl"], but it didn't work and find the cause of this problem. The error stops the construction of the image.

### Information about Prisma Schema, Client Queries and Environment (optional)

```prisma
datasource db {
  provider = "postgres"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

```

`Logs`
```shell
This happened because Prisma Client was generated for "windows", but the actual deployment required "debian-openssl-1.1.x".
server_container    | Add "debian-openssl-1.1.x" to `binaryTargets` in the "schema.prisma" file and run `prisma generate` after saving it:
server_container    |
server_container    | generator client {
server_container    |   provider      = "prisma-client-js"
server_container    |   binaryTargets = ["native", "debian-openssl-1.1.x"]
server_container    | }
server_container    |
server_container    | The following locations have been searched:
server_container    |   /app/node_modules/.prisma/client
server_container    |   /app/node_modules/@prisma/client
server_container    |   C:\Users\Chirac\OneDrive\Documents\Github\PasteBox\node_modules\@prisma\client
server_container    |   /tmp/prisma-engines
server_container    |   /app/src/prisma
server_container    |     at Lo (/app/node_modules/@prisma/client/runtime/library.js:55:776)
server_container    |     at async wr.loadLibrary (/app/node_modules/@prisma/client/runtime/library.js:101:598)
server_container    |     at async _t.loadEngine (/app/node_modules/@prisma/client/runtime/library.js:103:537)
server_container    |     at async _t.instantiateLibrary (/app/node_modules/@prisma/client/runtime/library.js:102:1708)
server_container    |     at async _t.start (/app/node_modules/@prisma/client/runtime/library.js:103:2254)
server_container    |     at async connectToDatabase (/app/src/config/database.js:7:5) {
server_container    |   clientVersion: '5.0.0',
server_container    |   errorCode: undefined
server_container    | }
```

`Dockerfile`
```shell
# syntax=docker/dockerfile:1
FROM node:lts

RUN mkdir -p /usr/src
WORKDIR /usr/src/

ENV HTTPS_SERVER_PORT=${HTTPS_SERVER_PORT}
ENV HTTP_SERVER_PORT=${HTTP_SERVER_PORT}
ENV DATABASE_DIALECT=${DATABASE_DIALECT}
ENV DATABASE_URL=${DATABASE_URL}
ENV PASTEBOX_COOKIE_SECRET=${PASTEBOX_COOKIE_SECRET}

COPY package*.json ./
RUN npm install
# If you are building your code for production
# RUN npm ci --omit=dev

# Bundle app source
COPY . .

EXPOSE 8080
CMD [ "npm", "run", "start" ]
```

`docker-compose.yaml`
```
version: '3'

services:

  server:
    depends_on:
      # dépendance du service database, d'abord lancement du database puis du service server
      - database
    image: node:16
    container_name: chirac_server_container
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "${HTTP_SERVER_PORT}:${HTTP_SERVER_PORT_CONTAINER}"
      - "${HTTPS_SERVER_PORT}:${HTTPS_SERVER_PORT_CONTAINER}"
    restart: always
    environment:
      HTTPS_SERVER_PORT: "${HTTPS_SERVER_PORT}"
      HTTP_SERVER_PORT: "${HTTP_SERVER_PORT}"
      DATABASE_DIALECT: "${DATABASE_DIALECT}"
      DATABASE_URL: "${DATABASE_URL}"

    command: ["npm", "run", "start"]

  database:
    image: postgres:15
    container_name: chirac_database_container
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${DATABASE_PORT}:${DATABASE_CONTAINER_PORT}"
    restart: always
    environment:
      POSTGRES_USER: "${DATABASE_USERNAME}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
      POSTGRES_DB: "${DATABASE_NAME}"

  adminer:
    image: adminer
    container_name: chirac_adminer_container
    ports:
      - "${ADMINER_PORT}:${ADMINER_CONTAINER_PORT}"
    restart: always

volumes:
  pgdata:
```
`.env`
```shell
# Server
HTTPS_SERVER_PORT=8080
HTTP_SERVER_PORT=8081

# Database
DATABASE_DIALECT=postgres
DATABASE_HOST=127.0.0.1
DATABASE_PORT=5432
DATABASE_USERNAME=postgres
DATABASE_PASSWORD=password
DATABASE_NAME=chirac_database
DATABASE_SCHEMA=public
DATABASE_URL="postgresql://postgres:password@127.0.0.1:5432/chirac_database?schema=public"

ADMINER_PORT=8082

# Ports container
HTTPS_SERVER_PORT_CONTAINER=8000
HTTP_SERVER_PORT_CONTAINER=8001
DATABASE_CONTAINER_PORT=8002
ADMINER_CONTAINER_PORT=8003
```

- OS: Windows
- Database: PostgreSQL
- Node.js version: v16.18.0

prisma : 5.0.0
@prisma/client : 5.0.0
