### DISCUSSION TITLE
Error: P1001: Can't reach database server at `localhost`:`5432`

### DISCUSSION THREAD

**Discussion by ParasPandeyE** [prisma/prisma#20794] [Q&A] [answered]
### Bug description

I have a docker container running with postgres but prisma cant find the database server when i run npx prisma migrate dev

In my docker GUI it says that I have a running container with a name of postgres on PORT:5432

Output of docker ps:
`
CONTAINER ID   IMAGE         COMMAND                  CREATED       STATUS         PORTS                                       NAMES
fc318265578e   postgres:13   "docker-entrypoint.s…"   2 hours ago   Up 15 minutes   0.0.0.0:5434->5432/tcp, :::5434->5432/tcp   nest-api-dev-db-1
`
The error i get is

Error: P1001: Can't reach database server at `postgres`:`5432`

### How to reproduce

Please make sure your database server is running at `postgres`:`5432`.

How to reproduce
Install prisma and @prisma/client
run npx prisma init to get the following schema

```prisma
generator client {
   provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url = env("DATABASE_URL")
}
```

add the docker-compose.yml file

```yml
version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks:
      - myntwk
networks:
  myntwk:
```

Add database string to .env
`DATABASE_URL="postgresql://postgre:123@localhost:5432/nest?schema=public"`

run docker compose up 
run npx prisma migrate dev

### Expected behavior

Successful migration 

### Prisma information

```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}
```

### Environment & setup

- OS: MacOs
- Database: PostgreSQL
- Node.js version: 16.17.0

### Prisma Version

```
"prisma": "^5.1.1"
```
