### DISCUSSION TITLE
mongodb_replica always Error: couldn't connect to server 127.0.0.1:27017

### DISCUSSION THREAD

**Discussion by febrimaulana** [prisma/prisma#20820] [Q&A]
### Question

i want to ask following my Dockerfile

```
FROM mongo:4

# we take over the default & start mongo in replica set mode in a background task
ENTRYPOINT mongod --port $MONGO_REPLICA_PORT --replSet rs0 --bind_ip 0.0.0.0 & MONGOD_PID=$!; \
# we prepare the replica set with a single node and prepare the root user config
INIT_REPL_CMD="rs.initiate({ _id: 'rs0', members: [{ _id: 0, host: '$MONGO_REPLICA_HOST:$MONGO_REPLICA_PORT' }] })"; \
INIT_USER_CMD="db.getUser('$MONGO_INITDB_ROOT_USERNAME') || db.createUser({ user: '$MONGO_INITDB_ROOT_USERNAME', pwd: '$MONGO_INITDB_ROOT_PASSWORD', roles: [ 'root' ] })"; \
# we wait for the replica set to be ready and then submit the commands just above
until (mongo admin --port $MONGO_REPLICA_PORT --eval "$INIT_REPL_CMD && $INIT_USER_CMD"); do sleep 1; done; \
# we are done but we keep the container by waiting on signals from the mongo task
echo "REPLICA SET ONLINE"; wait $MONGOD_PID;
```
here is my docker compose
```
version: '3.8'
services:
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
  mongo:
    build: ./configs/docker/mongodb
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_REPLICA_HOST: 127.0.0.1
      MONGO_REPLICA_PORT: 27017
    volumes:
      - mongo-data:/data/db
volumes:
  redis-data:
  mongo-data:
```
why always error when running
```
MongoDB shell version v4.4.23
answer-user-service-mongo-1  | connecting to: mongodb://127.0.0.1:27017/admin?compressors=disabled&gssapiServiceName=mongodb
answer-user-service-mongo-1  | Error: couldn't connect to server 127.0.0.1:27017, connection attempt failed: SocketException: Error connecting to 127.0.0.1:27017 :: caused by :: Connection refused :
answer-user-service-mongo-1  | connect@src/mongo/shell/mongo.js:374:17
answer-user-service-mongo-1  | @(connect):2:6
answer-user-service-mongo-1  | exception: connect failed
answer-user-service-mongo-1  | exiting with code 1
```
