### DISCUSSION TITLE
Error: @prisma/client did not initialize yet. Please run "prisma generate" and try to import it again.

### DISCUSSION THREAD

**Discussion by vikasrathod4299** [prisma/prisma#21187] [Q&A]
### Question

I have containerize my node application with docker and getting this error in app container stating Prisma Client is not generated 
But in logs of prisma container we can see that prisma client is generated. 

Here are logs from docker compose

![image](https://github.com/prisma/prisma/assets/13855608/d7135fe7-01e4-455a-8815-a0e78ef5adb2)

Here is my compose file
```
version: "3"
services:
  db:
    image: postgres
    container_name: my_postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: v-chat
    ports:
      - "5432:5432"

  prisma:
    image: v-chat/client
    container_name: my_prisma_migration
    environment:
      DATABASE_URL: postgres://postgres:1234@db:5432/v-chat
    depends_on:
      - db
    volumes:
      - ./src/prisma:/app/src/prisma
    command: "npx prisma migrate dev --schema=/app/src/prisma/schema.prisma"

  app:
    image: v-chat/client
    ports:
      - "3002:3001"
    depends_on:
      - prisma 
```
