### DISCUSSION TITLE
Database url can not be found by prisma in docker

### DISCUSSION THREAD

**Discussion by rukaiyafahmida** [prisma/prisma#21212] [Q&A] [answered]
### Question

Database url can not be found by prisma

hello, I have been trying to dockerize my nestjs app and prisma, but i am facing this error saying it can't find the `DATABASE_URL`.   

```bash
` > [7/9] RUN npx prisma db push:
#0 0.910 Prisma schema loaded from prisma/schema.prisma
#0 0.913 Datasource "db": PostgreSQL database
#0 0.914 
#0 0.914 Error: Prisma schema validation - (get-config wasm)
#0 0.914 Error code: P1012
#0 0.914 error: Environment variable not found: DATABASE_URL.
#0 0.914   -->  schema.prisma:10
#0 0.914  9 |   provider = "postgresql"
#0 0.914 10 |   url      = env("DATABASE_URL")
#0 0.914 Validation Error Count: 1\
#0 0.914 Prisma CLI Version : 5.3.1
------
failed to solve: executor failed running [/bin/sh -c npx prisma db push]: exit code: 1`

```

this is my Dockerfile:

```
FROM node:18
WORKDIR /app

COPY package*.json ./
COPY prisma ./prisma/

RUN npm install
RUN npx prisma generate 
RUN npx prisma db push

COPY . .

RUN npm run build
CMD [ "npm", "run", "start:dev" ]
```    

.env file:

```
DATABASE_URL="postgresql://postgres:abcd@practice-nest-postgres:5432/nest?schema=public"

```   

docker-compose.yaml:

```
version: '3.8'
services:
  practice-nest-postgres:
    image: postgres
    restart: always
    user: postgres
    environment:
      POSTGRES_PASSWORD: abcd
      POSTGRES_DB: nest
    container_name: practice-nest-postgres
    expose:
      - 5432
    networks:
      - practice
    

  practice-nest-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: practice-nest-app
    ports:
      - '3000:3000'
    depends_on:
      - practice-nest-postgres
    networks:
      - practice
networks:
  practice:
```

And this is my folder structure:

```bash
├── docker-compose.yaml
├── Dockerfile
├── nest-cli.json
├── package.json
├── package-lock.json
├── prisma
│   ├── migrations
│   │   ├── 20230919060901_relation_and_modification_added
│   │   │   └── migration.sql
│   │   └── migration_lock.toml
│   └── schema.prisma
├── src
│   ├── app.module.ts
│   ├── auth
│   │   ├── auth.controller.ts
│   │   ├── auth.module.ts
│   │   ├── auth.service.ts
│   │   ├── decorator
│   │   │   ├── get-user.decorator.ts
│   │   │   └── index.ts
│   │   ├── dto
│   │   │   ├── auth.dto.ts
│   │   │   └── index.ts
│   │   ├── guard
│   │   │   ├── index.ts
│   │   │   └── jwt.guard.ts
│   │   └── strategy
│   │       ├── index.ts
│   │       └── jwt.strategy.ts
│   ├── main.ts
│   ├── prisma
│   │   ├── prisma.module.ts
│   │   └── prisma.service.ts
│   └── user
│       ├── dto
│       │   ├── edit-user.dto.ts
│       │   └── index.ts
│       ├── user.controller.ts
│       ├── user.module.ts
│       └── user.service.ts
├── tsconfig.build.json
└── tsconfig.json
```   

Can someone please help me.

This is my schema.prisma:  
```prisma

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model User {
  id Int @id @default(autoincrement())
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt

  email String @unique
  hash String

  firstName String?
  lastName String?
  @@map("users")
}
```
