### DISCUSSION TITLE
Prisma can't reach postgresql instance

### DISCUSSION THREAD

**Discussion by younes101020** [prisma/prisma#21671] [Q&A] [answered]
### Bug description

Hi, 
i have two services on my docker compose, 'app' and 'db', prisma runs on 'app'.

When i launch ``docker compose up -d`` for build image and start the container, the error occurs on building 'app' service steps with this error message:
```
[bookhair 6/6] RUN npx prisma migrate dev --name init && npx prisma generate:                                                                                           
1.606 Prisma schema loaded from prisma/schema.prisma                                                                                                                       
1.611 Datasource "db": PostgreSQL database "mydb", schema "public" at "localhost:5432"                                                                                     
1.611 
1.670 Error: P1001: Can't reach database server at `localhost`:`5432`
1.670 
1.670 Please make sure your database server is running at `localhost`:`5432`.
------
WARN[0019] buildx: failed to read current commit information with git rev-parse --is-inside-work-tree 
failed to solve: process "/bin/sh -c npx prisma migrate dev --name init && npx prisma generate" did not complete successfully: exit code: 1
```
this is my app dockerfile:

```
from node:16
WORKDIR /app
COPY /package*.json ./
RUN npm install
COPY . .
ENV DATABASE_URL="postgresql://postgres:Azerty-02@localhost:5432/mydb?schema=public"
RUN npx prisma migrate dev --name init && npx prisma generate
ENTRYPOINT npx prisma studio
EXPOSE 3000 5555
```

and this is my docker compose:

```
version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: Azerty-02
      POSTGRES_DB: mydb
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  bookhair:
    container_name: bookhair
    depends_on:
      - db
    build:
      dockerfile: Dockerfile
    ports:
      - '3333:3000'
      - '5555:5555'
    volumes:
      - ./src:/app/src
```

Also docker is running on wsl **Ubuntu 22.04.2 LTS**

### Expected behavior

Make PostgreSQL container instance reachable from App container

### Prisma information

```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
```
```ts
// Add your code using Prisma Client
RUN npx prisma migrate dev --name init && npx prisma generate
```

### Environment & setup

- OS: Ubuntu
- Database: PostgreSQL
- Node.js version: v18.15.0

### Prisma Version

```
4.14.1
```
