### DISCUSSION TITLE
Our docker compose config to setup a MongoDB Replica Set for Prisma Client

### DISCUSSION THREAD

**Discussion by Jolg42** [prisma/prisma#22442] [Q&A]
### Question

Related to https://github.com/prisma/prisma/issues/8266 which is an issue closed since early 2022.
Currently, the Replica Set setup is required to use Prisma Client.

The easiest way to set this up, is to create a database for free on MongoDB Atlas: https://www.mongodb.com/atlas

For local usage, here is what we use:
`docker-compose.yml`
```yml
version: "3.8"

services:
  # This config is for MongoDB v4
  # It's a Replica Set (required for Prisma Client)
  mongo:
    build:
      context: ./mongodb_replica
      args:
        MONGO_VERSION: 4
    environment:
      MONGO_REPLICA_HOST: 127.0.0.1
      MONGO_REPLICA_PORT: 27017
      # Use "mongosh" instead of "mongo" for v5+
      MONGO_COMMAND: "mongo"
    ports:
      - "27017:27017"
    restart: unless-stopped
    healthcheck:
      # Use "mongosh" instead of "mongo" for v5+
      test:
        [
          "CMD",
          "mongo",
          "admin",
          "--port",
          "27017",
          "--eval",
          "db.adminCommand('ping').ok",
        ]
      interval: 5s
      timeout: 2s
      retries: 20
```

`mongodb_replica/Dockerfile`
```Dockerfile
ARG MONGO_VERSION

FROM mongo:${MONGO_VERSION}

# we take over the default & start mongo in replica set mode in a background task
ENTRYPOINT mongod --port $MONGO_REPLICA_PORT --replSet rs0 --bind_ip 0.0.0.0 & MONGOD_PID=$!; \
# we prepare the replica set with a single node and prepare the root user config
INIT_REPL_CMD="rs.initiate({ _id: 'rs0', members: [{ _id: 0, host: '$MONGO_REPLICA_HOST:$MONGO_REPLICA_PORT' }] })"; \
# we wait for the replica set to be ready and then submit the command just above
until ($MONGO_COMMAND admin --port $MONGO_REPLICA_PORT --eval "$INIT_REPL_CMD"); do sleep 1; done; \
# we are done but we keep the container by waiting on signals from the mongo task
echo "REPLICA SET ONLINE"; wait $MONGOD_PID;
```

After creating these 2 files, It's as easy as the following:
```
docker compose up -d mongo
```
and then connect with
```
DATABASE_URL="mongodb://localhost:27017/helloworld"
```

Not that if you make changes to the `mongodb_replica/Dockerfile` you will need to use `--build` like `docker compose up --build -d mongo`.

I'm curious to hear what you think about this docker compose setup for development.
For example: did you try this, does this work for you?
