### DISCUSSION TITLE
Encountering P1000 Error: Authentication Failure with Dockerized PostgreSQL Database in Prisma Migration

### DISCUSSION THREAD

**Discussion by dshinde96** [prisma/prisma#23537] [Q&A]
### Question

I've configured my Dockerfile with all the necessary credentials, and my Docker container is running smoothly. However, when I execute npx prisma migrate dev --name create_user_table, I encounter the following error: 

```
PS E:\MERN\GraphQL\Threads\server> npx prisma migrate dev --name create_user_table
Environment variables loaded from .env
Prisma schema loaded from prisma\schema.prisma
Datasource "db": PostgreSQL database "threads", schema "public" at "localhost:5432"

Error: P1000: Authentication failed against database server at `localhost`, the provided database credentials for `postgres` are not valid.
```

Please make sure to provide valid database credentials for the database server at `localhost`.

PS E:\MERN\GraphQL\Threads\server> 
```
docker-compose file: 
version: '3.4'

services:
  postgres:
    container_name: threads-db
    image: postgres
    ports:
      - "5432:5432" #default port of postgres:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data #store the data from this add to volume postgres data such that upon shutting off, the data is still stored in our local machine
    environment:
       POSTGRES_USER: postgres #Use this in DATABASE_URL-user in .env
       POSTGRES_DB: threads #db name
       POSTGRES_PASSWORD: 1234 #do not use @ -password


volumes:
  postgres_data:
```
Here is my .env file:
`DATABASE_URL='postgresql://postgres:1234@localhost:5432/threads'`

I'm attempting to migrate the Prisma schema into a PostgreSQL database running within a Docker container. Despite verifying all the fields, I'm still encountering an error.

I'm puzzled as to where I might have gone wrong. Could anyone lend a hand in pinpointing the issue? Any help would be greatly appreciated!

### How to reproduce (optional)

run the following command in parent directory:
`npx prisma migrate dev --name create_user_table`

### Information about Prisma Schema, Client Queries and Environment (optional)

// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema
```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model User{
  id String @id @default(uuid())
  firstName String @map("first_name")  //at code level-firstName, in db-first_name ->mapping is not compulsory.
  lastName String @map("last_name")
  proflieImgURL String @map("profile_img_url")
  email String @unique  //will take email as it is for db
  password String
  salt String


  @@map("users")  //will make the table as users
}
```
