### DISCUSSION TITLE
Unable to connect to Postgres in Docker when db PORT is different than 5432

### DISCUSSION THREAD

**Discussion by QAdamek** [prisma/prisma#23625] [Q&A]
### Bug description

I am unable to connect prisma to database when postgres is run in container with port set to different than `5432`.

Compose:
```
version: "3.9"

services:
  database:
    image: postgres:16.2
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: cases_dev
      POSTGRES_PASSWORD: cases_dev
      POSTGRES_DB: cases_dev
    expose:
      - 5432
    ports:
      - 4001:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cases_ninja_dev"]
      interval: 10s
      timeout: 5s
      retries: 5

  service:
    build:
      dockerfile: Dockerfile.dev
    ports:
      - 4000:4000
    expose:
      - 4000
    environment:
      - PORT=4000
      - JWT_SECRET=jwtsecret
      - JWT_REFRESH=jwtrefresh
    depends_on:
      database:
        condition: service_healthy
```

Log from `service`:
```
root@cc31cbb3aa36:/usr/src/app# npx prisma migrate dev
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": PostgreSQL database "cases_dev", schema "public" at "database:4001"

Error: P1001: Can't reach database server at `database`:`4001`

Please make sure your database server is running at `database`:`4001`.
```

`.env`:
```
DATABASE_URL="postgresql://cases_dev:cases_dev@database:4001/cases_dev?schema=public"
```

There is no problem at all when PORT is set to 5432 (compose && env).

### How to reproduce

1. Start Postgres in container with container port 5432 mapped to different than 5432 on host
2. Start Prisma in different container and try to connect/migrate to db

**Comment by QAdamek** [comment]
Additional info:

Host that run Docker has an IP of: 192.168.1.204

When I provide following url to Prisma: `DATABASE_URL="postgresql://cases_ninja_dev:cases_ninja_dev@192.168.1.204:4001/cases_ninja_dev` then Prisma is **able** to connet.

So:
* Prisma is **able** to connect using postgres container hostname and port 5432: `DATABASE_URL="postgresql://cases_ninja_dev:cases_ninja_dev@database:5432/cases_ninja_dev`
* Prisma is **able** to connect using host IP and port 4001: `DATABASE_URL="postgresql://cases_ninja_dev:cases_ninja_dev@192.168.1.204:5432/cases_ninja_dev`
* Prisma is **NOT ABLE** to connect using postgres container hostname and port **different** than 5432, eg 4001: `DATABASE_URL="postgresql://cases_ninja_dev:cases_ninja_dev@database:4001/cases_ninja_dev`

**Comment by ludralph** [comment]
Hi @QAdamek 👋 

Thank you for raising this question and adding additional details.

The issue is that Prisma is trying to connect to the Postgres container on port `4001`, which is the container's internal port. However, your docker-compose configuration maps this port to `5432` on the host machine specifically within the service definition for your Postgres container.
```
ports:
      - 4001:5432
```

- `4001`: This represents the exposed port inside the Postgres container. Any connection attempt to this port within the Docker network will reach the Postgres service.

- `5432`: This represents the port mapped on the host machine. When you access the Postgres container from your host machine using a tool like psql, you'll specify this port (`5432`) to connect to the container's internal port (`4001`). 

This configuration creates a tunnel between the host machine's port `5432` and the container's internal port `4001`. Any traffic reaching port `5432` on the host gets forwarded to port `4001` within the container, allowing you to connect to the Postgres service. This mapping only affects connections originating from the host machine. Inside the Docker network, services can often communicate using container names or service discovery mechanisms.

This is why Prisma can connect using:

`database:5432` (assuming "database" resolves to the Postgres container name) because it leverages the internal network and doesn't rely on port mapping.

But it fails with:

`database:4001` because Prisma might be trying to resolve "database" to the host machine itself. Since the host doesn't have a service running on port `4001`, the connection attempt fails.

`DATABASE_URL="postgresql://cases_ninja_dev:cases_ninja_dev@192.168.1.204:4001/cases_ninja_dev"`: This works because you're explicitly specifying the host IP (`192.168.1.204`) along with the container's internal port (`4001`). Prisma bypasses the container name resolution and connects directly to the IP and port.

If your Docker environment supports service discovery (like with Docker Swarm or Kubernetes), configure it to allow Prisma to discover the Postgres service by name. This way, Prisma can find the container regardless of its internal hostname and use the mapped port (`4001`).


If this answers your question, it would be great if you could **mark this Discussion as answered** to indicate that it has been resolved. 

Otherwise please let us know how else we can help you further or close the Discussion if it was resolved in some other way 🙏

**Reply by QAdamek** [reply]
> 4001: This represents the exposed port inside the Postgres container. Any connection attempt to this port within the Docker network will reach the Postgres service.
5432: This represents the port mapped on the host machine. When you access the Postgres container from your host machine using a tool like psql, you'll specify this port (5432) to connect to the container's internal port (4001).

Is that true? 🤔 

https://docs.docker.com/compose/networking/ :
```
services:
  web:
    build: .
    ports:
      - "8000:8000"
  db:
    image: postgres
    ports:
      - "8001:5432"
```
      
> It is important to note the distinction between HOST_PORT and CONTAINER_PORT. In the above example, for db, the **HOST_PORT is 8001** and the **container port is 5432** (postgres default). Networked service-to-service communication uses the CONTAINER_PORT. When HOST_PORT is defined, the service is accessible outside the swarm as well.
