### DISCUSSION TITLE
Module not found: Can't resolve '.prisma/client/default'

### DISCUSSION THREAD

**Discussion by DavDeDev** [prisma/prisma#23766] [Q&A] [answered]
### Bug description

I am getting the following error:
```
./node_modules/.pnpm/@prisma+client@5.12.0_prisma@5.12.0/node_modules/@prisma/client/default.js:2:0
Module not found: Can't resolve '.prisma/client/default'

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./src/lib/prisma-client.ts
./src/auth.ts
./src/middleware.ts
```

when trying to open `http://localhost:3000/` which is the exposed port of my Docker container:
```dockerfile
FROM node:18-alpine as base
ENV NEXT_TELEMETRY_DISABLED 1
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
# enbable corepack to use pnpm
RUN corepack enable
COPY . /pulsecare-webapp
WORKDIR /pulsecare-webapp

FROM base AS deps
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile
RUN pnpm exec next telemetry disable
# Trying to freshly install prisma client every time as suggested here: https://github.com/prisma/prisma/issues/7234#issuecomment-846606919
RUN pnpm add prisma @prisma/client
RUN DEBUG='*' pnpm dlx prisma generate

FROM deps as production-bundle
RUN pnpm build

FROM deps as development
EXPOSE 3000
CMD ["pnpm", "dev"]


FROM production-bundle as production
EXPOSE 3000
CMD ["pnpm", "start"]

```
Service definition in docker-compose.yaml
```yaml
 web_dev:
    profiles:
      - dev
    restart: always
    environment:
      - MONGODB_URL=mongodb://localhost:27018/PulseCare
      # For WSL: https://www.reddit.com/r/nextjs/comments/1638ec6/comment/jy1h8ys/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button
      - WATCHPACK_POLLING=true
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: development
    ports:
      - "3000:3000"
      # This port to test `pnpm run dev` from within the container
      - "3001:3001"
    depends_on:
      - mongo6
    links:
      - mongo6
    # This is only for hot reload in development
    volumes:
      - ../:/pulsecare-webapp
      - /pulsecare-webapp/node_modules
      - /pulsecare-webapp/.next
```

Although, if I run `pnpm run dev` inside the container's terminal this creates a new port, the app would work just fine, as well if try to run the app on my local machine through `pnpm run dev`.

### How to reproduce

Run the following commands
pnpm i
```


Once you get to that commit run:
```
docker compose -f ./docker/docker-compose.yaml -p pulsecare-web --profile dev up -d -V --build
```

Now open `localhost:3000` and you will notice it doesn't work, but if you open the container's terminal at `/pulsecare-web` and run `pnpm run dev`, the app will run just fine at `localhost:3001`

Thank you.

### Expected behavior

My web app should start on `localhost:3000` just fine without errors, when using Dockerfile, without the need of going inside the container and run `pnpm run dev` manually.

### Prisma information

<!-- Do not include your database credentials when sharing your Prisma schema! -->
```prisma
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

// Looking for ways to speed up your queries, or scale easily with your serverless or edge functions?
// Try Prisma Accelerate: https://pris.ly/cli/accelerate-init

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mongodb"
  url      = env("DATABASE_URL")
}

model Account {
  id                String  @id @default(auto()) @map("_id") @db.ObjectId
  userId            String  @db.ObjectId
  type              String
  provider          String
  providerAccountId String
  refresh_token     String?
  access_token      String?
  expires_at        Int?
  token_type        String?
  scope             String?
  id_token          String?
  session_state     String?

  user User @relation(fields: [userId], references: [id], onDelete: Cascade)

  @@unique([provider, providerAccountId])
}

model Session {
  id           String   @id @default(auto()) @map("_id") @db.ObjectId
  sessionToken String   @unique
  userId       String   @db.ObjectId
  expires      DateTime
  user         User     @relation(fields: [userId], references: [id], onDelete: Cascade)
}

model User {
  id            String    @id @default(auto()) @map("_id") @db.ObjectId
  name          String?
  email         String?   @unique
  emailVerified DateTime?
  image         String?
  accounts      Account[]
  sessions      Session[]
}

// model VerificationToken {
//   identifier String
//   token      String   @unique
//   expires    DateTime

//   @@unique([identifier, token])
// }
```

```ts
import { PrismaClient } from "@prisma/client";

const globalForPrisma = global as unknown as { prisma: PrismaClient };

export const prisma = globalForPrisma.prisma || new PrismaClient();

if (process.env.NODE_ENV !== "production") globalForPrisma.prisma = prisma;

export default prisma;

});

```

### Environment & setup

- OS: Docker Linux `node:alpine-18`
- prisma                  : 5.12.1
@prisma/client          : 5.12.1
Computed binaryTarget   : linux-musl-openssl-3.0.x
Operating System        : linux
Architecture            : x64
Node.js                 : v18.20.1
Query Engine (Node-API) : libquery-engine 473ed3124229e22d881cb7addf559799debae1ab (at .pnpm-store/v3/tmp/dlx-71/node_modules/.pnpm/@prisma+engines@5.12.1/node_modules/@prisma/engines/libquery_engine-linux-musl-openssl-3.0.x.so.node)
Schema Engine           : schema-engine-cli 473ed3124229e22d881cb7addf559799debae1ab (at .pnpm-store/v3/tmp/dlx-71/node_modules/.pnpm/@prisma+engines@5.12.1/node_modules/@prisma/engines/schema-engine-linux-musl-openssl-3.0.x)
Schema Wasm             : @prisma/prisma-schema-wasm 5.12.0-21.473ed3124229e22d881cb7addf559799debae1ab
Default Engines Hash    : 473ed3124229e22d881cb7addf559799debae1ab
Studio                  : 0.499.0
- Database: MongoDB local cluster
- Node.js version: 18

### Prisma Version

```
prisma                  : 5.12.1
@prisma/client          : 5.12.1
Computed binaryTarget   : linux-musl-openssl-3.0.x
Operating System        : linux
Architecture            : x64
Node.js                 : v18.20.1
Query Engine (Node-API) : libquery-engine 473ed3124229e22d881cb7addf559799debae1ab (at .pnpm-store/v3/tmp/dlx-71/node_modules/.pnpm/@prisma+engines@5.12.1/node_modules/@prisma/engines/libquery_engine-linux-musl-openssl-3.0.x.so.node)
Schema Engine           : schema-engine-cli 473ed3124229e22d881cb7addf559799debae1ab (at .pnpm-store/v3/tmp/dlx-71/node_modules/.pnpm/@prisma+engines@5.12.1/node_modules/@prisma/engines/schema-engine-linux-musl-openssl-3.0.x)
Schema Wasm             : @prisma/prisma-schema-wasm 5.12.0-21.473ed3124229e22d881cb7addf559799debae1ab
Default Engines Hash    : 473ed3124229e22d881cb7addf559799debae1ab
Studio                  : 0.499.0
```
