### DISCUSSION TITLE
MongoDB + Docker -  No available servers

### DISCUSSION THREAD

**Discussion by DavDeDev** [prisma/prisma#23790] [Q&A] [answered]
### Bug description

I am running my application in Docker with this configuration:

`mongodb_rs/Dockerfile`: [(same as the one used by prisma)](https://github.com/prisma/prisma/blob/6a050c6530bab6096348bc96c3d93765171433fb/docker/mongodb_replica/Dockerfile#L4)
```dockerfile
# src: https://github.com/prisma/prisma/blob/6a050c6530bab6096348bc96c3d93765171433fb/docker/mongodb_replica/Dockerfile#L4
# We need to set up a MongoDB cluster because Prisma requires a replica set to perform transitions.
ARG MONGO_VERSION

FROM mongo:${MONGO_VERSION}

# we take over the default & start mongo in replica set mode in a background task
ENTRYPOINT mongod --port $MONGO_REPLICA_PORT --replSet rs0 --bind_ip 0.0.0.0 & MONGOD_PID=$!; \
# we prepare the replica set with a single node and prepare the root user config
INIT_REPL_CMD="rs.initiate({ _id: 'rs0', members: [{ _id: 0, host: '$MONGO_REPLICA_HOST:$MONGO_REPLICA_PORT' }] })"; \
# we wait for the replica set to be ready and then submit the command just above
until ($MONGO_COMMAND admin --port $MONGO_REPLICA_PORT --eval "$INIT_REPL_CMD"); do sleep 1; done; \
# we are done but we keep the container by waiting on signals from the mongo task
echo "REPLICA SET ONLINE"; wait $MONGOD_PID;
```

`Dockerfile`: 
```
FROM node:18-alpine as base
ENV NEXT_TELEMETRY_DISABLED 1
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
ENV NEXT_TELEMETRY_DISABLED 1
# enbable corepack to use pnpm
RUN corepack enable
COPY . /pulsecare-webapp
WORKDIR /pulsecare-webapp

FROM base AS deps
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile
# Trying to freshly install prisma client every time as suggested here: https://github.com/prisma/prisma/issues/7234#issuecomment-846606919
RUN pnpm dlx prisma generate --schema=prisma/schema.prisma


FROM deps as development
# RUN ls -la node_modules/.prisma/client
ENV PORT 3000
CMD ["pnpm", "dev"]

```

`docker-compose.yaml`: 
- please, note that I have applied the suggestion from this [answer ](https://github.com/prisma/prisma/discussions/11929#discussioncomment-6918038)provided to [issue](https://github.com/prisma/prisma/discussions/11929#discussion-3889595), hence my connection string looks like: `mongodb://localhost:27018/pulsecare-web?replicaSet=rs0&retryWrites=true&w=majority&directConnection=true`
```
version: "3.1"
services:
  mongo6:
    profiles:
      - dev
    build:
      context: ./mongodb_rs
      args:
        MONGO_VERSION: 6
    environment:
      MONGO_REPLICA_HOST: 127.0.0.1
      MONGO_REPLICA_PORT: 27018
      # Use "mongo" instead of "mongosh" before v5.0
      MONGO_COMMAND: "mongosh"
    ports:
      - "27018:27018"
    restart: always
  web_dev:
    profiles:
      - dev
    restart: always
    environment:
      - DATABASE_URL=mongodb://localhost:27018/pulsecare-web?replicaSet=rs0&retryWrites=true&w=majority&directConnection=true
      # For WSL: https://www.reddit.com/r/nextjs/comments/1638ec6/comment/jy1h8ys/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button
      - WATCHPACK_POLLING=true
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: development
    ports:
      - "3000:3000"
    depends_on:
      - mongo6
    links:
      - mongo6
    # This is only for hot reload in development
    volumes:
      - ../:/pulsecare-webapp
      - /pulsecare-webapp/node_modules
      - /pulsecare-webapp/.next

```

Although, I am getting this error when trying to call a basic Prisma operation:
```
⨯ PrismaClientKnownRequestError: 
Invalid `prisma.user.findFirst()` invocation:
Raw query failed. Code: `unknown`. Message: `Kind: Server selection timeout: No available servers. Topology: { Type: Single, Set Name: rs0, Servers: [ { Address: localhost:27018, Type: Unknown, Error: Kind: I/O error: Address not available (os error 99), labels: {} } ] }, labels: {}`
    at async $$ACTION_0 (./src/actions/register.ts:32:26)
```

I even tried the solutions provided in this [#11925](https://github.com/prisma/prisma/issues/11925#issuecomment-1046166986), and so using `mongo` or `host.docker.internal` as `MONGO_REPLICA_HOST` in the docker compose, but still same log (and when putting `mongo` I was not able to connect with any client from my machine as mentioned [here](https://github.com/prisma/prisma/issues/11925#issuecomment-1046394946), while, in other two cases, `host.docker.internal` and `127.0.0.1`, I am able to connect through MongoDBCompass).

### How to reproduce

Run the containers with the following commands: `docker compose --profile dev up --build`

Perform any Prisma operation 

### Expected behavior

The app should connect to my local MongoDB Cluster

### Prisma information

```prisma
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

// Looking for ways to speed up your queries, or scale easily with your serverless or edge functions?
// Try Prisma Accelerate: https://pris.ly/cli/accelerate-init

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mongodb"
  url      = env("DATABASE_URL")
}

model Account {
  id                String  @id @default(auto()) @map("_id") @db.ObjectId
  userId            String  @db.ObjectId
  type              String
  provider          String
  providerAccountId String
  refresh_token     String?
  access_token      String?
  expires_at        Int?
  token_type        String?
  scope             String?
  id_token          String?
  session_state     String?

  user User @relation(fields: [userId], references: [id], onDelete: Cascade)

  @@unique([provider, providerAccountId])
}

model Session {
  id           String   @id @default(auto()) @map("_id") @db.ObjectId
  sessionToken String   @unique
  userId       String   @db.ObjectId
  expires      DateTime
  user         User     @relation(fields: [userId], references: [id], onDelete: Cascade)
}

model User {
  id            String    @id @default(auto()) @map("_id") @db.ObjectId
  firstName     String?   @map("first_name")
  lastName      String?   @map("last_name")
  password      String?
  email         String?   @unique
  isNurse       Boolean   @default(false)
  emailVerified DateTime?
  image         String?
  accounts      Account[]
  sessions      Session[]
}

// model VerificationToken {
//   identifier String
//   token      String   @unique
//   expires    DateTime

//   @@unique([identifier, token])
// }

```

```ts
import { PrismaClient } from "@prisma/client";

// TODO: implement password hashing https://www.prisma.io/docs/orm/prisma-client/queries/custom-models

// PrismaClient is attached to the `global` object in development to prevent
// exhausting your database connection limit.
//
// Learn more:
// https://pris.ly/d/help/next-js-best-practices

const globalForPrisma = global as unknown as { prisma: PrismaClient };

export const db = globalForPrisma.prisma || new PrismaClient();

if (process.env.NODE_ENV !== "production") globalForPrisma.prisma = db;

export default db;

```

I think this is not relevant

### Environment & setup

- OS: 
- Database: 
- Node.js version: 

- OS: WSL Docker
- Database: MongoDB
- 18-alpine

### Prisma Version

```
Environment variables loaded from .env
prisma                  : 5.12.1
@prisma/client          : 5.12.1
Computed binaryTarget   : windows
Operating System        : win32
Architecture            : x64
Node.js                 : v20.11.1
Query Engine (Node-API) : libquery-engine 473ed3124229e22d881cb7addf559799debae1ab (at ..\..\.pnpm-store\v3\tmp\dlx-17600\node_modules\.pnpm\@prisma+engines@5.12.1\node_modules\@prisma\engines\query_engine-windows.dll.node)
Schema Engine           : schema-engine-cli 473ed3124229e22d881cb7addf559799debae1ab (at ..\..\.pnpm-store\v3\tmp\dlx-17600\node_modules\.pnpm\@prisma+engines@5.12.1\node_modules\@prisma\engines\schema-engine-windows.exe)
Schema Wasm             : @prisma/prisma-schema-wasm 5.12.0-21.473ed3124229e22d881cb7addf559799debae1ab
Default Engines Hash    : 473ed3124229e22d881cb7addf559799debae1ab
Studio                  : 0.499.0
```
