### DISCUSSION TITLE
prisma docker continuously restarting

### DISCUSSION THREAD

**Discussion by brucem1976** [prisma/prisma#2418] [Q&A] [answered]
I've installed prisma: Prisma CLI version: prisma/1.34.10 (windows-x64) node-v10.14.1
Did a 'docker-compose up -d' and all went well.

However, 'docker ps' gives me:
08ed71be3588        prismagraphql/prisma:1.34   "/bin/sh -c /app/sta…"   15 minutes ago      Restarting (1) 32 seconds ago                                      graphql-24r_prisma_1
continuously

In creation I chose to connect to an existing db, MySQL and it generated the schema perfectly from it. I did not create a client as I will do that manually.

Any tips on tracking down the continuous restarts of the docker?

**Comment by ryands17** [comment]
Hey @brucem1976 :wave: 
Could you share your `docker-compose.yml` so that I could replicate it?

**Reply by brucem1976** [reply]
Thanks so much:

```
version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: mysql
            host: host.docker.internal
            schema: <hidden>
            user: <hidden>
            password: <hidden>
            rawAccess: true
            port: '3306'
            migrations: false
```
