### DISCUSSION TITLE
How can I use Prisma and Kubernetes?

### DISCUSSION THREAD

**Discussion by Tsimopak** [prisma/prisma#24664] [Q&A]
### Question

Hi,

I could not see any source on the internet explaining how to use Kubernetes with Prisma ORM.
So I would have the following manifests:
1. My Node JS Server that includes the Prisma ORM logic
2. Postgres
3. Services to expose the server + database.

I also have skaffold for my dev environment and I also ingress nginx.
and I also use zenstack

My question is:
1. Where should I do `npx zenstack generate` (or `npx prisma generate` which is the equivalent) and `npx prisma migrate deploy/dev`? Should it be as part of my manifest of the server? or maybe as part of my Dockerfile? or maybe as part of initContainers?
2. How can I verify that the postgres service has up before I do npx prisma generate?

**Comment by ludralph** [comment]
Hi @Tsimopak 👋 

> Where should I do npx zenstack generate (or npx prisma generate which is the equivalent) and npx prisma migrate deploy/dev? Should it be as part of my manifest of the server? or maybe as part of my Dockerfile? or maybe as part of initContainers?

You can use docker and deploy your app to Kubernetes. Including `npx prisma generate` in your Dockerfile ensures that the Prisma Client is generated during the build process. This is a common practice and ensures that the client is always up-to-date with your schema. For example:
```
FROM node:20

# Set working directory
WORKDIR /app

# Copy package.json and install dependencies
COPY package.json ./
RUN npm install

# Copy application code
COPY . .

# Generate Prisma Client
RUN npx zenstack generate

# If using Prisma directly
# RUN npx prisma generate

# Start the application
CMD ["node", "server.js"]

```

> How can I verify that the postgres service has up before I do npx prisma generate?

Use an initContainer to ensure the database is ready before the main application starts.
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      initContainers:
        - name: migrate
          image: node:14
          command: ["sh", "-c", "npx prisma migrate deploy"]
          volumeMounts:
            - name: app
              mountPath: /app
          envFrom:
            - configMapRef:
                name: my-app-config
            - secretRef:
                name: my-app-secrets
      containers:
        - name: my-app
          image: my-app-image
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: app
              mountPath: /app
          envFrom:
            - configMapRef:
                name: my-app-config
            - secretRef:
                name: my-app-secrets
      volumes:
        - name: app
          configMap:
            name: my-app-config
```
