### DISCUSSION TITLE
Prisma is unable to fetch new data (GET REQUEST), but is able to send POST and UPDATE request on Docker

### DISCUSSION THREAD

**Discussion by Nicklelodeon** [prisma/prisma#25277] [Q&A]
### Question

Hi, I am trying to dockerise my next.js application which uses Prisma as an ORM to connect to my vercel postgre database. However, Prisma is unable to fetch new data (GET REQUEST), but is able to send POST and UPDATE request on the Docker container while it works well locally with 
```
npm install
npm run dev
```

My current file structure is:
```
/app 
  - /utils
     - prisma.ts
/prisma 
 - schema.json
```

My prisma.ts file is used to create a global prisma client that is used around my app.

Below is my docker file:
```
FROM node:18-alpine as builder
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci
COPY . .
RUN npx prisma generate
RUN npm run build
FROM node:18-alpine AS runner
ENV NODE_ENV=production
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci --only=production
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/prisma ./prisma
COPY --from=builder /app/node_modules/.prisma ./node_modules/.prisma
COPY --from=builder /app/node_modules/@prisma ./node_modules/@prisma
EXPOSE 3000
CMD ["npm", "start"]
```

```
version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: <redacted>
    container_name: nextjs-app
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '3000:3000'
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
```
I am running the containers with `docker-compose -up --build -d`. 
I have tried referring to this discussion [https://github.com/prisma/prisma/discussions/24885](https://github.com/prisma/prisma/discussions/24885), but I am still unable to get it to work. Appreciate any advice given!

### Information about Prisma Schema, Client Queries and Environment (optional)

```prisma
// Add your schema.prisma
```

```ts
// Add any relevant Prisma Client queries here
```

- OS: 
- Database: 
- Node.js version: 

- Run `prisma -v` to see your Prisma version and paste it
