### DISCUSSION TITLE
Error: Schema engine exited. Error: Could not find schema-engine binary. - GithubActions, AWS Lambda

### DISCUSSION THREAD

**Discussion by lucasdavidferrero** [prisma/prisma#25282] [Q&A]
### Question

I'm following [this guide](https://www.prisma.io/docs/orm/prisma-client/deployment/serverless/deploy-to-aws-lambda#deploying-with-the-serverless-framework) where you prepare prisma to communicate with lambdas, which is my case.

The problem is that when the github action reaches the `npx prisma migrate deploy` I get the error: 
```
Prisma schema loaded from src/prisma/schema
Datasource "db": MySQL database "yume-dev" at "yumedb-dev.cja6suse4cq7.us-east-1.rds.amazonaws.com:3306"

Error: Schema engine exited. Error: Could not find schema-engine binary. Searched in:
- /home/runner/work/yume-cloud-backend-core/yume-cloud-backend-core/node_modules/@prisma/engines/schema-engine-debian-openssl-1.1.x
- /home/runner/work/yume-cloud-backend-core/yume-cloud-backend-core/node_modules/prisma/schema-engine-debian-openssl-1.1.x
- /home/runner/work/yume-cloud-backend-core/yume-cloud-backend-core/node_modules/schema-engine-debian-openssl-1.1.x
- /home/runner/work/yume-cloud-backend-core/yume-cloud-backend-core/node_modules/prisma/runtime/schema-engine-debian-openssl-1.1.x
Error: Process completed with exit code 1.
```
How could I fix this error? Seems like the engine that I'm specifying in prisma schema doesn't exist when building the app.

### Relevant files

main.prisma
```prisma
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["prismaSchemaFolder"]
  binaryTargets   = ["native", "rhel-openssl-3.0.x"]
}

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}

```

dev-stage.yml
```yaml
name: Deploy Dev Stage

on:
  workflow_dispatch: # Manual trigger only for the dev branch

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      DATABASE_URL: ${{ secrets.DATABASE_URL_DEV }}
      SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
      CURRENT_ENV: dev
      GH_TOKEN: ${{ github.token }} # github cli -> gh
      PRISMA_CLI_BINARY_TARGETS: 'rhel-openssl-3.0.x'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.17.0"
          cache: 'npm'
      - name: Install dependencies
        run: npm install

      - name: Install Serverless Framework Globally
        run: npm install -g serverless@4.3.2
      
      - name: Install Prisma CLI
        run: npm install prisma @prisma/client

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Prisma Migrate Deploy # Prisma Sync Database with migration files.
        run: npx prisma migrate deploy


      - name: Deploy dev stage
        run: |
          echo "Deploying to Development environment";
          serverless deploy -s dev --r us-east-1;

```

serverless.yaml
```yaml
# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: mchogar
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: yume-cloud
# "service" is the name of this project. This will also be added to your AWS resource names.
service: backend-core

useDotenv: true

provider:
  name: aws
  runtime: nodejs20.x
  tracing:
    lambda: true
  environment:
    DATABASE_URL: ${env:DATABASE_URL}
    CURRENT_ENV: ${env:CURRENT_ENV}

functions:
  getListadoBannersGrillaBannersFn:
    handler: src/modules/HomeCMS/SliderBanners/handlers/getListadoBannersGrillaBanners.handler
    events:
      - http:
          path: slider-banners/listar-grilla-banners
          method: get
  
  updateBannerFn:
    handler: src/modules/HomeCMS/SliderBanners/handlers/updateBanner.handler
    events:
      - http:
          path: slider-banners/actualizar/{id}
          method: put

package:
  patterns:
    - '!node_modules/.prisma/client/libquery_engine-*'
    - 'node_modules/.prisma/client/libquery_engine-rhel-*'
    - '!node_modules/prisma/libquery_engine-*'
    - '!node_modules/@prisma/engines/**'
    - '!node_modules/.cache/prisma/**'  # only required for Windows
```

**Settings**

- OS: Windows
- Database: MySQL
- Node.js version: 20.17.0

- prisma -v
```
prisma                  : 5.19.1
@prisma/client          : 5.19.1
Computed binaryTarget   : windows
Operating System        : win32
Architecture            : x64
Node.js                 : v20.17.0
Query Engine (Node-API) : libquery-engine 69d742ee20b815d88e17e54db4a2a7a3b30324e3 (at node_modules\@prisma\engines\query_engine-windows.dll.node)
Schema Engine           : schema-engine-cli 69d742ee20b815d88e17e54db4a2a7a3b30324e3 (at node_modules\@prisma\engines\schema-engine-windows.exe)
Schema Wasm             : @prisma/prisma-schema-wasm 5.19.1-2.69d742ee20b815d88e17e54db4a2a7a3b30324e3
Default Engines Hash    : 69d742ee20b815d88e17e54db4a2a7a3b30324e3
Studio                  : 0.502.0
Preview Features        : prismaSchemaFolder
```
