### DISCUSSION TITLE
Unable to set DATABASE_URL inside of docker in GitHub Actions

### DISCUSSION THREAD

**Discussion by vdemcak** [prisma/prisma#25330] [Q&A]
### Question

I'm currently trying to build a Docker image for my Qwik app within a GitHub Actions pipeline. However, the build process keeps failing with the following error:
```
Environment variable not found: DATABASE_URL.
```
I attempted to set the environment variables in the .env file inside the Dockerfile, but that approach didn't resolve the issue either. Am I missing something? Why does prisma even need to connect to the database during the build step?

Here is my GitHub pipeline step:
```yaml
- name: Set up Docker Buildx
  uses: docker/setup-buildx-action@v3

- name: Build and Push Docker image
  uses: docker/build-push-action@v6
  with:
    context: .
    push: true
    secrets: |
      "database_url=${{ secrets.DATABASE_URL }}"
    tags: |
      foo:latest
```

And here's my Dockerfile for reference:
```dockerfile
# syntax=docker/dockerfile:1
# -------------------------------- Image base -------------------------------- #
FROM node:lts-alpine AS base

RUN --mount=type=secret,id=database_url \
  echo "DATABASE_URL=$(cat /run/secrets/database_url)" > .env

RUN apk add git
RUN npm install -g pnpm

WORKDIR /app

# ---------------------------- Dependencies stage ---------------------------- #
FROM base AS dependencies

COPY package.json pnpm-lock.yaml ./.npmrc ./

RUN pnpm install --frozen-lockfile

COPY prisma ./prisma

RUN pnpm prisma generate

# -------------------------------- Build stage ------------------------------- #
FROM dependencies AS build

COPY . .

RUN pnpm build

# -------------------------------- Final stage ------------------------------- #
FROM base AS final

ENV NODE_ENV=production

RUN addgroup -S foo && adduser -S foo -G foo
USER foo

# Copy static files
COPY package.json pnpm-lock.yaml ./.npmrc ./

COPY --from=dependencies /app/node_modules ./node_modules
COPY --from=build /app/dist ./dist
COPY --from=build /app/server ./server

EXPOSE 3000

CMD ["node", "--import", "./server/sentry-instrument.js", "./server/entry.express.js"]```

**Comment by ludralph** [comment]
Hi @vdemcak 👋 

Prisma needs to connect to the database during the build step, especially when running commands like `prisma generate`, to ensure that the schema is correctly introspected and the client is generated based on the current state of the database.

To resolve this issue, you can follow these steps

1. Set the `DATABASE_URL` as a GitHub Secret: Make sure your `DATABASE_URL` is set as a repository secret in GitHub. This is crucial as it ensures the secret is securely stored and accessible during the workflow. Double-check that the `DATABASE_URL` secret is correctly set in your GitHub repository under `Settings > Secrets > Actions`. When setting the `DATABASE_URL` in GitHub secrets, ensure you do not use quotation marks around the URL.

2. You can modify your GitHub Actions workflow to pass the `DATABASE_URL` secret to the Docker build context.

3. Use the Secret in Dockerfile: Ensure that the Dockerfile correctly reads the secret and sets it as an environment variable.

Here is an updated version of your GitHub Actions workflow and Dockerfile:

```
// Github Actions workflow

name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          secrets: |
            database_url=${{ secrets.DATABASE_URL }}
          tags: |
            foo:latest
```

Dockerfile

```docker
# syntax=docker/dockerfile:1
# -------------------------------- Image base -------------------------------- #
FROM node:lts-alpine AS base

RUN --mount=type=secret,id=database_url \
  echo "DATABASE_URL=$(cat /run/secrets/database_url)" > .env

RUN apk add git
RUN npm install -g pnpm

WORKDIR /app

# ---------------------------- Dependencies stage ---------------------------- #
FROM base AS dependencies

COPY package.json pnpm-lock.yaml ./.npmrc ./

RUN pnpm install --frozen-lockfile

COPY prisma ./prisma

RUN pnpm prisma generate

# -------------------------------- Build stage ------------------------------- #
FROM dependencies AS build

COPY . .

RUN pnpm build

# -------------------------------- Final stage ------------------------------- #
FROM base AS final

ENV NODE_ENV=production

RUN addgroup -S foo && adduser -S foo -G foo
USER foo

# Copy static files
COPY package.json pnpm-lock.yaml ./.npmrc ./

COPY --from=dependencies /app/node_modules ./node_modules
COPY --from=build /app/dist ./dist
COPY --from=build /app/server ./server

EXPOSE 3000

CMD ["node", "--import", "./server/sentry-instrument.js", "./server/entry.express.js"]
```
