### DISCUSSION TITLE
How do I run prisma deploy within a docker container

### DISCUSSION THREAD

**Discussion by jerilcj1** [prisma/prisma#4112] [Q&A] [answered]
This is repo that I am using

What I am looking to do is, when I build the dockerfile from the below repo ```prisma deploy``` should be executed.

```
https://github.com/jerilcj1/prisma
```

I am using ```entrypoint.sh``` and ```wait-for-it.sh``` to make sure prisma server is running. 

But ```prisma deploy``` is not executing the below from prisma.yml

```
generate:
  - generator: javascript-client
    output: ./generated/prisma-client
hooks:
 post-deploy:
  - prisma generate
  - npx nexus-prisma-generate --client ./generated/prisma-client --output ./generated/nexus-prisma 
```

```prisma deploy``` is invoked from entrypoint.sh script
