### DISCUSSION TITLE
Connecting to a dockerized postgres database from outside docker

### DISCUSSION THREAD

**Discussion by rodrigojmr** [prisma/prisma#5377] [Q&A]
Hello, I've been trying to connect to a dockerized postgres database for a few days. I attempted to follow [this video](https://www.youtube.com/watch?v=SvtXgRA7KsE) but failed to be able to connect to the database.

I am in WSL2. I am trying to connect to a dockerized database from outside docker, with @prisma/cli installed as a dev dependency on a node/typescript project. I've seen many ways to run this (dockersized database and prisma service) and as I'm new to prisma and docker I don't really know which is the best to set this up. This is just what I've tried.

This is my `docker-compose.yml`:

```
version: '3.8'
services:
  db:
    image: postgres:latest
    restart: always
    container_name: pg
    #tty: true
    ports:
      - '5432:5432'
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: prisma
    command: -p 5432
    expose:
      - 5432
volumes:
  data:
    external: true
```

And this is the DATABASE_URL:
`DATABASE_URL=postgres://prisma:prisma@prisma:5432/prisma`

This is my `docker ps` output:

```
CONTAINER ID   IMAGE             COMMAND                  CREATED         STATUS                  PORTS                    NAMES
336ddc3d53c9   postgres:latest   "docker-entrypoint.s…"   3 seconds ago   Up Less than a second   0.0.0.0:5432->5432/tcp   pg
```

When I use `docker exec -it 336ddc3d53c9 psql -d prisma -U prisma -W` I am able to get into the database:

```
prisma=# \du
                                   List of roles
 Role name |                         Attributes                         | Member of 
-----------+------------------------------------------------------------+-----------
 prisma    | Superuser, Create role, Create DB, Replication, Bypass RLS | {}
```

```
prisma=# \l
                              List of databases
   Name    | Owner  | Encoding |  Collate   |   Ctype    | Access privileges 
-----------+--------+----------+------------+------------+-------------------
 postgres  | prisma | UTF8     | en_US.utf8 | en_US.utf8 | 
 prisma    | prisma | UTF8     | en_US.utf8 | en_US.utf8 | 
```

When I attempt to use `npx prisma migrate dev --preview-feature` I get: 

```
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": PostgreSQL database "prisma", schema "public" at "prisma:5432"

Error: P1001: Can't reach database server at `prisma`:`5432`
```

I've had many other errors while troubleshooting this but this is the current one. I've tried many ways of trying to solve this, with different DATABASE_URL values, none have worked yet.
