### DISCUSSION TITLE
Prisma DATABASE_URL Environment Variable in Kubernetes ConfigMap

### DISCUSSION THREAD

**Discussion by L-U-C-K-Y** [prisma/prisma#6510] [Q&A]
Hi all

I am creating a backend microservice POC with Prisma and while everything went smoothly on local, I am facing environment variable difficulties when deploying to Kubernetes.

The issue is that the `DATABASE_URL` is not recognized by Prisma.

I have the `DATABASE_URL` defined in a configMap and include it as an environment variable into the container with `envFrom`:

```yaml
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: <configMapName>
```

I also have other environment variables that are used within the microservice that work well.

Anyone has a clue on how to resolve this?
