### DISCUSSION TITLE
How to apply prisma migration deploy for Google Cloud SQL using Google Cloud Build?

### DISCUSSION THREAD

**Discussion by enheit** [prisma/prisma#7588] [Q&A] [answered]
I was not able to find any resource which describes the process of integrating Prisma with Google Cloud SQL. 

I want to use Google Cloud Build to run `prisma migrate deploy` which theoretically should update my database schema in the continuous deployment process.

Does Prisma support such integration? If yes, could you provide me links to the respective resources?

**Comment by ryands17** [comment]
@enheit 👋 

I'm not aware of Google Cloud Build, but I had performed a similar process with `prisma migrate deploy` on `AWS Codebuild` and it worked fine. Is your database reachable when you run this command? Also are you facing any issue when you do so?

**Reply by enheit** [reply]
> Is your database reachable when you run this command?

Rather no than yes

> Also are you facing any issue when you do so?

As far I understand I should use **Cloud SQL Proxy** to connect to the **Cloud SQL** database. Unfortunately, it throws an error during the build `Error: connect ENOENT /cloudsql/project:us-east1:project-posgresql1/.s.PGSQL.5432`. Wondering if there any good article (tutorial) which describes the process of configuring **Cloud Build** + **Cloud SQL** via **Cloud SQL Proxy**

**Comment by enheit** [comment, marked as answer]
I was able to integrate prisma migrate into Cloud Build + Cloud Run + Cloud SQL configuration. I am not sure if my approach if the best one at least it works.

**Reply by armandoborge** [reply]
@enheit how did you manage to solved it? Would you mind to explain your solution.
Thank you

**Reply by armandoborge** [reply]
@enheit nevermind I figure out a solution already! thanks

**Reply by enheit** [reply]
@armandoborge What exactly the problem you had?

**Reply by armandoborge** [reply]
I was having a connection issue in one step of my CI/CD flow on Cloud Run: 
`Error: P1001: Can't reach database server at /cloudsql/project:region:instance:5432`

Got solved by updating the DB URL, ended up using this one:
`postgresql://username:password@127.0.0.1:5432/database`

Thanks for your reply

**Reply by enheit** [reply]
> @enheit how did you manage to solved it? Would you mind to explain your solution.
> Thank you

I actually had a problem of connecting prisma to the Cloud SQL. The root cause of the problem was somewhere inside Cloud SQL Proxy which for some reason couldn't connect to the Cloud SQL. After a while I was able to fix the config. 

Here is my config. It consists of several steps. The most important is `id: proxy-install` which ensures connection from cloud build to Cloud SQL.

<details>
  <summary>cloudbuild.yml</summary>
  
```yml
steps:
  - name: 'node:14.16.0'
    entrypoint: 'yarn'
    id: yarn-install
    args: ['install']
    waitFor: ["-"]

  - name: gcr.io/cloud-builders/wget
    id: proxy-install
    entrypoint: bash
    args:
      - "-c"
      - "wget https://storage.googleapis.com/cloudsql-proxy/v1.15/cloud_sql_proxy.linux.386 -O /workspace/cloud_sql_proxy && chmod +x /workspace/cloud_sql_proxy"
    waitFor: ["-"]

  - id: migrate
    name: gcr.io/cloud-builders/yarn
    env:
      - NODE_ENV=$_NODE_ENV
      # - DB_NAME=$_DB_NAME
      # - DB_USER=$_DB_USER
      # - DB_PASSWORD=postgres
      - DB_URL=postgresql://$_DB_USER:postgres@localhost/$_DB_NAME?host=127.0.0.1
    entrypoint: sh
    args:
      - "-c"
      - "(/workspace/cloud_sql_proxy -dir=/workspace -instances=$_CLOUD_SQL_CONNECTION_NAME=tcp:5432 & sleep 2) && yarn run prisma:migrate"
    timeout: "1200s"
    waitFor: ["yarn-install", "proxy-install"]

  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '--build-arg'
      - NODE_ENV=$_NODE_ENV
      - '--build-arg'
      - DB_NAME=$_DB_NAME
      - '--build-arg'
      - DB_USER=$_DB_USER
      - '--build-arg'
      - DB_PASSWORD=postgres
      - '--build-arg'
      - DB_URL=postgresql://$_DB_USER:postgres@localhost/$_DB_NAME?host=127.0.0.1
      - '--no-cache'
      - '-t'
      - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
      - .
      - '-f'
      - Dockerfile
    id: Build
    secretEnv:
      - DB_PASSWORD
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
    id: Push
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - '--platform=managed'
      - '--image=$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
      - >-
        --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID,$_LABELS
      - '--region=$_DEPLOY_REGION'
      - '--quiet'
    id: Deploy
    entrypoint: gcloud
images:
  - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
options:
  substitutionOption: ALLOW_LOOSE
substitutions:
  _PLATFORM: managed
  _SERVICE_NAME: project-api-dev
  _LABELS: gcb-trigger-id=6d25e9b4-371a-4f91-b6ad-dcda855db56a
  _TRIGGER_ID: 6d25e9b4-371a-4f91-b6ad-dcda855db56a
  _DEPLOY_REGION: europe-west4
  _GCR_HOSTNAME: eu.gcr.io
tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - project-api-dev
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/DB_PASSWORD/versions/1
      env: DB_PASSWORD
```
  
</details>

P.S. This is my first try of configuring such services. Use this config as a reference not as a guide.
