### DISCUSSION TITLE
Prisma migrate works, but prisma client can't connect to the DB

### DISCUSSION THREAD

**Discussion by kevinmamaqi** [prisma/prisma#7833] [Q&A]
I am running Postgres in a docker container.

When I run docker-compose up --build -d, it builds redis, postgres, node-api and succesfully execute the migrations with npx prisma migrate dev --name init.

The ouput from the container db is that the tables have been created:
<img width="617" alt="Screen Shot 2021-06-23 at 20 04 37" src="https://user-images.githubusercontent.com/972664/123146518-4552ca00-d45e-11eb-927c-54de7f4a921a.png">

The problem is that then when I try to make a findMany against a table it returns the following error:

```
PrismaClientKnownRequestError2 [PrismaClientKnownRequestError]:
Invalid `prisma.user_role.findMany()` invocation:

The table `public.user_role` does not exist in the current database.
at cb (/home/node/app/node_modules/@prisma/client/runtime/index.js:33816:17)
at processTicksAndRejections (internal/process/task_queues.js:95:5)
at async loadConstants (/home/node/app/app/utils/CONSTANTS.js:8:21) {
  code: 'P2021',
  clientVersion: '2.25.0',
  meta: { table: 'public.user_role' }
}
```

Any idea what is going on?

**Comment by janpio** [comment]
What commands are you using to migrate? Inside or outside the container? How are you setting the connection URL?
Docker databases are often available under different hostnames internally and externally of the container, leading to trouble.

**Reply by kevinmamaqi** [reply]
For the migration I use `docker-compose up --detach --build; docker-compose exec ita-api npm run dev:migrate`, so I execute after the container is built from the docker command. In package.json: `"dev:migrate": "npx prisma migrate dev --name init"`.

**Reply by janpio** [reply]
That sounds like it should indeed run the command inside your container, and thus use the same ENV var or connection string as using the Prisma Client. That is weird.

Can you maybe do a simple reproduction of this and push the resulting repo to GH so we can take a look? That would be easiest to debug waht is going on.

**Reply by kevinmamaqi** [reply]
HI @janpio , here is the repository link. The composer + prisma files are in the develop branch: https://github.com/it-academyproject/ita-directory-backend/tree/develop

**Comment by l2D** [comment]
My solution is add `RUN npx prisma generate;` on Dockerfile after install dependencies.  

and in `.env` I used  

`DATABASE_URL="postgresql://[user]:[password]@[** docker service name **]:[port]/[databaseName]"`

My docker-compose.yaml:

```yaml
   db:  <---- Docker service name
        image: postgres
        restart: always
        expose:
            - "5432"
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: your_database_name
            POSTGRES_USER: your_database_user
            POSTGRES_PASSWORD: your_database_password
            POSTGRES_HOST_AUTH: trust
        volumes:
            - postgres-db:/var/lib/postgresql/data

 volumes:
     postgres-db:

```
