### DISCUSSION TITLE
How to deploy Azure Function App with Prisma and Azure DevOps Pipeline

### DISCUSSION THREAD

**Discussion by khussell** [prisma/prisma#8597] [Q&A] [answered]
Hello! I am experiencing some trouble when deploying Prisma to my Azure function app with an **Azure DevOps pipeline**. Everything runs fine locally, but then I run the pipeline and test my deployed function app and it fails with this error:

**Error: Cannot find module '.prisma/client'**

My package.json looks like this:

```
{
  "name": "centuriontelemetryblobparser",
  "version": "1.0.0",
  "description": "",
  "scripts": {
    "build": "tsc",
    "watch": "tsc -w",
    **"prisma:generate": "npx prisma generate",**
    "prisma:introspect": "npx prisma introspect",
    "prestart": "npm run build",
    "start": "func start",
    "test": "echo \"No tests yet...\""
  },
  "devDependencies": {
    "@azure/functions": "^1.2.3",
    "@types/superagent": "^4.1.10",
    "prisma": "^2.27.0",
    "typescript": "^4.0.0"
  },
  "dependencies": {
    "@azure/storage-blob": "^12.5.0",
    **"@prisma/client": "^2.28.0",**
    "@types/knex": "^0.16.1",
    "axios": "^0.21.1",
    "csv-parse": "^4.15.3",
    "date-fns": "^2.20.2",
    "durable-functions": "^1.4.6",
    "joi": "^17.4.1",
    "knex": "^0.95.4",
    "lodash": "^4.17.21",
    "tedious": "^11.0.7"
  }
}

```

and my pipeline scripts looks like this:

```
   - script: |
              npm install
              **npm run prisma:generate**
              npm run build --if-present
              npm run test --if-present
```

My other modules are loading correctly in my function app with the npm install. I believe it has something to do with **npx prisma generate**

I have also followed this guideline for my database's connection string: 
`sqlserver://DB_SERVER_NAME.database.windows.net:1433;database=DB_NAME;user=DB_ADMIN_USER@DB_SERVER_NAME;password={DB_ADMIN_PASSWORD};encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30`

We have an Azure app service that is running with the same configuration as well, and is working. Any insight would be very much appreciated! Thank you!

**Comment by janpio** [comment, marked as answer]
On first sight this looks fine really. (The connection string should not influence the generation of the Client).

What output is that `npx prisma generate` call giving you?

How and where are you deploying the function app or is that some magic between DevOps Pipelines and Azure Functions?

**Reply by khussell** [reply]
There are actually logs in the Azure DEVOPS pipeline build stage, which I just learned about. It looks like my issue is running the wrong version of Node in my pipeline!

**Reply by janpio** [reply]
Oh wow, that is _weird_. Can you share the error here? (Might help future people googling for the same problem :p )

**Reply by khussell** [reply]
Of course!

I solved this error by clicking on my Azure DevOps pipeline that I was using, I then clicked on build stage, and then under Build I selected Prepare binaries to see the log output, here is an image of the output, and with this error I was easily able to see that my issue was the Node version. Running locally I was using Node version 14, but in my pipeline that I had generated, it specified Node version 10. Prisma needs >= 12.2


<img width="729" alt="Screen Shot 2021-08-06 at 11 08 52 AM" src="https://user-images.githubusercontent.com/45740230/128531905-e3968bd2-c9fc-415b-9d54-29562d60a104.png">

Here was is my new pipeline with the NodeTool versionSpec corrected to 14.x:

```
trigger:
  - staging

variables:

  azureSubscription: 'Osmosis Centurion-Supreme (SECRET)'

  functionAppName: 'TelemetryBlobParser-Centurion-Staging'

  environmentName: 'TelemetryBlobParser-Centurion-Staging'

  vmImageName: 'ubuntu-latest'

stages:
  - stage: Build
    displayName: Build stage
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: $(vmImageName)

        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '14.x'
            displayName: 'Install Node.js'

          - script: |
              if [ -f extensions.csproj ]
              then
                  dotnet build extensions.csproj --runtime ubuntu.16.04-x64 --output ./bin
              fi
            displayName: 'Build extensions'
          - script: |
              npm install
              npm run prisma:generate
              npm run build --if-present
              npm run test --if-present
            displayName: 'Prepare binaries'
          - task: ArchiveFiles@2
            displayName: 'Archive files'
            inputs:
              rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
              includeRootFolder: false
              archiveType: zip
              archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
              replaceExistingArchive: true

          - upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
            artifact: drop

  - stage: Deploy
    displayName: Deploy stage
    dependsOn: Build
    condition: succeeded()
    jobs:
      - deployment: Deploy
        displayName: Deploy
        environment: $(environmentName)
        pool:
          vmImage: $(vmImageName)
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureFunctionApp@1
                  displayName: 'Azure Functions App Deploy: TelemetryBlobParser-Centurion-Staging'
                  inputs:
                    azureSubscription: '$(azureSubscription)'
                    appType: functionAppLinux
                    appName: $(functionAppName)
                    package: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'
                    startUpCommand: 'npm run start'
```
