### DISCUSSION TITLE
p1000 authentication failed against database server

### DISCUSSION THREAD

**Discussion by alucardu** [prisma/prisma#8925] [Q&A] [answered]
I'm trying to use docker, postgres and prisma together but I'm running into an error.

I have a `docker-compose.yml` file:
```
version: '3.8'
services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: college_db
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
    postgres:
```

A `.env` file:
```
DATABASE_URL="postgresql://postgres@localhost:5432/college_db"
```

And a Prisma schema:
```
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}
```

When I run a prisma command `npx prisma db pull` I get an error:

![image](https://user-images.githubusercontent.com/779921/130805186-96b8ba38-d455-425f-b0f6-8f22a87d715e.png)

But when I checkout my postgres database I can login the `college_db` database without any issue using the `postgres` superuser: 

![image](https://user-images.githubusercontent.com/779921/130804813-37818177-1a06-4405-9a68-1d579eb3ee42.png)

I'm using Windows 10 and the latest docker installation.
