### DISCUSSION TITLE
Electron-Prisma won't read the sqlite  database

### DISCUSSION THREAD

**Discussion by M-Barari** [prisma/prisma#9432] [Q&A]
Hi, after two weeks I finally connected my nuxt-electron to prisma , and then another problem!

on dev I get connected to database but on build it won't ! I thought it's because of electron packing , so added my db to extraResources but still no result! what should I do??

```prisma
// schema.prisma
datasource db {
  provider = "sqlite"
  url      = "file: ../resource/dev.db"
}

generator client {
  provider = "prisma-client-js"
}

model Admin {
  id        Int       @id @default(autoincrement())
  email     String    @unique()
  password  String
  fName     String?
  lName     String?
  createdAt DateTime  @default(now())
  updatedAt DateTime  @updatedAt
}
```

my package.json

```json
{
  "private": true,
  "name": "my-app",
  "description": "My application description",
  "version": "1.0.0",
  "author": "Shiono Yoshihide <shiono.yoshihide@gmail.com>",
  "main": "app/background.js",
  "scripts": {
    "dev": "nuxtron",
    "build": "nuxtron build"
  },
  "dependencies": {
    "@prisma/client": "^3.0.2",
    "electron-serve": "^1.0.0",
    "electron-store": "^6.0.1"
  },
  "devDependencies": {
    "electron": "^10.1.5",
    "electron-builder": "^22.9.1",
    "nuxt": "^2.14.7",
    "nuxtron": "^0.3.1",
    "prisma": "^3.0.2"
  }
}
```

and my electron-builder config

```yml
appId: com.example.nuxtron
productName: My Nuxtron App
copyright: Copyright © 2019 Shiono Yoshihide
directories:
  output: dist
  buildResources: resources
files:
  - from: .
    filter:
      - package.json
      - app
extraResources:
  - "resources/dev.db"
  - "node_modules/.prisma/**/*"
  - "node_modules/@prisma/client/**/*"
publish: null
```

I'm simply send in my front (renderer) :
```vue
mounted(){
  this.mmm = ipcRenderer.sendSync('mmm')
}
```

and getting , processing and returning in my back (main.js)

```javascript
import { PrismaClient } from '@prisma/client';
app.on('ready', ()=>{
  ipcMain.on('mmm', async (event, arg) => {  
    const prisma = new PrismaClient();
    const readValue = await prisma.admin.findFirst();
    event.returnValue = readValue;
  })
})
```

if I don't return prisma query result the app works fine , but the moment I return the result ( `event.returnValue = readValue;` ) , It breaks down (load the initial page and get stuck, if the initial page has many elements,css,js , it will massively increase memory (+10GB RAM) and wont load page properly) . I'm pretty sure it's because of database! so what should I do?
