### DISCUSSION TITLE
Deploying to GCP - Cloud Build & Cloud Run

### DISCUSSION THREAD

**Discussion by tomwray13** [prisma/prisma#9709] [Q&A] [answered]
Hi guys,

I have an application deployed to Google Cloud Run, built with Cloud Build and have a Postgres Cloud SQL database.

I believe I've done everything to set up on the Google side, I'm now just trying to figure out how to use the `npx prisma migrate deploy` command and struggling to know where to include it in the build process.

In my `cloudbuild.yaml` file, I've tried to run the command after the build has been deployed to Cloud Run:

```
steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      ['build', '-t', 'gcr.io/zeus-328019/$_BRANCH_NO_SLASH:$COMMIT_SHA', '.']
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/zeus-328019/$_BRANCH_NO_SLASH:$COMMIT_SHA']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '$_BRANCH_NO_SLASH'
      - '--image'
      - 'gcr.io/zeus-328019/$_BRANCH_NO_SLASH:$COMMIT_SHA'
      - '--region'
      - 'europe-west6'
  # Run database migrations
  - name: 'gcr.io/cloud-builders/npm'
    entrypoint: npx
    args:
      - 'prisma'
      - 'migrate'
      - 'deploy'
```

The build succeeds every step until the final step (the migration step) and then throws this error:

```
Step #3:  6 |   url      = env("DATABASE_URL")
Step #3:  5 |   provider = "postgresql"
Step #3:    | 
Step #3:   -->  schema.prisma:6
Step #3: error: Environment variable not found: DATABASE_URL.
Step #3: 
Step #3: Error: Get config: Schema Parsing P1012
Step #3: Prisma schema loaded from prisma/schema.prisma
```

I have definitely added the ENV variables for the database connection in Cloud Run.

I've not done loads of cloud build stuff before, maybe the final step in the build is incorrect?

If you're able to suggest anything, thank you in advance 🙏

**Comment by armandoborge** [comment]
I would first execute the Prisma migrations and just after that the deploy to Cloud Run, this way if the migration fails you don't end up with a service without the DB changes required to run.

Regarding the error, you can inject the ENV variable in your step so it can be available for your command:    
```
# Run database migrations
  - name: 'gcr.io/cloud-builders/npm'
    entrypoint: npx
    env:
     - DATABASE_URL=$_DATABASE_URL <----- HERE
    args:
      - 'prisma'
      - 'migrate'
      - 'deploy'
```
