### DISCUSSION TITLE
How to connect to mongoDb locally

### DISCUSSION THREAD

**Discussion by RichardBray** [prisma/prisma#9994] [Q&A] [answered]
Hey all,

So I've been able to connect to a MongoDB cluster with Prisma but not locally. 

I have a `DATABASE_URL` in my .env file with this value
`mongodb+srv://myUserAdmin:<password>@localhost:27017/myDB?retryWrites=true&w=majority`

And this is the error message I get:

**The provided database string is invalid. Invalid MongoDB connection string in database URL. Please refer to the documentation in https://www.prisma.io/docs/reference/database-reference/connection-urls for constructing a correct connection string. In some cases, certain characters must be escaped. Please check the string for any illegal characters.**

I am using Prisma with Express and GraphQL but I don't think that should make a difference.

With the same values above I am able to connect to MongoDB Compass fine but not with Prisma 🤔 

Any ideas?

**Comment by austincrim** [comment]
Hey @RichardBray 👋!

Are you trying to connect to MongoDB Atlas while running locally or are you running Mongo locally?

If you are running Mongo locally, try removing `+srv` from your connection string.

Let me know!

**Reply by RichardBray** [reply]
Hey @austincrim thanks for your response, that kind of worked but now I have a different error:

**Error occurred during query execution:\nConnectorError(ConnectorError { user_facing_error: None, kind: AuthenticationFailed { user: \"SCRAM failure: Authentication failed.\"**

Maybe this is because I have SCRAM authentication enabled? But it works fine on Compass 🤔

**Reply by austincrim** [reply]
Could you please double check your user/password are correct and have any special characters URL-encoded? Compass is probably handling that part for you.

**Comment by RichardBray** [comment, marked as answer]
I figured the issue out, I needed to add this to `?authSource=admin`

In the mongo shell, I need to change the table to "admin" before I can authenticate. Maybe Compass adds this for you automatically.

For anyone interested the working env variable looks like this:
```
DATABASE_URL="mongodb://myUserAdmin:<password>@localhost:27017/trimm?authSource=admin"
```

Thanks for all your help @austincrim

**Reply by younes-io** [reply]
This does not solve it for me

**Reply by max-programming** [reply]
@younes-io What is your connection string?

**Reply by juniorcost4** [reply]
I added "?authSource=admin" and it solved it for me. Thank you!

**Reply by mbledkowski** [reply]
WTFFFF?!?! I lost so much time and solution was that simple, I AM DONE. Why this is not present in docs?

**Reply by austincrim** [reply]
@mbledkowski I'm really sorry to hear that! I am now working with the docs team to get a note added about `authSource=admin` 👍.

**Reply by antraxbr666** [reply]
> I added "?authSource=admin" and it solved it for me. Thank you!

Man, you are my hero!

**Reply by vitosdeveloper** [reply]
Saved me a lot of time. Ty.

**Reply by SDAravind** [reply]
this is required for prisma odm as well. While native mongodb nodejs doesn't require this but required by the prisma ODM.

**Comment by tkssharma** [comment]
you guys should put a proper example of how can I connect to mongo URI 
i followed Prisma docs and it didn't work 

```
version: "3"
services:
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - "27017:27017"
```
based on this my URL will become
DATABASE_URL="mongodb://root:root@localhost:27017/admin?authSource=admin?retryWrites=false"
what is wrong with this i am getting as i am able to connect to mongo with above url 

```
  Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: AuthenticationFailed { user: "SCRAM failure: Authentication failed." } })
    at cb (/Users/tkssharma/tkssharma/nodejs-db-orm-world/with Prisma/express-prisma-mongo-apis/node_modules/@prisma/client/runtime/index.js:38687:17) {
  clientVersion: '3.6.0'
}
```

**Reply by janpio** [reply]
A connection string with 2 parameters uses `?` for the first one, but then `&` for the second one in the query string:
`mongodb://root:root@localhost:27017/admin?authSource=admin?retryWrites=false` should be `mongodb://root:root@localhost:27017/admin?authSource=admin&retryWrites=false`

**Reply by tkssharma** [reply]
that was just a small error .. after fixing that also i see same issue

**Comment by akarabach** [comment]
any updates on it ? I'm facing the same issue @tkssharma

**Reply by tkssharma** [reply]
don't use local container as replica set is not there use from cloud cluster 
https://www.youtube.com/watch?v=dVA0DAyI3J8

**Comment by younes-io** [comment]
I am facing the same issue. I don't want to do it on the cloud. I absolutely have to do it locally in a docker container... any tips?

EDIT:

Finally, I used this setup : https://github.com/prisma/prisma-examples/blob/latest/databases/mongodb/docker-compose.yml and this env variable `DATABASE_URL=mongodb://username:password@localhost:27017/db_name?authSource=admin&retryWrites=false`

**Reply by tkssharma** [reply]
post here when you get the solution. I spent enough time and then give up !!

**Reply by younes-io** [reply]
@tkssharma : I used this image `image: prismagraphql/mongo-single-replica:4.4.3-bionic` instead of the official `mongodb` image. Check out the link I shared

**Reply by Barlow1** [reply]
This helped me get some sleep tonight, thank you sir!

**Reply by benlyazid** [reply]
Thank yoooooooooou I have spent 2 days trying to fix this 👍

**Reply by vicentematus** [reply]
This worked great. I was using the official mongodb image with Docker, but it didn't support replica set. Make sure you use an image that supports replica sets (so it can work for transactions for like next auth etc). Also using the option ?authSource=admin help me fix it. And also using localhost instead of 0.0.0.0 or whatever ip address for your localhost.

This was my final connection string using the docker compose file:
`DATABASE_URL=mongodb://root:prisma@localhost:27017/database_name?authSource=admin&retryWrites=false`

**Reply by ali-d-coded** [reply]
> @tkssharma : I used this image `image: prismagraphql/mongo-single-replica:4.4.3-bionic` instead of the official `mongodb` image. Check out the link I shared

now this happens 👇👇👇
$ docker compose up
[+] Running 1/1
 - Container mongonest-mongodb_container-1  Recreated                                                                                 0.3s 
Attaching to mongonest-mongodb_container-1
mongonest-mongodb_container-1  | Waiting for initialization...
mongonest-mongodb_container-1  | Initializing replica set...
mongonest-mongodb_container-1  | /usr/local/bin/docker-entrypoint.sh: line 407: -u: command not found
mongonest-mongodb_container-1 exited with code 127

🤷‍♂️🤷‍♂️🤷‍♂️

**Reply by mohammadsaadshafiq** [reply]
Hi check this article of it solves your problem, I use the same image 
https://github.com/prisma/prisma/discussions/9994#discussioncomment-3970355

**Comment by verbose117** [comment]
This information should probably be added in the docs.

**Comment by mohammadsaadshafiq** [comment]
For future reference, I wrote this article for this issue.
https://medium.com/@saad.shafiq1997/connect-prisma-with-mongo-db-image-358ddcc300ee

**Comment by verbose117** [comment]
Thanks 👍🏻

**Comment by LOGANLEEE** [comment]
in my case this code solved.
user and pw suppose to have root role.

    DATABASE_URL="mongodb://root:example@localhost:3333/liz?retryWrites=true&w=majority&authSource=admin"

    DATABASE_URL="mongodb://username:password@ip:port/db?retryWrites=true&w=majority&authSource=admin"

do remove +rsv if you want to connect to your local mongodb

**Comment by Gil3co** [comment]
Maybe it's because of the mongo I'm running on a container, but adding this: `directConnection=true` helped me

**Comment by christianbueschi** [comment]
I had a running mongo service on my Mac. So I had to shut it down first - then it worked.

How to shut it down:
https://stackoverflow.com/questions/8495293/whats-a-clean-way-to-stop-mongod-on-mac-os-x

**Comment by IsaacHatilima** [comment]
How do I set username and password on local machine?

**Reply by mohammadsaadshafiq** [reply]
In connection string where it says admin and root  DATABASE_URL="mongodb://root:prisma@localhost:27017/test?authSource=admin&retryWrites=false"

**Reply by IsaacHatilima** [reply]
Thanks, I am able to connect but then I am getting `Prisma needs to perform transactions, which requires your MongoDB server to be run as a replica set` I am on Windows. But with cloud mongo everything works

**Reply by mohammadsaadshafiq** [reply]
Yes use the article I have written above, use the mongo image that I am using. Hope that helps

**Reply by alialshara94** [reply]
> 

same error with me !

**Reply by verbose117** [reply]
Check this article I wrote!
https://medium.com/@haneenmahdin/set-up-mongodb-prisma-with-docker-c8c2f28e85de

**Reply by verbose117** [reply]
I also created an npm package to simplify this process: https://github.com/haneenmahd/dmp

**Comment by mandeepsingh10** [comment]
I was facing the same issue trying to dockerize a full stack app which was originally developed using React, Tailwind, Next, Prisma, Mongo Atlas, NextAuth.
https://github.com/mandeepsingh10/chwitter
The docker-compose.yml spins up mongoDB replica along with the nextjs-frontend.
The code can be used to fix the connectivity issue between prisma and MongoDB replicasets.
```
DATABASE_URL "mongodb://root:prisma@mongodb-primary:27017/test?authSource=admin&retryWrites=false"
```
```
version: '2'
services:
  mongodb-primary:
    image: 'bitnami/mongodb:latest'
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-primary
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_PASSWORD=prisma
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
    ports:
      - 27017:27017

    volumes:
      - 'mongodb_master_data:/bitnami'

  mongodb-secondary:
    image: 'bitnami/mongodb:latest'
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-secondary
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
      - MONGODB_INITIAL_PRIMARY_PORT_NUMBER=27017
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=prisma
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
    ports:
      - 27027:27017

  mongodb-arbiter:
    image: 'bitnami/mongodb:latest'
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-arbiter
      - MONGODB_REPLICA_SET_MODE=arbiter
      - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
      - MONGODB_INITIAL_PRIMARY_PORT_NUMBER=27017
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=prisma
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
    ports:
      - 27037:27017

  nxtjs-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongodb-primary
      - mongodb-secondary
      - mongodb-arbiter

volumes:
  mongodb_master_data:
    driver: local
```

**Reply by raul-repos** [reply]
This worked for me, thanks for sharing.

**Comment by verbose117** [comment]
The issue that persists is that mongodb should be a replica set and the url should have `?authSource=admin` to fix this isssue.

I have created an npm package to fix this issue and simplify the process: https://github.com/haneenmahd/dmp

**Reply by ridoystarlord** [reply]
Not working: https://prnt.sc/QPSUY7hBEQnN

**Reply by verbose117** [reply]
Can you show how your connecting string looks like?

**Reply by ridoystarlord** [reply]
https://prnt.sc/mHDnwACIcV8e

**Reply by verbose117** [reply]
Try moving `authSource` to the end of the url.
```
mongodb://root:prisma@localhost:27017/test?w=majority&retryWrites=fase&authSource=admin
```

**Reply by ridoystarlord** [reply]
https://prnt.sc/QK2yX0sgRL7P

**Reply by verbose117** [reply]
I think you should remove the existing diagnostic data and if you run the container again it'll fix this issue.
```
sudo rm -rf /srv/mongo/diagnostic.data
```

**Reply by ridoystarlord** [reply]
I am windows user so i try rm -rf /srv/mongo/diagnostic.data , after that when run this docker-compose up again it gives me same error.

**Comment by virturio** [comment]
Adding `?replicaSet=rs0` to the `DATABASE_URL` should fix the issue, source [https://medium.com/workleap/the-only-local-mongodb-replica-set-with-docker-compose-guide-youll-ever-need-2f0b74dd8384](https://medium.com/workleap/the-only-local-mongodb-replica-set-with-docker-compose-guide-youll-ever-need-2f0b74dd8384)

`DATABASE_URL="mongodb://127.0.0.1:27017/testdb?replicaSet=rs0"`

also, here is my dockerfile config
```
services:
  mongo:
    image: mongo:latest
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    ports:
      - 27017:27017
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'host.docker.internal:27017'}]}) }" | mongosh --port 27017 --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      start_interval: 1s
      retries: 30
    environment:
      MONGO_INITDB_DATABASE: testdb

```
