### ISSUE TITLE
Github Actions is printing the database url after running prisma migrate deploy

### ISSUE THREAD

**Issue by kharann** [prisma/prisma#10167]
### Bug description

It seems like that prisma migrate deploy is printing out the database URL, including the password. This is my workflow file

```yaml
name: Migrate database
on:
    workflow_run:
        workflows: ['Continuous Deployment']
        types:
            - completed
    workflow_dispatch:
        release:
            types: [published, edited]
jobs:
    migrate:
        runs-on: ubuntu-latest
        environment: Migration
        steps:
            - uses: actions/checkout@v2
            - uses: actions/cache@v2
              with:
                  path: '**/node_modules'
                  key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
            - name: Set up Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: 14
            - name: Install Node.js dependencies
              run: yarn

            - name: Run migrations
              run: yarn migrate:db
              env:
                  DATABASE_URL: ${{ secrets.DATABASE_URL }}
```

### How to reproduce

1. Make a workflow file as above
2. Add a database URL and successfully migrate from the pipeline
3. See the printed url

### Expected behavior

Does not print the USB url

### Prisma information

yarn migrate:db runs the command `prisma migrate deploy`

### Environment & setup

The pipeline runs Ubunutu

### Prisma Version

Prisma is a devdependency with the version 2.21
```
prisma               : 2.21.2
@prisma/client       : 2.21.2
Current platform     : debian-openssl-1.1.x
Query Engine         : query-engine e421996c87d5f3c8f7eeadd502d4ad402c89464d (at node_modules/@prisma/engines/query-engine-debian-openssl-1.1.x)
Migration Engine     : migration-engine-cli e421996c87d5f3c8f7eeadd502d4ad402c89464d (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine : introspection-core e421996c87d5f3c8f7eeadd502d4ad402c89464d (at node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary        : prisma-fmt e421996c87d5f3c8f7eeadd502d4ad402c89464d (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Default Engines Hash : e421996c87d5f3c8f7eeadd502d4ad402c89464d
Studio               : 0.371.0
```
