### ISSUE TITLE
Github Action Workflow fails because of env("DATABASE_URL") in `schema.prisma` file.

### ISSUE THREAD

**Issue by cvrlnolan** [prisma/prisma#10204]
### Bug description

Upon pushing my project to Github with a set of github action workflows, the actions work well until reaching the job step of `Run tests` which fails generating the following error:

> `UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "Error: error: Error validating datasource "db": You must provide a nonempty URL. The environment variable "DATABASE_URL" resolved to an empty string.` 

This occurs when the test hits the following line in the `schema.prisma` file:

> `-->  schema.prisma:6`
> `| `
> `5 |   provider = "mongodb"`
> ` 6 |   url      = env("DATABASE_URL")`
> `| `

Here is a screenshot of failed tests and error generated:
![Screen Shot 2021-11-11 at 8 16 25 AM](https://user-images.githubusercontent.com/42778495/141255918-c6c2d9eb-51f2-4479-992d-7aa3d31df24c.png)

### How to reproduce

1. Node.js should be installed on your machine.
2. Create a project directory `mkdir directory-name` and switch working directory to newly created directory `cd directory-name`
3. Initialize a TypeScript project and add the Prisma CLI as a development dependency to it 
```bash
npm init -y
```
```bash
npm install prisma typescript ts-node @types/node --save-dev
```
4. Next, create a `tsconfig.json` file and add the following configuration to it:
```json
{
  "compilerOptions": {
    "sourceMap": true,
    "outDir": "dist",
    "strict": true,
    "lib": ["esnext"],
    "esModuleInterop": true
  }
}
```
5. You can now invoke the Prisma CLI by prefixing it with npx:
```bash
npx prisma
```
6. Next, set up your Prisma project by creating your Prisma schema file with the following command:
```bash
npx prisma init
```
7. To connect your database, you need to set the url field of the datasource block in your Prisma schema to your database connection URL:

```js
datasource db {
  provider = "mongodb"
  url      = env("DATABASE_URL")
}
```

In this case, the url is set via an environment variable which is defined in .env (the project uses a [MongoDB Atlas](https://www.mongodb.com/cloud/atlas) URL):

```js
DATABASE_URL="mongodb+srv://test:test@cluster0.ns1yp.mongodb.net/myFirstDatabase"
```
8. Because MongoDB is currently a preview feature, you need to explicitly define that in the generator block.
```js
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["mongoDb"]
}
```
No need to install the prisma client since we are not focusing on that. We will skip directly into setting up the github action workflows.

9. Create a new `.github` folder in the project direcoty. Inside this folder, we create another folder `workflows` and add a `.yml` file of any name (example: `integration.yml`). We will setup our actions in this file as follows:

```yml
name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build on node ${{ matrix.node-version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [16.x]
        os: [ubuntu-latest, macOS-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Run tests
        run: npm run test
        # env:
        #   DATABASE_URL: ${{ secrets.DATABASE_URL }}
        # Tried this too, but didn't work.

      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v1
      # upload to codecov after successful coverage tests.

      # - name: Next build
      #   run: npm run build
      # # next build causes error on windows os
```
10. Save all files, create a new git repository & push the project a let the automated workflow integrations do the job.

### Expected behavior

All tests should run without that bug occuring. Because when I enter directly the `DATABASE_URL` value to the `schema.prisma` file, the github action workflows builds successfully.

```js
datasource db {
  provider = "mongodb"
  // url      = env("DATABASE_URL")
  url      = "mongodb+srv://test:test@cluster0.ns1yp.mongodb.net/myFirstDatabase"
}
```

Here is a screenshot of a successful test & eventual github workflow successful build.
![Screen Shot 2021-11-11 at 8 28 55 AM](https://user-images.githubusercontent.com/42778495/141256340-93277cbc-4d84-4608-88ae-391bff6e9634.png)

### Prisma information

![Screen Shot 2021-11-11 at 7 55 51 AM](https://user-images.githubusercontent.com/42778495/141252131-f2646bad-aa49-4e48-9389-5e2adb7d548d.png)

### Environment & setup

- OS: ubuntu-latest, macOS-latest (Virtual Environments running Github Actions)
- Database: MongoDB
- Node.js version: 16.x

### Prisma Version

```
Environment variables loaded from .env
prisma                  : 3.0.2
@prisma/client          : 3.0.2
Current platform        : darwin
Query Engine (Node-API) : libquery-engine 2452cc6313d52b8b9a96999ac0e974d0aedf88db (at node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Migration Engine        : migration-engine-cli 2452cc6313d52b8b9a96999ac0e974d0aedf88db (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine    : introspection-core 2452cc6313d52b8b9a96999ac0e974d0aedf88db (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary           : prisma-fmt 2452cc6313d52b8b9a96999ac0e974d0aedf88db (at node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash    : 2452cc6313d52b8b9a96999ac0e974d0aedf88db
Studio                  : 0.423.0
```

**Comment by janpio** [comment]
- What does `npm run test` actually do?
- If it uses Prisma: Can you set `DEBUG=*` and post the output that is creating when running your script?

**Comment by cvrlnolan** [comment]
@janpio Sorry I didn't mention the test folder & files to create ..
`npm run test` actually runs the test files created for the project with coverage ie `jest --coverage` and when it comes across the `schema.prisma` file it generates the error state above in the issue.
I don't understand clearly where the `DEBUG=*` should be inserted to visualize the output you mentioned.

**Comment by janpio** [comment]
> `npm run test` actually runs the test files created for the project with coverage ie `jest --coverage` and when it comes across the `schema.prisma` file it generates the error state above in the issue.

Can you share the relevant code that is triggering this? What Prisma code is executed in there? Does it also happen if you extract that code to a plain script file and run that directly in GH Actions instead of via Jest and `npm run`?

Right now we do not have enough information to reproduce this unfortunately.


> I don't understand clearly where the `DEBUG=*` should be inserted to visualize the output you mentioned.

Sorry, should have linked to the docs: https://pris.ly/debugging

**Comment by cvrlnolan** [comment]
Here is the code triggering the error:
![Screen Shot 2021-11-16 at 7 07 46 AM](https://user-images.githubusercontent.com/42778495/141930367-4b6d40df-1f70-4d6a-a31e-313cf7ccf7ba.png)

When the test coverage encounters the 
```js 
url      = env("DATABASE_URL")
```

It triggers the following clarified error: 

> `The promise rejected with the reason "Error: error: Error validating datasource "db": You must provide a nonempty URL. The environment variable "DATABASE_URL" resolved to an empty string.`

And from the attempts I have described above, I have tried accessing the environmental variables through GH Actions & more attempts but still produces the error.

Same error is being output by Prisma `DEBUG=*`
![Screen Shot 2021-11-16 at 7 19 21 AM](https://user-images.githubusercontent.com/42778495/141932165-af0666ef-74f0-4123-a4b6-388061b2de72.png)
:

And all Environment Variable values are entered accordingly in the `.env` & `.env.local` files.

**Comment by janpio** [comment]
Can you please create a minimal reproduction repository? Instead of going via `npm run test` for example executing `npx prisma db pull` should also try to read the environment variable and fail if it is not available to Prisma.

**Comment by cvrlnolan** [comment]
Actually to be clear, this problem occurs when running the GH Actions & I need to run `npm run test` as part of the build jobs in my GH Actions. 
On local development server, everything works fine & it is able to read values from the `.env` file including the `npx prisma db pull`
But in  the virtual environment of the GH Actions, it is unable to read values from the `.env` file hence generating that error which I described above via clear steps.

**Comment by cvrlnolan** [comment]
@janpio here are two different repos. One where the workflow works, & the other the workflow fails because of the prisma error.

- https://github.com/cvrlnolan/prisma_issue (Workflow builds)
- https://github.com/cvrlnolan/realestate_typescript (Workflow fails)

Any help identifying the issue will be great !

**Comment by janpio** [comment]
Interesting. 

Do I read this correctly that when trying to build a reproduction, things suddenly started to work? That would be great as it would point to _something_ in the real project being the cause here vs. a real bug that we might not be able to fix. (On the other hand: Does the reproduction try to use Prisma the same way in the code that is being tested?)

Looking at https://github.com/cvrlnolan/realestate_typescript/runs/4221172670?check_suite_focus=true#step:5:645 it seems that actually all tests are passing, although we have some output above that indicates something might not be going well - is that correct? Is any of the weird output connected to Prisma not working?

I can play around a bit with different options if you approve my PR: https://github.com/cvrlnolan/realestate_typescript/pull/1

**Comment by cvrlnolan** [comment]
@janpio Yes sure I approved it. Any help is welcomed !

**Comment by cvrlnolan** [comment]
@janpio, the test still fails after your PR ran the workflows with the modifications you did. But this time it logged some interesting things to the console because you included the `DEBUG=*` in the workflow.
Either way, it still display the same cause of error unfourtunately.

![Screen Shot 2021-11-18 at 7 25 19 AM](https://user-images.githubusercontent.com/42778495/142363498-a218c003-aa7e-464c-a32b-79ae7c2893f2.png)

**Comment by janpio** [comment]
The error is quite different: 
```
"Error: error: Error validating datasource `db`: the URL must start with the protocol `mongo`.
```
This is the case because I set it manually to `foo`.

This indicates that in your run there really was no value in the env var.

**Comment by janpio** [comment]
We should learn more if you approve these waiting Actions runs: https://github.com/cvrlnolan/realestate_typescript/actions/runs/1478306154 + https://github.com/cvrlnolan/realestate_typescript/actions/runs/1478316346

**Comment by cvrlnolan** [comment]
@janpio Both Actions failed .. This issue is really tricky & interesting.

**Comment by cvrlnolan** [comment]
Here is the secret DATABASE_URL for the workflow

![Screen Shot 2021-11-19 at 5 03 29 AM](https://user-images.githubusercontent.com/42778495/142562941-e8fffef2-cb5a-47b3-aaf8-e10e1a6a9f18.png)

**Comment by janpio** [comment]
Can you try putting it as `Repository secrets` instead, the table below? I am not sure how GH Actions interacts with the "Environments".

**Comment by cvrlnolan** [comment]
@janpio, it solved the issue ! Thanks !
I too am not quite certain how GH Actions use the "Environments"

Thanks again.

**Comment by janpio** [comment]
They put their secret into the `Repository secrets` area of the settings so it is available to GitHub Actions.

**Comment by ValiDraganescu** [comment]
I also encountered this issue, after one hour I found the fix.

Originally, in my .env file I had DB_URL='mysql://connection-string' and this is what I put in the github secret. It turns out you need to put it without the quotes, like this: mysql://connection-string

**Comment by gotpop** [comment]
# Fixed it!

I just sorted this out here's my solution.

1. go to `settings/secrets/actions`
2. Add your `DATABASE_URL` secret under `Repository secrets` _not_ Environment secrets.
3. Ensure you don't use quotation marks
4. In your GitHub workflow file import the environment variable in the build step not at the top.

```yml
name: Cypress Tests 🧪

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛒
        uses: actions/checkout@v2
      - name: Cypress build & run 🏗️
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        uses: cypress-io/github-action@v4.2.0
        with:
          build: npm run build
          start: npm start
      - name: Run Component tests 🔬
        uses: cypress-io/github-action@v4
        with:
          install: false
          component: true

```

## Resources
https://docs.github.com/en/actions/learn-github-actions/environment-variables
https://github.com/gotpop/gotpop-starter/blob/master/.github/workflows/main.yml
https://snyk.io/blog/how-to-use-github-actions-environment-variables

_Good luck!_
