### ISSUE TITLE
Prisma not connecting to postgres docker container in the same network. It gets connected using pg

### ISSUE THREAD

**Issue by Dnyaneshwar-dev** [prisma/prisma#10574]
### Bug description

I have two docker containers one with postgres and other with nodejs backend. They are under same external docker network.
Prisma is not getting connected when I run npx prisma db push in Dockerfile for pushing database tables.

### How to reproduce

docker-compose file of postgres:
`version: '3.8'
services:
 postgres:
    image: postgres:latest
    container_name: postgresfe
    ports:
      - 5430:5432
    restart: always
    environment:
      - PGHOST=postgres
      - POSTGRES_PASSWORD=fe@2021
      - POSTGRES_DB=freshdb
    expose:
      - 5432

networks:
  default:
    external : true
    name: webnet

`

docker-compose file of backend:
`version: '3.8'

services:
  backend:
    build: ./
    hostname: backend
    container_name: backend
    ports:
      - 5000:5000
    environment:
      - DATABASE_URL=postgres://postgres:fe@2021@postgres:5432/freshdb
    
networks:
  default:
    external : true
    name: webnet
    `

Dockerfile of backend:
`FROM node:17-alpine

WORKDIR /app

COPY package*.json /app

RUN npm install

COPY . .

RUN npx prisma generate

RUN npx prisma db push --accept-data-loss

CMD [ "npm" ,"start"]
`

### Prisma information

Version : 3.6.0

### Environment & setup

Windows

### Prisma Version

```
3.6.0
```

**Comment by piotr-chowaniec** [comment]
Hi There! I have a similar issue with Prisma `3.6.0`. 
I can't connect to Postgres from inside the docker container in order to set up DB at startup.
OS: mac os 11.6
docker version: `20.10.11, build dea9396`

`dockerfile` definition of my `events-board` service:
```
FROM node:16.10

WORKDIR /app

COPY package*.json ./
COPY ./client/package*.json ./client/
COPY ./server/package*.json ./server/
COPY ./commonPackages ./commonPackages

RUN npm run install:all

```

`docker-compose.yml`:

```
version: '3.8'

services:
  events-board:
    container_name: events-board
    restart: on-failure
    build: .
    command: npm run dev
    volumes:
      - .:/app
      - /app/node_modules
      - /app/client/node_modules
      - /app/server/node_modules
    ports:
      - 3000:3000
    depends_on:
      - events-db

  events-db:
    container_name: events-db
    restart: always
    image: postgres:14
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB

volumes:
  postgres:
```

I've tried to run `npx prisma migrate dev` from within `events-board` container.
I've accessed it by `docker exec -it events-board sh`
However, what I'm seeing is the following error:
![Screenshot 2021-12-06 at 21 22 43](https://user-images.githubusercontent.com/45924475/144916829-05afd989-7040-4c9e-90ff-bffbd6321ab9.png)

I'm also possible to ping that `events-board` container:
![Screenshot 2021-12-06 at 21 23 37](https://user-images.githubusercontent.com/45924475/144916936-1b3fc377-7a60-406f-9f70-c4dccd18ff93.png)

Changing hostname from service name `events-board` to IP address `172.25.0.3` solves the issue, however, it makes it unusable from the containerized perspective.
