### ISSUE TITLE
Unable to run migration with `docker-compose` in 

### ISSUE THREAD

**Issue by vaclav-stummer** [prisma/prisma#12100]
### Bug description

First of all, I love Prisma, and thank you for the development of such a great tool. Unfortunately I am unable to make it working with `docker-compose` locally. I am stuck in the setup prisma guide (https://www.prisma.io/docs/getting-started/setup-prisma/start-from-scratch/relational-databases/using-prisma-migrate-typescript-postgres). Where when I run command `npx prisma migrate dev --name init` I get response:

```shell
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": PostgreSQL database "postgres", schema "public" at "localhost:5432"

Error: P1010: User `user` was denied access on the database `postgres.public`
```

`docker-compose.yml`:

```yml
services:
  db:
    image: postgres:12
    restart: always
    env_file:
      - ./db/.env
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123
    ports:
      - 5432:5432
```

`.env`:

```
DATABASE_URL=postgresql://user:123@localhost:5432/postgres?schema=public&connection_limit=250&pool_timeout=0
```

### How to reproduce

-

### Expected behavior

-

### Prisma information

-

### Environment & setup

-

### Prisma Version

3.10.0
