### ISSUE TITLE
Official docker image for testing

### ISSUE THREAD

**Issue by PinkaminaDianePie** [prisma/prisma#12192]
## Problem

It would be nice to have docker images with supported databases for running e2e tests. Such images exist:
`prismagraphql/mongo-single-replica:4.2.17-bionic`
`prismagraphql/mongo-single-replica:4.4.3-bionic`
`prismagraphql/mongo-single-replica:5.0.3`
But they are not supported officially.

## Suggested solution

Not sure what kind of support such images need because in my case everything worked fine without any issues. Maybe they are stable enough to add them to Prisma documentation about testing?

**Comment by pantharshit00** [comment]
You can achieve the single replica setup easily without using the above images like so:
```yaml
version: '3'

services:
  mongo:
    container_name: mongo
    image: mongo:4
    command: --replSet rs0  # <--- this startup command enables the replicaset.
    ports:
      - '27017:27017'
      - '28017:28017'
    volumes:
      - ./data/mongo:/data/db
```

Then you need run the following once to start the replicaset:
```
docker-compose exec mongo mongo --eval "rs.initiate({_id: 'rs0', members: [{_id: 0, host: 'localhost:27017'}]});"
```

I don't think we would add the images directly in the documentation as they tailor to our specific testing needs. You can find some docs on them here:
https://github.com/prisma/engine-images/tree/main/mongo
