### ISSUE TITLE
MySQL: Parsing fails if `?` is included in the password section of the DATBASE_URL environment variable

### ISSUE THREAD

**Issue by ever0de** [prisma/prisma#13350]
### Bug description

Parsing fails if `?` is included in the password section of the DATBASE_URL environment variable

### How to reproduce

- Setup MySQL User and Database

```sql
# Create User (The password is "?" must include)
mysql> CREATE USER 'question'@'localhost' IDENTIFIED BY 'asdf?';
Query OK, 0 rows affected (0.04 sec)

# Create DATABASE
mysql> CREATE DATABASE prisma;
Query OK, 1 row affected (0.01 sec)

# Authorization
mysql> GRANT ALL PRIVILEGES ON prisma.* TO 'question'@'localhost';
Query OK, 0 rows affected (0.01 sec)
```

- Attempt to connect using `@prisma/client` in Typescript
<https://github.com/ever0de/prisma-bug-report>
Clone this git repository and do `pnpm install & pnpm start`

### Prisma information

```yaml
dependencies:
  '@prisma/client': 3.14.0_prisma@3.14.0
devDependencies:
  '@trivago/prettier-plugin-sort-imports': 3.2.0_prettier@2.6.2
  '@types/node': 17.0.33
  prettier: 2.6.2
  prisma: 3.14.0
  ts-node: 10.7.0_2e3zkt3gzqz6r43dj4x46rot3i
  typescript: 4.6.4
```

### Environment & setup

- OS: `Mac OS Monterey 12.2.1(21D62) arm`
- Database: `MySQL  Ver 8.0.28 for macos12.2 on arm64 (Homebrew)`
- Node.js version: `v16.15.0`

### Prisma Version

```
❯ npx prisma -v      
Environment variables loaded from .env
prisma                  : 3.14.0
@prisma/client          : 3.14.0
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine 2b0c12756921c891fec4f68d9444e18c7d5d4a6a (at node_modules/.pnpm/@prisma+engines@3.14.0-36.2b0c12756921c891fec4f68d9444e18c7d5d4a6a/node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Migration Engine        : migration-engine-cli 2b0c12756921c891fec4f68d9444e18c7d5d4a6a (at node_modules/.pnpm/@prisma+engines@3.14.0-36.2b0c12756921c891fec4f68d9444e18c7d5d4a6a/node_modules/@prisma/engines/migration-engine-darwin-arm64)
Introspection Engine    : introspection-core 2b0c12756921c891fec4f68d9444e18c7d5d4a6a (at node_modules/.pnpm/@prisma+engines@3.14.0-36.2b0c12756921c891fec4f68d9444e18c7d5d4a6a/node_modules/@prisma/engines/introspection-engine-darwin-arm64)
Format Binary           : prisma-fmt 2b0c12756921c891fec4f68d9444e18c7d5d4a6a (at node_modules/.pnpm/@prisma+engines@3.14.0-36.2b0c12756921c891fec4f68d9444e18c7d5d4a6a/node_modules/@prisma/engines/prisma-fmt-darwin-arm64)
Default Engines Hash    : 2b0c12756921c891fec4f68d9444e18c7d5d4a6a
Studio                  : 0.460.0
```
