### ISSUE TITLE
migrate deploy: Error: P1010: User `user` was denied access on the database `db.public`

### ISSUE THREAD

**Issue by ICiscoStu** [prisma/prisma#13384]
### Bug description

migrate deploy throws Error: P1010: User `user` was denied access on the database `db.public`

### How to reproduce

run migrate deploy

### Expected behavior

migrations should run and tables on the migration should be created

since this is a production deploy, no shadow database should be necessary as per the documentation:

> The migrate deploy command:
> 
> * Does not issue a warning if an already applied migration is missing from migration history
> * Does not detect drift (production database schema differs from migration history end state - for example, due to a hotfix
> * Does not reset the database or generate artifacts (such as Prisma Client)
> * Does not rely on a shadow database

the user used has grant all on the database schema and its a superuser

### Prisma information

`datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}`
`postgresql://postgres:[pwd]@localhost:5432/postgres?schema=public`

### Environment & setup

- OS: CentOS Stream 9
- Database: PostgreSQL 13.7
- Node.js version: v16.14.0

### Prisma Version

```
3.10.0
```

**Comment by ICiscoStu** [comment]
the database is local to the machine and listens to localhost

the connection works for the user and it can perform every possible operation on the database and schema

**Comment by janpio** [comment]
Does `npx prisma db pull` work?
Can you paste the full output you are getting? I am confused where the error message gets `db.public` from when the database is called `postgres` and the schema is `public`.

**Comment by janpio** [comment]
Does `npx prisma db pull` work?

**Comment by ICiscoStu** [comment]
> Does `npx prisma db pull` work?

no it does not, the error I get is the one posted above...

``` 
npx prisma db pull
Environment variables loaded from .env
Datasource "db": PostgreSQL database "postgres", schema "public" at "localhost:5432"

✖ Introspecting based on datasource defined in prisma/schema.prisma

Error: P1010

User 'postgres' was denied access on the database 'postgres.public'```

**Comment by janpio** [comment]
Ah sorry, did not read close enough then.

This error messge is directly from PostgreSQL, so it is talking to `locahost:5432` on database `postgres` with schema `public` with the credentials you provided, and really getting that error message back. I can imagine no way how Prisma could interfere with that in any way leading to such an error message from the database.

**Comment by ICiscoStu** [comment]
it does, and thanks to you I found the issue, since it's a peer connection, the way the connection works requires an OS user to initiate the connection directly.

updating pg_hba.conf to reflect a localhost connection trusted for the user solved the issue

it was indeed a problem with Postgres and not prisma.

thank you and absolutely in love with the project

keep it up!

**Comment by janpio** [comment]
Awesome I could help you figure that out. Let us know if you stumble over anything else 👍

**Comment by Boubalou** [comment]
For any other like me that stumbled upon this while trying to use a Remix `Stack` project with a `docker-compose` using Postgres included, I simply specified a different `volume` for the postres data: 

Example of my complete `docker-compose.yml` file:

```yaml
version: "3.7"
services:
  postgres:
    image: postgres:14-alpine
    container_name: remix-blues-stack
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - remix-blues-stack:/var/lib/postgresql/data
volumes:
  remix-blues-stack:
```

**Comment by herbievine** [comment]
For anyone running into this in the future, you have to map the port to another one, as the error (in my case) came from ports colliding.

Final `docker-compose.yml`:

```yaml
version: '3.8'
services:
  postgres:
    image: postgres:13
    restart: always
    container_name: my-db
    ports:
      - "5555:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - my-db:/var/lib/postgresql/data
volumes:
  my-db:
```

Then connect to it using `postgresql://postgres:postgres@localhost:5555/my-db?schema=public`

Should work then!
