### ISSUE TITLE
Prisma crashes when using pgpool-II 

### ISSUE THREAD

**Issue by 0x77dev** [prisma/prisma#13427]
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v16.15.0           | 
| OS              | linux-musl         |
| Prisma Client   | 2.30.3             |
| Query Engine    | query-engine b8c35d44de987a9691890b3ddf3e2e7effb9bf20|
| Database        | undefined|

## Logs
```
n+PostgreSQL+connection%3A+Error+%7B+kind%3A+Closed%2C+cause%3A+None+%7D&template=bug_report.md

If you want the Prisma team to look into it, please open the link above 🙏
To increase the chance of success, please post your schema and a snippet of
how you used Prisma Client in the issue. 

    at BinaryEngine.throwAsyncErrorIfExists (/usr/src/app/server/asset/prisma/runtime/index.js:30038:21)
    at BinaryEngine.handleRequestError (/usr/src/app/server/asset/prisma/runtime/index.js:29358:16)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async BinaryEngine.request (/usr/src/app/server/asset/prisma/runtime/index.js:29959:9)
    at async cb (/usr/src/app/server/asset/prisma/runtime/index.js:36464:26)
    at async /usr/src/app/server/lib/services/search/middleware.ts:20:20
    at async /usr/src/app/server/asset/middleware/asset.ts:8:20
    at async tracing (/usr/src/app/server/lib/middleware/tracing.ts:15:18)
    at async orderBy (/usr/src/app/server/lib/middleware/order-by.ts:13:18)
    at async getAssetResolver (/usr/src/app/server/asset/services/resolver.ts:80:15)
prisma:engine {
  error: PrismaClientUnknownRequestError3 [PrismaClientUnknownRequestError]: Error occurred during query execution:
  ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState("25006"), message: "cannot execute INSERT in a read-only transaction", detail: None, hint: None, position: None, where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("utility.c"), line: Some(249), routine: Some("PreventCommandIfReadOnly") }) }) })
      at BinaryEngine.graphQLToJSError (/usr/src/app/server/asset/prisma/runtime/index.js:30061:14)
      at BinaryEngine.request (/usr/src/app/server/asset/prisma/runtime/index.js:29944:24)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async cb (/usr/src/app/server/asset/prisma/runtime/index.js:36464:26)
      at async /usr/src/app/server/lib/services/search/middleware.ts:20:20
      at async /usr/src/app/server/asset/middleware/asset.ts:8:20
      at async tracing (/usr/src/app/server/lib/middleware/tracing.ts:15:18)
      at async orderBy (/usr/src/app/server/lib/middleware/order-by.ts:13:18)
      at async getAssetResolver (/usr/src/app/server/asset/services/resolver.ts:80:15)
      at async Promise.all (index 1) {
    clientVersion: '2.30.3'
  }
}
prisma:engine {
  error: PrismaClientUnknownRequestError3 [PrismaClientUnknownRequestError]: Error occurred during query execution:
  ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(
  
```

# PGPool-II Configuration

Docker image: `bitnami/pgpool:4`
Environment:
```yaml
env:
  - name: PGPOOL_BACKEND_NODES
    value: 0:master:5432:0:primary:DISALLOW_TO_FAILOVER,1:replica:5432:1:replica:ALWAYS_PRIMARY|DISALLOW_TO_FAILOVER
  - name: PGPOOL_POSTGRES_USERNAME
    value: postgres
  - name: PGPOOL_POSTGRES_PASSWORD
    value: postgres
  - name: PGPOOL_ADMIN_USERNAME
    value: postgres
  - name: PGPOOL_ADMIN_PASSWORD
    value: postgres
  - name: PGPOOL_ENABLE_LOAD_BALANCING
    value: "yes"
  - name: PGPOOL_ENABLE_STATEMENT_LOAD_BALANCING
    value: "yes"
  - name: PGPOOL_HEALTH_CHECK_PERIOD
    value: "5"
  - name: PGPOOL_HEALTH_CHECK_MAX_RETRIES
    value: "20"
  - name: PGPOOL_HEALTH_CHECK_RETRY_DELAY
    value: "1"
  - name: PGPOOL_RESERVED_CONNECTIONS
    value: "5"
  - name: PGPOOL_SR_CHECK_USER
    value: postgres
  - name: PGPOOL_SR_CHECK_PASSWORD
    value: postgres
  - name: PGPOOL_AUTHENTICATION_METHOD
    value: md5
```

It happens when the replica has a 1.0 lb weight.
