### ISSUE TITLE
 Can't reach database server which run in Docker

### ISSUE THREAD

**Issue by harmnot** [prisma/prisma#1385]
I currently try run Postgresql  in Docker, and use that database in prisma2 
in my docker list, my Postgresql running on `localhost:5555` and I connecting it on DBeaver, it was successfully , after i run prisma2 app with Postgresql in docker-compose 
it does't work,

my docker-compose.yml like this 
```
version: "3"
services:
  app:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - postgres
    ports:
      - "8100:8100"
  postgres:
    container_name: postgres
    image: postgres:10-alpine
    ports:
      - "5555:5432"
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: prod
```

in my `.env` **DB_URI = postgres://username:s@localhost:5555/prod** for my `schema.prisma` 

and after I run my docker-compose 
I got error like this :
```
Error: P1001: Can't reach database server at `localhost`:`5555`

Please make sure your database server is running at `localhost`:`5555`.
```
thought my Postgresql already running on that `localhost:5555` 
is there any way to resolve this ?

**Comment by pantharshit00** [comment]
Localhost inside docker is bound to the container, not the machine. So you can't access your postgres container via `localhost` on inside you application docker container. So please use `postgres`(the container name) instead of `localhost` as a host in order to connect to your database instance.

If you still want to access your machines loopback interface inside docker for some reason, you can use `host.docker.internal`(It doesn't work on linux though). But I would highly recommend you to use your container name as the database host.

**Comment by harmnot** [comment]
it was work with IP I get from this command `ipconfig getifaddr en0` , copy that ip in use it in schema.prisma, also I think it is very tricky if our Postgres not up in our machine docker for first time when it build in docker, because in my docker-compose I must run Postgres first time first and then run my server. so I create separate file
one for build postures `docker-compose.db.yml` and another is `docker-compose.build.yml` for our server app
and then I create script 
```
#!/bin/bash

export DB_URI=postres//username:password@IP:5555/database

docker-compose -f docker-compose.db.yml up -d

sleep 10

docker-compose -f docker-compose.build.yml up -d
```
and it was works , BUT.....


when I use Postgres docker for development 

and then running my server via `ts-node-dev` ( or development mode )

I got error like this 
```
Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: 
QueryError(Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), 
code: SqlState("42P01"), message: "relation \"public.people\" does not exist", 
detail: None, hint: None, position: Some(Original(176)), 
where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, 
file: Some("parse_relation.c"), line: Some(1159), routine: Some("parserOpenTable") }) }
```

it seems migration not created , but when I check in my database which running in docker with port 5555
the tables and migration look created,

**Comment by pantharshit00** [comment]
By development, you mean you are running your setup in the host and not in docker? Can you share a minimal reproduction in a git repository as I am unable to figure out all of the parts of your setup with the given information?

**Comment by harmnot** [comment]
I think that is because schema.prisma can't read my `.env.prod` thought I already export it and set -a and source ./.env.prod , it still not working in production,, when I export the URI of db , I need to create it on .env.prod as well, if I didn't do that , it got error like above

**Comment by pantharshit00** [comment]
Hm, we don't read .env file right now(#1255). For sourcing to work can you make sure you have `export` in front of all of the env vars in the env file?

**Comment by JulianRuiseco** [comment]
Is this ticket still active? It seems incredibly important.

I think even being able to set environment variables from the Dockerfile would be plenty

**Comment by pantharshit00** [comment]
@JulianRuiseco Which OS are you using? Please note that host.docker.internal doesn't work linux as per https://github.com/docker/for-linux/issues/264

**Comment by JulianRuiseco** [comment]
> @JulianRuiseco Which OS are you using? Please note that host.docker.internal doesn't work linux as per [docker/for-linux#264](https://github.com/docker/for-linux/issues/264)

@pantharshit00 

Yes, I did notice that. There appear to be linux workarounds as well, I have edited my comment above to reflect that this is for windows.

**Comment by harmnot** [comment]
@JulianRuiseco I @pantharshit00  can u try `docker.host.for.linux` or `docker.host.for.windows`

**Comment by softmarshmallow** [comment]
```
# docker-compose.yml
version: '3.1'
services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - database.env # configure postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
```

https://github.com/softmarshmallow/robbin/tree/master/server

https://github.com/softmarshmallow/robbin/blob/master/server/docker-compose.yml

here is my example for running postgres on doecker. had same issue, it works but, your docker postres will be generated under poject root.

still working on it.

**Comment by damianesteban** [comment]
I'm having a similar problem but with Kubernetes (and Docker). I've never had this issue with postgres and other ORMs / database clients. It is very confusing.

**Comment by samyabouseda** [comment]
@harmnot Try changing your `DB_URI` in your `.env` file from this: 
`DB_URI=postgres://username:s@localhost:5555/prod` to this `DB_URI=postgres://username:s@postgres/prod`

In the updated URI, the host is the name of your service (defined in docker-compose.yml) in which your PostgreSQL image is running. 

Suppose you had a `docker-compose.yml` as follow:
```
version: "3"

services:
  web:
    build: .
    ports:
      - "8000:8000"
  db:
    image: postgres
    ports:
      - "8001:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: strongpass
      POSTGRES_DB: example-db
```

When you run `docker-compose up`, two containers are created. The first, using `web`'s config and accessible under the name `web`. And the second, using `db`'s config and accessible under the name `db`. 

Once created, each container can then look up the hostname `web` or `db` and get back the appropriate container’s IP address. For example, `web`’s application code could connect to the URL `postgres://admin:strongpass@db/example-db` and start using the Postgres database.

For more info on how docker-compose handle networking, checkout this link: https://docs.docker.com/compose/networking/

**Comment by damianesteban** [comment]
The issue is that I'm not using docker compose files. I get the following error:

```
"errors": [
    {
      "message": "\nInvalid `prisma.patient.findMany()` invocation in\n/usr/src/app/node_modules/nexus-prisma/src/builder.ts:315:20\n\nError occurred during query execution:\nConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: Db, cause: Some(DbError { severity: \"ERROR\", parsed_severity: Some(Error), code: SqlState(\"42P01\"), message: \"relation \\\"public.Patient\\\" does not exist\", detail: None, hint: None, position: Some(Original(92)), where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some(\"parse_relation.c\"), line: Some(1159), routine: Some(\"parserOpenTable\") }) }) })",
```

**Comment by damianesteban** [comment]
I was able to get this running when I manually ran the migration in the pod's shell.

**Comment by harmnot** [comment]
can you all try not use built in `env` in Docker compose ? just use it with command line when running prisma
`export POSTGRES_ENV="LINK" && npm run dev `

**Comment by jferrettiboke** [comment]
@harmnot

> in my .env DB_URI = postgres://username:s@localhost:5555/prod for my schema.prisma

You must use the service name instead of `localhost`. Based on your `docker-compose.yaml`, it should be `postgres:5555`.

```
# .env
DB_URI="postgres://username:s@postgres:5555/prod"
```

**Comment by jferrettiboke** [comment]
@harmnot

> in my .env DB_URI = postgres://username:s@localhost:5555/prod for my schema.prisma

You must use the service name instead of `localhost`. Based on your `docker-compose.yaml`, it should be `postgres:5555`.

```
# .env
DB_URI="postgres://username:s@postgres:5555/prod"
```

This should work. Let me know whatever.

**Comment by Xaedblade** [comment]
I've got the answer you are all waiting for... **Docker starts services by alphabetical order!**!!!! DUMMEST THING EVER!
If you want to fix this like  I did... just put a 'z' in front of the service you want to run last, or an a in front of the service you want to run first... they should really just add an order field to this...
your code fails because your app service is called 'app' which runs first... and your db is called 'postgres' which means it will run after...

**Comment by JulianRuiseco** [comment]
DOCKERFILE

ADD
https://github.com/ufoscout/docker-compose-wait/releases/download/2.7.3/wait
 /wait
RUN chmod +x /wait

CMD /wait && npm run start



docker-compose.yml
backend:
    container_name: backend
    restart: always
    depends_on:
      - mysql
    environment:
      WAIT_HOSTS: mysql:3306

**Comment by epavanello** [comment]
to fix you need to config your docker-compose with **network_mode: "host"**
https://stackoverflow.com/a/55270528

Example of working configuration:

`DATABASE_URL="postgresql://USER:PWD@localhost:5432/DB"`

```
# docker-compose.yml
version: "3"
services:
  database:
    image: "postgres"
    env_file:
      - database.env # Or your variables
    network_mode: "host"

```

**Comment by Salehjarad** [comment]
I had the same error using `**docker-compose**`, and i did tried everything nothing works, cos before building the app, i need to do some migrations with Postgres.

the problem when i use `npx prisma migrate save --experimental` it's giving me an error that database not reachable, my **DATABASE_URL `postgres://USER:PASSWORD@db:5432/DATABASE_NAME`** .

---
I found a solution and i'm not sure if this is the best practice but it did works fine.

- Making a bash file to run after i start `docker-compose up`
- Dockerfile
```js
FROM node:12.19.0

WORKDIR /usr/app
COPY package*.json ./
RUN npm install
COPY . .

RUN apt-get update -y && apt-get upgrade -y && apt-get install git -y \
    && chmod +x /usr/app/wait-for-it.sh \
    && chmod +x /usr/app/run-it.sh

EXPOSE 9090

CMD [ "./run-it.sh" ]

```
- docker-compose.yml

```yml
version: "3.8"

services:
  some-server:
    image: some-server:1.0.0
    restart: always
    env_file:
      - ./prisma/.env
    build: .
    container_name: some-server
    depends_on:
      - db
    links:
      - db
    ports:
      - 9090:9090
  db:
    image: postgres:latest
    restart: always
    container_name: "db"
    environment:
      - POSTGRES_PASSWORD=PASSWORD
      - POSTGRES_USER=USER
      - POSTGRES_DB=DB_NAME
    volumes:
      - "pgsata:/var/lib/postgresql/data"
    expose:
      - 5432

volumes:
  pgdata:
```

- run-it.sh

```bash
#!/usr/bin/env bash
echo "-> starting prisma migrations to postgres...\n"
cd /usr/app/
./wait-for-it.sh db:5432 -- echo "db online\n"
npm run migrate:save --name init_prod
npm run migrate:up
sleep 5
npm run build
npm start
```

- package.json scripts

```json
  "scripts": {
    "start": "node dist/src/server",
    "clean": "rm -rf dist || true && rm ./schema.graphql || true && rm -rf src/generated || ture && echo \"\n cleaning done!\" ",
    "build": "npm -s run clean && npm -s run generate && tsc",
    "generate": "npm -s run generate:prisma && npm -s run generate:nexus",
    "generate:prisma": "prisma generate",
    "migrate:save": "prisma migrate save --experimental",
    "migrate:up": "prisma migrate up --experimental",
    "migrate:down": "prisma migrate down 1 --experimental",
    "generate:nexus": "ts-node --transpile-only src/schema",
    "dev": "ts-node-dev --no-notify --respawn --transpile-only src/server"
  },

```
- wait-for-it.sh -> [https://github.com/vishnubob/wait-for-it](url)

--

I hope this will help others. 😇

**Comment by devakrishna33** [comment]
If anyone is facing this issue, even after trying everything please make sure that the permissions to the /var/lib/docker folder is properly set. I was running docker on ec2 with an ebs volume, by default it doesn't provide access to all the users I noticed it and added read permissions for all users, deleted the containers and started it again, it started working

**Comment by rodrigojmr** [comment]
I'm having a similar issue on probably a different setup. I'm running everything on WSL, have no other part of my application dockerized, just the database so it's accessed by prisma. This is my `docker-compose.yml`:

```
version: '3.8'
services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: pg
    #tty: true
    ports:
      - '5432:5432'
    volumes:
      - data:/var/lib/postgresql/data
    network_mode: 'host'
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: prisma
    expose:
      - 5432
volumes:
  data:
    external: true
```

If I do `docker-compose up -d` and `docker exec -it {container_id} psql -d prisma -U prisma -W` I can get in just fine. 

It works. If I use `npx prisma migrate dev --preview-feature` I get:

```
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": PostgreSQL database "prisma", schema "public" at "postgres:5432"

Error: P1001: Can't reach database server at `postgres`:`5432`

Please make sure your database server is running at `postgres`:`5432`.
```

My DATABASE_URL is `DATABASE_URL=postgresql://prisma:prisma@postgres:5432/prisma`. I've tried changing `@postgres`to everything else that's been pointed out here. Doesn't work. Any help please? I've tried solving this for 2 days.
