### ISSUE TITLE
Using Prisma breaks `ts-node-dev` auto-reloading

### ISSUE THREAD

**Issue by austincrim** [prisma/prisma#14289]
### Reproduction
You can access this repo https://github.com/alexsro/Chat-Project.
The project is in folder Auth and in the readme file are the instructions for making the environment available.

You can perform the following steps to reproduce the problem:

Make a request on the route http://localhost:3334/users/test. (The response will be "users");
change response text to "jhon doe" for example;
When you save changes container will restart auto and will be freeze in "Restarting: /usr/app/src/modules/users/infra/http/routes/users.routes.ts has been modified";
if you make another request to the same route the response will not be "jhon doe" as it should;
To demonstrate that the problem occurs by prisma connection you can perform the following steps:

Stop the containers if they are running;
In client.ts file comment line 3 and uncomment file 4;
Make the same step decribed above and the problem will not happen.
Any questions I am at your disposal.
Thanks!

### Discussed in https://github.com/prisma/prisma/discussions/13208

<div type='discussions-op-text'>

<sup>Originally posted by **alexsro** May  5, 2022</sup>
Hello, I am just starting to use prism and I face a problem when I save my file and my containers are restarted, if the connection to prism has not been established yet everything is fine, otherwise the container cannot restart.
Obs. The connection with database and the requests work well.

message:
![Captura de tela de 2022-05-05 21-02-33](https://user-images.githubusercontent.com/65572080/167045818-8e62d73d-eb1b-4121-9aaa-0b7ade26beca.png)

My docker-compose.yml:
```
version: "3"

services:
  postgres:
    image: postgres
    container_name: postgres-auth-api
    environment:
      - POSTGRES_USER=User
      - POSTGRES_PASSWORD=Pass
    ports:
      - 6432:5432
    volumes:
      - data_postgres

  data_postgres:
    image: cogniteev/echo
    command: echo 'Data Container for Postgres'
    volumes:
      - /var/lib/postgresql/data

  app:
    build: .
    command: yarn dev:server
    container_name: auth-api
    ports:
      - 3334:3334
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    links: 
      - data_postgres
      - postgres
    restart: always
```
my database url : 
```
DATABASE_URL="postgresql://User:Pass@172.25.0.2:5432/postgres?schema=public"
```
I created a network for communication between the containers with the following commands:
```
docker network create auth-api-network
docker network connect auth-api-network auth-api
docker network connect auth-api-network postgres-auth-api
```</div>
