### ISSUE TITLE
(re)-Introspection errors have a misleading error message

### ISSUE THREAD

**Issue by jkomyno** [prisma/prisma#16176]
## Reproduction

- Given the following `docker-compose.yml` definition,

```yaml
version: '3.7'

services:
  postgres:
    image: postgres:15
    restart: always
    command: postgres -c 'max_connections=1000'
    environment:
      POSTGRES_PASSWORD: "prisma"
      POSTGRES_HOST_AUTH_METHOD: "md5"
      POSTGRES_INITDB_ARGS: "--auth-host=md5"
    ports:
      - "5432:5432"
```

run a `postgres` instance via

```sh
docker-compose up postgres
```

- Create the following `schema.prisma`:

```prisma
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["referentialIntegrity"]
}

datasource db {
  provider     = "postgres"
  url          = env("DATABASE_URL")
  referentialIntegrity = "prisma"
}

model A {
  id Int @id
  bs B[]
}

model B {
  id  Int @id
  aId Int
  a   A   @relation(fields: [aId], references: [id], onUpdate: Cascade, onDelete: NoAction)
}
```

- Set up the `DATABASE_URL` environment variable via

```sh
export TEST_POSTGRES_URI="postgresql://postgres:prisma@localhost:5432/tests"
```

- Push it to the database via `pnpx prisma@4.4.0 db push`, which uses the latest Prisma version that still supported an emulated `NoAction` referential action on `postgres`

- Re-introspect the database via `pnpx prisma@4.5.0 db pull`. This results in the following error, without any further detail:

> Error: P1012 Introspection failed as your current Prisma schema file is invalid
>
> Please fix your current schema manually, use prisma validate to confirm it is valid and then run this command again.
Or run this command with the --force flag to ignore your current schema and overwrite it. All local modifications will be lost.

## Solutions

We should tell the user to first run `prisma validate` to understand why the schema is not valid, then fix the current schema depending on what `prisma validate` suggests, and run the same command again to confirm the validity of the schema. (We might even suggest to use `prisma format` to both validate and format the Prisma schema)

The new error message could be something like:

> Error: P1012 Introspection failed as your current Prisma schema file is invalid
>
> Please run `prisma validate` to understand why the Prisma schema is not valid, modify the schema as suggested, and run `prisma validate` again to confirm the validity of the schema; you may then run this command again.
Alternatively, you can run this command with the `--force` flag to ignore your current schema and overwrite it. All local modifications will be lost.
