### ISSUE TITLE
Can't find prisma engine

### ISSUE THREAD

**Issue by revmischa** [prisma/prisma#16872]
I am trying to run prisma using SST (v2 preview https://docs.sst.dev/live-lambda-development)

There is a openssl-3.0.x.so.node in `/home/cyber/dev/tombo/node_modules/.pnpm/@prisma+client@4.2.1_prisma@4.2.1/node_modules/@prisma/.client`
in .client but not in client (see screenshot) 

![image](https://user-images.githubusercontent.com/245131/208154165-5fb5d53a-139d-44b4-9aaa-31191169d5ec.png)

```
(Prisma Client looked in "/home/cyber/dev/tombo/.sst/artifacts/c8166de0c7150c4e49f1170198e61b2079a9dd1fc0/libquery_engine-debian-openssl-3.0.x.so.node")

Searched Locations:

  /home/cyber/dev/tombo/.prisma/client
  /home/cyber/dev/tombo/node_modules/.pnpm/@prisma+client@4.2.1_prisma@4.2.1/node_modules/@prisma/client
  /home/cyber/dev/tombo/.sst/artifacts
  /home/cyber/dev/tombo/.sst/artifacts/c8166de0c7150c4e49f1170198e61b2079a9dd1fc0
  /home/cyber/dev/tombo/.sst/artifacts/c8166de0c7150c4e49f1170198e61b2079a9dd1fc0
  /tmp/prisma-engines
  /home/cyber/dev/tombo/.sst/artifacts/c8166de0c7150c4e49f1170198e61b2079a9dd1fc0

You already added the platform "debian-openssl-3.0.x" to the "generator" block
in the "schema.prisma" file as described in https://pris.ly/d/client-generator,
but something went wrong. That's suboptimal.

Please create an issue at https://github.com/prisma/prisma/issues/new
         Error: Query engine library for current platform "debian-openssl-3.0.x" could not be found.
         You incorrectly pinned it to debian-openssl-3.0.x
         
         This probably happens, because you built Prisma Client on a different platform.
         (Prisma Client looked in "/home/cyber/dev/tombo/.sst/artifacts/c8166de0c7150c4e49f1170198e61b2079a9dd1fc0/libquery_engine-debian-openssl-3.0.x.so.node")
         
         Searched Locations:
         
           /home/cyber/dev/tombo/.prisma/client
           /home/cyber/dev/tombo/node_modules/.pnpm/@prisma+client@4.2.1_prisma@4.2.1/node_modules/@prisma/client
           /home/cyber/dev/tombo/.sst/artifacts
           /home/cyber/dev/tombo/.sst/artifacts/c8166de0c7150c4e49f1170198e61b2079a9dd1fc0
           /home/cyber/dev/tombo/.sst/artifacts/c8166de0c7150c4e49f1170198e61b2079a9dd1fc0
           /tmp/prisma-engines
           /home/cyber/dev/tombo/.sst/artifacts/c8166de0c7150c4e49f1170198e61b2079a9dd1fc0
         
         You already added the platform "debian-openssl-3.0.x" to the "generator" block
         in the "schema.prisma" file as described in https://pris.ly/d/client-generator,
         but something went wrong. That's suboptimal.
         
         Please create an issue at https://github.com/prisma/prisma/issues/new
             at Object.handleRequestError (/home/cyber/dev/tombo/node_modules/.pnpm/@prisma+client@4.2.1_prisma@4.2.1/node_modules/@prisma/client/runtime/index.js:28844:13)
             at <anonymous> (/home/cyber/dev/tombo/node_modules/.pnpm/@prisma+client@4.2.1_prisma@4.2.1/node_modules/@prisma/client/runtime/index.js:29231:25)
             at PrismaClient2._executeRequest (/home/cyber/dev/tombo/node_modules/.pnpm/@prisma+client@4.2.1_prisma@4.2.1/node_modules/@prisma/client/runtime/index.js:29782:22)
             at PrismaClient2._request (/home/cyber/dev/tombo/node_modules/.pnpm/@prisma+client@4.2.1_prisma@4.2.1/node_modules/@prisma/client/runtime/index.js:29753:16)
             at Module.handler (/home/cyber/dev/tombo/packages/service/src/cognito/triggers/preTokenGeneration.ts:14:24)
             at async file:///home/cyber/dev/tombo/node_modules/.pnpm/sst@0.0.0-20221215185326_o5y4mdthrs7ed27ibxm4wyqwiq/node_modules/sst/support/nodejs-runtime/index.mjs:14644:16
```

**Comment by focux** [comment]
You can find the fix for that problem here https://github.com/prisma/prisma/issues/16553#issuecomment-1353302617

**Comment by janpio** [comment]
I don't think @revmischa's problem is Alpine related. This is more a bundling/path/tooling problem, which we unfortunately have quite some - but this seems to be a new variant.

**Comment by JakeGinnivan** [comment]
This is how we were doing our pnpm cache. Removing it the build succeeds.

```
    - uses: pnpm/action-setup@v2.2.4
      with:
        version: 7
        run_install: false

    - name: Get pnpm store directory
      id: pnpm-cache
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
    - uses: actions/cache@v3
      name: Setup pnpm cache
      with:
        path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-
    - shell: bash
      run: pnpm install
```
