### ISSUE TITLE
Prisma + Docker =  Query engine library for current platform "linux-arm64-openssl-1.1.x" could not be found.

### ISSUE THREAD

**Issue by allangrds** [prisma/prisma#17680]
### Bug description

When I run `docker-compose up`, after up postgres container and api container, the error bellow appears:

![Captura de Tela 2023-02-01 às 11 57 08](https://user-images.githubusercontent.com/4103305/216077843-566e2067-1137-4bb7-95e0-d991114ea977.png)

### How to reproduce

**Dockerfile**
```dockerfile
FROM node:18 As development

# Required for Prisma Client to work in container
RUN apt-get update && apt-get install -y openssl

WORKDIR /usr/src/app

COPY --chown=node:node package*.json ./

RUN npm ci

COPY --chown=node:node . .

RUN npm run prisma:generate

USER node
```

**docker-compose**
```yml
services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public
    command: npm run start:dev
    ports:
      - 3000:3000
    depends_on:
      - postgres
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - docker-nest-postgres:/var/lib/postgresql/data

volumes:
  docker-nest-postgres:
```

### Expected behavior

To generate prisma client correctly.

### Prisma information

```prisma
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

generator client {
  provider = "prisma-client-js"
  binaryTargets = ["native", "darwin-arm64", "linux-musl", "linux-arm64-openssl-1.1.x"]
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model Notification {
  id          String    @id
  recipientId String
  content     String
  category    String
  readAt      DateTime?
  createdAt   DateTime  @default(now())
  updatedAt   DateTime  @default(now())

  @@index([recipientId])
}

```

### Environment & setup

- OS: macOS Ventura 13.2, M1 Pro

### Prisma Version

```
"@prisma/client": "^4.9.0",
"prisma": "^4.9.0",
```
