### ISSUE TITLE
error: Environment variable not found: DATABASE_URL.

### ISSUE THREAD

**Issue by Helios69** [prisma/prisma#17730]
### Bug description

Hello. I'm struggling with connecting to a database running in the docker container alongside my main app (nestjs+prisma).
I'm getting the following error:

```
#0 9.627 Prisma schema loaded from prisma/schema.prisma                                                                                                
#0 9.646 Datasource "db": PostgreSQL database                                                                                                          
#0 9.652                                                                                                                                               
#0 9.654 Error: Prisma schema validation - (get-config wasm)                                                                                           
#0 9.654 Error code: P1012
#0 9.654 error: Environment variable not found: DATABASE_URL.
#0 9.654   -->  schema.prisma:10
#0 9.654    | 
#0 9.654  9 |   provider = "postgresql"
#0 9.654 10 |   url      = env("DATABASE_URL")
#0 9.654    | 
#0 9.654 
#0 9.654 Validation Error Count: 1
#0 9.654 [Context: getConfig]
#0 9.654 
#0 9.654 Prisma CLI Version : 4.9.0
```

Here is my docker-compose.yml file:

```
version: "3.8"
services:
  api:
    platform: linux/amd64
    container_name: api
    build: 
      context: ./api
      dockerfile: ./Dockerfile
      target: development
    command: npm run start:debug
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - PORT=4000
      - DATABASE_URL="postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@db:5432/${DATABASE_NAME}?schema=public"
    ports:
      - ${PORT}:${PORT}
      - 9229:9229
    volumes: 
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
  db:
    image: postgres
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
```

Dockerfile:

```
FROM node:14-alpine AS development

WORKDIR /usr/src/app

COPY package*.json ./
COPY prisma ./prisma/

RUN npm ci

RUN npx prisma generate
RUN npx prisma migrate deploy

COPY . .

RUN npm run build

FROM node:14-alpine AS production

ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm ci

COPY . .

COPY --from=development /usr/src/app/dist ./dist

CMD ["node", "dist/main"]

```

.env

```
PORT=4000

DATABASE_USER=username
DATABASE_PASSWORD=password
DATABASE_NAME=database

```

And that's my directory structure: 
├── Jenkinsfile
├── .env
├── api
 │  ├── Dockerfile
 │  ├── README.md
 │  ├── nest-cli.json
 │  ├── package-lock.json
 │  ├── package.json
 │  ├── prisma
 │   │  ├── migrations
 │   │  └── schema.prisma
 │  ├── src
 │   │   ├── app.controller.spec.ts
 │   │   ├── app.controller.ts
 │   │   ├── app.module.ts
 │   │   ├── app.service.ts
 │   │   └── main.ts
 │  ├── test
 │   │   ├── app.e2e-spec.ts
 │   │   └── jest-e2e.json
 │  ├── tsconfig.build.json
 │  ├── tsconfig.json
 │  └── yarn.lock
└── docker-compose.yml

note: my app is nested inside root directory, where i placed docker-compose and .env file 

### Prisma information

```
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model User {
  id    Int    @id @default(autoincrement())
  email String @unique
}

```

```ts
// Add your code using Prisma Client
```

### Environment & setup

- OS: macOS
- Database: Postgres
- Node.js version: node:14-alpine

### Prisma Version

```
4.9.0
```
