### ISSUE TITLE
Error: Illegal mix of collations (utf8mb3_general_ci,COERCIBLE) and (utf8mb3_unicode_ci,COERCIBLE) for operation '='

### ISSUE THREAD

**Issue by ApacheAlpha** [prisma/prisma#18030]
### Bug description

```
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}

model User {
  id    Int     @id @default(autoincrement())
  email String  @unique
  name  String?
  posts Post[]
}

model Post {
  id        Int     @id @default(autoincrement())
  title     String
  content   String?
  published Boolean @default(false)
  author    User    @relation(fields: [authorId], references: [id])
  authorId  Int
}
```

If I try to run : `npx prisma migrate dev --preview-feature`
I get the following error:

```
Error: Illegal mix of collations (utf8mb3_general_ci,COERCIBLE) and (utf8mb3_unicode_ci,COERCIBLE) for operation '='
   0: sql_migration_connector::flavour::mysql::connection::describe_schema
             at migration-engine/connectors/sql-migration-connector/src/flavour/mysql/connection.rs:34
   1: migration_core::state::DevDiagnostic
             at migration-engine/core/src/state.rs:269
```
I don't know where this encoding problem comes from

### How to reproduce

According to this tutorial

https://www.prisma.io/docs/getting-started/quickstart

When I execute the third step “Run a migration to create your database tables with Prisma Migrate”
`npx prisma migrate dev --name init`

and then get this error：
```
Error: Illegal mix of collations (utf8mb3_general_ci,COERCIBLE) and (utf8mb3_unicode_ci,COERCIBLE) for operation '='
   0: sql_migration_connector::flavour::mysql::connection::describe_schema
             at migration-engine/connectors/sql-migration-connector/src/flavour/mysql/connection.rs:34
   1: migration_core::state::DevDiagnostic
             at migration-engine/core/src/state.rs:269
```

### Expected behavior

I am a novice, I just hope that the execution of this command will not report an error。I hope to get the .sql file after executing the command :"npx prisma migrate dev --name init"

### Prisma information

```
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}

model User {
  id    Int     @id @default(autoincrement())
  email String  @unique
  name  String?
  posts Post[]
}

model Post {
  id        Int     @id @default(autoincrement())
  title     String
  content   String?
  published Boolean @default(false)
  author    User    @relation(fields: [authorId], references: [id])
  authorId  Int
}
```

### Environment & setup

- OS:  Ubuntu 20.04.5 LTS
- Database: MySQL Version: '8.0.32'
- Node.js version: v18.1.0
mysql docker-compose
```
version: '3.3'
services:
  db:
    image: mysql:latest
    restart: always
    container_name: mysql
    environment:
      TZ: Asia/Shanghai
      MYSQL_USER: 'aa'
      MYSQL_PASSWORD: 'aaaa'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'aaaa'
    ports:
      - '28306:3306'
    volumes:
      - /apps/mysql/mydir:/mydir
      - /apps/mysql/datadir:/var/lib/mysql
      - /apps/mysql/conf/my.cnf:/etc/my.cnf
      - /apps/mysql/source:/docker-entrypoint-initdb.d
```

### Prisma Version

```
Environment variables loaded from .env
prisma                  : 4.10.1
@prisma/client          : 4.10.1
Current platform        : debian-openssl-1.1.x
Query Engine (Node-API) : libquery-engine aead147aa326ccb985dcfed5b065b4fdabd44b19 (at node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node)
Migration Engine        : migration-engine-cli aead147aa326ccb985dcfed5b065b4fdabd44b19 (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Format Wasm             : @prisma/prisma-fmt-wasm 4.10.1-1.80b351cc7c06d352abe81be19b8a89e9c6b7c110
Default Engines Hash    : aead147aa326ccb985dcfed5b065b4fdabd44b19
Studio                  : 0.481.0
```
