### ISSUE TITLE
NestJS Prisma Monorepo can't reach Mysql Docker at port!

### ISSUE THREAD

**Issue by letuss004** [prisma/prisma#18743]
I currently try run a Turborepo app (NestJS, Prisma, MySQL) using Docker, in my docker list, my DBs are running but I can't connect from Webstorm. And after the docker-compose up my NestJS throw "Can't reach database server at PORT". 

My directory structure:
```
order-payment
├── apps
│   └── orders-app (NestJS)
│       └── prisma
│       └── src
└── packages
└── Dockerfile
└── docker-compose.yml
└── turbo.json
└── package.json
```

My Dockerfile:
```
FROM node:16.14.2
WORKDIR /app
COPY  ["yarn.lock", "package.json", "./"]
COPY . .
RUN yarn install
EXPOSE 2828
CMD ["turbo", "db:generate", "db:push"]
CMD ["yarn", "dev"]
```

My Docker-compose file:
```
version: "3"
networks:
  op-network:
    driver: bridge

services:
  apps:
    image: op-apps
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3001:3001"
    restart: always
    depends_on:
      - payment-db
      - order-db
    networks:
      - op-network

  order-db:
    image: mysql:8.0.24
    container_name: order-db
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: order
    ports:
      - "3308:3308"
    restart: always
    networks:
      - op-network

  payment-db:
    image: mysql:8.0.24
    container_name: payment-db
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: payment
    restart: always
    ports:
      - "3309:3309"
    networks:
      - op-network
```

My .env file:
```
DATABASE_URL="mysql://root:12345678@order-db:3308/order?schema=public"
```

What I expected:
- My NestJS app should connect to my Mysql service

What actually happen:
```
Error: Can't reach database server at `order-app`:`3308`
------------
Can not read response from server. Expected to read 4 bytes, read 0 bytes before connection was unexpectedly lost. (Trying to connect by fromWebstorm)
```

What wrong:
1. Every service should start in order because I was use "depend_on"
2. The network is set to bridge so I should connected by service-name as above
3. It should connected from Webstorm

My Environment:
- Webstorm (IDE)
- Windows 10, Ubuntu 22.04
- Docker version 20.10.24
- Source code: https://github.com/letuss004/oders-payment
