### ISSUE TITLE
I can't use prisma client with AWS SAM/esbuild

### ISSUE THREAD

**Issue by carlosLMZarego** [prisma/prisma#18858]
### Bug description

Hello everybody

I've a lambda configured through cloudformation sam

```
  OrganizationPOSTFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: OrganizationPOST
      CodeUri: ../src/
      Handler: organization-post.lambdaHandler
      Events:
        Organization:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /organization
            Method: post
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - organization-post.ts
```

Right now all files in my lambda are merged into a single file, so inside my lambda there is only the .ts file (Is there any way to avoid this?) inside my lambda there is no prisma folder.

and inside my organization-post.ts I'm trying to use the Prisma Client

```ts
//inside my lambdaHandler
  const prisma = new PrismaClient()

//lots of lines
const organization = await prisma.organization.create({
            data : organizationRequest
        })

```

I have done the migration and the PrismaClient imported from @prisma/client works fine...I get autocomplete and everything seems to be ok

but when I run the project I get this error

```
'errorMessage': "ENOENT: no such file or directory, open '/var/task/schema.prisma'"
```

I want to know why the client is trying to access to the schema in that path...also is it possible to change the schema path in my PrismaClient instantiation?

Because everything in my lambda is bundled into a single file I found this solution

[How to include static files into the lambda package with AWS SAM esbuild?](https://stackoverflow.com/questions/74534054/how-to-include-static-files-into-the-lambda-package-with-aws-sam-esbuild)

seems to be a good option but I'd need pass my schema dynamically like this

```ts
import { PrismaClient } from "@prisma/client";
import schema from "./prisma/schema.prisma"

console.log(`schema is ${schema}`) //print a weird name generated in runtime
const prisma = new PrismaClient({schema}) // <= I need an option like this but I can't find anything
```

Has anyone had any luck integrating prisma into a lambda with SAM/esbuild and can give me some guidance on how to configure it? Or is it impossible to use prisma with SAM/esbuild?

any help will be appreciated...thanks

### Expected behavior

the Prisma Client must work, I don't need lambda migration, just that my Prisma Client works with SAM

### Prisma information

```prisma
// Add your schema.prisma
```

```ts
// Add your code using Prisma Client
```

### Environment & setup

- OS: 
- Database: 
- Node.js version: 

### Prisma Version

```

```
