### ISSUE TITLE
Running Prisma Migrate command on read only file system leads to errors

### ISSUE THREAD

**Issue by joriregter** [prisma/prisma#20768]
### Bug description

I'm using Prisma on Platform.sh. Platform.sh uses roughly 3 steps to deploy an application:

1. Install phase, installs dependencies, all directories writable (database not available)
2. Build phase, builds applications, all directories writable (database not available)
3. Deploy phase, deploys applications, allowing for migrations, all directories read only (database available)

Migrations have to be run in step 3, but Prisma uses temporary files that require a writable root directory. This results in errors when running the migrations.

```
          W:  EROFS  EROFS: read-only file system, open '/app/apps/api/_tmp_193_b39d08c8a96de5022c0882e3be1cb10f'
          W: 
          W: 
          W: 
          W:  EROFS  EROFS: read-only file system, open '/app/apps/api/_tmp_211_e18736f02895240f952730c448f7f99d'
          W: 
          W: 
          W: 
          W:  EROFS  EROFS: read-only file system, open '/app/apps/api/_tmp_223_027d2ad94819493069d66334e895541d'
          W: 
```

How can I either change the temporary directory, so I can mount it as a writable directory OR prohibit Prisma from using temporary files?

### How to reproduce

N/A

### Expected behavior

N/A

### Prisma information

N/A

### Environment & setup

N/A

### Prisma Version

```
5.1.1
```
