### ISSUE TITLE
Support pgcat

### ISSUE THREAD

**Issue by casey-chow** [prisma/prisma#20904]
## Problem

pgBouncer is nearly table-stakes when working with Postgres at scale, but has a number of issues:
- The lack of prepared statement support forces transactions for everything, leading to performance (https://github.com/prisma/prisma/issues/19325, https://github.com/prisma/prisma/issues/16081) losses.
- No awareness of underlying queries means that read replica support lies on the application to handle.

## Suggested solution

Checking for support for pgcat may be a clean solution for all the issues seen with pgBouncer. It already [supports prepared statements](https://postgresml.org/blog/making-postgres-30-percent-faster-in-production) and [load balancing queries](https://github.com/postgresml/pgcat#load-balancing-of-read-queries).

## Alternatives

There's a number of alternatives out there, some older, like Odyssey, and some newer, like supavisor, but pgcat seems to strike the best balance of strong featureset and provenness in production.

**Comment by janpio** [comment]
A first step to verify if this might already work could be to replace our PostgreSQL instances in our tests here and in the prisma-engines repository with a pgcat instance that then talks to the underlying PostgreSQL. PRs welcome!

**Comment by tobiaskkd** [comment]
I'm running Prisma against [pgCat](https://github.com/postgresml/pgcat) as a connection pooler and load balancer, expecting it to distribute read and write queries between a primary and multiple replicas. I've configured pgCat with `query_parser_enabled = true` and `query_parser_read_write_splitting = true`.

However, when using Prisma, **all queries go to the primary**, even for simple reads like `findMany`.

---

### 🛠 My pgCat configuration

```toml
[general]
host = "0.0.0.0"
port = 6432
admin_username = "********"
admin_password = "***********"
connect_timeout = 5000
idle_timeout = 30000
healthcheck_timeout = 100
healthcheck_delay = 3000
shutdown_timeout = 6000
ban_time = 5
prepared_statements = true
prepared_statements_cache_size = 500

[pools.database_name]
pool_mode = "transaction"
query_parser_enabled = true
query_parser_read_write_splitting = true
primary_reads_enabled = false
default_role = "any"

[pools.database_name.users.0]
pool_size = 180
username = "******"
password = "********"

[pools.database_name.shards.0]
database = "database_name"
servers = [
  ["...", 23505, "primary"],
  ["...", 5432, "replica"],
  ["...", 5432, "replica"]
]
```

My connection string: postgresql://user:password@load-balancer-ip:6432/database_name?pgbouncer=true

### What works
* pgCat health checks succeed 
* Connections through pgCat function correctly 
* `query_parser_enabled` and `transaction` pool mode are both configured

### What doesn’t 
* Prisma never routes read queries to the replicas 
* Even basic reads like `await prisma.model.findMany()` go to the primary

Has anyone successfully connected Prisma with pgCat and observed correct read/write query routing to replicas? Any Prisma-specific settings or workarounds that helped?

Thanks in advance 🙏
