### ISSUE TITLE
getProxyAgent() is not parsing docker secrets correctly

### ISSUE THREAD

**Issue by rivermanbw** [prisma/prisma#21559]
### Bug description

Hi,
I've set up a docker container with several prisma-clients inside. 
I need to do `prisma generate` during setup of the container. That's why i need to download current prisma engines.
The container runs behind coorporate proxy.
When passing the proxy credentials as a `docker secret` to the container, the parsing inside getProxyAgent() failes.

Here's part of the logs:
```
An error occurred in getProxyAgent(), no proxy agent will be used. Error: Error while instantiating HttpsProxyAgent with URL: "/run/secrets/http_proxy"
TypeError [ERR_INVALID_URL]: Invalid URL
Check the following env vars "https_proxy" or "HTTPS_PROXY". The value should be a valid URL starting with "https://"
```

### How to reproduce

Make sure you simulate an environment behind a proxy.

Create a dokcer secret for your proxy credentials.

Spin up a docker container with 
```
FROM node:18.17.0
ENV HTTPS_PROXY=$HTTP_PROXY
...example project here etc.
```

Use docker compose file like this:

```
version: "3.7"

services:
  service-db:
    container_name: service-db
    build:
      dockerfile: ../db/Dockerfile
      context: .
    restart: "always"

    environment:
      HTTPS_PROXY: /run/secrets/http_proxy    
    ports:
      - 3333:3333
    secrets:
      - http_proxy     
    command: <your command here>

secrets:
  http_proxy:
    file: ./secrets/bits-dev/http_proxy
 ```
`docker compose up` your docker compose file.

`docker exec -it ` into your container.

try running `prisma generate`

### Expected behavior

Expected [getProxyAgent](https://github.com/prisma/prisma/blob/23d5ef0672372035a84552b6b457197ca19f486d/packages/fetch-engine/src/getProxyAgent.ts#L90C31-L90C31) to correctly parse /run/secrets/http_proxy e.g. by using `cat /run/secrets/http_proxy` instead of just using /run/secrets/http_proxy

### Prisma information

-

### Environment & setup

`node:18.17.0` container uses Debian 12.

### Prisma Version

```
5.4.2
```
