### ISSUE TITLE
`createMany()` does not exist when a model has an `Unsupported()` field on PostgreSQL

### ISSUE THREAD

**Issue by rs-nikic** [prisma/prisma#21756]
I'm using postgreSQL, still facing the same issue.

```prisma
datasource db {
  provider = "postgresql"
  url      = env("PG_CONNECTION_STRING")
}

model node_locations {
  NodeId String @unique(map: "node_locations_id_idx") @default(dbgenerated("gen_random_uuid()")) @db.Uuid
  ExternalId String @unique(map: "node_locations_ext_id_idx")
  Name String
  Description String
  Geometry Unsupported("geometry(Point, 4326)")
  Meta Json
  Provider String
  Species String[]
  Status String
  LastPing DateTime

  @@index([Geometry], name: "node_locations_geometry_idx", type: Gist)
}
```

Prisma version: 5.5.2

Note: `prisma db push` is used for code generation 

![image](https://github.com/prisma/prisma/assets/143053594/81a1b7d1-02e1-4591-82f7-2829b147883c)

_Originally posted by @rs-nikic in https://github.com/prisma/prisma/issues/11507#issuecomment-1791963064_

**Comment by Jolg42** [comment]
Thanks! I could reproduce this, only when using the `Geometry Unsupported("geometry(Point, 4326)")` field, after removing it, `createMany` was available.

```prisma
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["postgresqlExtensions"]
}

datasource db {
  provider   = "postgresql"
  url        = "postgresql://postgres:password@localhost:5492/21756"
  extensions = [postgis]
}

model node_locations {
  NodeId      String                               @unique(map: "node_locations_id_idx") @default(dbgenerated("gen_random_uuid()")) @db.Uuid
  ExternalId  String                               @unique(map: "node_locations_ext_id_idx")
  Name        String
  Description String
  Geometry    Unsupported("geometry(Point, 4326)")
  Meta        Json
  Provider    String
  Species     String[]
  Status      String
  LastPing    DateTime

  @@index([Geometry], name: "node_locations_geometry_idx", type: Gist)
}
```

And I randomly found a Postgis docker file on my computer to try it with `docker compose up -d`
```
version: "3.6"
services:
  pgDB:
    image: postgis/postgis:13-3.1-alpine
    restart: always
    ports:
      - "5492:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: geoexample
volumes:
  db_data:
```
