### ISSUE TITLE
Prisma running in Docker cannot connect to AWS RDS Postgres instance

### ISSUE THREAD

**Issue by digitaldavenyc** [prisma/prisma#23494]
### Bug description

Our team is migrating to a Docker version of node running `prisma` and cannot get a database connection to work. Simply running any prisma commands generate the dreaded `User was denied access on the database error`. I've read through every other similar bug report and stackoverflow post and none of the proposed solutions seem to work here. Using the same credentials, we can connect to the RDS instance running Postgres using `psql` and can run any commands.

I read that it could be an issue with prisma needing to create a shadow database, so I granted our db user access to `CREATEDB` permissions AND explicitly setup a shadow database in our db instance. This did not fix the issue.

```
root@8k3k2k29s:/code# prisma migrate status
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": PostgreSQL database "api-dev", schema "public" at "api-dev.xxxxxx.us-east-9.rds.amazonaws.com"
Error: P1010: User `backuser` was denied access on the database `api-dev.public`
```

But this is not an issue with our credentials, we can connect use `psql` in the Docker instance just fine:

```
root@398fba4348c9:/code# psql -h api-dev.xxxxxx.us-east-9.rds.amazonaws.com -U backuser -d api-dev
Password for user backuser:
psql (15.6 (Debian 15.6-0+deb12u1), server 16.1)
WARNING: psql major version 15, server major version 16.
         Some psql features might not work.
SSL connection (protocol: TLSv1.3, cipher: TLS_AES_256_GCM_SHA384, compression: off)
Type "help" for help.

api-dev=>
```

Here is a copy of our `docker-compose.yml`:

```
version: '3'

services:
  api:
    platform: linux/x86_64
    container_name: api
    image: api
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
    ports:
      - "8081:8000"
    environment:
      - APP_ENV=dev
      - PORT=8000
      - DATABASE_URL=postgresql://backuser:supersecretpassword@api-dev.xxxxxx.us-east-9.rds.amazonaws.com/api-dev?sslmode=disable&schema=public
      - SHADOW_DATABASE_URL=postgresql://backuser:supersecretpassword@api-shadow.xxxxxx.us-east-9.rds.amazonaws.com/api?sslmode=disable&schema=public
```

I've tried everything I can think of and find and out of ideas... need help.

### How to reproduce

I think it's more about the environment setup then steps but here you go

1. Create node/express api in Docker 
2. Setup prisma connection to AWS RDS instance running Postgres
3. Create RDS Parameter group and change `rds.forcessl` to `0`
4. Apply Parameter Group to RDS Instance
5. Run `prisma migrate status`

### Expected behavior

Can connect to RDS instance of Postgres and outputs the results of `prisma migrate status`

### Prisma information

```prisma
generator client {
  provider        = "prisma-client-js"
  output          = "../src/generated/client"
  previewFeatures = ["postgresqlExtensions", "fullTextSearch"]
  binaryTargets   = ["native", "debian-openssl-3.0.x"]
}

datasource db {
  provider          = "postgresql"
  url               = env("DATABASE_URL")
  shadowDatabaseUrl = env("SHADOW_DATABASE_URL")
  extensions        = [pgcrypto()]
}
````

### Environment & setup

- OS: Debian Bookworm
- Database: Postgres 16.1
- Node.js version: `v21.7.1`

### Prisma Version

```
prisma                  : 5.11.0
@prisma/client          : 5.10.2
Computed binaryTarget   : debian-openssl-3.0.x
Operating System        : linux
Architecture            : x64
Node.js                 : v21.7.1
Query Engine (Node-API) : libquery-engine efd2449663b3d73d637ea1fd226bafbcf45b3102 (at ../../../usr/local/lib/node_modules/prisma/node_modules/@prisma/engines/libquery_engine-debian-openssl-3.0.x.so.node)
Schema Engine           : schema-engine-cli efd2449663b3d73d637ea1fd226bafbcf45b3102 (at ../../../usr/local/lib/node_modules/prisma/node_modules/@prisma/engines/schema-engine-debian-openssl-3.0.x)
Schema Wasm             : @prisma/prisma-schema-wasm 5.11.0-15.efd2449663b3d73d637ea1fd226bafbcf45b3102
Default Engines Hash    : efd2449663b3d73d637ea1fd226bafbcf45b3102
Studio                  : 0.499.0
Preview Features        : fullTextSearch, postgresqlExtensions
```
