### ISSUE TITLE
Unable to connect to Postgres in Docker when db PORT is different than 5432

### ISSUE THREAD

**Issue by QAdamek** [prisma/prisma#23624]
### Bug description

I am unable to connect prisma to database when postgres is run in container with port set to different than `5432`.

Compose:
```
version: "3.9"

services:
  database:
    image: postgres:16.2
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: cases_ninja_dev
      POSTGRES_PASSWORD: cases_ninja_dev
      POSTGRES_DB: cases_ninja_dev
    expose:
      - 5432
    ports:
      - 4001:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cases_ninja_dev"]
      interval: 10s
      timeout: 5s
      retries: 5

  service:
    build:
      dockerfile: Dockerfile.dev
    ports:
      - 4000:4000
    expose:
      - 4000
    environment:
      - PORT=4000
      - JWT_SECRET=jwtsecret
      - JWT_REFRESH=jwtrefresh
    depends_on:
      database:
        condition: service_healthy
```

Log from `service`:
```
root@cc31cbb3aa36:/usr/src/app# npx prisma migrate dev
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": PostgreSQL database "cases_ninja_dev", schema "public" at "database:4001"

Error: P1001: Can't reach database server at `database`:`4001`

Please make sure your database server is running at `database`:`4001`.
```

`.env`:
```
DATABASE_URL="postgresql://cases_ninja_dev:cases_ninja_dev@database:4001/cases_ninja_dev?schema=public"
```

There is no problem at all when PORT is set to 5432 (compose && env).

### How to reproduce

1. Start Postgres in container with container port 5432 mapped to different than 5432 on host
2. Start Prisma in different container and try to connect/migrate to db

### Prisma information

```prisma
// Add your schema.prisma
```

```ts
// Add your code using Prisma Client
```

### Environment & setup

- OS: 
- Database: 
- Node.js version: 

### Prisma Version

```

```
