### ISSUE TITLE
Connect to MongoDB running on a container with different port than 27017

### ISSUE THREAD

**Issue by rares2002** [prisma/prisma#23880]
### Bug description

I simply want to connect using Prisma to a mongodb instance running in a container. 
The tricky part is that I am running this container on port 27018. (The host can connect to the container only on 27018)
When im trying to acces it with npx prisma db push, the command freezez (probably it tries to connect and retries and fails)

### How to reproduce

This is the docker compose:
```
  mongo:
    build: ./mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: md_love-sac
      MONGO_INITDB_ROOT_PASSWORD: love-sac
      MONGO_INITDB_DATABASE: mongo
      MONGO_REPLICA_HOST: localhost
      MONGO_REPLICA_PORT: 27018
    ports:
      
'27018:27018'
  volumes:
mongo-data:/data/db
```

This is the Database URL:
```
mongodb://md_love-sac:love-sac@localhost:27018/mongo?authSource=admin?directConnection=tru
```

Here is also the Dockerfile that builds the mongo image (i have to run mongo in replica set)
```
FROM mongo:4

ENTRYPOINT mongod --port $MONGO_REPLICA_PORT --replSet rs0 --bind_ip 0.0.0.0 & MONGOD_PID=$!; \

INIT_REPL_CMD="rs.initiate({ _id: 'rs0', members: [{ _id: 0, host: '$MONGO_REPLICA_HOST:$MONGO_REPLICA_PORT' }] })"; \
INIT_USER_CMD="db.getUser('$MONGO_INITDB_ROOT_USERNAME') || db.createUser({ user: '$MONGO_INITDB_ROOT_USERNAME', pwd: '$MONGO_INITDB_ROOT_PASSWORD', roles: [ 'root' ] })"; \

until (mongo admin --port $MONGO_REPLICA_PORT --eval "$INIT_REPL_CMD && $INIT_USER_CMD"); do sleep 1; done; \

echo "REPLICA SET ONLINE"; wait $MONGOD_PID;
```

### Expected behavior

If I run the container back on port 27017, it connects imediatly. Changing back to 27018 both in the docker compose and in the url will not sucessfully connect.

### Prisma information

This is the schema.prisma file
```
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mongodb"
  url = env("DB_URL")
  directUrl = env("DB_URL")
}
```

### Environment & setup

- OS: macOS with docker
- Database: MongoDB
- Node.js version: 21

### Prisma Version

```
4.14.0
```
