### ISSUE TITLE
P1001 when attempting to connect to database

### ISSUE THREAD

**Issue by amimberg** [prisma/prisma#24040]
### Bug description

Hi all,

when trying to connect to my MariaDB-Server using Prisma.IO I always get the following error message:

```log
Environment variables loaded from .env
Prisma schema loaded from prisma\schema.prisma
Datasource "db": MySQL database "app_wk_event" at "192.168.101.65:3306"

Error: P1001: Can't reach database server at `192.168.101.65`:`3306`
```

I have no problem connecting to the server using MySQL from the command line or using other software such as DBeaver CE.

I've checked all URLs and other credentials and even changed the password to one that does not require %-encoding. 

### How to reproduce

```
npx prisma migrate dev --name init
```

### Prisma information

```prisma
generator client {
    provider    = "prisma-client-js"
}

datasource db {
    provider    = "mysql"
    url         = env("DATABASE_URL")
}

/// A user of the webapplication
model User {
    ....
}
```

```ts
DATABASE_URL = "mysql://<user>:<pass>@192.168.101.65:3306/app_wk_event"
```

```ts
const {PrismaClient} = require('@prisma/client');
const prisma = new PrismaClient({ log: ['query', 'info', 'warn'] });
```

### Environment & setup

- OS: Dev on Windows 11, VS Code 1.88.1
- Database: MariaDB 10.6.11 running inside Docker 20.10.21 on Debian 10 Buster
- Node.js version: 20.10.0

 - Docker Stack:
```yaml
version: '3'

volumes:
  mariadb:
    driver: local

networks:
    db:
        driver: bridge

services:
  mariadb:
    image: mariadb:10.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: <SUPERPASS>
      MYSQL_USER:  <USER>
      MYSQL_PASSWORD: <PASS>
    ports:
        - "3306:3306"
    volumes:
     - mariadb:/var/lib/mysql
    networks:
      db:

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "4080:80"
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306 
    networks:
      db:
```

### Prisma Version

```
prisma                  : 5.12.1
@prisma/client          : 5.12.1
Computed binaryTarget   : windows
Operating System        : win32
Architecture            : x64
Node.js                 : v20.10.0
Query Engine (Node-API) : libquery-engine 473ed3124229e22d881cb7addf559799debae1ab (at node_modules\@prisma\engines\query_engine-windows.dll.node)
Schema Engine           : schema-engine-cli 473ed3124229e22d881cb7addf559799debae1ab (at node_modules\@prisma\engines\schema-engine-windows.exe)
Schema Wasm             : @prisma/prisma-schema-wasm 5.12.0-21.473ed3124229e22d881cb7addf559799debae1ab
Default Engines Hash    : 473ed3124229e22d881cb7addf559799debae1ab
Studio                  : 0.499.0
```
