### ISSUE TITLE
Test Pgpool-II

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#2459]
Pgpool-II might be an alternative to PgBouncer that we want to test and confirm working with Prisma:

https://www.pgpool.net/mediawiki/index.php/Main_Page

**Comment by pantharshit00** [comment]
Assigning myself, I will get back to this later

**Comment by jonathanheilmann** [comment]
Are there any updates on this topic?
I‘m using Pgpool-II and have been asking myself if I should give it a try to config PrismaClient for pgbounce. Is there anything against it?

**Comment by janpio** [comment]
We did not get to this yet. If you want to give it a go, that would be nice.

If you have experience with Pgpool-II you can maybe also point out a simple Docker Compose config we could add to our tests? Running our complete test suite against it is of course the only way to really make sure everything works as it should and to get some kind of confidence in that.

**Comment by pantharshit00** [comment]
I can actually migrate and read data over the pool. I tried this locally using the following docker image:
```yaml
version: '2.1'
services:
  pg-0:
    image: docker.io/bitnami/postgresql-repmgr:11
    ports:
      - 5432
    volumes:
      - pg_0_data:/bitnami/postgresql
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=adminpassword
      - POSTGRESQL_USERNAME=customuser
      - POSTGRESQL_PASSWORD=custompassword
      - POSTGRESQL_DATABASE=customdatabase
      - POSTGRESQL_NUM_SYNCHRONOUS_REPLICAS=1
      - REPMGR_PASSWORD=repmgrpassword
      - REPMGR_PRIMARY_HOST=pg-0
      - REPMGR_PARTNER_NODES=pg-0,pg-1
      - REPMGR_NODE_NAME=pg-0
      - REPMGR_NODE_NETWORK_NAME=pg-0
  pg-1:
    image: docker.io/bitnami/postgresql-repmgr:11
    ports:
      - 5432
    volumes:
      - pg_1_data:/bitnami/postgresql
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=adminpassword
      - POSTGRESQL_USERNAME=customuser
      - POSTGRESQL_PASSWORD=custompassword
      - POSTGRESQL_DATABASE=customdatabase
      - POSTGRESQL_NUM_SYNCHRONOUS_REPLICAS=1
      - REPMGR_PASSWORD=repmgrpassword
      - REPMGR_PRIMARY_HOST=pg-0
      - REPMGR_PARTNER_NODES=pg-0,pg-1
      - REPMGR_NODE_NAME=pg-1
      - REPMGR_NODE_NETWORK_NAME=pg-1
  pgpool:
    image: docker.io/bitnami/pgpool:4
    ports:
      - 5432:5432
    environment:
      - PGPOOL_BACKEND_NODES=0:pg-0:5432,1:pg-1:5432
      - PGPOOL_SR_CHECK_USER=customuser
      - PGPOOL_SR_CHECK_PASSWORD=custompassword
      - PGPOOL_ENABLE_LDAP=no
      - PGPOOL_POSTGRES_USERNAME=postgres
      - PGPOOL_POSTGRES_PASSWORD=adminpassword
      - PGPOOL_ADMIN_USERNAME=admin
      - PGPOOL_ADMIN_PASSWORD=adminpassword
      - PGPOOL_ENABLE_LOAD_BALANCING=yes
    healthcheck:
      test: ["CMD", "/opt/bitnami/scripts/pgpool/healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  pg_0_data:
    driver: local
  pg_1_data:
    driver: local
 ```
 
 Migrate was quite slow over the pool even locally but it worked and didn't fail.
