### ISSUE TITLE
Cannot configure OIDC with self-managed MongoDB

### ISSUE THREAD

**Issue by radoslawszulgo** [prisma/prisma#25211]
### Bug description

My configuration file:
```
setParameter:
   authenticationMechanisms: MONGODB-OIDC
   oidcIdentityProviders: 
     - issuer: "http://localhost:9000/.well-known/openid-configuration"
       clientId: "your-client-id"
       clientSecret: "your-client-secret"
       authorizationEndpoint: "https://your-identity-provider.com/authorize"
       tokenEndpoint: "https://your-identity-provider.com/token"
       userInfoEndpoint: "https://your-identity-provider.com/userinfo"
```

When I run mongod I get:
`setParameter has a map with non scalar values, which is not allowed`

Additionally, when I try to pass this via command line:
./mongod --config "../config/mongod.conf" --setParameter 'oidcIdentityProviders=[ {"issuer": "https://example.com", "clientId": "yourClientId", "clientSecret": "yourClientSecret"} ]'

I get:
`{"t":{"$date":"2024-09-11T11:40:46.072Z"},"s":"F",  "c":"CONTROL",  "id":20574,   "ctx":"thread1","msg":"Error during global initialization","attr":{"error":{"code":2,"codeName":"BadValue","errmsg":"Unknown --setParameter 'oidcIdentityProviders'"}}}`

Something's wrong at my end or it's a bug?

### How to reproduce

1. Configure as in description
2. Run mongod

### Expected behavior

Mongod starts successfully

### Prisma information

```prisma
// Add your schema.prisma
```

```ts
// Add your code using Prisma Client
```

### Environment & setup

- OS: macOS
- Database: MongoDB Enterprise

### Prisma Version

```

```
