### ISSUE TITLE
Error P1000

### ISSUE THREAD

**Issue by ValiuchenkoVladyslav** [prisma/prisma#26172]
### Bug description

I'm unable to run Prisma on Windows machine, always getting same error:
```
Environment variables loaded from .env
Prisma schema loaded from prisma\schema.prisma
Datasource "db": PostgreSQL database "pg", schema "public" at "localhost:5432"

Error: P1000: Authentication failed against database server at `localhost`, the provided database credentials for `pg` are not valid.

Please make sure to provide valid database credentials for the database server at `localhost`.
```

### How to reproduce

1. Run `bun install` or `pnpm install`
2. Run `docker-compose up -d`
3. run `bun prisma migrate dev` or `pnpm prisma migrate dev`

### Expected behavior

Be able to run Prisma migration

### Prisma information

prisma schema
```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = "postgresql://pg:pg@localhost:5432/pg"
}

model User {
  id        Int      @id @default(autoincrement())
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt

  email    String  @unique
  hash     String
  hashedRt String?
}
```

docker compose file
```
volumes:
  pgdata:

services:
  postgres:
    image: postgres:17.2-alpine
    shm_size: 128mb

    ports: [5432:5432]

    environment:
      POSTGRES_USER: pg
      POSTGRES_PASSWORD: pg
      POSTGRES_DB: pg

    volumes: [pgdata:/var/lib/postgresql/data]
```

### Environment & setup

- OS: Windows 10 22H2
- Database: PostgreSQL
- Node.js version: v20.17.0
- Bun version: 1.2.0

### Prisma Version

```
prisma                  : 6.2.1
@prisma/client          : 6.2.1
Query Engine (Node-API) : libquery-engine 4123509d24aa4dede1e864b46351bf2790323b69 (at node_modules\@prisma\engines\query_engine-windows.dll.node)
Schema Engine           : schema-engine-cli 4123509d24aa4dede1e864b46351bf2790323b69 (at node_modules\@prisma\engines\schema-engine-windows.exe)
Schema Wasm             : @prisma/prisma-schema-wasm 6.2.0-14.4123509d24aa4dede1e864b46351bf2790323b69
Default Engines Hash    : 4123509d24aa4dede1e864b46351bf2790323b69
Studio                  : 0.503.0
```
