### ISSUE TITLE
Prisma deploy doesn't catch PostgreSQL migration error on adding @unique

### ISSUE THREAD

**Issue by lucasbordeau** [prisma/prisma#2675]
## Bug description

The command `prisma deploy` does not catch migration error thrown by PostgreSQL, the command output shows that everything passed with flying colors, the `prisme-schema.ts` file gets modified but the database migration throws an error and it is not shown anywhere except if we look into prisma's migration management table : 

`SELECT * FROM management."Migration"
ORDER BY "projectId" ASC, revision DESC`

![image](https://user-images.githubusercontent.com/26528466/83941250-4335b300-a7ea-11ea-98d3-f621d8dd1cb2.png)

## How to reproduce

1. Bootstrap a basic prisma application
2. Add an email field to the User schema of type `String!`
3. Run `prisma deploy`
4. Create users with the same email using GraphQL playground 
5. Add the `@unique` decorator on the email field
6. Run `prisma deploy`
7. You should see no error
8. In pgAdmin run : `SELECT * FROM management."Migration" ORDER BY "projectId" ASC, revision DESC`
9. You should see a migration error and a rollback.

## Expected behavior

The command `prisma deploy` must throw an error if a migration error happens on postgreSQL.

## Prisma information

`datamodel.prisma`

```gql
type User {
  id: ID! @id
  name: String!
  email: String! @unique
}
```

`docker-compose.yml`

```yml
version: '3.1'

services:
  db:
    image: postgres
    restart: always
    volumes: 
      - ./.pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "default_db"
      POSTGRES_USER: "postuser"
      POSTGRES_PASSWORD: "postpass"
    ports:
      - 5432:5432
  
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: host.docker.internal
            database: default_db
            schema: public
            user: postuser
            password: postpass
            ssl: false
            rawAccess: true
            port: '5432'
            migrations: true
```

## Environment & setup

- OS: MacOS 10.15.4
- Database: PostgreSQL
- Prisma version: 1.34.10
- Node.js version: 10.16.2
