### ISSUE TITLE
Cannot delete a field with relation to scalar (simple type) array.

### ISSUE THREAD

**Issue by marktani** [prisma/prisma#2756]
@tomitrescak commented on [Wed Jul 11 2018](https://github.com/prismagraphql/graphql-server-example/issues/264)

Hi, asked this question as well in the [forum](https://www.prisma.io/forum/t/cannot-delete-a-field-in-the-database-with-relation-to-string-array/3956), but to me this seems as a bug.

I have a type with a string array field

```graphql
type Notification {
  id: ID
  params: [String!]!
}
```

Prisma generates the Notification_params table.

I have an issue deleting notification as I am receiving server error:

```
DELETE FROM "default$default"."Notification" as "Alias" WHERE TRUE
update or delete on table "Notification" violates foreign key constraint "Notification_params_nodeId_fkey" on table "Notification_params"
Now, there is no exposed function to delete something from Notification_params table
Nor, I can use Cascading delete relation.
```

Shouldn't these array fields be deleted automatically? Any help is greatly appreciated. If you answer here I will lint the answer in forum to this post.

**Comment by marktani** [comment]
Thanks for bringing this up, @tomitrescak.

Can you share additional information according to [the bug report template](https://github.com/prismagraphql/prisma/issues/new?template=bug_report.md)?

In particular, your Prisma server version, as well as the mutation that results in that error.

Thanks!

**Comment by tomitrescak** [comment]
**Describe the bug**

Description above

**To Reproduce**
Steps to reproduce the behavior:

1. Insert a new notification in the system with some parameters
2. Try to delete the notification
3. Error appears in the Postgre database

```

**Expected behavior**
The related array would be deleted automatically.

**Versions (please complete the following information):**
 - OS X High Sierra
 - prisma/1.10.2
 - Prisma Server: Running in docker from latest image with PostgreSql
 - Using graphql-yoga: 1.14.12

**Comment by tomitrescak** [comment]
Sorry and the code that deletes this is: `db.mutation.deleteNotification({ where: { id } })` and id is part of the Mutation resolvers args.

**Comment by tomitrescak** [comment]
It is definietly a bug in the Progres server ... I just used MySQL version and all works as expected.

**Comment by marktani** [comment]
Hey @tomitrescak, I am not able to reproduce this issue.

I used this datamodel:

```graphql
type Notification {
  id: ID! @unique
  params: [String!]!
}
```

I used this JavaScript file:

```js
const { Prisma } = require("prisma-binding");

const prisma = new Prisma({
  typeDefs: "./prisma.graphql",
  endpoint: "http://localhost:4466/r-2756/dev"
});

const id = 'cjjqsgtsd001z0980qcffws1x'
prisma.mutation.deleteNotification({ where: { id } })
```

The `Notification` node and `Notification_params` was correctly deleted.

I used Postgres and Prisma `1.12`.

Did you use the verbatim datamodel you shared in the initial issue? The error message refers to a FK on `nodeId` which does not exist in this datamode.

**Comment by tomitrescak** [comment]
Hi, my model is a bit more complex then that, I thought this minimal example would help. 

```graphql
#import BpmnProcessInstance from './bpmn_process_instance.graphql'
#import User from './user.graphql'

enum NotificationCode {
  ServiceStarted
  ServiceStopped
}

type BpmnProcessInstance {
  id: ID! @unique
}

type Notification {
  id: ID! @unique
  processInstance: BpmnProcessInstance
  code: NotificationCode
  text: Localisation
  params: [String!]!
  visible: Boolean
}
```

I'll investigate a bit more on a clean repo and post back.

**Comment by marktani** [comment]
It's not clear if the GraphQL file you shared is the datamodel, or the application schema.
The datamodel does not support `import` statements (see #1913).

Thanks for looking into a detailed repo 🙏

**Comment by tomitrescak** [comment]
Hi, let me investigate, as after I switched to MySQL I did not go back to. Progress.

**Comment by pschoffer** [comment]
Interesting. I just had the same issue.
My docker-compose:
```
 ...
 prisma:
    image: prismagraphql/prisma:1.8
    depends_on:
      - postgres
    restart: always
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: ***
            password: ***
            migrations: true
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ***
      POSTGRES_PASSWORD: ***
```

But it is weird as I have other tables where scalar arrays are deleted just fine. As a **workaround** I update the entity just before delation. So something like this:

```
const where = { id }
// This sets the array to [], which I assume does the deletion of the linked table 
await ctx.db.mutation.updateEntity({
      where,
      data: { problematicField: { set: [] } },
    })
// This deletes the main table and because of the previous step there is no fk constraint issue
await ctx.db.mutation.deleteEntity({ where })
```
