### ISSUE TITLE
Failed to connect Prisma to existing Database via Docker

### ISSUE THREAD

**Issue by SiddharthaSauravGogoi** [prisma/prisma#2782]
**Describe the bug**
Upon running _prisma deploy_ i get the error

> org.postgresql.Driver connect
> SEVERE: Connection error:
> org.postgresql.util.PSQLException: FATAL: no pg_hba.conf entry for host "172.18.0.2", user "prisma", 
>  database "postgres", SSL off  

My `docker-compose.yml`

```
version: '3'

services:
  prisma:  
    image: prismagraphql/prisma:1.9  
    restart: always  
    ports:  
    - "4466:4466"  
    environment:  
      PRISMA_CONFIG: |  
        port: 4466  
        databases:  
          default:  
            connector: postgres  
            host: postgres  
            port: 5432  
            user: prisma  
            password: prisma  
            migrations: true  
  postgres:  
    image: postgres  
    restart: always  
    environment:  
      POSTGRES_USER: prisma  
      POSTGRES_PASSWORD: prisma  
    volumes:  
      - postgres:/var/lib/postgresql/data  
volumes:  
  postgres:  
```

My `prisma.yml`
```
endpoint: http://192.168.99.100:4465  
datamodel: datamodel.graphql  
hooks:  
  post-deploy:  
    - graphql get-schema -p prisma
```

**To Reproduce**
1. Inititiate a prisma service with the stated docker.yml and prisma.yml code
2. Install the needed dependencies
3. Go the directory with the docker-compose.yml file and run docker-compose up 

**Expected behavior**
The connection to the database and `prisma deploy` command to be executed.

**Screenshots**
None

**Versions (please complete the following information):**
 - OS: [ `Windows 7`]
 - `prisma` CLI: [`prisma/1.11.1` , `node -v8.11.1` ]
 - Prisma Server: [ `1.12.0`]
 - `graphql-yoga`

**Additional context**
None
