### ISSUE TITLE
Getting default$default does not exist with external db

### ISSUE THREAD

**Issue by wieseljonas** [prisma/prisma#2795]
**Describe the bug**
I've been  able to introspect my database and manually tweak my schema and deployment is find

However when running queries I  get the following error: 
```
db_1      | ERROR:  relation "default$default.property_types" does not exist at character 15
db_1      | STATEMENT:  select *
db_1      | 	from "default$default"."property_types" as "Alias"
db_1      | 	where (
db_1      | 	  1 = 1
db_1      | 	  and 1 = 1
db_1      | 	)
db_1      | 	order by "Alias"."id" asc
```
**To Reproduce**

My docker yaml
```
version: '3'

services:
  # SQL and document data store
  db:
    image: db
    build:
      context: ./images/db
    tmpfs:
      - /tmp
      - /var/run/postgresql
    volumes:
      - db:/var/lib/postgresql/data
      - ./postgres-initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
      - ./seeds:/seeds
    ports:
      - "127.0.0.1:5432:5432" # you can override it via docker-compose.override.yml

  # Prisma
  prisma:
    image: prismagraphql/prisma:1.12
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: db
            port: '5432'
            user: root
            password: ''
            database: realadvisor
            schema: public
            migrations: false

  # Distributed in-memory cache
  redis:
    image: redis:***
    read_only: true
    volumes:
      - redis:/data
    user: redis

volumes:
  db:
  redis:
  yarn:

```

my prisma yml

```
endpoint: http://localhost:4466
datamodel: datamodel.graphql
```

**Versions (please complete the following information):**
 - `OS`: OS X High Sierra
 - Prisma: `prisma1.12`

**Additional context**

**Comment by wieseljonas** [comment]
Never mind I need to create a server or deploy to hosted cloud. To fix just had to remove endpoint from  prisma.yaml and run prisma deploy again

**Comment by divyenduz** [comment]
@wieseljonas : Can you please share your `datamodel.graphql` as well?

**Comment by wieseljonas** [comment]
I can but it’s huge! Any information you would like to see? 

Basically a schema called default$default get created in my db and of course it’s empty. Can’t get it to connect to public.

**Comment by kraisorns** [comment]
I'm not sure this will help. I kind of got this issue before and it about relation name has to be like this document. 

https://www.prisma.io/docs/reference/service-configuration/data-model/data-modelling-(sdl)-eiroozae8u#required-relations

the name of the relation should be something like 

`@relation(name: "StoriesByUser")`

not

`@relation(name: "storiesByUser"`

**Comment by flybayer** [comment]
I'm having the exact same problem connecting Prisma to an existing DB that's managed by Ruby on Rails.

Prisma isn't picking up the schema config item

```yaml
version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.12
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: xxx.rds.amazonaws.com
            port: '5432'
            database: ebdb
            schema: public
            user: xxx
            password: xxx
            migrations: false
```

```gql
type User @pgTable(name: "users") {
  id: Int! @unique
  admin: Boolean
  authentication_token: String
  created_at: DateTime!
  current_sign_in_at: DateTime
  email: String! @default(value: "")
  encrypted_password: String! @default(value: "")
  last_sign_in_at: DateTime
  remember_created_at: DateTime
  reset_password_sent_at: DateTime
  reset_password_token: String
  sign_in_count: Int! @default(value: 0)
  updated_at: DateTime!
}
```

**Comment by chrisbull** [comment]
Same problem here! I've tried everything (local db, docker db, remote db) uggg...
I've even tried limiting my datamodel.graphql to a single type such as :
```
type Likes @pgTable(name: "likes") {
  id: Int! @unique
  alert_id: Int
  created_at: DateTime!
  updated_at: DateTime!
  user_id: Int
}
```

This is the generated Likes tables that was created from the `prisma introspect`. I know it's missing the pgRelation to the user table... but for now it should and could just return the Int. But still getting error like the above. `ERROR: relation "default$default.likes" does not exist`

And I agree with @wieseljonas . I think it's because it's trying to look in the `default$default` schema even though migration is set to `false`. Which according to documentation is supposed to be false (and comes this way when you set it up using an existing database with prisma init). 

So then the big question is, how do make the prisma server work without migrating the database?

**Comment by wieseljonas** [comment]
@divyenduz  Issue is the name even with the most minimalistic datamodel.graphql as indicated by @chrisbull.

Do you need more details?

**Comment by alvinthen** [comment]
I'm having the same issue, but with Mutations.

I have a table under public schema `public.watchlist`, when I do Queries, things work. But when I do mutations, I have this error

<pre>ERROR: relation "default$default.watchlist" does not exist</pre>

And so I proceed to move my table into the `default$default` schema, weirdly both Mutations and Queries stop working giving the below error.

<pre>ERROR: relation "public.watchlist" does not exist</pre>

I'm using 1.14-alpha

**Comment by marktani** [comment]
Related to https://github.com/prismagraphql/prisma/issues/2846.

**Comment by berstend** [comment]
Still present in `1.14.0 (2018-08-15)`.

Removing the `schema` declaration and using the `default$default` schema is working for now, can be renamed once this is fixed. :-)

**Comment by Cottin** [comment]
I also hit this issue in prisma/1.16.4

Exactly same as @jgoux 's description, ie. external database and removing the `schema` key from `docker-compose.yml` works but then tables are created under schema `default$default` making it quite troublesome to execute sql.

**Comment by anodynos** [comment]
I have the same problem with `prisma/1.18.0-beta.12 (linux-x64) node-v9.9.0` running prisma & postgress with the default docker-compose on the simple `User` & `Posts` example, without writing any code. 
When I connect to the DB with DBeaver 5.2.0 I can see the `default$default` schema and the tables, when I try `SELECT * FROM "default$default"."User";` I get

```
Query execution failed

Reason:
SQL Error [42P01]: ERROR: relation "default$default.User" does not exist
  Position: 55
```

**Comment by marktani** [comment]
It seems that the error most commenters mention is that the `schema` property in `docker-compose.yml` is ignored. Is my understanding correct? Can someone provide a step by step guide for reproducing this locally? I was able to use the `schema` property to introspect/connect to an existing Postgres database on `1.17`.

**Comment by SarjuHansaliya** [comment]
@marktani 

I am using new database flow.
**To Reproduce**
1. `docker-compose.yml` file
```
version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.18
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: host.docker.internal
            port: 5432
            database: testing_dev
            schema: public
            user: postgres
            password: postgres
            migrations: true
            ssl: false
```
2. `prisma.yml` file
```
endpoint: http://localhost:4466
datamodel: datamodel.prisma
generate:
  - generator: javascript-client
    output: ./generated/prisma-client/
```
3. `datamodel.prisma`
```
type User {
  id: ID! @unique
  email: String
  first_name: String
  last_name: String
  password: String
}
```
4. I ran `docker-compose up -d` command
5. Then I ran `prisma deploy` command.
6. It created table named `User` in `default$default` but it should create table in `public` schema based on `schema` property defined in `docker-compose.yml` file.

Thanks
