### ISSUE TITLE
Troubleshooting while developing with docker with env variables

### ISSUE THREAD

**Issue by Sharlaan** [prisma/prisma#2835]
I would like to share and suggest adding 2 troubleshooting issues:

initial setup for `database/docker-compose.yml` :
```yml
version: '3'
services:
  # TODO: Add graphql-container

  prisma:
    # for production image, check https://hub.docker.com/r/prismagraphql/prisma-prod/tags/
    image: prismagraphql/prisma:1.12
    container_name: prisma-container
    restart: always
    ports:
    - ${PRISMA_PORT}:${PRISMA_PORT}
    environment:
      PRISMA_CONFIG: |
        port: ${PRISMA_PORT}
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ${DB_HOST}
            port: ${DB_PORT}
            database: ${DB_NAME}
            user: ${DB_USER}
            password: ${DB_PASSWORD}
            migrations: true

  postgres:
    image: postgres
    container_name: database-container
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
```

1. if you get error "... driver failed programming external connectivity on endpoint ..." => restart your docker by right-clicking the docker icon > "restart"

2. if you get error "Could not connect to server at http://localhost:4466. Please check if your server is running." while redeploying prisma, wipe everything beforehand with this script :
```
"clear:dockers": "dotenv -e .env.dev -- docker-compose -f database/docker-compose.yml down && docker volume prune -f"
```
then re-deploy with :
```
"deploy:dev": "dotenv -e .env.dev -- docker-compose -f database/docker-compose.yml up -dV && dotenv -e .env.dev cross-var \"wait-port $PRISMA_PORT\" && prisma deploy -e .env.dev",
```
