### ISSUE TITLE
Raw query failed. Code: `42704`. Message: `db error: ERROR: type \"geography\" does not exist`

### ISSUE THREAD

**Issue by RafaelKr** [prisma/prisma#2847]
## Bug description

I'm using PostgresQL with the PostGIS extension and have the following Query:
```typescript
const query = `
SELECT
	id
FROM
	my_project_prisma2."JobLocation"
WHERE
	ST_DWithin(ST_MakePoint(lng, lat)::geography, ST_MakePoint($1, $2)::geography, $3)
`

export const queryLocationsWithinAreaIds = (areaCenter: AreaCenter, ctx: Context) => {
	return ctx.pg.query(query, [areaCenter.lng, areaCenter.lat, areaCenter.radius])
}
```

As you can see I'm using `ctx.pg` which is a [pg Pool](https://node-postgres.com/api/pool) instance. This is working as expected.

Yesterday I upgraded from Prisma `2.0.0-preview021` to `2.1.0` and wanted to use the now available `prisma.queryRaw`. But when changing to `prisma.queryRaw` I get the following error:
```
Raw query failed. Code: `42704`. Message: `db error: ERROR: type \"geography\" does not exist`
```

## How to reproduce

Create a `kartoza/postgis:12.0` container. I'm using the following docker-compose.yaml:
```yaml
version: '3.7'

volumes:
  my_project_postgres:
    name: my_project_postgres

networks:
  my_project:
    name: my_project

services:
  postgres:
    container_name: my_project_postgres
    image: kartoza/postgis:12.0
    restart: unless-stopped
    networks:
      - my_project
    environment:
      POSTGRES_USER: my_project
      POSTGRES_PASSWORD: prisma2
      POSTGRES_DB: my_project
    volumes:
      - my_project:/var/lib/postgresql/data
```
2. Run it with the schema below
3. Insert some dummy data (probably not even needed to get the error)
4. Run the following query:
```typescript
import { PrismaClient } from '@prisma/client'

const query = `
SELECT
	id
FROM
	my_project_prisma2."JobLocation"
WHERE
	ST_DWithin(ST_MakePoint(lng, lat)::geography, ST_MakePoint($1, $2)::geography, $3)

async function main() {
  const result = await prisma.queryRaw(query, [areaCenter.lng, areaCenter.lat, areaCenter.radius])
}

main()
	.catch(console.error)
```

## Expected behavior

It should give me a result. The `pg` client works.

## Prisma information
```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("POSTGRES_URL")
}

model JobLocation {
  id            String   @default(cuid()) @id
  lat           Float?
  lng           Float?
}
```

`POSTGRES_URL=postgresql://my_project:prisma2@127.0.0.1:5432/my_project?schema=my_project_prisma2`

## Environment & setup

- OS: Linux Mint 19.2 Cinnamon
- Database: PostgreSQL + PostGIS extension
- Node.js version: 13.7.0
- Prisma version: 

```Environment variables loaded from prisma/.env
@prisma/cli          : 2.1.0
Current platform     : debian-openssl-1.1.x
Query Engine         : query-engine 4440772035795a0424be62040e2295c56e5c6ad0 (at /home/rafael/[...]/node_modules/@prisma/cli/query-engine-debian-openssl-1.1.x)
Migration Engine     : migration-engine-cli 4440772035795a0424be62040e2295c56e5c6ad0 (at /home/rafael/[...]/node_modules/@prisma/cli/migration-engine-debian-openssl-1.1.x)
Introspection Engine : introspection-core 4440772035795a0424be62040e2295c56e5c6ad0 (at /home/rafael/[...]/node_modules/@prisma/cli/introspection-engine-debian-openssl-1.1.x)
Format Binary        : prisma-fmt 4440772035795a0424be62040e2295c56e5c6ad0 (at /home/rafael/[...]/node_modules/@prisma/cli/prisma-fmt-debian-openssl-1.1.x)
```
