### ISSUE TITLE
Requiring an Enum as a non-nullable value breaks case sensitivity

### ISSUE THREAD

**Issue by selipso** [prisma/prisma#2922]
**Describe the bug**
I've only been able to verify this with Postgres, but when I require an Enum field type to be non-nullable, I get an error but when I remove the exclamation mark (allowing the field to be null), the error goes away when running `prisma deploy`.

**To Reproduce**
1) Start with one of the graphql boilerplate templates and edit the datamodel.graphql file to be:
```graphql
enum UserRolesEnum {
  GUEST
  VERIFIED
  AUTHENTICATED
}
type User {
  id: ID! @unique
  email: String @unique
  createdAt: DateTime!
  updatedAt: DateTime!
  password: String
  name: String
  userType: UserRolesEnum!
}
```
2) Run `prisma deploy`

3) Get rekt by an error. At first it says internal server error. Going to the prisma logs I see the following (running prisma and Postgres with docker-compose):
```
postgres_1  | 2018-08-14 20:27:58.276 UTC [29] ERROR:  column User.usertype does not exist at character 74
postgres_1  | 2018-08-14 20:27:58.276 UTC [29] HINT:  Perhaps you meant to reference the column "User.userType".
postgres_1  | 2018-08-14 20:27:58.276 UTC [29] STATEMENT:  SELECT EXISTS(Select "id" FROM "postgres$default"."User"
postgres_1  | 	          WHERE "postgres$default"."User".userType IS NULL)
prisma_1    | org.postgresql.util.PSQLException: ERROR: column User.usertype does not exist
prisma_1    |   Hint: Perhaps you meant to reference the column "User.userType".
prisma_1    |   Position: 74
prisma_1    | 	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433)
prisma_1    | 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2178)
prisma_1    | 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:306)
prisma_1    | 	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
prisma_1    | 	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
prisma_1    | 	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:155)
prisma_1    | 	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:144)
prisma_1    | 	at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
prisma_1    | 	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
prisma_1    | 	at slick.jdbc.StatementInvoker.results(StatementInvoker.scala:38)
prisma_1    | 	at slick.jdbc.StatementInvoker.iteratorTo(StatementInvoker.scala:21)
prisma_1    | 	at slick.jdbc.Invoker.foreach(Invoker.scala:47)
prisma_1    | 	at slick.jdbc.Invoker.foreach$(Invoker.scala:46)
prisma_1    | 	at slick.jdbc.StatementInvoker.foreach(StatementInvoker.scala:15)
prisma_1    | 	at slick.jdbc.StreamingInvokerAction.run(StreamingInvokerAction.scala:22)
prisma_1    | 	at slick.jdbc.StreamingInvokerAction.run$(StreamingInvokerAction.scala:20)
prisma_1    | 	at slick.jdbc.SQLActionBuilder$$anon$1.run(StaticQuery.scala:95)
prisma_1    | 	at slick.jdbc.SQLActionBuilder$$anon$1.run(StaticQuery.scala:95)
prisma_1    | 	at slick.basic.BasicBackend$DatabaseDef$$anon$2.liftedTree1$1(BasicBackend.scala:275)
prisma_1    | 	at slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:275)
prisma_1    | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
prisma_1    | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
prisma_1    | 	at java.lang.Thread.run(Thread.java:748)
```

4) Remove the exclamation mark from UserRolesEnum and watch the code magically work again when running `prisma deploy`

**Expected behavior**
The presence of an exclamation point with an Enum in GraphQL shouldn't affect the case sensitivity of the column name.

**Versions (please complete the following information):**
 - OS: MacOS High Sierra
 - `prisma` CLI: 1.13.7
 - Prisma Server: 1.13.7 (docker image)
 - `graphql-cli@2.16.4`

**Additional context**

**Comment by marktani** [comment]
I can't reproduce this using this `docker-compose.yml`:

```yml
version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.13
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: prisma
            password: prisma
            migrations: true
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
```

Did you also start from complete scratch, or did your deploy in step 2 was to an existing service with a different datamodel?
