### ISSUE TITLE
Subscriptions only fire on 'DELETE' action never on 'CREATE' or 'UPDATE'

### ISSUE THREAD

**Issue by midmandle** [prisma/prisma#2933]
**Describe the bug**
This is a duplicate the question at StackOverflow : [LINK](https://stackoverflow.com/questions/51890993/graphql-prisma-subscriptions-only-fire-for-delete)

Essentialy, regardless of where I subscribe (the App or Prisma API directly) the subscriptions will only fire on the 'DELETE' action. Any mutations which UPDATE or CREATE have no effect, the subscription just ignores the changes. The subscription will work without any problems but only for DELETE actions.

**To Reproduce**

- Implement the resolvers in index.js as below : 

```
Subscription: {
    userChanges: {
        subscribe: (_, args, context, info) => {
            console.log("CHECKCHECK");
            return context.prisma.subscription.user(
                { where: { mutation_in: ['CREATED', 'UPDATED', 'DELETED'] } }, 
                info
            )
        }
    },
    taskChanges: {
        subscribe: (_, args, context, info) => {
            return context.prisma.subscription.task({}, info)
        }
    }
}
```
- Run the server and open Playground in the browser.
- Create a subscription to userChanges like below: 

```
subscription {
	userChanges {
            node {
	        name
            }
      }
}
```
- Run the subscription on the App
- Make a mutation to add. Then make a mutation to update and finally make a mutation to delete.

- Create a subscription to user like below for the Prsima API:

```
subscription {
	user(where:{mutation_in:[CREATED]}){
            mutation
                node {
			id
                        name
                }
          }
}
```
- Run the subscription on the Prsima API.
- Make a mutation to add. Then make a mutation to update and finally make a mutation to delete.

**Expected behavior**
I expect the subscriptions for both the App and the Prisma API to respond to all changes to the user model.

**Screenshots**
App Subscription responding to DELETE:
![appresponsive](https://user-images.githubusercontent.com/12828641/44266026-e33ed880-a220-11e8-9cd6-4013865a1a17.PNG)

App Subscription non-responsive to UPDATE or CREATE:

![appnonresponsive](https://user-images.githubusercontent.com/12828641/44266031-e9cd5000-a220-11e8-9cee-f0d26d5380ce.PNG)

Prisma API Subscription responding to DELETE:

![prismaresponsive](https://user-images.githubusercontent.com/12828641/44266038-ef2a9a80-a220-11e8-99b3-a5a29bd6b882.PNG)

Prisma API Subscription non-responsive to UPDATE or CREATE:

![prismanonresponsive](https://user-images.githubusercontent.com/12828641/44266042-f2be2180-a220-11e8-8e7d-5c61658ac186.PNG)

**Versions (please complete the following information):**
 - OS: Windows 10
 - `prisma` CLI: prisma/1.14.0 (windows-x64) node-v8.11.1
 - Prisma Server: prismagraphql/prisma:1.12?? Not sure where to find this.
- `prisma-binding`: "2.1.1" 
- `graphql-yoga`: "1.14.12"

**Comment by midmandle** [comment]
I've resolved this issue now. For others who may come accross this I wasn't aware my Docker image version was out of date. I was on 1.12. Simply upgrading the image to 1.14 and redeploying the Docker image fixed this issue. Hope it helps someone else! 

Here is my updated docker-compose.yml

```
version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.14
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: mysql
            host: mysql
            port: 3306
            user: root
            password: prisma
            migrations: true
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: prisma
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql:
```

After changing this I pulled the images down and redeployed them up.
