### ISSUE TITLE
Unable to Connect to MariaDB Database

### ISSUE THREAD

**Issue by gakalantzis** [prisma/prisma#2966]
I'm attempting to set up a Prisma instance with a MariDBb database.  When I run "prisma deploy", the execution just hangs before eventually timing out.  I know that it's able to access MariDBb as it'll create the Prisma database and the default@default database, however as soon as it comes time to create all the types and tables, it won't work.  I've tested this with older versions of Prisma, the beta and alpha branches, and various versions of MariDB.

I have no problems connecting to a MySQL database.  Are there any extra configuration steps that need to be taken in order to use MariaDB, is MariaDB just not supported, or am I just completely missing something?  Thank you!

docker-compose.yml using MariaDB docker image
```
version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.14.2
    restart: always
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        managementApiSecret: mysecret
        databases:
          default:
            connector: mysql
            host: mariadb
            port: 3306
            user: root
            password: prisma
            migrations: true
  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: prisma
    volumes:
      - mariadb:/var/lib/mysql
volumes:
  mariadb:
```
docker-compose using local MariaDB

```
version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.14.2
    restart: always
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        managementApiSecret: mysecret
        databases:
          default:
            connector: mysql
            host: host.docker.internal
            port: 3306
            user: root
            password: prisma
            migrations: true
```

prisma deploy log

```
client Initializing cluster client +0ms
  deploy checking if project exists +0ms
  client Sending query to cluster local +3ms
  client http://localhost:4466/management +0ms
  client 
  client       query($name: String! $stage: String!) {
  client         project(name: $name stage: $stage) {
  client           name
  client           stage
  client         }
  client       }
  client      +0ms
  client { name: 'default', stage: 'default' } +1ms
  client { project: { name: 'default', stage: 'default' } } +36ms

Deploying service `default` to stage `default` to server `local`...  client Sending query to cluster local +2ms
  client http://localhost:4466/management +0ms
  client       mutation($name: String!, $stage: String! $types: String! $dryRun: Boolean $secrets: [String!], $subscriptions: [FunctionInput!], $force: Boolean) {
  client         deploy(input: {
  client           name: $name
  client           stage: $stage
  client           types: $types
  client           dryRun: $dryRun
  client           secrets: $secrets
  client           subscriptions: $subscriptions
  client           force: $force
  client         }) {
  client           errors {
  client             type
  client             field
  client             description
  client           }
  client           warnings {
  client             type
  client             field
  client             description
  client           }
  client           migration {
  client             ...MigrationFragment
  client           }
  client         }
  client       }
  client       
  client fragment MigrationFragment on Migration {
  client   revision
  client   steps {
  client     type
  client     __typename
  client     ... on CreateEnum {
  client       name
  client       ce_values: values
  client     }
  client     ... on CreateField {
  client       model
  client       name
  client       cf_typeName: typeName
  client       cf_isRequired: isRequired
  client       cf_isList: isList
  client       cf_isUnique: unique
  client       cf_relation: relation
  client       cf_defaultValue: default
  client       cf_enum: enum
  client     }
  client     ... on CreateModel {
  client       name
  client     }
  client     ... on CreateRelation {
  client       name
  client       leftModel
  client       rightModel
  client     }
  client     ... on DeleteEnum {
  client       name
  client     }
  client     ... on DeleteField {
  client       model
  client       name
  client     }
  client     ... on DeleteModel {
  client       name
  client     }
  client     ... on DeleteRelation {
  client       name
  client     }
  client     ... on UpdateEnum {
  client       name
  client       newName
  client       values
  client     }
  client     ... on UpdateField {
  client       model
  client       name
  client       newName
  client       typeName
  client       isRequired
  client       isList
  client       isUnique: unique
  client       relation
  client       default
  client       enum
  client     }
  client     ... on UpdateModel {
  client       name
  client       um_newName: newName
  client     }
  client   }
  client }
  client 
  client      +0ms
  client { name: 'default',
  client   stage: 'default',
  client   types: 'type User {\n  id: ID! @unique\n  login: String\n  email: String\n  firstName: String\n  lastName: String\n}\n\n',
  client   dryRun: undefined,
  client   secrets: null,
  client   subscriptions: [],
  client   force: undefined } +0ms
 !
FetchError: request to http://localhost:4466/management failed, reason: socket hang up
    at ClientRequest.<anonymous> (/Users/kalag003/.config/yarn/global/node_modules/cross-fetch/node_modules/node-fetch/lib/index.js:1393:11)
    at ClientRequest.emit (events.js:182:13)
    at ClientRequest.EventEmitter.emit (domain.js:442:20)
    at Socket.socketOnEnd (_http_client.js:409:9)
    at Socket.emit (events.js:187:15)
    at Socket.EventEmitter.emit (domain.js:460:23)
    at endReadableNT (_stream_readable.js:1086:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Exiting with code: 1
```
