### ISSUE TITLE
[new generator] env var used in endpoint (prisma.yml) breaks generated/index.ts

### ISSUE THREAD

**Issue by brikou** [prisma/prisma#3081]
**Describe the bug**

env var used in endpoint (prisma.yml) breaks generated/index.ts

**To Reproduce**

```yml
# prisma.yml
datamodel: datamodel.graphql

endpoint: http://localhost:4466/default/${env:PRISMA__ENDPOINT__STAGE}
```

Then run generate command, now we have:

```ts
# generated/index.ts
/**
 * Type Defs
 */

export const Prisma = makePrismaBindingClass<BindingConstructor<Prisma>>({
    typeDefs,
    endpoint: process.env["PRISMA__ENDPOINT__STAGE"],
});
export const prisma = new Prisma();
```

**Expected behavior**

```ts
# generated/index.ts

export const Prisma = makePrismaBindingClass<BindingConstructor<Prisma>>({
    typeDefs,
    endpoint: `http://localhost:4466/default/${process.env["PRISMA__ENDPOINT__STAGE"]}`,
});
export const prisma = new Prisma();
```
