### ISSUE TITLE
Migrations set to false results in Array field errors

### ISSUE THREAD

**Issue by brunoprela** [prisma/prisma#3095]
**Describe the bug**
Deploying to a database with `migrations: true`, results in a seamless deployment. Deploying, either to an existing database with the proper tables and `migrations: false`, or to a database with no existing  tables and `migrations false` results in errors regarding PostgreSQL array fields which didn't previously exist.

**To Reproduce**
Steps to reproduce the behavior (this assumes that there is a hidden step in which the db is populated with tables using another prisma service, so that `migrations: false` has a fresh db deployed with `migrations: true` to look at; left it out to reduce complexity):
1. Setup `docker-compose.yml`with the following basic services:
 ```
version: "3"
services:

  database:
    image: postgres:9.6
    restart: always
    ports:
      - "5432:5432"
    networks:
      - dev
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: prisma

  prisma:
    image: prismagraphql/prisma:1.16.0
    restart: always
    depends_on:
      - database
    networks:
      - dev
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        managementApiSecret: my-prisma-api-secret
        databases:
          default:
            connector: postgres
            active: true
            host: database
            port: 5432
            user: postgres
            password: prisma
            migrations: false

networks:
  dev:
    driver: bridge

volumes:
  queue-persistence:
```

2. Setup a model such as 
```
type ExampleType {
    id: ID! @unique
    createdAt: DateTime!
    updatedAt: DateTime!
    firstList: [String!]
    secondList: [String!]!
}
```
3. Start your docker setup, and run `prisma deploy` with the proper environment variables.
4. You should see an error:
```
Errors:
  ExampleType
    ✖ The scalar field `firstList` has the wrong format: `[String!]` Possible Formats: `String`, `String!`
    ✖ The scalar field `secondList` has the wrong format: `[String!]!` Possible Formats: `String`, `String!`
```

**Expected behavior**
I expect the behavior to be the same as running without `migrations: false`. PostgreSQL array fields should still be supported.

**Versions (please complete the following information):**
 - OS: `OS X High Sierra 10.13.6` 
 - `prisma` CLI: `prisma/1.16.0 (darwin-x64) node-v9.9.0`
 - Prisma Server: `1.16.0`
