### ISSUE TITLE
Prisma service not using the mysql database it created

### ISSUE THREAD

**Issue by canpan14** [prisma/prisma#3118]
I'm creating a mysql database with some initial data
Prisma deploy 'succeeds' but all queries return an empty array.

When deploying it looks like it succeeds if not for the errors in the log and the empty returns:
```
Creating stage default for service default ✔
Deploying service `default` to stage `default` to server `local` 793ms
...
Applying changes 6.2s

Your Prisma GraphQL database endpoint is live:

  HTTP:  http://localhost:4466
  WS:    ws://localhost:4466
```

What I think might be an issue is the fact that I have a `default` database that I initialized, and I have a `default@default` database that I'm assuming the prisma service made:
![image](https://user-images.githubusercontent.com/9167489/45629063-80c93a00-ba63-11e8-9187-700ab4bbc0af.png)

Looking at the databases, `default` has all the data i initialized where `default@default` is where it applied to schema from `datamodel.graphql`

docker-compose:
```
version: "3"
services:
  prisma:
    image: prismagraphql/prisma:1.9
    restart: always
    depends_on:
      - mysql
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: mysql
            active: true
            host: mysql
            port: 3306
            user: root
            password: prisma
            migrations: true
  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: prisma
      MYSQL_DATABASE: default
    volumes:
      - mysql:/var/lib/mysql
      - ./dump_1_tables.sql:/docker-entrypoint-initdb.d/init_1.sql
      - ./dump_2_data.sql:/docker-entrypoint-initdb.d/init_2.sql
volumes:
  mysql:
```

Docker log error:
```
{  
   "key":"error/handled",
   "requestId":"local:management:cjm6ceaa300010838m6vp60uh",
   "payload":{  
      "exception":"com.prisma.deploy.schema.InvalidProjectId: No service with name 'default' and stage 'default' found",
      "query":"\n      query($name: String! $stage: String!) {\n        project(name: $name stage: $stage) {\n          name\n          stage\n        }\n      }\n    ",
      "variables":"{\"name\":\"default\",\"stage\":\"default\"}",
      "code":"4000",
      "stack_trace":"com.prisma.deploy.schema.SchemaBuilderImpl.$anonfun$projectField$3(SchemaBuilder.scala:139)\\n scala.Option.getOrElse(Option.scala:121)\\n com.prisma.deploy.schema.SchemaBuilderImpl.$anonfun$projectField$2(SchemaBuilder.scala:139)\\n scala.util.Success.$anonfun$map$1(Try.scala:251)\\n scala.util.Success.map(Try.scala:209)\\n scala.concurrent.Future.$anonfun$map$1(Future.scala:287)\\n scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)\\n scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)\\n scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)\\n akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)\\n akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)\\n scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)\\n scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)\\n akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)\\n akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)\\n akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43)\\n akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)\\n akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)\\n akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)\\n akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)",
      "message":"No service with name 'default' and stage 'default' found"
   }
}
```

Formatted stack trace:
```
com.prisma.deploy.schema.SchemaBuilderImpl.$anonfun$projectField$3(SchemaBuilder.scala:139)\\n
scala.Option.getOrElse(Option.scala:121)\\n 
com.prisma.deploy.schema.SchemaBuilderImpl.$anonfun$projectField$2(SchemaBuilder.scala:139)\\n
scala.util.Success.$anonfun$map$1(Try.scala:251)\\n scala.util.Success.map(Try.scala:209)\\n 
scala.concurrent.Future.$anonfun$map$1(Future.scala:287)\\n 
scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)\\n 
scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)\\n 
scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)\\n 
akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)\\n 
akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)\\n 
scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)\\n 
scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)\\n 
akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)\\n 
akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)\\n 
akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.sc
ala:43)\\n akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)\\n 
akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)\\n 
akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)\\n 
akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Versions (please complete the following information):**
 - OS: `OS X High Sierra`
 - `prisma/1.16.2 (darwin-x64) node-v10.0.0`
 - Prisma Server: `1.8.x` & `1.9`
