### ISSUE TITLE
Prisma deploy hangs at the time of "Applying changes" 

### ISSUE THREAD

**Issue by vadim-shilov** [prisma/prisma#3166]
Hello!
Thanks for the Prisma!
Try to start my first Prisma Server, but *prisma deploy* hangs at the time of "Applying changes." 

**prisma.yml**:
```
endpoint: http://localhost:4466
datamodel: datamodel.graphql
secret: my_secret
```

**datamodel.graphql**:
```
type UserType {
  id: ID! @unique
  name: String! @unique
  description: String
}

type User {
  id: ID! @unique
  type: UserType!
  name: String!
  email: String! @unique
  emailVerified: Boolean! @default(value: "false")
}
```

**docker-compose.yml**:
```
version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.16
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        managementApiSecret: my_secret
        port: 4466
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: prisma
            password: prisma
            migrations: true
  postgres:
    image: postgres:10.5
    restart: always
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
```
Versions:
 - OS: OS X High Sierra 10.13.6
 - prisma CLI: prisma/1.17.0-beta.22 (darwin-x64) node-v10.4.1

*docker-compose up* log:
```
Creating database_prisma_1   ... done
Creating database_postgres_1 ... done
Attaching to database_postgres_1, database_prisma_1
postgres_1  | 2018-09-21 00:47:03.286 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres_1  | 2018-09-21 00:47:03.286 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgres_1  | 2018-09-21 00:47:03.292 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres_1  | 2018-09-21 00:47:03.311 UTC [21] LOG:  database system was interrupted; last known up at 2018-09-21 00:44:09 UTC
postgres_1  | 2018-09-21 00:47:03.567 UTC [21] LOG:  database system was not properly shut down; automatic recovery in progress
postgres_1  | 2018-09-21 00:47:03.573 UTC [21] LOG:  redo starts at 0/16342B8
postgres_1  | 2018-09-21 00:47:03.576 UTC [21] LOG:  invalid record length at 0/166E9D0: wanted 24, got 0
postgres_1  | 2018-09-21 00:47:03.576 UTC [21] LOG:  redo done at 0/166E998
postgres_1  | 2018-09-21 00:47:03.576 UTC [21] LOG:  last completed transaction was at log time 2018-09-21 00:44:12.812698+00
postgres_1  | 2018-09-21 00:47:03.647 UTC [1] LOG:  database system is ready to accept connections
postgres_1  | 2018-09-21 00:47:07.733 UTC [29] ERROR:  database "prisma" already exists
postgres_1  | 2018-09-21 00:47:07.733 UTC [29] STATEMENT:  CREATE DATABASE "prisma"
prisma_1    | Obtaining exclusive agent lock...
prisma_1    | Obtaining exclusive agent lock... Successful.
prisma_1    | Deployment worker initialization complete.
postgres_1  | 2018-09-21 00:47:09.244 UTC [28] ERROR:  null value in column "lastPinged" violates not-null constraint
postgres_1  | 2018-09-21 00:47:09.244 UTC [28] DETAIL:  Failing row contains (7677d416-194e-4f5d-a7fb-0f01e1b2b75f, null).
postgres_1  | 2018-09-21 00:47:09.244 UTC [28] STATEMENT:  insert into "TelemetryInfo" ("id","lastPinged")  values ($1,$2)
prisma_1    | Initializing workers...
prisma_1    | Successfully started 1 workers.
prisma_1    | Server running on :4466
prisma_1    | Version is up to date.
```
*prisma deploy* log:
```
Deploying service `default` to stage `default` to server `local` 1.0s

Changes:

  UserType (Type)
  + Created type `UserType`
  + Created field `id` of type `GraphQLID!`
  + Created field `name` of type `String!`
  + Created field `description` of type `String`
  + Created field `updatedAt` of type `DateTime!`
  + Created field `createdAt` of type `DateTime!`

  User (Type)
  + Created type `User`
  + Created field `id` of type `GraphQLID!`
  + Created field `type` of type `Relation!`
  + Created field `name` of type `String!`
  + Created field `email` of type `String!`
  + Created field `emailVerified` of type `Boolean!`
  + Created field `updatedAt` of type `DateTime!`
  + Created field `createdAt` of type `DateTime!`

  UserToUserType (Relation)
  + Created relation between User and UserType

Applying changes (0/15) ⣻
```

Is this a bug?
