### ISSUE TITLE
Adjust `prisma init` flow

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma#3199]
- [x] the interactive `prisma init` wizard should already invoke `generate` so that the client is already initially generated
- [x] the value for `generate.output` in `prisma.yml` should be: `generated/prisma-client/`:

```yml
generate:
  - generator: javascript-client
    output: ./generated/prisma-client/
```

- [x] remove the `post-deploy` hook from prisma.yml
