### ISSUE TITLE
Make usage of `generate.output` consistent across examples and docs

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma#3200]
Whenever the `generate` property is specified in prisma.yml, it should be consistent in that the `output` uses the following values:

```yml
generate:
  - generator: javascript-client
    output: ./generated/prisma-client/
```

`./generated/prisma-client/` is chosen to favor explicitness and clarity for what's going on.
