### ISSUE TITLE
prisma playground command fails in combination with generate definitions

### ISSUE THREAD

**Issue by kporten** [prisma/prisma#3215]
**Describe the bug**
`prisma playground` command fails if you use a `.graphqlconfig.yml` file in combination with the `generate` property in the `prisma.yml` file.

```sh
$ prisma playground
 ▸    Cannot read property 'getProjects' of null
```

**To Reproduce**
1. Create a complete new prisma project (prisma init > local docker)
2. Create a GraphQL Config (graphql init)
3. Optional: Move the files in the folder structure of the following screenshot
4. Modify the file content of `prisma.yml` and `.graphqlconfig.yml` like below
5. Execute `prisma deploy`
6. Execute `prisma playground`
7. See error
8. If you remove the `generate` property from the `prisma.yml` and execute `prisma playground` again, it works but now you don't have generated files anymore

**Screenshots**
<img width="194" alt="prisma-bug" src="https://user-images.githubusercontent.com/1839345/46249302-22b73200-c427-11e8-8563-af8a61f13fcd.png">

**Versions (please complete the following information):**
 - OS: macOS Mojave
 - Prisma: 1.17.1

**prisma.yml**
```yml
endpoint: http://localhost:4466
datamodel: datamodel.prisma

generate:
  - generator: typescript-client
    output: ../src/generated/prisma
  - generator: graphql-schema
    output: ../src/generated/prisma

hooks:
  post-deploy:
    - prisma generate
```

**.graphqlconfig.yml**
```yml
projects:
  database:
    schemaPath: ./src/generated/prisma.graphql
    extensions:
      prisma: ./database/prisma.yml
```

**Comment by jide** [comment]
Until this is fixed, I make `prisma deploy`, then comment the generate part, then `prisma playground`, and do it again when I need to deploy.

**Comment by marktani** [comment]
I can confirm this bug.

**Comment by lterfloth** [comment]
@jide thanks for the workaround. Even the obvious ones may not seem obvious for some people. 

@marktani is there an update on the issue?

**Comment by pantharshit00** [comment]
Hi,

I can't reproduce this in the latest version of prisma cli: https://www.youtube.com/watch?v=wRSSwz8eWuA

**Comment by divyenduz** [comment]
Thanks for the reproduction Harshit. I can confirm that even using the Prisma CLI version mentioned in the issue with Harshit's reproduction does not reproduce this issue. 

```
divyendusingh [prisma-issue-3215]$ npx prisma@1.17.1 generate
Generating schema 28ms
Saving Prisma Client (TypeScript) at /Users/divyendusingh/Documents/projects/graphcool/triage/prisma-issue-3215/generated/prisma
```

I will close this one for now. If the problem persists, please open a new issue with a reproduction. Thanks.

**Comment by darrylyoung** [comment]
I'm not using a `.graphqlconfig.yml` file yet I still get this issue.

_prisma.yml_
```
endpoint: http://localhost:4466
datamodel: datamodel.prisma
secret: ***

generate:
  - generator: typescript-client
    output: ../src/generated/prisma-client/

hooks:
  post-deploy:
    - prisma generate
```

Folder structure

<img width="296" alt="screenshot 2019-02-11 at 10 52 58" src="https://user-images.githubusercontent.com/1460800/52555898-40d86a00-2deb-11e9-9603-9f955f73deb8.png">
