### ISSUE TITLE
service failure when deploying to docker swarm

### ISSUE THREAD

**Issue by mateodelnorte** [prisma/prisma#3247]
**Describe the bug**
I'm attempting to deploy a simple prisma stack to a docker swarm. It's essentially the getting started compose example, converted into a stack file for docker swarm on AWS. The prisma service and postgres db are both giving some unusual logs which don't present themselves with the local compose file: 

prisma service, cycling, ending with Killed.
```
denormalizer-api_prisma.1.vnh653rlrx96@ip-172-31-21-171.ec2.internal    | Obtaining exclusive agent lock...
denormalizer-api_prisma.1.vnh653rlrx96@ip-172-31-21-171.ec2.internal    | Obtaining exclusive agent lock... Successful.
denormalizer-api_prisma.1.vnh653rlrx96@ip-172-31-21-171.ec2.internal    | Deployment worker initialization complete.
denormalizer-api_prisma.1.vnh653rlrx96@ip-172-31-21-171.ec2.internal    | Killed
denormalizer-api_prisma.1.xkdgwrd96loh@ip-172-31-21-171.ec2.internal    | Obtaining exclusive agent lock...
denormalizer-api_prisma.1.xkdgwrd96loh@ip-172-31-21-171.ec2.internal    | Obtaining exclusive agent lock... Successful.
denormalizer-api_prisma.1.xkdgwrd96loh@ip-172-31-21-171.ec2.internal    | Deployment worker initialization complete.
denormalizer-api_prisma.1.xkdgwrd96loh@ip-172-31-21-171.ec2.internal    | Killed
denormalizer-api_prisma.1.1x6ran9pct2w@ip-172-31-21-171.ec2.internal    | Obtaining exclusive agent lock...
denormalizer-api_prisma.1.1x6ran9pct2w@ip-172-31-21-171.ec2.internal    | Obtaining exclusive agent lock... Successful.
denormalizer-api_prisma.1.1x6ran9pct2w@ip-172-31-21-171.ec2.internal    | Deployment worker initialization complete.
denormalizer-api_prisma.1.1x6ran9pct2w@ip-172-31-21-171.ec2.internal    | Killed
denormalizer-api_prisma.1.rwuek1czk9rn@ip-172-31-27-66.ec2.internal    | Obtaining exclusive agent lock...
denormalizer-api_prisma.1.rwuek1czk9rn@ip-172-31-27-66.ec2.internal    | Obtaining exclusive agent lock... Successful.
denormalizer-api_prisma.1.rwuek1czk9rn@ip-172-31-27-66.ec2.internal    | Deployment worker initialization complete.
denormalizer-api_prisma.1.rwuek1czk9rn@ip-172-31-27-66.ec2.internal    | Killed
denormalizer-api_prisma.1.kczqswx0qn5h@ip-172-31-47-14.ec2.internal    | Obtaining exclusive agent lock...
denormalizer-api_prisma.1.kczqswx0qn5h@ip-172-31-47-14.ec2.internal    | Obtaining exclusive agent lock... Successful.
denormalizer-api_prisma.1.kczqswx0qn5h@ip-172-31-47-14.ec2.internal    | Deployment worker initialization complete.
denormalizer-api_prisma.1.kczqswx0qn5h@ip-172-31-47-14.ec2.internal    | Killed
```

postgres service, continually giving errors that prisma already exists:
```
denormalizer-api_postgres.1.iue7w71s0fgm@ip-172-31-33-214.ec2.internal    | 2018-10-03 20:38:25.769 UTC [211] STATEMENT:  CREATE DATABASE "prisma"
denormalizer-api_postgres.1.iue7w71s0fgm@ip-172-31-33-214.ec2.internal    | 2018-10-03 20:38:27.201 UTC [210] ERROR:  null value in column "lastPinged" violates not-null constraint
denormalizer-api_postgres.1.iue7w71s0fgm@ip-172-31-33-214.ec2.internal    | 2018-10-03 20:38:27.201 UTC [210] DETAIL:  Failing row contains (cf76f5e9-fb9f-4b66-aa7a-108c038fc32f, null).
denormalizer-api_postgres.1.iue7w71s0fgm@ip-172-31-33-214.ec2.internal    | 2018-10-03 20:38:27.201 UTC [210] STATEMENT:  insert into "TelemetryInfo" ("id","lastPinged")  values ($1,$2)
denormalizer-api_postgres.1.iue7w71s0fgm@ip-172-31-33-214.ec2.internal    | 2018-10-03 20:38:38.503 UTC [213] ERROR:  database "prisma" already exists
denormalizer-api_postgres.1.iue7w71s0fgm@ip-172-31-33-214.ec2.internal    | 2018-10-03 20:38:38.503 UTC [213] STATEMENT:  CREATE DATABASE "prisma"
denormalizer-api_postgres.1.iue7w71s0fgm@ip-172-31-33-214.ec2.internal    | 2018-10-03 20:38:39.771 UTC [212] ERROR:  null value in column "lastPinged" violates not-null constraint
denormalizer-api_postgres.1.iue7w71s0fgm@ip-172-31-33-214.ec2.internal    | 2018-10-03 20:38:39.771 UTC [212] DETAIL:  Failing row contains (6dc1b2f9-d635-40f8-b4c9-c2a32d446cda, null).
denormalizer-api_postgres.1.iue7w71s0fgm@ip-172-31-33-214.ec2.internal    | 2018-10-03 20:38:39.771 UTC [212] STATEMENT:  insert into "TelemetryInfo" ("id","lastPinged")  values ($1,$2)
denormalizer-api_postgres.1.iue7w71s0fgm@ip-172-31-33-214.ec2.internal    | 2018-10-03 20:38:50.804 UTC [216] ERROR:  database "prisma" already exists
denormalizer-api_postgres.1.iue7w71s0fgm@ip-172-31-33-214.ec2.internal    | 2018-10-03 20:38:50.804 UTC [216] STATEMENT:  CREATE DATABASE "prisma"
denormalizer-api_postgres.1.iue7w71s0fgm@ip-172-31-33-214.ec2.internal    | 2018-10-03 20:38:52.046 UTC [215] ERROR:  null value in column "lastPinged" violates not-null constraint
denormalizer-api_postgres.1.iue7w71s0fgm@ip-172-31-33-214.ec2.internal    | 2018-10-03 20:38:52.046 UTC [215] DETAIL:  Failing row contains (8bb85bac-9ccd-4499-ab91-9ab460297d99, null).
denormalizer-api_postgres.1.iue7w71s0fgm@ip-172-31-33-214.ec2.internal    | 2018-10-03 20:38:52.046 UTC [215] STATEMENT:  insert into "TelemetryInfo" ("id","lastPinged")  values ($1,$2)
```

The prisma db *does* exist, however has no tables in it. 

**To Reproduce**

Create a docker for AWS swarm and deploy a stack that looks like the following: 

```
version: '3'

services:

  prisma:
    image: prismagraphql/prisma:1.15
    networks:
      - denormalizer-api
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: prisma #todo: replace with credential
            password: prisma #todo: replace with credential
            migrations: true
    deploy:
      mode: replicated
      placement:
        constraints:
          - node.role == worker
      resources:
        reservations:
          memory: 128M
        limits:
          memory: 256M
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.port=4466
        - com.df.serviceDomain=${SERVICE_DOMAIN:-localhost}
        - com.df.alertName=memlimit
        - com.df.alertIf=@service_mem_limit_nobuff:0.9
        - com.df.alertFor=30s

  postgres:
    image: postgres
    restart: always
    networks:
      - denormalizer-api
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: prisma #todo: replace with credential
      POSTGRES_PASSWORD: prisma #todo: replace with credential
    volumes:
      - postgres_db:/var/lib/postgresql/data

volumes:

  postgres_db:
    driver: cloudstor:aws
    driver_opts:
      ebstype: gp2
      size: 250
      backing: relocatable
    external: false


networks:

  denormalizer-api:
    external: true
```

**Expected behavior**

I'd expect the prisma service to spin up, detect the postgres database, create a database within it, populate it with tables and carry on its way. 

**Screenshots**

None needed. See above text sections. 

**Versions (please complete the following information):**

- prisma:1.15 docker image
- postgres docker image
