### ISSUE TITLE
CLI not handling errors in post-deploy

### ISSUE THREAD

**Issue by alizhdanov** [prisma/prisma#3257]
**Describe the bug**
My post-deploy looks like this:
```yml
hooks:
  post-deploy:
    - echo "Deployment finished"
    - graphql get-schema --project database
    - graphql codegen
```

This is what I see in the terminal:
![screen shot 2018-10-05 at 16 26 28](https://user-images.githubusercontent.com/14041032/46541144-81632c80-c8bb-11e8-9059-beffc2c8f1c8.png)

The issue is, that it is always succesful. For instance `graphql get-schema --project database` was returning an exception, but prisma deploy not breaking on this exception. But continuing and showing green check marks. 

**Expected behavior**
It'd exit with the error from the command.

**Versions (please complete the following information):**
 - OS: `OS X High Sierra`
 - `prisma` CLI: `prisma/1.17.1 (darwin-x64) node-v8.11.1`
 - `graphql-cli` - 2.16.7
