### ISSUE TITLE
Can I do 'all the way' docker development meaning the nodejs app also in docker-compose?

### ISSUE THREAD

**Issue by goldenbearkin** [prisma/prisma#3343]
Here is my docker-compose file for local development
```yml
version: "3"
services:
  app:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules/
  prisma:
    image: prismagraphql/prisma:1.18
    restart: always
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: prisma
            password: prisma
            migrations: true
  postgres:
    image: postgres:10.5
    restart: always
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  ? postgres
```
In the prisma.yml file, I have 
```yml
endpoint: http://localhost:4466
datamodel: datamodel.prisma
```
when I run prisma deploy, I want the endpoint to be  http://localhost:4466.

However, I want the nodejs app to point to http://prisma:4466 since it is run inside docker.

Can I do that? or it needs a feature request?

**Comment by thanatchakromsang** [comment]
I think you can do that, here is my stack with graphql yoga
```yaml
version: "3.3"
services:
  prisma:
    image: prismagraphql/prisma:1.18
    ports:
      - "4466:4466"
    restart: always
    environment:
      PRISMA_CONFIG: |
        port: 4466
        managementApiSecret: hello
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: prisma
            password: prisma
            migrations: true

  postgres:
    image: postgres:10.5
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - database:/var/lib/postgresql/data

  app:
    build:
      context: ./app
      dockerfile: Dockerfile.local
    ports:
      - "4000:4000"
    restart: always
    depends_on:
      - prisma
    volumes:
      - ./senator:/usr/src/app
    environment:
      - HOME=/usr/src/app
      - NODE_ENV=development

volumes:
  ? database
```
