### ISSUE TITLE
`graphql-schema` generator should output a single file

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma#3359]
The built-in generator for `graphql-schema` in the Prisma CLI should output a single file instead of a directory. 

Currently it's configured as follows:

```yml
generate:
    - generator: graphql-schema
      output: ./generated/prisma/
```

Instead, `output` should simply specify the name of a single file:

```yml
generate:
    - generator: graphql-schema
      output: ./generated/prisma.graphql
```
