### ISSUE TITLE
Using Lando for docker creation

### ISSUE THREAD

**Issue by cloudsociety** [prisma/prisma#3386]
I am trying to run Prisma from within a Lando set-up (which is a wrapper for Docker). I have a working `.lando.yml` file except my logs show that the Prisma endpoint doesn't exist. I think this is because Lando is trying to mount the working directory to `/app` — which Prisma has already populated — leading to it being overwritten.

Here's my Lando file: 

```
# The name of my app
name: prisma

# Use the lando proxy to map to the custom service
proxy:
  prisma:
    - prisma.lndo.site
  postgres:
    - postgres.lndo.site

services:
  prisma:
    type: compose
    services:
      image: prismagraphql/prisma:1.18
      command: ["/bin/sh", "-c", "/app/start.sh"]
      restart: always
      ports:
      - "4466:4466"
      environment:
        PRISMA_CONFIG: |
          port: 4466
          databases:
            default:
              connector: postgres
              host: postgres.lndo.site
              port: '5432'
              database: prismadb
              user: prismadb
              password: prismadb
              migrations: true
  node:
    type: node
    globals:
      prisma: "latest"
  postgres:
    type: postgres:10.1
    portforward: 5432
    creds:
      user: prismadb
      password: prismadb
      database: prismadb
tooling:
  npm:
    service: node
  node:
    service: node
  yarn:
    service: node
  prisma:
    service: node
```

`lando logs` shoes this message for the Prisma container:

```
prisma_1    | user-perms.sh kicking off as user uid=0(root) gid=0(root) groups=0(root),1(bin),2(daemon),3(sys),4(adm),6(disk),10(wheel),11(floppy),20(dialout),26(tape),27(video)
prisma_1    | Lando ENVVARS set at
prisma_1    | LANDO_WEBROOT_USER: www-data
prisma_1    | LANDO_WEBROOT_GROUP: www-data
prisma_1    | LANDO_WEBROOT_UID: 33
prisma_1    | LANDO_WEBROOT_GID: 33
prisma_1    | Making sure correct user:group (www-data:www-data) exists...
prisma_1    | /helpers/user-perms.sh: line 91: groupadd: not found
prisma_1    | /helpers/user-perms.sh: line 91: useradd: not found
prisma_1    | id: unknown user www-data
prisma_1    | /helpers/user-perms.sh: line 91: chsh: not found
prisma_1    | And here. we. go.
prisma_1    | chown: unknown user/group www-data:www-data
prisma_1    | chown: unknown user/group www-data:www-data
prisma_1    | chown: unknown user/group www-data:www-data
prisma_1    | Scanning /user/.ssh for keys...
prisma_1    | chown: unknown user/group www-data:www-data
prisma_1    | Running command /bin/sh -c /app/start.sh
prisma_1    | /bin/sh: /app/start.sh: not found
prisma_1    | Terminated
```

And `lando ssh prisma` gives this message:

```
unable to find user www-data: no matching entries in passwd file
error: unable to find user www-data: no matching entries in passwd file
```

Again, I think it's because Prisma is being overwritten. SSHing into Prisma as root and listing `/app` only shows my working files.

Any help or suggestions on how to make it work would be appreciated.
