### ISSUE TITLE
Prisma deploy is not generating a prisma.graphql file

### ISSUE THREAD

**Issue by pacifio** [prisma/prisma#3469]
I have initiated a project using prisma-cli . It has provided me with a <strong>datamodel.prisma</strong> file which I changed to <strong>datamodel.graphql</strong> file but after deploying the project it won't give me a generated <strong>prisma.graphql</strong> file .

<strong>My prisma.yml file</strong>
```yml
endpoint: "my_valid_prisma_endpoint"
datamodel: datamodel.graphql

hooks:
  post-deploy:
    - graphql get-schema -p database
    - graphql codegen
```
<strong>My datamodel.graphql file</strong>
```graphql
type User {
  id: ID! @unique
  name: String!
  email: String!
  firstName: String
  lastName: String
  password: String
}
```

<strong>My .graphqlconfig.yml file</strong>
```yml
projects:
  main:
    schemaPath: "lib/schema.graphql"
    extensions:
      endpoints:
        default: "http://localhost:8000"
  database:
    schemaPath: "src/prisma.graphql"
    extensions:
      prisma: prisma.yml

```

I should get a <strong>prisma.graphql</strong> file generated under the <strong>src</strong> folder but I am not getting .
<strong>Note that : </strong> when I initiated the project I did not generate anything . I choose the <strong>Don't generate</strong> option . But how can I get the expected <strong>prisma.graphql </strong> file ?? :thinking: :thinking: :thinking:

**Comment by timsuchanek** [comment]
Thanks for asking @pacifio !
Renaming the `datamodel.prisma` to `datamodel.graphql` is totally fine and legit.

The "new" way of getting the schema is using the following `prisma.yml` file:

```yaml
endpoint: "my_valid_prisma_endpoint"
datamodel: datamodel.graphql

generate:
  - generater: graphql-schema
    output: ./src/generated/
```

It will create the file `./src/generated/prisma.graphql` for you, including the API Schema.

Let me know if this solved your problem. If not, I can reopen this issue :)

**Comment by pacifio** [comment]
It's not working @timsuchanek

**Comment by pacifio** [comment]
I added the following ...
```yml
...
generate:
  - generater: graphql-schema
    output: ./src/generated/
...
```

**Comment by timsuchanek** [comment]
Thanks @pacifio ! When you execute `prisma -v` -  which version is shown? The latest version is `1.20.5`

**Comment by kyleshevlin** [comment]
I stumbled on this issue because I had a similar difficulty. I noticed you had a typo @pacifio, you wrote "generater" instead of "generator". Might want to fix that and try it again.

**Comment by andrewowen** [comment]
I am also running into this issue when attempting to generate a schema file. The script completes fine, but no file is generated. I followed everything mentioned above. Here is my `prisma.yml` and `datamodel.prisma`

```yml
endpoint: ${env:PRISMA_ENDPOINT}
datamodel: datamodel.prisma

generate:
  - generator: graphql-schema
    output: ./src/generated/
```
```graphql
type Deck {
  id: ID! @unique
  deckName: String!
  deckCommander: String!
  elo: Float!
  rank: Int!
  totalGames: Int!
  gamesWon: Int!
  gamesLost: Int!
  winPercentage: Float!
  createdAt: DateTime!
  updatedAt: DateTime!
}
```

**Comment by vaunus** [comment]
Came across this as well and managed to get it working. You still need the post deploy hook in your config or else it won't work. My full `prisma.yml` is as follows:

```
endpoint: "my_valid_prisma_endpoint"
datamodel: datamodel.prisma

generate:
  - generator: graphql-schema
    output: ../generated/prisma
  - generator: javascript-client
    output: ../generated/prisma
 
hooks:
  post-deploy:
    - prisma generate
```

**Comment by GreggSquire** [comment]
@andrewowen  - I followed all of the advice here, and I can't get mine to work either.  I am on v 1.22.2 What version did you revert back to? How did you revert back? Thanks in advance.

**Comment by rostgoat** [comment]
this worked for me

```
endpoint: ${env:PRISMA_ENDPOINT}
datamodel: datamodel.prisma
# secret: ${env:PRISMA_SECRET}

generate:
  - generator: graphql-schema
    output: ./src/generated/

hooks:
  post-deploy:
    - graphql get-schema -p prisma
    - prisma generate
```

**Comment by khamwas** [comment]
Thank the gods.

I run into so many problems when I use walk throughs with deprecated code. 
(shame on me)
But i've been on this for a solid 2 hours. 

Thank you

worked for me

endpoint: ${env:PRISMA_ENDPOINT}
datamodel: datamodel.prisma
# secret: ${env:PRISMA_SECRET}
generate:
  - generator: graphql-schema
    output: ./src/generated

hooks:
  post-deploy:
    - prisma generate

**Comment by jakerainis** [comment]
Thank you so much for this. I was pulling my hair out.

**Comment by balabukha** [comment]
So, if you have a warning like:

>  ▸    Error: output for generator graphql-schema should be a .graphql-file.
>  ▸    Please change the output property for this generator in prisma.yml

Just create a file `/src/generated/prisma.graphql`
Thanks work for me!

**Comment by jonmajorc** [comment]
@balabukha I did something similar, but I did it by explicitly adding the file name in the yaml

```yml
generate:
  - generator: javascript-client
    output: ../src/generated/prisma-client
  - generator: graphql-schema
    output: ../src/generated/schema.graphql # <--schema.graphql
```
You may want to eplicitly add it too. That way if it ever gets deleted your post-deploy hook can recreate it for you 😃
