### ISSUE TITLE
"GraphQL Error" happening on `prismagraphql/prisma:1.22-alpha` with Prisma client

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma#3570]
This is a pretty weird issue happening when running the `1.22-alpha` of a Prisma server, however the problem only seems to be located in the Prisma client 🤔 Here's my observations.

I'm running a Prisma server based on Timescale DB: 

```yml
version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.22-alpha
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: prisma
            password: prisma
            migrations: true
            rawAccess: true
  postgres:
    image: timescale/timescaledb
    restart: always
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
```

My datamodel and `prisma.yml` are simple:

`datamodel.prisma`

```graphql
type User {
  id: ID! @unique
  name: String!
}
```

`prisma.yml`

```yml
endpoint: http://localhost:4466
datamodel: datamodel.prisma

generate:
  - generator: javascript-client
    output: ./generated/prisma-client/
```

> This uses the `javascript-client`, but the same observations were made with the `typescript-client`.

Now I run `prisma generate` and have my client available in `generated/prisma-client`.

Here's the simple script I'm using for testing:

```js
const { Prisma } = require('./prisma-client')

const prisma = new Prisma({
  endpoint: "http://localhost:4466",
  debug: true
})

async function main() {
  await prisma.createUser({
    name: "Nikoooooo"
  })

  const users = await prisma.users()
  console.log(users)
}

main().catch(x => console.error(x))
```

> This was first tried by directly importing the `prisma` instance instead of the `Prisma` constructor, same observations.

Running the script yields the following error:

```
{ Error: GraphQL Error: {
  "0": {
    "data": {
      "createUser": {
        "id": "cjor1zkwe000k0956664m6k0b",
        "name": "Alice"
      }
    }
  },
  "status": 200
}
    at BatchedGraphQLClient.<anonymous> (/Users/nikolasburk/Desktop/timescale/tsdb-example/node_modules/http-link-dataloader/dist/src/BatchedGraphQLClient.js:77:35)
    at step (/Users/nikolasburk/Desktop/timescale/tsdb-example/node_modules/http-link-dataloader/dist/src/BatchedGraphQLClient.js:40:23)
    at Object.next (/Users/nikolasburk/Desktop/timescale/tsdb-example/node_modules/http-link-dataloader/dist/src/BatchedGraphQLClient.js:21:53)
    at fulfilled (/Users/nikolasburk/Desktop/timescale/tsdb-example/node_modules/http-link-dataloader/dist/src/BatchedGraphQLClient.js:12:58)
    at process._tickCallback (internal/process/next_tick.js:68:7) result: { '0': { data: [Object] }, status: 200 } }
```

More observations:

- The user was created in the DB (can be fetched in the Playground)
- The mutation and variables sent to the Prisma API by the client look correct, here's the output from the `debug` flag:
    ```
    Query:
    mutation ($data: UserCreateInput!) {
      createUser(data: $data) {
        id
        name
      }
    }

    Variables:
    {"data":{"name":"Nikoooooo"}}
    ```

This only happens when using the `prisma:1.22-alpha` Docker image - using the current `1.20` version everything works without errors.
