### ISSUE TITLE
$connect doesn't actually connect, the first query does

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma#3649]
## Bug description

`$connect` doesn't create a database connection, the first query from the client does that. 

## How to reproduce

1. Run this docker-compose file. It is postgres with existing data and only 1 max connection

```yml
version: '3'
services:
  postgres:
    image: divyenduz/postgres-with-data:0.0.2
    command: postgres -c 'max_connections=1' -c 'superuser_reserved_connections=0'
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
```

2. Create the following Prisma schema and generate a client

```prisma
datasource ds {
  provider = "postgresql"
  url      = "postgresql://root:prisma@localhost:5432/basic-blog?schema=public"
}

generator client {
  provider = "prisma-client-js"
}

model blogs {
  id        Int    @default(autoincrement()) @id
  name      String
  viewcount Int
}
```

3. Run the following script
```js
const { PrismaClient } = require('@prisma/client')

async function main() {
  const client1 = new PrismaClient()
  console.log(`Client 1 before connect`)
  await client1.$connect()
  console.log(`Client 1 after connect`)
  console.log(`Client 1 before query`)
  console.log(await client1.blogs.findMany())
  console.log(`Client 1 after query`)

  const client2 = new PrismaClient()
  console.log(`Client 2 before connect`)
  await client2.$connect()
  console.log(`Client 2 after connect`)
  console.log(`Client 2 before query`)
  console.log(await client2.blogs.findMany())
  console.log(`Client 2 after query`)
}

main()
```

4. Observe that the logs are
```
Client 1 before connect
Client 1 after connect
Client 1 before query
[]
Client 1 after query
Client 2 before connect
Client 2 after connect
Client 2 before query
(node:39934) UnhandledPromiseRejectionWarning: Error:
Invalid `prisma.blogs.findMany()` invocation in
/Users/divyendusingh/Documents/prisma/triage/connect/index.js:17:35


  Error in connector: Error querying the database: db error: FATAL: sorry, too many clients already
```

However, after connect should never be printed, since max_connections is 1 and this is the 2nd connection, it should immediately fail.

## Expected behavior

Client should fail at the `$connect`, not when first query is run through a client. 

## Prisma information

```
divyendusingh [connect]$ yarn prisma --version                                                                                              130 ↵
yarn run v1.22.4
$ /Users/divyendusingh/Documents/prisma/triage/connect/node_modules/.bin/prisma --version
@prisma/cli          : 2.7.0-dev.72
Current platform     : darwin
Query Engine         : query-engine a6a6ecba74cbaeee0756c312b1b0f2502b27e49c (at node_modules/@prisma/cli/query-engine-darwin)
Migration Engine     : migration-engine-cli a6a6ecba74cbaeee0756c312b1b0f2502b27e49c (at node_modules/@prisma/cli/migration-engine-darwin)
Introspection Engine : introspection-core a6a6ecba74cbaeee0756c312b1b0f2502b27e49c (at node_modules/@prisma/cli/introspection-engine-darwin)
Format Binary        : prisma-fmt a6a6ecba74cbaeee0756c312b1b0f2502b27e49c (at node_modules/@prisma/cli/prisma-fmt-darwin)
Studio               : 0.286.0
✨  Done in 1.93s.

```
