### ISSUE TITLE
How to set database in prisma mysql?

### ISSUE THREAD

**Issue by dooboolab** [prisma/prisma#3664]
Hi. I am new to Prisma and today I've got to access mysql with graphql with prisma.

I want to set my database for prisma manually but `database` attribute doesn't seem to work.
I've set my prisma `env` like  below
```
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: secret
        databases:
          default:
            database: talktalk
            connector: mysql
```

However when I tried the insert, the table mutates in `default@default` database instead of my `talktalk` database.
![Alt desc](https://www.prisma.io/forum/uploads/default/original/2X/1/1abbdff1d197ef2f2a2044593bb244629dd7d2b2.png)

How can I change the database name that is used in prisma docker-compose?

**Comment by pantharshit00** [comment]
Hi,

We use `default@default` naming schema as to support multiple services and stages. This allows us to share the database with multiple services and stages. The stage and scheme are defined in your endpoint, for example, `http://localhost:4666/service/stage`. If there is nothing it fallbacks to `default@default`.

The data do indeed getting into `talktalk` DB but we create those name odd looking name to support multiple services.

**Comment by dooboolab** [comment]
Ok so it is better not to change the database name currently. Thanks for the confirm.

**Comment by soullivaneuh** [comment]
Maybe the behavior change since this issue, but FYI, you can know change the database name:

```
  prisma:
    image: prismagraphql/prisma:1.34
    restart: unless-stopped
    depends_on:
      - mysql
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            database: custom_name
            connector: mysql
            host: mysql
            port: 3306
            user: root
            password: prisma
```
