### ISSUE TITLE
Cluster secret in .env does not match cluster local

### ISSUE THREAD

**Issue by ivorpad** [prisma/prisma#3696]
**Describe the bug**

I know this has been reported multiple times but after reading/experimenting quite a bit I can't get over it.

After doing `prisma deploy` I get the error: 

`Cluster secret in env var PRISMA_MANAGEMENT_API_SECRET does not match for cluster local`

Here's my `docker-compose.yml`

```yml
version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.22
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        managementApiSecret: my-secret
        databases:
          default:
            connector: mysql
            host: mysql
            port: 3306
            user: root
            password: prisma
            migrations: true
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: prisma
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql:
```

And my `.env` file:

`PRISMA_MANAGEMENT_API_SECRET=my-secret`

I tried adding this to `~/.prisma/config.yml` to no avail:

```yml
cloudSessionKey: >-
  [redacted]
clusters: 
  local:
    host: 'http://localhost:4466'
    clusterSecret: "my-secret"
```

**Expected behavior**

The server should be deployed correctly.

* I'm using Prisma CLI v1.22.2
* I ran `prisma account` and I'm logged in
