### ISSUE TITLE
[mongodb] cannot query with relational fields  (link: INLINE)

### ISSUE THREAD

**Issue by beeplin** [prisma/prisma#3713]
**Describe the bug**
Cannot query multiple records with relational fields in the `where` condition

**To Reproduce**

1. `docker-compose.yml` (copied from 1.22 docs, unchanged): 

```yml
version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.22
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: mongo
            uri: mongodb://prisma:prisma@mongo
  mongo:
    image: mongo:3.6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: prisma
      MONGO_INITDB_ROOT_PASSWORD: prisma
    ports:
      - "27017:27017"
    volumes:
      - mongo:/var/lib/mongo
volumes:
  mongo:
```

2. `datamodel.graphql`: (a simplified version from the 1.22 docs)

```graphql
type User {
  id: ID! @id
  name: String!
  posts: [Post!]! @relation(link: INLINE)
}

type Post {
  id: ID! @id
  title: String!
  author: User
}
```

3.  check prisma's playground via port 4466:

![image](https://user-images.githubusercontent.com/13058150/50051609-e3a89b00-0150-11e9-9604-04355e22b122.png)

In the `where` condition of the `users` query, only `id` and `name` related conditions are allowed. **We cannot query users by posts, which makes the new mongodb connector basically useless.**

**Expected behavior**
In the postgres connector, relational fields can be used in `where` queries.

**Versions (please complete the following information):**
 - OS: Windows 10
 - `prisma` CLI 1.22
 - Prisma Server: 1.22
