### ISSUE TITLE
`prisma introspect` does not work for MongoDB

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma#3751]
When running the `prisma introspect` command, I am always getting this error: `ERROR: Project not found: 'default_default'`

Here's what I did:

1. Kill and remove all Docker containers
2. Create new Docker Compose file:
    ```yml
    version: '3'
    services:
      prisma:
        image: prismagraphql/prisma:1.23
        restart: always
        ports:
        - "4466:4466"
        environment:
          PRISMA_CONFIG: |
            port: 4466
            databases:
              default:
                connector: mongo
                uri: mongodb+srv://Admin:asd@cluster0-sapwg.mongodb.net/test?retryWrites=true
                database: testdb
    ```
3. Run `docker-compose up -d`
4. Create `prisma.yml` and add `endpoint: http://localhost:4466` to it
5. Run:
    ```
    prisma introspect \
      --mongo-uri "mongodb+srv://Admin:asd@cluster0-sapwg.mongodb.net/test?retryWrites=true" \
      --mongo-db testdb
    ```

The CLI now throws this error:

```
$ prisma introspect \
                    --mongo-uri "mongodb+srv://Admin:asd@cluster0-sapwg.mongodb.net/test?retryWrites=true" \
                    --mongo-db testdb

ERROR: Project not found: 'default_default'

{
  "errors": [
    {
      "message": "Project not found: 'default_default'",
      "code": 3016,
      "requestId": "local:cjpwohq5b00000939vm45rf67"
    }
  ],
  "status": 200
}

Get in touch if you need help: https://www.prisma.io/forum/
To get more detailed output, run $ set -x DEBUG "*"
```

Removing the `endpoint` from `prisma.yml` and rerunning the same command leads to this error:

```
$ prisma introspect \
                    --mongo-uri "mongodb+srv://Admin:asd@cluster0-sapwg.mongodb.net/test?retryWrites=true" \
                    --mongo-db testdb
 ▸    Cannot read property 'custom' of null

Get in touch if you need help: https://www.prisma.io/forum/
To get more detailed output, run $ set -x DEBUG "*"
```
