### ISSUE TITLE
Instructions for "Existing database" don't work, error code 3016

### ISSUE THREAD

**Issue by AndrewRayCode** [prisma/prisma#3818]
`docker-compose.yml`:

```yaml
  prisma:
    image: prismagraphql/prisma:1.23
    restart: always
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: host.docker.internal
            port: 5431
            database: mydb
            schema: public
            user: myuser
            password: mypass
            migrations: false
            ssl: false
```

Note I can connect to the db fine:

```bash
psql -h localhost -p 5431 -U myuser mydb
```

Following the instructions

```bash
$ brew tap prisma/prisma
$ brew install prisma
```
It ran fine...
```bash
$ docker-compose up -d
$ docker ps
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS              PORTS                              NAMES
38c8788d07be        prismagraphql/prisma:1.23   "/bin/sh -c /app/sta…"   11 minutes ago      Up 11 minutes       0.0.0.0:4466->4466/tcp             myproject-2_prisma_1

$ docker logs 38c8788d07be
...
Deployment worker initialization complete.
Version is up to date.
```

I can hit `4466` and have it in `prisma.yml`:
```yaml
endpoint: http://localhost:4466
```

And then kablooie 💥 
```bash
 $ prisma introspect


ERROR: Project not found: 'default$default'

{
  "errors": [
    {
      "message": "Project not found: 'default$default'",
      "code": 3016,
      "requestId": "local:cjqnew5uh00050741sxocl2tz"
    }
  ],
  "status": 200
}
```

I've tried googling for that error but didn't find anything.

**Versions**
 - OSX
 - `prisma` prisma/1.17.0-alpha.2 (darwin-x64) node-v10.4.1

Also, since I installed prisma via homebrew, why do I get the message "update available" to install a global version of prisma? "npm i -g prisma"
