### ISSUE TITLE
Importing with `createdAt` system field not working

### ISSUE THREAD

**Issue by andruxnet** [prisma/prisma#3856]
I'm trying to import some data where the `createdAt` field is needed for several of my app's features.

I found [this section](https://www.prisma.io/docs/reference/service-configuration/data-modelling-(sdl)-eiroozae8u#system-fields) in the docs where it says modifying that field should be possible when importing data, however, when I run `prisma seed` it tells me that `Field 'createdAt' is not defined in the input type 'UserCreateInput'.`.

Here's the section mentioned above:
> The values of these fields are currently read-only in the GraphQL API (except when importing data) but will be made configurable in the future.

This is my current setup:

```
# prisma.yml
endpoint: ${env:PRISMA_ENDPOINT}
datamodel: datamodel.graphql
secret: ${env:PRISMA_SECRET}
seed:
  import: ./src/seed.graphql
hooks:
  post-deploy:
  - graphql get-schema -p prisma
```

```
# seed.graphql
mutation {
  createUser(
    data: {
      email: "me@email.com"
      createdAt: "2018-11-21T07:00:00.000Z"
      ...
    }
  )
  {
    id
    email
  }
}
```

Am I missing something here?
