### ISSUE TITLE
No primary found in replicaset or invalid replica set name - MongoDb/Azure Cosmos

### ISSUE THREAD

**Issue by stilren** [prisma/prisma#3883]
**Describe the bug**
Connection to database error: "no primary found in replicaset or invalid replica set name"

**To Reproduce**
1. Create a new "Azure Cosmos Db for MongoDb API"
2. Run Prisma Init Hello-World
3. Choose Existing DB -> No data
4. Add connection string provided by Azure (mongodb://dbname:secret==@dbname.documents.azure.com:10255/?ssl=true&replicaSet=globaldb"

**Expected behavior**
Connection succeeds

**Comment by pantharshit00** [comment]
Hi,

There is a bug in the onboarding workflow so can you please you the getting start guide for an existing database for now. https://www.prisma.io/docs/get-started/01-setting-up-prisma-existing-database-JAVASCRIPT-a003/

**Comment by stilren** [comment]
@pantharshit00 - I got the same error: "no primary found in replicaset or invalid replica set name"

**Comment by pantharshit00** [comment]
Hi @stilren 

Can you try this again in the newer version of prisma?

**Comment by JacksonS918** [comment]
Using prisma v1.28.3. Bug still exists.

Output:

`MongoError: no primary found in replicaset or invalid replica set name
    at /usr/lib/node_modules/prisma/node_modules/mongodb-core/lib/topologies/replset.js:636:11
    at Server.<anonymous> (/usr/lib/node_modules/prisma/node_modules/mongodb-core/lib/topologies/replset.js:357:9)
    at Object.onceWrapper (events.js:277:13)
    at Server.emit (events.js:189:13)
    at Server.EventEmitter.emit (domain.js:459:23)
    at /usr/lib/node_modules/prisma/node_modules/mongodb-core/lib/topologies/server.js:508:16
    at /usr/lib/node_modules/prisma/node_modules/mongodb-core/lib/connection/pool.js:532:18
    at process._tickCallback (internal/process/next_tick.js:61:11)
`

**Comment by pantharshit00** [comment]
Hi @JacksonS918 

Can you please provide a small reproduction of the issue? That way we can triage this and fix the issue.

Also, please make sure you are using the connection string that is pointing to the admin db

**Comment by JacksonS918** [comment]
1. Brand new install of node-v10.15.3, prisma-v1.28.3 installed via npm. Running on Ubuntu WSL LTS 18.04.
2. Ran `prisma init hello-world`
3. Selected "Use existing database"
4. Selected "MongoDB"
5. Entered connection string in the format `"mongodb://username:password@dbname.documents.azure.com:10255/?ssl=true&replicaSet=globaldb"`
6. Selected "No: set up without existing data"
7. Received error: `no primary found in replicaset or invalid replica set name`

I did that on Windows as with in PowerShell, and the same result happened.

**Comment by pantharshit00** [comment]
Hi all,

I tried to connect to a cosmos DB instance and the CLI workflow is broken currently(see #4302 ) but if you create the files manually it is working fine(Just create using a new database template from the CLI and copy paste the docker-compose file given below)

See it is working fine: 

![image](https://user-images.githubusercontent.com/22195362/55484029-604e7f00-5645-11e9-997f-eaa7ffb15ea1.png)

![image](https://user-images.githubusercontent.com/22195362/55483751-e3230a00-5644-11e9-960f-03a1b3e0c1d2.png)

![image](https://user-images.githubusercontent.com/22195362/55484070-72c8b880-5645-11e9-8c56-661a65a4b352.png)


Here is the docker-compose file that I used: 

```yml
version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.29
    restart: always
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: mongo
            uri: 'mongodb://test:<password>@test.documents.azure.com:10255/admin?ssl=true'
```

I am going to close this now as a connection to cosmos is working fine. Feel free reach out if you are having some trouble
