### ISSUE TITLE
unable to verify the first certificate

### ISSUE THREAD

**Issue by Gujie-Novade** [prisma/prisma#3929]
**Describe the bug**
Cannot use `prisma deploy` to update a remote server. The error message is:
`environment FetchError: request to https://myserver/management failed, reason: unable to verify the first certificate`

**To Reproduce**
1. Setup an Ubuntu VM 16.04
2. Setup nginx as a reverse proxy to redirect traffic to prisma server (see config file) 
3. Setup prisma server following the tuto 1.25 for Mongodb with docker
4. On your local machine, create datamodel.prisma and prisma.yml
5. Run `prisma deploy`

**Expected behavior**
I was expecting prisma to deploy the schema on the remote server

**Versions (please complete the following information):**
 - Connector: MongoDB
 - Prisma Server: 1.25.0
 - `prisma` CLI: [e.g. `prisma/1.25.3 node-v10.4.0`]
 - OS: Windows 10

**Additional context**
I checked the management endpoint was ok by going to https://myserver/management on my browser.
It may be related to [#2852](https://github.com/prisma/prisma/issues/2852)

/etc/nginx/sites-enabled/default (on Ubuntu 16.04)
```
server {
        # SSL configuration
        listen 443 ssl default_server;
        listen [::]:443 ssl default_server;
        ssl_certificate /etc/nginx/ssl/cert.crt;
        ssl_certificate_key /etc/nginx/ssl/certPrivate.rsa;

        server_name myserver;

        # Prisma Server
        location / {
                proxy_pass http://localhost:4466;
        }
}
```

prisma.yml (on Windows 10)
```
# The HTTP endpoint for your Prisma API
endpoint: https://myserver/myservice/dev

# Points to the file that contains your datamodel
datamodel: datamodel.prisma

# Specifies language & location for the generated Prisma client
generate:
  - generator: javascript-client
    output: ../src/generated/prisma-client
```
