### ISSUE TITLE
Workspace does not exist

### ISSUE THREAD

**Issue by Fh-abeyer** [prisma/prisma#3944]
**Describe the bug**
On prisma deploy I get the following message
```
ERROR: Workspace alex-beyer does not exist

{
  "data": {
    "generateClusterToken": null
  },
  "errors": [
    {
      "message": "Workspace alex-beyer does not exist",
      "locations": [
        {
          "line": 3,
          "column": 9
        }
      ],
      "path": [
        "generateClusterToken"
      ],
      "code": 222
    }
  ],
  "status": 200
}
```

**To Reproduce**
1. Run prisma deploy

**Expected behavior**
I expect the prisma generation to happen.

**Versions (please complete the following information):**
 - Connector: prisma demo server
 - Prisma Server: [e.g. `1.25.4`]
 - `prisma` CLI: [e.g. `prisma/1.25.4 (windows-x64) node-v8.11.2`]
 - OS: [`Windows 10`] 

**Additional context**
prisma.yml file

```
# The HTTP endpoint for your Prisma API
#endpoint: ''
endpoint: https://us1.prisma.sh/alex-beyer/api/dev


# Points to the file that contains your datamodel
datamodel: datamodel.prisma

# Specifies language & location for the generated Prisma client
generate:
  - generator: javascript-client
    output: ../src/generated/prisma-client

hooks:
  post-deploy:
    - prisma generate
```
I have even logged into the prisma console to see that its running and it is. Copied the link and still says it doesnt exist
