### ISSUE TITLE
Issue with `connect` on latest dev

### ISSUE THREAD

**Issue by thebiglabasky** [prisma/prisma#4026]
## Bug description

Using the following schema:
```
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["connectOrCreate", "transactionApi", "microsoftSqlServer"]
}

datasource db {
  provider = "sqlserver"
  url      = env("DATABASE_URL")
}

model User {
  id          Int                @id @default(autoincrement())
  email       String             @unique
  courses     CourseEnrollment[]
}
model Course {
  id            Int                @id @default(autoincrement())
  name          String
  courseDetails String?
  members       CourseEnrollment[]
}
model CourseEnrollment {
  userId    Int
  courseId  Int
  role      String
  course    Course   @relation(fields: [courseId], references: [id])
  user      User     @relation(fields: [userId], references: [id])
  @@id([userId, courseId])
}
```

The following code doesn't work:
```
const course = await prisma.course.create({
  data: {
    name: `test-course-1`,
    courseDetails: `test-course-1-details`,
    members: {
      create: [
        {
          role: 'TEACHER',
          user: {
            connect: {
              id: 1,
            },
          },
        }
      ],
    }
  }
})
```

It complains that connecting on `id` isn't allowed and only proposes `email`.

Version I'm using:

```
    "@prisma/client": "^2.10.0-dev.54"
    "@prisma/cli": "^2.10.0-dev.54",
```

## Expected behavior

The connect should allow connecting on `id` and not only on `email`.

## Environment & setup

- OS: MacOSX
- Database: MSSQL, local docker instance.

docker-compose.yml:
```
version: "3"
services:
  mssql-2019:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: "<YourStrong@Passw0rd>"
    ports:
      - "1433:1433"
    networks:
      - databases
networks:
  databases:
```

- Node.js version: v13.14.0
- Prisma version: 
```
@prisma/cli          : 2.10.0-dev.54
@prisma/client       : 2.10.0-dev.54
Current platform     : darwin
Query Engine         : query-engine 77abecc4840127ebdcc02b83ee1e2c9cc27009f2 (at node_modules/@prisma/cli/query-engine-darwin)
Migration Engine     : migration-engine-cli 77abecc4840127ebdcc02b83ee1e2c9cc27009f2 (at node_modules/@prisma/cli/migration-engine-darwin)
Introspection Engine : introspection-core 77abecc4840127ebdcc02b83ee1e2c9cc27009f2 (at node_modules/@prisma/cli/introspection-engine-darwin)
Format Binary        : prisma-fmt 77abecc4840127ebdcc02b83ee1e2c9cc27009f2 (at node_modules/@prisma/cli/prisma-fmt-darwin)
Studio               : 0.296.0
Preview Features     : connectOrCreate, transactionApi, microsoftSqlServer
```
