### ISSUE TITLE
Improve CLI wording

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma#4041]
The CLI wording can be improved.

- [x] The `prisma` command prints `GraphQL Database Gateway` as a description for Prisma. Instead it should print `Prisma replaces traditional ORMs`

**Comment by nikolasburk** [comment]
The CLI outputs should consistently uses colors when they reference:

- properties from prisma.yml
- file names
- other code references (URLs, ...)

**Comment by nikolasburk** [comment]
- [ ] Adjust wording from Demo server to also include Demo database

**Comment by nikolasburk** [comment]
- [ ] The generated `docker-compose.yml` from running `prisma init` should have an additional commented line with an explanatory comment on the database container configuration that maps the port, e.g. for Postgres:

```yml
version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.30-alpha
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # Uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        prototype: true
        databases:
          default:
            connector: postgres
            host: postgres
            user: prisma
            password: prisma
            port: 5432
  postgres:
    image: postgres
    restart: always
    # Uncomment the next line to connect to your your database from outside the Docker environment, e.g. using a database GUI like Postico
    # ports:
    # - "5432:5432"
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
```

Note that `Uncomment` should be uppercased in both comments.
