### ISSUE TITLE
Pagination with `after` causes internal server error

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma#4145]
This is my Docker Compose file I used to locally launch a Prisma server + DB:

```yml
version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.27
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: mysql
            host: mysql
            port: 3306
            user: root
            password: prisma
            migrations: true
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: prisma
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql:
```

My `prisma.yml`:

```
# Specifies the HTTP endpoint of your Prisma API.
#endpoint: ''
# endpoint: https://eu1.prisma.sh/nikolas/script/gbfevdwcsad
endpoint: http://localhost:4466/test/dev

# Defines your models, each model is mapped to the database as a table.
datamodel: datamodel.prisma

# Specifies the language and directory for the generated Prisma client.
generate:
  - generator: go-client
    output: ../prisma-client/

# Ensures Prisma client is re-generated after a datamodel change.
hooks:
  post-deploy:
    - prisma generate

# Seeds initial data into the database by running a script.
seed:
  import: ./seed.graphql
```

My `seed.graphql`:

```graphql
mutation {
  ada: createUser(data: {
    name: "Ada"
    email: "ada@prisma.io"
    role: ADMIN
    posts: {
      create: [
        {
          title: "Introducing the Analytical Engine"
        }
        {
          title: "Building General-Purpose Computers"
          published: true
        }
        {
          title: "RESTful APIs Considered Harmful"
        }
        {
          title: "Why Algorithms are Awesome"
          published: true
        }
      ]
    }
  }) {
    id
  }

  grace: createUser(data: {
    name: "Grace"
    email: "grace@prisma.io"
    posts: {
      create: [
        {
          title: "Five Things You Didn't Know About Compilers"
        }
        {
          title: "GraphQL - The Query Language of the Future"
          published: true
        }
        {
          title: "Progamming with English Words"
          published: true
          comments: {
            create: {
              text: "Great work!"
              writtenBy: {
                connect: {
                  email: "ada@prisma.io"
                }
              }
            }
          }
        }
      ]
    }
  }) {
    id
  }

  lynn: createUser(data: {
    name: "Lynn"
    email: "lynn@prisma.io"
    posts: {
      create: [
        {
          title: "Working at Xerox PARC"
        }
        {
          title: "Introduction to VLSI Systems"
          published: true
          comments: {
            create: [
              {
                text: "I love this."
                writtenBy: {
                  connect: {
                    email: "ada@prisma.io"
                  }
                }
              }
              {
                text: "Very interesting!"
                writtenBy: {
                  connect: {
                    email: "grace@prisma.io"
                  }
                }
              }
            ]
          }
        }
      ]
    }
  }) {
    id
  }
}
```

My datamodel:

```graphql
type Post {
  id: ID! @unique
  createdAt: DateTime!
  updatedAt: DateTime!
  title: String!
  published: Boolean! @default(value: "false")
  author: User
  comments: [Comment!]!
}

type User {
  id: ID! @unique
  name: String
  email: String! @unique
  role: Role! @default(value: "USER")
  posts: [Post!]!
  comments: [Comment!]!
}

type Comment {
  id: ID! @unique
  createdAt: DateTime!
  text: String!
  post: Post!
  writtenBy: User!
}

enum Role {
  USER
  ADMIN
}
```

Now the following query in the Playground causes an internal server error:

```graphql
{
  posts(
    first:3,
    after: "cjsyqxwqo000j0982da8cvw7o"
  ) {
    id
    title
  }
}
```

Response:

```json
{
  "data": null,
  "errors": [
    {
      "message": "Whoops. Looks like an internal server error. Search your server logs for request ID: local:cjsyv270h002t0982m8u8qhz2",
      "path": [
        "posts"
      ],
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "requestId": "local:cjsyv270h002t0982m8u8qhz2"
    }
  ]
}
```

Server logs:

```
prisma_1  | {"key":"error/unhandled","requestId":"local:cjsyv270h002t0982m8u8qhz2","clientId":"test@dev","payload":{"exception":"scala.MatchError: (\"test@dev\".\"Post\".\"id\",\"Alias\".\"id\",asc) (of class scala.Tuple3)","query":"{\n  posts(first: 3, after: \"cjsyqxwqo000j0982da8cvw7o\") {\n    id\n    title\n  }\n}\n","variables":"{}","code":"0","stack_trace":"com.prisma.api.connector.jdbc.database.CursorConditionBuilder.buildCursorCondition(CursorConditionBuilder.scala:26)\\n com.prisma.api.connector.jdbc.database.CursorConditionBuilder.buildCursorCondition$(CursorConditionBuilder.scala:16)\\n com.prisma.api.connector.jdbc.database.JdbcActionsBuilder.buildCursorCondition(JdbcActionsBuilder.scala:24)\\n com.prisma.api.connector.jdbc.database.NodeManyQueries.modelQuery(NodeManyQueries.scala:47)\\n com.prisma.api.connector.jdbc.database.NodeManyQueries.getNodes(NodeManyQueries.scala:15)\\n com.prisma.api.connector.jdbc.database.NodeManyQueries.getNodes$(NodeManyQueries.scala:14)\\n com.prisma.api.connector.jdbc.database.JdbcActionsBuilder.getNodes(JdbcActionsBuilder.scala:24)\\n com.prisma.api.connector.jdbc.impl.JdbcDataResolver.getNodes(JdbcDataResolver.scala:59)\\n com.prisma.api.resolver.GetNodesDeferredResolver.resolve(GetNodesDeferredResolver.scala:17)\\n com.prisma.api.resolver.DeferredResolverImpl.$anonfun$resolve$3(DeferredResolverImpl.scala:79)\\n scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:233)\\n scala.collection.immutable.Map$Map1.foreach(Map.scala:125)\\n scala.collection.TraversableLike.map(TraversableLike.scala:233)\\n scala.collection.TraversableLike.map$(TraversableLike.scala:226)\\n scala.collection.AbstractTraversable.map(Traversable.scala:104)\\n com.prisma.api.resolver.DeferredResolverImpl.resolve(DeferredResolverImpl.scala:78)\\n sangria.execution.Resolver.sangria$execution$Resolver$$resolveDeferred(Resolver.scala:766)\\n sangria.execution.Resolver.$anonfun$immediatelyResolveDeferred$2(Resolver.scala:132)\\n sangria.execution.Resolver.$anonfun$immediatelyResolveDeferred$2$adapted(Resolver.scala:132)\\n scala.collection.Iterator.foreach(Iterator.scala:937)\\n scala.collection.Iterator.foreach$(Iterator.scala:937)\\n scala.collection.AbstractIterator.foreach(Iterator.scala:1425)\\n scala.collection.IterableLike.foreach(IterableLike.scala:70)\\n scala.collection.IterableLike.foreach$(IterableLike.scala:69)\\n scala.collection.AbstractIterable.foreach(Iterable.scala:54)\\n sangria.execution.Resolver.$anonfun$immediatelyResolveDeferred$1(Resolver.scala:132)\\n sangria.execution.Resolver.$anonfun$immediatelyResolveDeferred$1$adapted(Resolver.scala:131)\\n scala.util.Success.foreach(Try.scala:249)\\n scala.concurrent.Future.$anonfun$foreach$1$adapted(Future.scala:225)\\n scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)\\n akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)\\n akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)\\n scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)\\n scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)\\n akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)\\n akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)\\n akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:44)\\n akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)\\n akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)\\n akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)\\n akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)","message":"(\"test@dev\".\"Post\".\"id\",\"Alias\".\"id\",asc) (of class scala.Tuple3)"}}
```

Side-note, the post with that provided ID for `after` exists:

![image](https://user-images.githubusercontent.com/4058327/53973499-2733f500-4101-11e9-9425-d80086c3ecd2.png)
