### ISSUE TITLE
Unable to deploy prisma for existing psql database with foreign key relations

### ISSUE THREAD

**Issue by jwld** [prisma/prisma#4195]
**Describe the bug**
I am unable to deploy prisma for an existing psql database with foreign key relations.

**To Reproduce**
1) Create a database with the following schema:
```
CREATE TABLE admin_users (
  id SERIAL PRIMARY KEY
);

CREATE TABLE customers (
  admin_user_id INTEGER NOT NULL REFERENCES admin_users(id),
  id SERIAL PRIMARY KEY
);
```

2) Running `prisma init` generates the following schema:
```
type AdminUser @pgTable(name: "admin_users") {
  id: Int! @unique
  customers: [Customer]
}

type Customer @pgTable(name: "customers") {
  id: Int! @unique
  admin_user_id: AdminUser!
}
```

3) Change `id: Int` to `id: ID` for both types.

4) Create docker container with `docker-compose up -d`

5) Running `prisma deploy` generates the following error:
```
Errors:

  Global
    ✖ Could not find the relation table _AdminUserToCustomer
```

6) This made sense to me, since that table doesn't exist in my existing database, so I instead tried using the `pgRelation` directive as detailed [here](https://www.prisma.io/docs/datamodel-and-migrations/introspection-POSTGRES-soi1/):
```
type Customer @pgTable(name: "customers") {
  id: ID! @unique
  adminUser: AdminUser! @pgRelation(column: "admin_user_id")
}
```

However I then see the following error:
```
Errors:

  Global
    ✖ Could not find the model table customers in the database
```

**Expected behavior**
I'm expecting 2 things here really:
1) For `prisma init` to automatically detect that I'm using foreign keys rather than relation tables and to set up the `@pgRelation` directive in the generated datamodel.
2) For the `@pgRelation` directive to work and not throw the above error.

**Versions (please complete the following information):**
 - Connector: Postgres (10.5)
 - `prisma` CLI: prisma/1.30.0-alpha.1
 - OS: macOS Mojave 10.14.2

**Additional context**
Not sure it's relevant, but this is what the `docker-compose.yml` looks like:
```
version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.30-alpha
    restart: always
    ports:
    - "4469:4469"
    environment:
      PRISMA_CONFIG: |
        port: 4469
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: host.docker.internal
            database: ---
            user: ---
            password: ---
            rawAccess: true
            port: '5432'
            migrations: false
```
