### ISSUE TITLE
Prisma server having memory leak / runaway cpu usage

### ISSUE THREAD

**Issue by murdockq** [prisma/prisma#4239]
**Describe the bug**
Shortly after running the prisma server it has memory leak / runaway cpu usage.  It allocates up 2gigs or ram and runs at 100% cpu and is completely unresponsive. Log output is below.

Currently running prisma server version 1.11.1 in production without issues.  
This error happens when attempting to upgrade to latest version 1.29.1,  a similar problem also occurred when trying to upgrade to 1.14.2 a while back and kept the current version waiting for a bug fix but situation has not yet improved.

I know there is not a  lot of details, so hoping to get some clues to help track this one down.

```
A  [INFO] {} - Started. 
A  [INFO] {} - Started. 
A  [INFO] {} - Close initiated... 
A  [INFO] {} - Closed. 
A  [INFO] Obtaining exclusive agent lock... 
A  [INFO] Initializing workers... 
A  [INFO] Obtaining exclusive agent lock... Successful. 
A  [INFO] Successfully started 1 workers. 
A  [INFO] Deployment worker initialization complete. 
A  Server running on :4466 
A  [INFO] {} - Started. 
A  [31m[SubscriptionSessionActor] Received unknown message: com.prisma.subscriptions.protocol.SubscriptionProtocolV07$Requests$GqlConnectionTerminate$@e43b78c[0m 
A  [31m[SubscriptionSessionActor] Received unknown message: com.prisma.subscriptions.protocol.SubscriptionProtocolV07$Requests$GqlConnectionTerminate$@e43b78c[0m 
A  [31m[SubscriptionSessionActor] Received unknown message: com.prisma.subscriptions.protocol.SubscriptionProtocolV07$Requests$GqlConnectionTerminate$@e43b78c[0m 
A  [31m[SubscriptionSessionActor] Received unknown message: com.prisma.subscriptions.protocol.SubscriptionProtocolV07$Requests$GqlConnectionTerminate$@e43b78c[0m 
A  [31m[SubscriptionSessionActor] Received unknown message: com.prisma.subscriptions.protocol.SubscriptionProtocolV07$Requests$GqlConnectionTerminate$@e43b78c[0m 
A  [31m[SubscriptionSessionActor] Received unknown message: com.prisma.subscriptions.protocol.SubscriptionProtocolV07$Requests$GqlConnectionTerminate$@e43b78c[0m 
A  [31m[SubscriptionSessionActor] Received unknown message: com.prisma.subscriptions.protocol.SubscriptionProtocolV07$Requests$GqlConnectionTerminate$@e43b78c[0m 
A  [31m[SubscriptionSessionActor] Received unknown message: com.prisma.subscriptions.protocol.SubscriptionProtocolV07$Requests$GqlConnectionTerminate$@e43b78c[0m 
A  [31m[SubscriptionSessionActor] Received unknown message: com.prisma.subscriptions.protocol.SubscriptionProtocolV07$Requests$GqlConnectionTerminate$@e43b78c[0m 
A  [31m[SubscriptionSessionActor] Received unknown message: com.prisma.subscriptions.protocol.SubscriptionProtocolV07$Requests$GqlConnectionTerminate$@e43b78c[0m 
A  [31m[SubscriptionSessionActor] Received unknown message: com.prisma.subscriptions.protocol.SubscriptionProtocolV07$Requests$GqlConnectionTerminate$@e43b78c[0m 
A  Uncaught error from thread [single-server-akka.actor.default-dispatcher-23]: GC overhead limit exceeded, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[single-server] 
A  java.lang.OutOfMemoryError: GC overhead limit exceeded 
A  	at scala.collection.immutable.HashMap$HashTrieMap.updated0(HashMap.scala:363) 
A  	at scala.collection.immutable.HashMap.$plus(HashMap.scala:61) 
A  	at scala.collection.immutable.HashMap.$plus(HashMap.scala:35) 
A  	at scala.collection.mutable.MapBuilder.$plus$eq(MapBuilder.scala:29) 
A  	at scala.collection.mutable.MapBuilder.$plus$eq(MapBuilder.scala:25) 
A  	at scala.collection.TraversableOnce.$anonfun$toMap$1(TraversableOnce.scala:316) 

```

docker-compose.yml
```
prisma:
    image: prismagraphql/prisma:1.29.1
    container_name: prisma
    restart: ${RESTART_MODE}
    ports:
      - 4466:4466
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: mysql
            active: true
            host: db
            port: 3306
            user: root
            password: prisma
            managementSchema: graphcool
    networks:
      - local_prisma

  db:
    image: mysql:5.7
    container_name: db
    restart: ${RESTART_MODE}
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: prisma
    volumes:
      - ./data/db:/var/lib/mysql
    networks:
      - local_prisma
```

prisma.yml
```
# to disable authentication:
# disableAuth: true
secret: ${env:PRISMA_SECRET}

# the file path pointing to your data model
datamodel: datamodel.graphql

# seed your service with initial data based on seed.graphql
seed:
  import: seed.graphql


endpoint: ${env:PRISMA_ENDPOINT}

hooks:
  post-deploy:
    - echo "Deployment finished"
    - npx graphql get-schema --project database
    - npx graphql prepare
```

**To Reproduce**
1. Previously running on version 1.11.1 of prisma server.
2. Upgraded to 1.29.1
3. See error

**Versions (please complete the following information):**
 - Connector: MySQL
 - Prisma Server: <1.29.1
 - `prisma` CLI:  prisma/1.29.1 (linux-x64) node-v10.8.0
 - OS:  Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64 GNU/Linux
