### ISSUE TITLE
Cannot access admin ui locally

### ISSUE THREAD

**Issue by liyucun** [prisma/prisma#4250]
**Describe the bug**
After run `prisma deploy` successfully, I can access Admin UI on prisma server, but I cannot access admin ui panel locally through docker-compose.

**To Reproduce**
1. Setup project with below docker-compose file
```
version: "3"
services:
  prisma:
    image: prismagraphql/prisma:1.30-beta
    restart: always
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 5432
        databases:
          default:
            connector: postgres
            host: db
            port: 5432
            user: postgres
            password: prisma
            migrations: true

  db:
    image: postgres:11.2
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
```
2. run [prisma graphql server example](https://github.com/prisma/prisma-examples/tree/master/typescript/graphql) by `npm run start`
3. you can access graphql ui locally
4. you cannot access admin ui through `http://localhost:4466/_admin`

**Expected behavior**
I can access admin ui by `http://localhost:4466/_admin`

**Versions (please complete the following information):**
 - Connector: Postgres
 - OS: OS X High Sierra
