### ISSUE TITLE
Error: `Prisma deploy` on docker-compose with param `schema: public`. Existing db.

### ISSUE THREAD

**Issue by SawasReaper** [prisma/prisma#4294]
Hi, bug i've found is related with `schema: public`. When I added it to my docker-compose.yml and went with `prisma deploy` it crashes on my real pgsql database and nth wasn't added to project/migration tables in managment schema. 

<img width="1158" alt="Screenshot 2019-03-31 at 00 23 32" src="https://user-images.githubusercontent.com/22744971/55282746-3fd3ab80-534b-11e9-8c4a-0c27bf83a13c.png">

But when I comment `schema: public` and run `prisma deploy` it's 👌 and my model is added to migration table in managment schema. 

<img width="545" alt="Screenshot 2019-03-31 at 00 36 10" src="https://user-images.githubusercontent.com/22744971/55282854-16b41a80-534d-11e9-8b6b-2a34e9bd3691.png">

<img width="719" alt="Screenshot 2019-03-31 at 00 26 30" src="https://user-images.githubusercontent.com/22744971/55282769-a789f680-534b-11e9-9862-ce5d351def55.png">

Then I uncommented my `schema: public` and restarted docker container and it's fine.

<img width="649" alt="Screenshot 2019-03-31 at 00 29 44" src="https://user-images.githubusercontent.com/22744971/55282804-1d8e5d80-534c-11e9-9407-71c82c7b2cfc.png">

Full log from debug: 

<img width="2052" alt="Screenshot 2019-03-31 at 00 31 12" src="https://user-images.githubusercontent.com/22744971/55282808-60e8cc00-534c-11e9-93e9-41bc1d00fc7d.png">

docker-compose.yml
```
version: "3.6"

services:
  offhub_pgsql:
    image: postgres:9.6.6-alpine
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    environment: 
      POSTGRES_USER: offhub
      POSTGRES_PASSWORD: offhub
      POSTGRES_DB: offhub
    ports:
      - 5432:5432

  prisma:
    image: prismagraphql/prisma:1.29.2
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: host.docker.internal 
            database: offhub
            user: offhub
            password: offhub
            rawAccess: true
            port: '5432'
            migrations: false
            schema: public

volumes:
  postgres:
```
Versions (please complete the following information):

Connector: Postgres
Prisma Server: 1.29.2
prisma CLI: prisma/1.29.1 (darwin-x64) node-v10.15.1
OS: OS X High Sierra
other dependencies: prisma-client

If you need some more info please tell me. I'm happy to help.
