### ISSUE TITLE
trying to connect to existing mysql database

### ISSUE THREAD

**Issue by mrtornado** [prisma/prisma#4376]
**Describe the bug**
[root@CentOS-73-64-minimal prisma]# prisma deploy
  environment FetchError: request to http://localhost:4466/management failed, reason: connect ECONNREFUSED 127.0.0.1:4466

datamodel.prisma seems to be created correctly, does Prisma support existing MySQL databases yet ? I saw that this was a problem like 1 year ago, but I suppose you made it support importing from existing database since datamodel.prisma is generated and it seem that prisma init worked. 

Seems that the docker image created with docker-compose up -d keeps restaring it-self.
I can never attach to it because it keeps restarting. Error in docker-compose logs is
`prisma_1  | Exception in thread "main" java.lang.RuntimeException: Unable to load Prisma config: com.prisma.config.InvalidConfiguration: Only Postgres connectors specify a schema. If they do they also need to specify a database. Other connectors only specify a database.
prisma_1  | 	at scala.sys.package$.error(package.scala:26)`

 if I remove the `schema` from docker-compose.yml I get another error 

`prisma_1  | Exception in thread "main" java.lang.RuntimeException: There is not passive mysql deploy connector yet!    | 	at scala.sys.package$.error(package.scala:26)`

docker-compose.yml file with schema: 

```
version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.32-alpha
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: mysql
            host: 176.9.44.11
            user: dbusername
            schema: dbpassword
            password: 'pass'
            rawAccess: true
            port: '3306'
            migrations: false
```

**Notice mysql server is on different server** but when I run prisma init prisma the setup wizard connects to the mySQL server and retrives the correct databases and I choose an existing one.

[root@central ~]# mysql --version
mysql  Ver 14.14 Distrib 5.5.45, for Linux (x86_64) using readline 5.1
 

**Versions (please complete the following information):**
 - Connector: MySQL
Prisma CLI version: prisma/1.32.0-alpha.3 (linux-x64) node-v10.15.2
also tried with last stable prisma first then upgraded to alpha
server is on CentOS 7 , remote server hosting mySQL db is CentOS 6
