### ISSUE TITLE
Prisma docker "message": "Project not found: 'default_default'"

### ISSUE THREAD

**Issue by therise3107** [prisma/prisma#4380]
versions: 
```
prisma/1.30.1 (darwin-x64) node-v10.9.0
```
docker compose.yml

```
version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.30
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: mongo
            uri: mongodb://prisma:prisma@mongo
  mongo:
    image: mongo:3.6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: prisma
      MONGO_INITDB_ROOT_PASSWORD: prisma
    ports:
      - "27017:27017"
    volumes:
      - mongo:/var/lib/mongo
volumes:
  mongo:
```
prisma.yml
```
endpoint: http://localhost:4466/auth/dev
datamodel: prisma/datamodel.prisma

generate:
  - generator: javascript-client
    output: ./generated/prisma-client/
```
`prisma deploy` ->

> Deploying service `auth` to stage `dev` to server `local` 87ms
> Service is already up to date.

I have started encountering it today after 
* Updating prisma.
* Running `prisma delete`
* Reinitialize the project.

Any help would be much helpful

**Comment by pantharshit00** [comment]
@therise3107 

I am unable to reproduce this. Can you please make a small repository that can have a minimal reproduction of the issue?

**Comment by therise3107** [comment]
@pantharshit00 here you go -> https://github.com/LiquidApi/authbackend

**Comment by therise3107** [comment]
I got this working with fresh installation in a new project, I assume it has to do something with the mongoDb default_default collection. I'm closing this, but if anyone faces similar issue then they might want to check their MongoDB collections under admin.

**Comment by giacomos** [comment]
Same error here. I just initialized a new mongo database with prisma init in docker, then I opened the playground in the browser and in the error console I get this:

```
Uncaught Error: {
  "errors": [
    {
      "message": "Project not found: 'default_default'",
      "code": 3016,
      "requestId": "local:cjus26adf00060742em6xe9rr"
    }
  ]
}
    at Object.next (SchemaFetcher.ts:127)
    at f (Observable.js:126)
    at d (Observable.js:161)
    at e.value (Observable.js:215)
    at httpLink.js:91
```

**Comment by pantharshit00** [comment]
@giacomos 

You will need to run prisma deploy to start a project. 

Also, you will need to go the exact stage and service you have chosen, depending upon the url in the prisma.yml file.

**Comment by havinhthai** [comment]
Same issue here, in my case, I think server can't connect to `default_default` database when I use `database` entity. But I don't know how I can connect to `demodb` database.

```
services:
  prisma:
    image: prismagraphql/prisma:1.31
    container_name: tuidev_prisma
    restart: always
    ports:
      - "4467:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: mongo
            database: demodb        <---- Here
            # schema: demodb
            uri: mongodb://prisma:prisma@mongo
```
One more thing, I don't know what is `schema` entity mean, I can't find it in [document](https://www.prisma.io/docs/releases-and-maintenance/features-in-preview/mongodb-b6o5/#prisma_config).
