### ISSUE TITLE
Error on prisma deploy

### ISSUE THREAD

**Issue by guigaoliveira** [prisma/prisma#4473]
**Describe the bug**
Errors:
  Global
    ✖ An unknown error happened: java.lang.ClassCastException: com.prisma.shared.models.TypeIdentifier$Relation$ cannot be cast to com.prisma.shared.models.TypeIdentifier$ScalarTypeIdentifier

**To Reproduce**
1. prisma deploy 

**Expected behavior**
I would expect the deploy to happen.

**Versions (please complete the following information):**
 - Connector: Postgres 
 - Prisma Server: 1.31.0
 - Prisma CLI version: prisma/1.31.2 (linux-x64) node-v12.1.0
 - OS: Ubuntu 18.10

**Comment by pantharshit00** [comment]
@guigaoliveira 

Can you please share your `datamodel.prisma` and `prisma.yml` files so that we can reproduce this issue? Right now with the provided information, it is not possible to reproduce the issue and triage the bug.

**Comment by guigaoliveira** [comment]
prisma.yml
```yml
endpoint: http://localhost:5001
datamodel:
  - entities/user.graphql
generate:
  - generator: javascript-client
    output: ./generated/prisma-client/
  - generator: graphql-schema
    output: ./generated/graphql-schema/prisma.graphql
hooks:
  post-deploy:
    - prisma generate
seed:
  run: node ./seed.js
```
entities/user.graphql
```graphql 
enum UserRole {
	USER
	COMPANY
}

type User {
	id: ID! @unique @id
	name: String!
	username: String @unique
	email: String! @unique
	password: String!
	role: UserRole @default(value: COMPANY)
	isDeleted: Boolean! @default(value: "false")
	createdAt: DateTime! @createdAt
	updatedAt: DateTime! @updatedAt
}
```
