### ISSUE TITLE
prisma generate fails on custom endpoint

### ISSUE THREAD

**Issue by diversit** [prisma/prisma#4502]
**Describe the bug**
`prisma generate` fails when using a custom endpoint in 2 cases:

1. command `prisma generate --endpoint http://my.server:1234/` is not using the endpoint from the command-line.

Response is a successful generation using the endpoint defined in the `prisma.yml` :
```
Downloading schema 974ms
Saving Prisma Client (TypeScript) at <path>
```
but expected an error that Prisma service at `http://my.server:1234/` cannot be reached.
Also, the endpoint values used in the generated `index.ts` is still the endpoint from the `prisma.yml` and not the one given on command-line.

Looking at the code for the Prisma Generate command, there is a `if` statement based on whether the argument is available, but the value of the argument is never used.

**To Reproduce**
1. Start up Prisma and db using docker-compose as described in Getting Started.
2. Use default prima.yml:
```yaml
endpoint: http://localhost:4466/ipos-api/develop
datamodel: datamodel.prisma

generate:
  - generator: typescript-client
    output: src/generated/prisma-client/
```
2. Run `prisma generate --endpoint http://my.server:1234`

**Expected behavior**
Expect generation to fail, but it still succeeds since it connects to endpoint from prisma.yml.
If the endpoint in prisma.yml is changed to `endpoint: http://my.server:1234` and using the command `prisma generate --endpoint http://localhost:4466/` then the command fails since it tries to connect to `http://my.server:1234` instead of `http://localhost:4466/` provided on command-line.

Expect the `generate` command to use the `endpoint` argument provided on the command-line _over_ the endpoint value defined in the prisma.yml when:
- connecting to the Prisma service
- generating the source code. The used `endpoint` value for constructing a Prisma client instance should have the value from the command-line.

2. Using a dynamic endpoint in `prisma.yml` fails generation of client.

The prisma CLI is able to connect to the Prisma service, so somewhere the endpoint is correctly evaluated and, in case the environment values are not set, the default values are being used.

However, the dynamic endpoint value does not seem the be evaluated when using it generating source code. Instead it is directly put in the `endpoint` value for constructing a new Prisma client instance which results in a Typescript syntax error.
I have not tested this, but I assume it fails for all client types.

Because of this error, the `generate` command does _not_ produce any output.

Error:
```sh
Generating schema 88ms
 ▸    '}' expected. (3385:108)
 ▸      3383 | */
 ▸      3384 |
 ▸    > 3385 | export const Prisma = makePrismaClientClass<ClientConstructor<Prisma>>({typeDefs, models, endpoint:
 ▸    `${self:custom.prismaUrl}/${self:custom.serviceName}/${self:custom.serviceStage}`})
 ▸           |                                                                                                            ^
 ▸      3386 | export const prisma = new Prisma()
 ▸      3387 |
```

**To Reproduce**
1. Start up Prisma and db using docker-compose as described in Getting Started.
2. Use default prima.yml with a dynamic endpoint based on custom values:
```yaml
endpoint: ${self:custom.prismaUrl}/${self:custom.serviceName}/${self:custom.serviceStage}
datamodel: datamodel.prisma

generate:
  - generator: typescript-client
    output: src/generated/prisma-client/

# Customize location of prisma service so values can be set via environment variables
custom:
  prismaUrl: ${env:PRISMA_URL, "http://localhost:14466"}
  serviceName: ${env:PRISMA_SERVICE_NAME, "myservice"}
  serviceStage: ${env:PRISMA_SERVICE_STAGE, "develop"}
```
2. Run `prisma generate`

**Expected behavior**
In the generated code, the evaluated value for endpoint must be used when constructing a new Prisma instance.
This this case it should have been evaluated into `index.ts` fragment (at the bottom):
```javascript
...
export const Prisma = makePrismaClientClass<ClientConstructor<Prisma>>({
  typeDefs,
  models,
  endpoint: `http://localhost:14466/myservice/develop`,
  secret: `0331d120b1da4304958f45f25c43c31a`
});
export const prisma = new Prisma();
```

**Versions (please complete the following information):**
 - Prisma Server: 1.32.0
 - `prisma` CLI: prisma/1.32.0 (darwin-x64) node-v11.3.0
 - OS: Darwin Kernel Version 18.5.0: Mon Mar 11 20:40:32 PDT 2019; root:xnu-4903.251.3~3/RELEASE_X86_64 x86_64
