### ISSUE TITLE
@relation(link: TABLE) no longer works

### ISSUE THREAD

**Issue by VRspace4** [prisma/prisma#4569]
**Describe the bug**
Declaring many to many (n:m) relationships no longer work. `prisma deploy` intermittently completes successfully but no tables are created or it fails with the following error:

> The Migration failed and has not been performed. This is very likely not a transient issue.
> org.postgresql.util.PSQLException: ERROR: column "gameId" referenced in foreign key constraint does not exist
> 

**To Reproduce**
```
# prisma.yml

endpoint: XXX
secret: XXX
datamodel:
  - ./test1.prisma

generate:
  - generator: typescript-client
    output: XXX
  - generator: graphql-schema
    output: XXX
```

```
# test1.prisma

type Game {
  gameId: ID! @id
  createdAt: DateTime! @createdAt
  updatedAt: DateTime! @updatedAt
  lastUpdatedOn: String!
  players: [Player!]! @relation(link: TABLE, name: "GamePlayer")
}

type Player {
  playerId: ID! @id
  createdAt: DateTime! @createdAt
  updatedAt: DateTime! @updatedAt
  lastUpdatedOn: String!
  games: [Game!]! @relation(name: "GamePlayer")
}
```

`prisma deploy`

**Expected behavior**
Three tables should be created:
1. Game
2. Player
3. _GamePlayer

**Versions (please complete the following information):**
 - Connector: Postgres:latest as of 5/21/2019
 - Prisma Server: v1.33.0
 - `prisma` CLI: prisma/1.33.0 (windows-x64) node-v11.4.0
 - OS: Windows 10

**Additional**
I've confirmed 1:1 and 1:n relationships do work still, just not n:m.
