### ISSUE TITLE
Invalid token in prisma deploy

### ISSUE THREAD

**Issue by tanujdoshi** [prisma/prisma#4614]
**Describe the bug**
i am trying to prisma deploy , but it shows me :

Creating stage default for service default !
ERROR : invalid token 

docker.compose.yml:

```
version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.28.3
    restart: always
    network_mode: "host"
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        managementApiSecret: thisismysupersecrettext
        databases:
          default:
            connector: mysql
            host: 192.168.56.1
            port: 3306
            user: root
            password: TfS5UnmQGrZDlTth
            migrations: true
```

prisma.yml: 

````
endpoint: http://192.168.99.100:4466
datamodel: datamodel.prisma
secret: thisismysupersecrettext
````

Error:

```
PS C:\Users\DHRUMIT\Desktop\mysql-node\helloworld> prisma deploy
Creating stage default for service default !

ERROR: Invalid token

{
  "data": {
    "addProject": null
  },
  "errors": [
    {
      "locations": [
        {
          "line": 2,
          "column": 9
        }
      ],
      "path": [
        "addProject"
      ],
      "code": 3015,
      "message": "Invalid token",
      "requestId": "local:cjwg4segg00020744ebssna52"
    }
  ],
  "status": 200
}
```
**Versions (please complete the following information):**
 - Connector: MySQL`
 - Prisma Server: 
 - `prisma` CLI: v1.28.3
 - OS: Windows 10
 - other dependencies: `prisma-client`, `prisma-binding`, etc. if applicable

**Additional context**
