### ISSUE TITLE
Invalid interpolation format for "environment" option in service "prisma": "port: 4466

### ISSUE THREAD

**Issue by t86** [prisma/prisma#4633]
**Description**

Executed command in terminal: docker-compose up -d, I got:

	ERROR: Invalid interpolation format for "environment" option in service "prisma": "port: 4466
	databases:
	  default:
	    connector: mysql
	    host: prisma
	    schema: prisma
	    user: root
	    password: prisma 
	    rawAccess: true
	    port: 3306
	    migrations: false

But if I use postgresql, everything is fine.

My docker-compose.yml file:

	  version: '3'
	  services:
	  prisma:
	    image: prismagraphql/prisma:1.34
	    restart: always
	    ports:
	    - "4466:4466"
	    environment:
	      PRISMA_CONFIG: |
	        port: 4466
	        databases:
	          default:
	            connector: mysql
	            host: 172.1.10.123
	            schema: prisma
	            user: root
	            password: prisma
	            rawAccess: true
	            port: 3306
	            migrations: false

**Versions:**
 - Connector: `MySQL`
 - Prisma Server: 1.34
 - `prisma` CLI: `prisma/1.34  node-v11.8.0`
 - OS: OS X High Sierra`

**Comment by pantharshit00** [comment]
Hi,

The only thing that looks off to me is your indentation:

```yml
version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: mysql
            host: 172.1.10.123
            user: root
            password: prisma
            rawAccess: true
            port: 3306
            migrations: false
```

Try this
