### ISSUE TITLE
allow array of generator output

### ISSUE THREAD

**Issue by zwhitchcox** [prisma/prisma#4642]
**Is your feature request related to a problem? Please describe.**

Right now, the generators in `prisma.yml` only accept one output path as a string:

```yml
generate:
  - generator: typescript-client
    output: ./generated/prisma-client
```

But sometimes, you need to generate the same file in multiple places. For instance, you need the client on your server and on your client app. Output does not accept multiple paths, so you have to create multiple generators like this:

```yml
generate:
  - generator: typescript-client
    output: ./server/generated/prisma-client
  - generator: typescript-client
    output: ./client/src/generated/prisma-client
```

This runs the entire generator multiple times, which already takes a long time as it is, and some projects like `create-react-app` will not allow you to import sources from outside the `src` directory, so you're forced to either import from the client folder on the server side or take twice as long to generate the client.

**Describe the solution you'd like**

A better solution, IMO would be to group the outputs together for each generator like so:

```yml
generate:
  - generator: typescript-client
    output:
      - ./server/generated/prisma-client
      - ./client/src/generated/prisma-client
```

But also accept a string so as not to break current apps.

You could also make it even better by just having a list of generators as properties and outputs paths as the value like so:

```yml
  - generator:
    typescript-client:
      - ./server/generated/prisma-client
      - ./client/src/generated/prisma-client
    graphql-schema: ./generated/graphql/prisma.graphql
```

This could be implemented without breaking current configurations by simply testing if the generator config is an array or an object.

**Describe alternatives you've considered**

Right now, I am running a script that generates the prisma output and then copies it to the server and client folder, which is considerably faster than regenerating it for both, but this is messy and complicated and clutters the project, so I would much rather this be handled by prisma automatically.
