### ISSUE TITLE
prisma.yml recursive self-referencing variables issue w/ prisma generate

### ISSUE THREAD

**Issue by jwondrusch** [prisma/prisma#4693]
**Describe the bug**
Getting started with Prisma and ran into an issue when trying to use recursive self references in my `prisma.yml` config file.

**To Reproduce**

1. Using the following `prisma.yml` file: 
```
endpoint: http://localhost:4466/{self:custom.serviceName}/${self:custom.stage}
datamodel: datamodel.prisma

generate:
  - generator: typescript-client
    output: ./generated/prisma-client/
hooks:
  post-deploy:
      - prisma generate
      - npx nexus-prisma-generate --client ./generated/prisma-client --output ./generated/nexus-prisma

custom:
  serviceName: test
  stage: dev
```
2. Execute `prisma generate` in my terminal will eventually throw the following error:
```
 ▸    '}' expected. (690:138)
 ▸    688 | */
 ▸    689 |
 ▸    > 690 | export const Prisma =
 ▸    makePrismaClientClass<ClientConstructor<Prisma>>({typeDefs, models,
 ▸    endpoint: `http://localhost:4466//${self:custom.serviceName}/${self:custom.stage}`})
 ▸    |
 ▸    ^
 ▸    691 | export const prisma = new Prisma()
 ▸    692 |
```

**Expected behavior**
App deploys using self-referencing variables.

**Screenshots**
N/a

**Versions (please complete the following information):**
 - Connector: Postgres
 - Prisma Server: 1.34
 - `prisma` CLI: 1.34
 - OS: Ubuntu 16.04`

**Additional context**
Pretty barebones, just following along with the docs (only users + posts schemas).  Using environment variables works fine, it's just the self-referencing ones that fail.  Looks like the self-referencing variables are not parsed before generating the file, but they are for environment vars.
