### ISSUE TITLE
Cannot specify schema/DB when using mysql connector.

### ISSUE THREAD

**Issue by hisco** [prisma/prisma#4762]
**Bug description**
Cannot specify existing schema/DB when using mysql connector.

Observations:
According to few examples and some errors it appears the mysql connector support specifying only `database`.
Only postgres supports specifying both `database` and `schema`.

Result
Prisma crashes because it cannot connect to DB with the following error:
[Note] Unknown database 'prisma'
 
**To Reproduce**
Use the following `docker-compose.yaml`

```yaml
version: '3'
services:
  db:
    image: mysql:5.7
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'foo'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'test'
      MYSQL_ROOT_PASSWORD: 'root'
  prisma:
    image: prismagraphql/prisma:1.34.3
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: mysql
            host: db
            database: foo
            user: root
            password: root
            rawAccess: true
            port: '3306'
            migrations: false
```

**Expected behavior**
By specifying `database: foo` I expected that prisma will use `foo` as the schema in the db.

**Versions (please complete the following information):**
 - Connector:`MySQL`
 - Prisma Server: 1.34.3  #multiple versions
 - `prisma` CLI: Prisma CLI version: prisma/1.34.0 (darwin-x64) node-v10.4.1
 - OS: `OS X mojave`

**Comment by zeddee** [comment]
same issue here. 

also related (since it may indicate that somewhere along the line, the expected API behaviour and actual API diverged):

when running the `prisma init` wizard with 

1. `prisma init` 
2. > Use existing database
3. > MySQL 
4. > Yes ("Does your DB contain existing data")
5. > [...]

it generates a `docker-compose.yml` that has a `schema` line in PRISMA_CONFIG, e.g.:

```
version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: mysql
            host: host.docker.internal
            schema: wordpress
            user: wordpress
            password: wordpress
            rawAccess: true
            port: '3307'
            migrations: false
```

which then causes Prisma to also throw an error saying that only PG accepts a `schema`.

what's _also_ weird is that the `prisma init` wizard successfully connects to my DB and generates a valid `datamodel.prisma` file and my prisma client of choice. It's just being able to start up the prisma server with `docker-compose up` that's blocking progress.

**Comment by pantharshit00** [comment]
I am unable to reproduce this. Prisma is correctly using the specified database when I specify it in the database property in the yaml file and run prisma deploy.
```yaml
version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: mysql
            host: mysql
            user: root
            password: prisma
            database: foo
            rawAccess: true
            port: 3306
            migrations: true
  mysql:
    image: mysql:5.7
    restart: always
    # Uncomment the next two lines to connect to your your database from outside the Docker environment, e.g. using a database GUI like Workbench
    ports:
    - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: prisma
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql:
```

![image](https://user-images.githubusercontent.com/22195362/62162216-66274900-b335-11e9-8787-62f71a0c75ad.png)

Regarding cli writing schema instead of database, that is a known issue. https://github.com/prisma/prisma/issues/4434

**Comment by zeddee** [comment]
@pantharshit00 Roger re: 4434

I'm still unable to get prisma to connect to the database specified in the yaml string though.

I'm running your exact docker-compose.yml as-is, and while the prisma service appears to be running fine, examining the mysql server output shows that the prisma service is still trying to connect to the `prisma` database which does not exist, but is not throwing an error because you're logged in as root anyway.

I noticed that both OP's and your docker-compose scripts are connecting to the mysql db as root, so that might be obscuring what's happening re: db connections a bit?

The issue is also more pronounced when you start the two services (prisma and mysql containers) separately i.e. not as part of one docker-compose.yml file.

i'd put up a repo to demo what i'm seeing, but i'm a bit time/attention poor right now; sorry!

**Comment by zeddee** [comment]
@pantharshit00 okay I'm 100% sure the issue persists.

Here's my repo: https://github.com/zeddee/prisma-issue-4762

Set up 2 scenarios:
- single docker compose cluster
- running as separate services

both instances cannot `prisma deploy` because the prisma cli is still attempting to connect to and work with the `prisma` database, which doesn't exist.

so i tried changing the database name in the `mysql-service/docker-compose.yml` file for, and ...
everything works i.e. `prisma deploy` runs smoothly. i didn't even change the `database` field in the `prisma-service/docker-compose.yml` file. You can replicate this using https://github.com/zeddee/prisma-issue-4762/tree/dbname-prisma

**Comment by juliendangers** [comment]
@zeddee Ran both scenarios, and everything worked as expected, prisma database has been created.

With single docker compose I had to restart manually prisma container, because it started before MySQL being available, but issue is not at prisma level.

With separate services I waited for mysql to be ready for connections and it ran smoothly. 

The only error I saw is that you got an error in your schema definition:

```
Encountered unknown SQL type date with column birth.
```

Could the issue itself be caused by an existing docker volume from a previous prisma init, with default values. It would explains why the cli successfully connects to the database, but doesn't work with `docker-compose up` (because it relies on the existing volume with default configuration...).

**Comment by zeddee** [comment]
hey @juliendangers , the expected behaviour is that it use the `pets` database (as specified in `docker-compose.yml`), and not create a new `prisma` database?

i'll run it again on a clean system sometime this week to double-check if my env is the issue

**Comment by juliendangers** [comment]
I think it always create a prisma database to hold its state (CloudSecret, InternalMigration, Migration, Project, TelemetryInfo) on MYSQL (it uses a management schema on PostgreSQL). But data relative to your prisma project (service and stage) will be stored in the specified database

**Comment by blazestudios23** [comment]
I'm completely blocked when trying to connect to an existing MySQL data. 

I run prisma Init which works perfectly. 
But uses "schema:" instead of "database:" as listed above. 

I then run Prisma deploy. Instead of connecting to "database: schemaName", I get this output: 
``
Deploying service `default` to stage `default` to server `default
``
It creates a new schema named default@default and my queries all return null as the data is stored under "schemaName" not "default@default".

I set the endpoint to ${url}/schemaName and that produces a new schema named "schemaName@default". 

There appears to be no way to just use "schemaName". 

Am I doing something wrong? Or is Prisma not actually able to connect to existing MySQL databases?  I have never seen a MySQL DB use "default@default" that's PostgreSQL.

**Comment by CWX-iggy** [comment]
My issue is somewhat related. Apparently, I can't use a specific MySQL (non-root) user for a custom database schema name other than "prisma".

```
services:
  prisma:
    image: prismagraphql/prisma:1.34
    ports:
    - "4466:4466"
    environment:
       PRISMA_CONFIG: |
         port: 4467
         databases:
            default:
              connector: mysql
              host: mysql
              database: mycustomdb
              user: prisma_user
              password: <prisma-password>
  mysql:
     image: mysql:5.7
     environment:
             MYSQL_DATABASE: mycustomdb
             MYSQL_USER: prisma_user
             MYSQL_PASSWORD: <prisma-password>
```

will cause the following error in the `prisma` service:

```
Exception in thread "main" java.sql.SQLSyntaxErrorException: (conn=4) Access denied for user 'prisma_user'@'%' to database 'prisma' at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:163)
```

**Comment by pantharshit00** [comment]
@CWX-iggy 

You will need to give the non-root user access to "prisma" database.


@blazestudios23 

I guess you went ahead and did a deployment when schema property was set in your docker-compose.yml file. What I suggest here is that you should delete the "prisma" database in your MySQL instance and should try deploying this again after restarting your container.

**Comment by blazestudios23** [comment]
@pantharshit00 

Thank you for the response. So I deplete the Prisma table and destroyed and rebuild the container with the following docker-compose file:

```
version: "3"
services:
  prisma:
    image: prismagraphql/prisma:1.34.6
    restart: always
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: mysql
            host: ${endpiont}
            database: transactions
            user: ${user}
            password: ${password}
            rawAccess: true
            port: '3306'
            migrations: false
```

It is still outputting the following message at build, and creating a default@default schema: 
```
Deploying service `default` to stage `default` to server `default`
```

I looked at the Prisma DB and the the prisma.Project first row has an id of default@default.  The prisma.Migration table has a projectId of default@defualt as well. I tried manually changing both to transactions, but that just results in "prisma deploy" opening a new browser window to the Prisma website login page. 

So I'm still stuck here on connecting to the existing MySQL database.
