### ISSUE TITLE
MySQL: Cannot connect to existing Schema

### ISSUE THREAD

**Issue by blazestudios23** [prisma/prisma#4827]
**Describe the bug**

Prisma cannot connect to MySQL Schema, it instead tries to connect to a PostgreSQL service and stage, which results in a new Schema being created. 

**To Reproduce**

I run prisma Init which works perfectly.
But uses "schema:" instead of "database:".

I then run Prisma deploy. Instead of connecting to "database: schemaName", I get this output:
```
Deploying service `default` to stage `default` to server `default
```
It creates a new schema named default@default and my queries all return null as the data is stored under "schemaName" not "default@default".

I set the endpoint to ${url}/schemaName in the prisma.yml file and that produces a new schema named "schemaName@default".

There appears to be no way to just use "schemaName".

Am I doing something wrong? Or is Prisma not actually able to connect to existing MySQL databases? I have never seen a MySQL DB use "default@default" that's PostgreSQL.

**Expected behavior**
It would be expected that when I enter, "prisma deploy", the created prisma instance to be a connection to the the schema defined in the docker-compose.yml. Which would allow one to view and edit data from that schema. 

**Screenshots**

```
version: "3"
services:
  prisma:
    image: prismagraphql/prisma:1.34.6
    restart: always
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: mysql
            host: ${host}
            database: transactions
            # schema: transactions
            user: ${user}
            password: ${password}
            rawAccess: true
            port: '3306'
            migrations: false
```

**Versions (please complete the following information):**
 - Connector: MySQL
 - Prisma Server: 1.34.6
 - `prisma` CLI:  1.34.6
 - OS: Windows 10

**Additional context**
I'm connecting to an Aurora DB that has been in existence for some time. I've used Aurora for fresh Prisma installs and these have worked perfectly.
