### ISSUE TITLE
Error: No cluster could be found for workspace '*' and cluster 'default'

### ISSUE THREAD

**Issue by kayali1411** [prisma/prisma#4899]
I got the following error when I run `prisma deploy`
**Error: No cluster could be found for workspace '*' and cluster 'default'**

 - Connector: `MongoDB`
 - `prisma` CLI: `prisma/1.34.8 (darwin-x64) node-v10.16.2`
 - OS: `OS X Mojave`

docker-compose.yml 
```
version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: mongo
            schema: blog
            uri: 'mongodb://host.docker.internal:27017'
```
prisma.yml
```
endpoint: http://host.docker.internal:4466
datamodel: datamodel.prisma
databaseType: document
```
