### ISSUE TITLE
The Compose file '.\docker-compose.yml' is invalid because:

### ISSUE THREAD

**Issue by bussiere** [prisma/prisma#4919]
here is my docker-compose.yml : 

```
version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: 127.0.0.1
            port: 5432
            user: admin_gp
            password: toto
  postgres:
    image: postgres:10.3
    restart: always
    environment:
      POSTGRES_USER: admin_gp
      POSTGRES_PASSWORD: toto
    volumes:
      - postgres: /cygdrive/c/Program\ Files/PostgreSQL/12/data/
volumes:
  postgres:
```
 i have this error : 

```
The Compose file '.\docker-compose.yml' is invalid because:
services.postgres.volumes contains an invalid type, it should be a string
```
