### ISSUE TITLE
ERROR: Invalid signature while deploying in circleCI

### ISSUE THREAD

**Issue by HugoLiconV** [prisma/prisma#4942]
**Describe the bug**
I'm running Prisma deploy in CircleCI and I'm getting this error

```
ERROR: Invalid signature

{
  "data": {
    "addProject": null
  },
  "errors": [
    {
      "locations": [
        {
          "line": 2,
          "column": 9
        }
      ],
      "path": [
        "addProject"
      ],
      "code": 3015,
      "message": "Invalid signature",
      "requestId": "local:ck3ar5fld000m0728xtyfd3h4"
    }
  ],
  "status": 200
}
```
I'm authenticateting by passing the cloud session key.
This is my circleCI config file: 

```yml
  deploy-prisma: 
    docker: 
      - image: circleci/node:lts

    steps:
      - checkout
      - run: sudo npm install -g prisma
      - run: prisma login --key ${CLOUD_KEY}
      - run: prisma deploy --env-file .env.production
```
the file .env.production exists in git

**Versions (please complete the following information):**
 - Connector: `Postgres`
 - Prisma Server: 1.34
 - `prisma` 

**Additional context**
