### ISSUE TITLE
Prisma stores all service and stages in 1 MySQL database

### ISSUE THREAD

**Issue by szepeviktor** [prisma/prisma#5007]
**Describe the bug**
All sql tables are created in the sql database called "prisma"
This is my `PRISMA_CONFIG`

```yaml
      PRISMA_CONFIG: |
        managementApiSecret: '*****'
        port: 4466
        databases:
          default:
            connector: 'mysql'
            host: 'sql'
            port: 3306
            user: 'root'
            password: 'mysecret'
            database: 'prisma'
            connectionLimit: 4
```

**To Reproduce**
1. Set up Prisma with the above `PRISMA_CONFIG`
2. Deploy a very simple (1 type only) datamodel
3. See new sql tables in the "prisma" sql database

**Expected behavior**
Prisma creates a a separate sql database per stage. https://github.com/prisma/prisma/issues/4520#issuecomment-500889467

**Versions (please complete the following information):**
 - Connector: mysql:5.7
 - Prisma Server: prisma:1.34
 - `prisma` CLI: prisma/1.33.0
 - OS: Debian 10
