### ISSUE TITLE
prisma asks to authenticate when running prisma deploy command

### ISSUE THREAD

**Issue by doums** [prisma/prisma#5025]
Hi,

I have my prisma service running into a Docker container locally.
I want to have my API (built on top of prisma service) running through a container too.
prisma.yml:
```
endpoint: ${env:PRISMA_ENDPOINT}
datamodel: datamodel.prisma
generate:
  - generator: typescript-client
    output: ../src/generated/prisma-client/
hooks:
  post-deploy:
    - prisma generate --env-file ../.env
secret: ${env:PRISMA_SECRET}
```
docker-compose.yml to start the prisma service and the data base:
```
version: '3.7'
services:
  prisma:
    container_name: pwa-prisma
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - 4469:4469
    environment:
      PRISMA_CONFIG: |
        port: 4469
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: prisma
            password: prisma
    networks:
      - prisma

  postgres:
    container_name: pwa-db
    image: postgres:10.3
    restart: always
    ports:
    - 5432:5432
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - pwa-volume:/var/lib/postgresql/data2
    networks:
      - prisma

volumes:
  pwa-volume: ~

networks:
  prisma:
    name: prisma
    driver: bridge
```
Note that the two services are under the same network named **prisma**.
Ok now here is the  Dockerfile of my API:
```
FROM node:latest

WORKDIR /usr/src/app

COPY package*.json ./
COPY deploy/.env ./
COPY src src/
COPY prisma prisma/
COPY tsconfig.json ./

RUN npm i
RUN cd prisma && npx prisma deploy --env-file ../.env
RUN npm run build

EXPOSE 4001

ENV NODE_ENV production

CMD [ "node", "dist/index.js" ]
```
and finally the docker-compose.yml to build it:
```
version: '3.7'

services:
  api:
    container_name: api
    build:
      context: ../
      dockerfile: deploy/Dockerfile
    restart: always
    ports:
      - 4001:4001
    networks:
      - prisma

networks:
  prisma:
    external: true
```
Note that I put the api service under the same network of the prisma service to allow them to communicate.
My .env looks like:
```
PRISMA_SECRET=xxx
PRISMA_ENDPOINT=http://<prisma_service_container_name>:4469
API_SECRET=xxx
```

When I run my docker-compose.yml to build the API, It fails:
```
Step 9/13 : RUN cd prisma && npx prisma deploy --env-file ../.env
 ---> Running in 8f9e5a9fd919
npx: installed 593 in 55.357s

Authenticating...
Opening https://app.prisma.io/cli-auth?secret=xxx in the browser

Could not open the authentication link, maybe this is an environment without a browser. Please open this url in your browser to authenticate: https://app.prisma.io/cli-auth?secret=xxx
```
We can see for some weird reason Prisma needs to authenticate when the command `prisma deploy --env-file ../.env` is run.
But if I run the exact same commands (`cd prisma && npx prisma depoy ..`) directly into the container (through `docker exec -it api /bin/bash`), the command succeds.
