### ISSUE TITLE
'Authorization' header not provided - prisma deploy

### ISSUE THREAD

**Issue by pmabres** [prisma/prisma#5043]
**Describe the bug**
Attempting to run prisma deploy on a local docker prisma configuration, I get the error 'Authorization' header not provided

**To Reproduce**
1. Create a docker compose file with prisma and postgresql images.
````
  prisma:
    image: prismagraphql/prisma:1.34.10
    restart: always
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        managementApiSecret: MYSECRETPRISMATOKEN
        port: 4466
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: prisma
            password: prisma
  postgres:
    image: postgres:10.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres:/var/lib/postgresql/data
````
2. Run the image with docker-compose up
3. Try with either global or local prisma cli version 10.34.10
4. prisma deploy --env-file variables.env
5. Result:
````
Error: Authentication token is invalid: 'Authorization' header not provided: {"response":{"data":{"addProject":null},"errors":[{"locations":[{"line":2,"column":9}],"path":["addProject"],"code":3015,"message":"Authentication token is invalid: 'Authorization' header not provided","requestId":"local:ck7trc2ts000g0715rbmqe47j"}],"status":200},"request":{"query":"      mutation addProject($name: String! $stage: String! $secrets: [String!]) {\n        addProject(input: {\n          name: $name,\n          stage: $stage\n          secrets: $secrets\n        }) {\n          project {\n            name\n          }\n        }\n      }\n      ","variables":{"name":"default","stage":"default","secrets":["MYSECRETPRISMATOKEN"]}}}
    at GraphQLClient.<anonymous> (/usr/local/lib/node_modules/prisma/node_modules/graphql-request/src/index.ts:72:13)
    at step (/usr/local/lib/node_modules/prisma/node_modules/graphql-request/dist/src/index.js:40:23)
    at Object.next (/usr/local/lib/node_modules/prisma/node_modules/graphql-request/dist/src/index.js:21:53)
    at fulfilled (/usr/local/lib/node_modules/prisma/node_modules/graphql-request/dist/src/index.js:12:58)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
````
**Expected behavior**
It should be deployed

prisma.yml
````
endpoint: ${env:PRISMA_DEPLOY_ENDPOINT}
datamodel: datamodel.graphql
secret: ${env:PRISMA_SECRET}
generate:
  - generator: graphql-schema
    output: ./src/generated/prisma.graphql
hooks:
  post-deploy:
    - graphql get-schema -p prisma
````
variables.env
````
PRISMA_DEPLOY_ENDPOINT="http://localhost:4466"
PRISMA_SECRET="MYSECRETPRISMATOKEN"
````

**Versions (please complete the following information):**
 - Connector: [`Postgres`]
 - Prisma Server: [ `1.34.10`]
 - `prisma` CLI: [e.g. `prisma/1.34.10 (darwin-x64) node-v11.5.0`]
 - OS: [`OS X Catalina (10.15.2)`,] 

Removing the managementApiSecret works atm which helps me to get forward with development, but that won't apply to production
