### ISSUE TITLE
prisma migrate deploy fails in gitlab and azure cicd (v2.20.1)

### ISSUE THREAD

**Issue by kokokenada** [prisma/prisma#6385]
## Bug description

prisma migrate deploy causes:
````
Error: Cannot find module '/root/.npm/_npx/489/lib/node_modules/prisma/scripts/preinstall-entry.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:831:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! prisma@2.20.1 preinstall: `node scripts/preinstall-entry.js`
npm ERR! Exit status 1
npm ERR! 
````

## How to reproduce

Running 'npx prisma migrate deploy' from the .gitlab-ci.yml encounters the error above
.npmrc has unsafe-perm=true which was required to fix npx prisma generate

## Environment & setup

prisma@2.20.1

**Comment by janpio** [comment]
Is Prisma already installed before executing this command as a local dependency of the project or do you think the command itself downloads and installs the Prisma CLI?

**Comment by kokokenada** [comment]
npm install was run prior to the error,  npm generate also run successfully prior to the error. (Until I added .npmrc with unsafe-perm=true, the error occurred at the prior npm generate step. Adding the .npmrc file advanced the process, but it still crashes at the migrate deploy stage.

**Comment by kokokenada** [comment]
I seem to have been able to work around this problem by downgrading to 2.16.1

**Comment by pantharshit00** [comment]
Can you share your gitlab ci config file?

**Comment by kokokenada** [comment]
Sure.  Here; you go:
````
image: node:12.19 # lambci/lambda:nodejs12.x

stages:
  - build_backend
  - pages

cloud_server_build:
  stage: build_backend
  tags:
    - alibitech
  before_script:
    - echo 'before_script cloud_server_build started'
    - npm config set prefix /usr/local
    - npm install
  script:
    - cd packages/back-end
    - export start=$SECONDS
    - echo 'npm install started'
    - npm install
    - npm run copy-lib
    - export duration=$(( $SECONDS - $start))
    - echo "npm Duration = $duration"
    - export start=$SECONDS
    - echo 'build cli'
    - npm run build-cli
    - export duration=$(( $SECONDS - $start))
    - echo "npm cli build = $duration"
    - export start=$SECONDS
    - echo 'set-env'
    - . ./set-env.sh
    - export duration=$(( $SECONDS - $start))
    - echo "set env = $duration"
    - export start=$SECONDS
    - echo 'script migrate_db started'
    - ./db-deploy.sh
    - export duration=$(( $SECONDS - $start))
    - echo "db-deploy.sh Duration = $duration"
    - export start=$SECONDS
    - ./compile.sh
    - export duration=$(( $SECONDS - $start))
    - echo "Compile Duration = $duration"
    - export start=$SECONDS
    - ./deploy-brand.sh
    - export duration=$(( $SECONDS - $start))
    - echo "Deploy Duration = $duration"
    - export start=$SECONDS
    - npm run config-shopify
    - export duration=$(( $SECONDS - $start))
    - echo "Shopify Config Duration = $duration"
    - export start=$SECONDS
    - cd ../fusion-auth
    - npm install
    - npm run copy-lib
    - npm run config
    - export duration=$(( $SECONDS - $start))
    - echo "Fusion Auth Config Duration = $duration"
  environment: $CI_COMMIT_BRANCH
#  cache:
#    paths:
#      - packages/back-end/node_modules
#  artifacts:
#    paths:
#      - packages/back-end
#    expire_in: 3 days

# https://github.com/gatsbyjs/gatsby/commit/c08fa4a6a6a7e8cc7e06ed4e28a8e325fbf96412
# https://github.com/gatsbyjs/gatsby/pull/24535

ssg_build:
  stage: pages
  tags:
    - alibitech
  variables:
    GATSBY_EXPERIMENTAL_PAGE_BUILD_ON_DATA_CHANGES: 'true'
    CONNECTION_TIMEOUT: 90000
    GATSBY_CONNECTION_TIMEOUT: 90000
    STALL_TIMEOUT: 90000
    GATSBY_STALL_TIMEOUT: 90000
    STALL_RETRY_LIMIT: 10
    GATSBY_STALL_RETRY_LIMIT: 10
    GATSBY_CONCURRENT_DOWNLOAD: 10
  before_script:
    - echo 'before_script cloud_deploy started'
    - export start=$SECONDS
    - npm config set prefix /usr/local
    # - npm install -g serverless
    # - export duration=$(( $SECONDS - $start))
    # - echo "npm install serverless globally = $duration"
    # - export start=$SECONDS
    - cd packages/back-end
    - npm ci --cache .npm --prefer-offline
    - npm install
    - npm run copy-lib
    - export duration=$(( $SECONDS - $start))
    - echo "npm install in back-end = $duration"
    - export start=$SECONDS
    - echo 'build cli'
    - npm run build-cli
    - export duration=$(( $SECONDS - $start))
    - echo "npm cli build = $duration"
    - cd ../..
    - . ./set-env.sh
    - export start=$SECONDS
    - cd packages/contentful
    - npm install
    - cd contentful-export
    - npm install
    - npm run build
    - cd ../contentful-import
    - npm install
    - npm run build
    - cd ..
    - ./migrate.sh $GATSBY_BRAND_ID
    - export duration=$(( $SECONDS - $start))
    - echo "migration duration = $duration"
    - export start=$SECONDS
    - echo "building widget"
    - cd ../widget-lib
    - npm install
    - npm run build
    - echo "widget build done = $duration"
    - export start=$SECONDS
    - cd ../ui
    - npm ci --cache .npm --prefer-offline
    - npm install
    - npm run copy-lib
    - export duration=$(( $SECONDS - $start))
    - echo "npm install in ui = $duration"
  script:
    - export start=$SECONDS
    - npm run build
    - export duration=$(( $SECONDS - $start))
    - echo "build ui = $duration"
    - export start=$SECONDS
    - npm run test
    - export duration=$(( $SECONDS - $start))
    - echo "test ui = $duration"
    - export start=$SECONDS
    - npm run deploy
    # - sls client deploy --no-confirm
    - export duration=$(( $SECONDS - $start))
    - echo "deploy ui = $duration"
    - export start=$SECONDS
    # pvep json-prod-to-db take json file that's in the source, and copy it to database
    - pvep --sync-shopify -b $GATSBY_BRAND_ID
    - export duration=$(( $SECONDS - $start))
    - echo "sync shopify products = $duration"
    - export start=$SECONDS
    - pvep --invalidate-cache
    - export duration=$(( $SECONDS - $start))
    - echo "invalidate cache = $duration"
    - cd ../..
  cache:
    key: "$CI_JOB_STAGE-$CI_COMMIT_REF_SLUG-v2"
    paths:
      - .npm/
      - .cache/
      - packages/ui/.npm/
      - packages/back-end/.npm/
      - packages/ui/.cache
      - packages/ui/public
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: http://$CI_COMMIT_REF_NAME-ui-pvep.s3-website-us-east-1.amazonaws.com/app
  needs: []

#pages:
#  stage: pages
#  script:
#    - yarn
#    - ./build.sh
#  artifacts:
#    paths:
#      - packages/ui/public
````

On it's own, it does't paint the full picture, so here's some scripts it calls:

npm run build-cli does 'rm -rf ./cli-build; npx prisma generate; tsc --build tsconfig-cli.json; npm install -g'

db-deploy.sh is: (the reason for the retries is sometimes Aurora serverless needs to wake up, if I recall correctly.

````
#!/bin/bash

#will exit if any of the commands fail
set -e

echo "db-deploy.sh: running 'npx prisma migrate deploy' to install tables"
echo "POSTGRES_USER=$POSTGRES_USER POSTGRES_SERVER=$POSTGRES_SERVER POSTGRES_PORT=$POSTGRES_PORT"
n=0
until [ "$n" -ge 5 ]
do
   npx prisma migrate deploy --preview-feature && break  # substitute your command here
   n=$((n+1))
   sleep 30
done
if [ "$n" == "5" ]; then
  echo "Migration failed after many retries"
  exit 1
fi
echo "db-deploy.sh: 'npx prisma migrate deploy' completed OK"
echo "db-deploy.sh: running 'npx prisma db seed' to install seed data"
npx prisma db seed --preview-feature
echo "db-deploy.sh: 'npx prisma db seed' completed OK"
````
