### ISSUE TITLE
Running ```npx prisma introspect``` throws access denied error

### ISSUE THREAD

**Issue by enoent4400** [prisma/prisma#6778]
## Bug description and reproduction
This is pretty basic example I used to experiment with Prisma introspect feature and to test it with existing DB. I'm running Postgres database inside Docker container with already defined schema. Existing model just creates one table like:
```CREATE TABLE users
(
    id SERIAL,
    name VARCHAR(80) NOT NULL,
    PRIMARY KEY(id)
);
```
My docker compose looks like:
```
version: "3"

services:
  pg:
    image: postgres:13
    restart: "always"
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=prisma
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - "./db/data:/var/lib/postgresql/data"
      - "./db/init:/docker-entrypoint-initdb.d"
```
After you run ```docker compose up``` you will have running DB in a container locally ready to accept connections.

Run ```npx prisma introspect```

You will get following output:

```
Prisma schema loaded from prisma/schema.prisma

Introspecting based on datasource defined in prisma/schema.prisma …
Error: P1010

User `postgres` was denied access on the database `postgres.public`
```

I tried also granting permissions to user postgres, no luck.

schema.prisma file

```
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

datasource db {
  provider = "postgresql"
  url      = "postgresql://postgres@localhost:5432/prisma"
}

generator client {
  provider = "prisma-client-js"
}
```

Running npx prisma validate is returning ok result.

## Expected behavior
It should run introspection and populate schema.prisma file. This is pretty basic example and should be pretty much covered inside the official docs.

## Environment & setup

- OS: Mac OS
- Database: PostgreSQL
- Node.js version: 14
- Prisma version: 2.21.2
```

```
