### ISSUE TITLE
Support Google Cloud Spanner

### ISSUE THREAD

**Issue by jhalborg** [prisma/prisma#717]
Hey! :) 

It would be awesome if Prisma Client could be compatible with https://cloud.google.com/spanner/

**Comment by wgottschalk** [comment]
I'd love to see Spanner supported. Now that Spanner has [granular instance sizing](https://cloud.google.com/blog/products/databases/get-more-out-of-spanner-with-granular-instance-sizing)[](https://github.com/wgottschalk) and cloud sql has mandatory downtime where Spanner doesn't, it makes it the preferred database over cloudsql.
 
Spanner is starting to rollout a postgres dialect to spanner. They mention it's not 100% compatible but it would be great have prisma add some documentation outlining limitations if any

https://cloud.google.com/spanner/docs/postgresql-interface

**Comment by janpio** [comment]
Nice.

(Note that the following does not indicate that we are committed to build a Google Spanner compatible connector any time soon. This is just me exploring and figuring out what might already work, and what does not. If Prisma will ever have this, and wants to spend more time on this, will be decided on a different level. I am just curious.)

Our next steps here would be to understand GCP enough to be able to have a Spanner instance with some schema and data in it, and enable the PostgreSQL interface. We would then try to run `npx prisma db pull` on it and see what fails (If it does not, we would probably still continue with a manually written schema of the database - starting with one table probably.) If it magically works out of the box, we would use the generated schema to send some manualy queries. If that also magically works, we could even try `migrate dev` after a small schema change to see what happens. And if _that_ also succeeds we would then start to think how to integrate a Cloud only service into our test suite - but that is quite a bit off.

So if _you_ understand GCP well, have a Spanner instance with data and the PostgreSQL interface enabled - please try these steps! (And/or send me an email at jan@prisma.io and send over the connection string, so we can do so at the side).

**Comment by glebbash** [comment]
Tried to use [PGAdapter](https://cloud.google.com/spanner/docs/pgadapter) and [Spanner Emulator](https://cloud.google.com/spanner/docs/emulator) locally with Prisma using the following docker-compose file:

```yaml
version: "3.3"
services:
  spanner:
    env_file: .env
    image: gcr.io/cloud-spanner-emulator/emulator
    ports:
      - '9010:9010'
      - '9020:9020'

  pg-adapter:
    image: gcr.io/cloud-spanner-pg-adapter/pgadapter:v0.6.1
    volumes:
      - ./test/fake-spanner-credentials.json:/acct_credentials.json
    ports:
      - 127.0.0.1:5432:5432
    command:
      - -p my_project
      - -i my_instance
      - -d my_database
      - -c /acct_credentials.json
      - -x
```

Getting this error:

```
Prisma CLI Version : 4.1.1
Error: Command failed: DATABASE_URL=cloudspanner:/projects/my_project/instances/my_instance/databases/my_database prisma migrate dev
Error: Get Config: Schema parsing - Error while interacting with query-engine-node-api library
Error code: P1012
error: Error validating datasource `db`: the URL must start with the protocol `postgresql://` or `postgres://`.
  -->  schema.prisma:6
   | 
 5 |   provider = "postgresql"
 6 |   url      = env("DATABASE_URL")
```

So the problem is that PGAdapter requires connection url to start with `cloudspanner://` while Prisma wants it to be `postgresql://`. 

Using `cloudspanner://` will error out on Prisma side.

Using `postgresql://` will error out on PGAdapter side.
