### ISSUE TITLE
Query engine binary for current platform "debian-openssl-1.1.x" could not be found.

### ISSUE THREAD

**Issue by Darren120** [prisma/prisma#7241]
### Bug description
THIS IS A TYPESCRIPT PROJECT
Docker container runs however, when using prisma client to begin querying the server crashes with the error.

```
app_1              |   Query engine binary for current platform "debian-openssl-1.1.x" could not be found.
app_1              | This probably happens, because you built Prisma Client on a different platform.
app_1              | (Prisma Client looked in "/app/node_modules/@prisma/client/runtime/query-engine-debian-openssl-1.1.x")
app_1              | 
app_1              | Searched Locations:
app_1              | 
app_1              |   /app/node_modules/.prisma/client
app_1              |   /Users/darren/Desktop/pixel-villains-cr/node_modules/@prisma/client
app_1              |   /app/node_modules/@prisma/client
app_1              |   /app/node_modules/.prisma/client
app_1              |   /app/prisma
app_1              |   /tmp/prisma-engines
app_1              |   /app/node_modules/.prisma/client
app_1              | 
app_1              | 
app_1              | To solve this problem, add the platform "debian-openssl-1.1.x" to the "binaryTargets" attribute in the "generator" block in the "schema.prisma" file:
app_1              | generator client {
app_1              |   provider      = "prisma-client-js"
app_1              |   binaryTargets = ["native"]
app_1              | }
app_1              | 
app_1              | Then run "prisma generate" for your changes to take effect.
app_1              | Read more about deploying Prisma Client: https://pris.ly/d/client-generator
app_1              |     at cb (/app/node_modules/@prisma/client/runtime/index.js:35107:17)
app_1              | (Use `node --trace-warnings ...` to show where the warning was created)
app_1              | (node:33) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
```

### How to reproduce
PRISMA SECHMA:
```
generator client {
  provider = "prisma-client-js"
  binaryTargets = ["native","debian-openssl-1.1.x"]
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model company {
  id      Int     @id
  name    String
  age     Int
  address String? @db.VarChar(50)
  salary  Float?  @db.Real
}

```
DOCKER dev file:

In my prisma/client file within node modules I have "query-engine-darwin" binary.

```
FROM node:14-slim
RUN apt-get update && apt-get install --no-install-recommends --yes openssl

WORKDIR /app/src

COPY package*.json /app



RUN npm install

COPY . /app
COPY prisma ./prisma

RUN npx prisma generate
RUN npm run build

```

DOCKER-COMPOSE
```
version: '3.8'

services: 
    app:
        build: 
            context: .
            dockerfile: DockerFile.dev
        env_file: 
            - ./.env
        volumes: 
          
             - "./src:/app/src"
             - "./nodemon.json:/app/nodemon.json"
             - "./node_modules:/app/node_modules"
        ports: 
            - 5000:3000
        depends_on: 
            - "cloud-sql-proxy"
        command: sh -c "npm run dev"
    cloud-sql-proxy:
         image: gcr.io/cloudsql-docker/gce-proxy:1.21.0
         volumes:
             - ./cloudsql_service_acct.json:/tmp/keys/keyfile.json
            
         command: /cloud_sql_proxy -instances=INSTANCE=tcp:0.0.0.0:5432 -credential_file=/tmp/keys/keyfile.json
         expose:
           - 5432
```

ERROR:
```
app_1              |   Query engine binary for current platform "debian-openssl-1.1.x" could not be found.
app_1              | This probably happens, because you built Prisma Client on a different platform.
app_1              | (Prisma Client looked in "/app/node_modules/@prisma/client/runtime/query-engine-debian-openssl-1.1.x")
app_1              | 
app_1              | Searched Locations:
app_1              | 
app_1              |   /app/node_modules/.prisma/client
app_1              |   /Users/darren/Desktop/pixel-villains-cr/node_modules/@prisma/client
app_1              |   /app/node_modules/@prisma/client
app_1              |   /app/node_modules/.prisma/client
app_1              |   /app/prisma
app_1              |   /tmp/prisma-engines
app_1              |   /app/node_modules/.prisma/client
app_1              | 
app_1              | 
app_1              | To solve this problem, add the platform "debian-openssl-1.1.x" to the "binaryTargets" attribute in the "generator" block in the "schema.prisma" file:
app_1              | generator client {
app_1              |   provider      = "prisma-client-js"
app_1              |   binaryTargets = ["native"]
app_1              | }
app_1              | 
app_1              | Then run "prisma generate" for your changes to take effect.
app_1              | Read more about deploying Prisma Client: https://pris.ly/d/client-generator
app_1              |     at cb (/app/node_modules/@prisma/client/runtime/index.js:35107:17)
app_1              | (Use `node --trace-warnings ...` to show where the warning was created)
app_1              | (node:33) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
app_1              | (node:33) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

### Prisma information

```
generator client {
  provider = "prisma-client-js"
  binaryTargets = ["native","debian-openssl-1.1.x"]
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model company {
  id      Int     @id
  name    String
  age     Int
  address String? @db.VarChar(50)
  salary  Float?  @db.Real
}

```

### Environment & setup

MAC CATLINA 10.15.7
Works in local, can read and introspect. But when testing on docker, i get the error.
I am trying to host this on cloud run.

### Prisma Version

```
prisma               : 2.23.0
@prisma/client       : 2.23.0
Current platform     : darwin
Query Engine         : query-engine adf5e8cba3daf12d456d911d72b6e9418681b28b (at node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli adf5e8cba3daf12d456d911d72b6e9418681b28b (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core adf5e8cba3daf12d456d911d72b6e9418681b28b (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt adf5e8cba3daf12d456d911d72b6e9418681b28b (at node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash : adf5e8cba3daf12d456d911d72b6e9418681b28b
Studio               : 0.393.0
```
