### ISSUE TITLE
Cluster Configuration `cluster.yml`

### ISSUE THREAD

**Issue by sorenbs** [prisma/prisma#748]
The goal of this issue is to suggest a format for the configuration of a Graphcool cluster. It specifies information like the connection to the database, the function runtime that is being used or secrets being used by the servers.

Once a cluster config has been defined it can be transformed into an executable cluster config, e.g. a Docker Compose file or an AWS CloudFormation template. This executable config can then be submitted to the cluster solution in use e.g. Docker Swarm or AWS CloudFormation. This way the configuration of a Graphcool Cluster is independent of the actual Cluster Solution in use. 

<pre>                                                       
                ┌───────────────────────┐              
                │    Cluster Config     │              
                └───────────────────────┘              
                            │ transformed into         
                            ▼                          
                 ┌────────────────────┐                
                 │                    │                
                 │ Executable Cluster │                
                 │       Config       │                
                 │                    │                
                 └────────────────────┘                
                            │submitted to              
                            ▼                          
                   ┌─────────────────┐                 
                   │Cluster Solution │                 
                   └─────────────────┘                 </pre>

The proposed YAML format looks like the following. The keys mean the following:

* `database`: 
  * `meta`: This config specifies the database the schema of a service is stored in. 
  * `data`: This database contains the actual data of services. 
* `messageQueue`: This config specifies the Message Queue being used, e.g. RabbitMQ, Amazon Kinesis on In-Memory.
* `cluster`: Cluster settings
  * `gateway`: This is DNS name under which the Graphcool API is available. It is needed so that the System API knows how to call the Simple API for example. It depends on what the system administrator has set up. In the case of the local version this would be simply localhost.
  * `clusterSecret`: This secret is used to authenticate the CLI with the System and Deploy APIs. 
* `serviceLimits`:
  * `requestsPerSecond`: max requests per second allowed per service
  * `maxNodes`: max number of nodes returned for a single relation

```
database:
  meta:
    type: mysql
    config:
      url: myhost
      port: 1234
      user: graphcool
      password: graphcool
      database: database
  data:
    type: mysql
    config:
      url: myhost
      replicaUrl: myReplicaHost
      port: 1234
      user: graphcool
      password: graphcool

cluster:
  clusterSecret: "sdjflksdfj"
  gateway: "gateway.supercorp.com"

messageQueue:
  type: rabbitmq
  config:
    url: amqp://foo:bar@bla.rmq.cloudamqp.com/quiz

limits:
  requestsPerSecond: 30
  maxNodes: 1000



```         

## Considerations

- [ ] Cloud provider configuration
