### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: User `postgres` was denied access on the database `testdb.public`

### ISSUE THREAD

**Issue by Darren120** [prisma/prisma#7682]
I am running a docker container on a separate vscode file with a simple express app to set up the cloud-sql-proxy. Looks like prisma was able to connect via 

DATABASE_URL = postgresql://username:PASS@172.20.10.3:5432/testdb

hence it gives the error of access denied. Idk why the access is being denied. I have all the keyfiles and everything set up in order to create the docker cloud sql proxy to run.

I am on my phone's hotspot wifi.

again, the error is 

```
UnhandledPromiseRejectionWarning: Error: User `postgres` was denied access on the database `testdb.public`
```

user is owner of testdb.

user has CREATE ROLE and CREATE DB privillege. 

**docker build info** 
```
Recreating cloudsqlproxy_cloud-sql-proxy_1 ... done
Recreating cloudsqlproxy_app_1             ... done
Attaching to cloudsqlproxy_cloud-sql-proxy_1, cloudsqlproxy_app_1
cloud-sql-proxy_1  | 2021/06/16 21:00:20 current FDs rlimit set to 1048576, wanted limit is 8500. Nothing to do here.
cloud-sql-proxy_1  | 2021/06/16 21:00:20 using credential file for authentication; email=docker-sql-proxy@pixel-villains-312919.iam.gserviceaccount.com
cloud-sql-proxy_1  | 2021/06/16 21:00:21 Listening on 0.0.0.0:5432 for ppp-3129:us-east1:ppp
cloud-sql-proxy_1  | 2021/06/16 21:00:21 Ready for new connections
app_1              | listening on port 3000!
```

**Comment by janpio** [comment]
This is an error message directly from the database, Prisma just uses the credentials you supplied in the connection URL.

**Comment by Darren120** [comment]
> This is an error message directly from the database, Prisma just uses the credentials you supplied in the connection URL.

Knex was able to connect no problem...

**Comment by Darren120** [comment]
> This is an error message directly from the database, Prisma just uses the credentials you supplied in the connection URL.

It works for kenex. Idk why prisma is only one giving me error. No errors in cloud logs either. hmmm

**Comment by Sytten** [comment]
Does your `password` contain non alphanumeric characters?
Is your user `postgres`?
How do you know the IP of the cloud sql proxy? Docker IPs usually change on every container spawn
Are you running your app in a docker or on the host? If on docker, is it the same docker as the cloud sql proxy?

**Comment by Darren120** [comment]
> Does your `password` contain non alphanumeric characters?
> Is your user `postgres`?
> How do you know the IP of the cloud sql proxy? Docker IPs usually change on every container spawn
> Are you running your app in a docker or on the host? If on docker, is it the same docker as the cloud sql proxy?

1. My password is literally eeeeee
2. Yes.
3. I used:
```
command: /cloud_sql_proxy -instances=game-3129:us-east1:game=tcp:0.0.0.0:5432 -credential_file=/tmp/keys/keyfile.json
```
The 0.0.0.0 is localhost, so I just copied my ip and connect.
5. I am running app on host attempting to connect to a docker that contains the sql proxy. 

HERE IS MORE INFO:

My docker project : https://imgur.com/a/Z2TVEFX

Dockerfile.dev

```
FROM node:14-slim

WORKDIR /app

COPY package*.json /app


RUN npm install

COPY . /app
```

Compose file

```
version: '3.8'

services: 
    app:
        build: 
            context: .
            dockerfile: DockerFile.dev
       
        ports: 
            - 3000:3000
        depends_on: 
            - "cloud-sql-proxy"
        command: sh -c "node ./index.js"
    cloud-sql-proxy:
         image: gcr.io/cloudsql-docker/gce-proxy:1.21.0
         volumes:
             - ./cloudsql_service_acct.json:/tmp/keys/keyfile.json
          
         command: /cloud_sql_proxy -instances=game-3129:us-east1:game=tcp:0.0.0.0:5432 -credential_file=/tmp/keys/keyfile.json
         expose:
           - 5432
```

Docker success start message

```
cloud-sql-proxy_1  | 2021/06/16 21:00:20 current FDs rlimit set to 1048576, wanted limit is 8500. Nothing to do here.
cloud-sql-proxy_1  | 2021/06/16 21:00:20 using credential file for authentication; email=docker-sql-proxy@gmae-3129.iam.gserviceaccount.com
cloud-sql-proxy_1  | 2021/06/16 21:00:21 Listening on 0.0.0.0:5432 for game-3129:us-east1:game
cloud-sql-proxy_1  | 2021/06/16 21:00:21 Ready for new connections
app_1              | Express app listening on port 3000!
```

The sql proxy says “Ready for new connections!” So I assume I set up the proxy correctly ?

Connection string for prisma

```
DATABASE_URL=postgresql://user:pass@myWifi-IP:5432/testdb?schema=public
DATABASE_URL_PROD=postgresql://user:pass@googleSql-IP:5432/testdb?schema=public
```

My WiFi IP found via system pretended-> network.

Error:

```
UnhandledPromiseRejectionWarning: Error: User `postgres` was denied access on the database `testdb.public`
```
