### ISSUE TITLE
Query Engine not found on Serverless App

### ISSUE THREAD

**Issue by lucas-a-pelegrino** [prisma/prisma#8483]
### Bug description

I'm building an application using: Serverless Framework + Yarn Workspaces + Serverless Bundle to package the lambdas;

I'm having issues with the `query engine binary`, tried a few of the solutions on the web but they didn't seem to work for my case;

`Query engine binary for current platform \"darwin\" could not be found. This probably happens, because you built Prisma Client on a different platform.`

This happens both when running `serverless-offline` or deployed to AWS...

The current state of my files are as follows:

serverless.yml
```
package:
  individually: true
  patterns:
    - '!**/node_modules/aws-sdk/**'
    - '!node_modules/.prisma/client/query-engine-*'
    - 'node_modules/.prisma/client/query-engine-rhel-*'

plugins:
  - serverless-bundle
  - serverless-plugin-monorepo
  - serverless-offline

custom:
  bundle:
    forceExclude:
      - _http_common
    packager: yarn
    packagerOptions:
      scripts:
        - yarn prisma generate

provider:
  name: aws
  runtime: nodejs14.x
```

schema.prisma
```
generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["native", "rhel-openssl-1.0.x"]
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model User {
  id        Int      @id @default(autoincrement())
  uuid      String   @unique
  email     String   @unique
  name      String?
  createdAt DateTime @default(now()) @map("created_at")
  updatedAt DateTime @default(now()) @map("updated_at")

  @@map("users")
}
```

Still wasn't able to find the cause of this behavior, if someone has bumped into this problem before and knows the solution, I would most definitely appreciate it, as I want to bring Prisma into the stack of this project but I need to get this working before I do. :)

### How to reproduce

1. Init a project using `yarn workspaces`;
2. Setup the lambdas to act as workspaces;
2. Setup Prisma for the project;
3. Add `serverless-offline`,`serverless-bundle`, `serverless-plugin-monorepo` as dev dependencies;
4. Run `sls offline` or `sls deploy` on the lambda as both behave the same way;

### Expected behavior

Prisma should work as expected, inserting/fetching data from the db;

### Prisma information

Used a simple query with `.findMany` to test the client;

```
  const users = await prisma.user.findMany({
    select: {
      uuid: true,
      email: true,
      name: true,
    },
  });
```

### Environment & setup

- OS: macOS 11.5 (20G71) / Kernel: Darwin 20.6.0
- Database: postgres (PostgreSQL) 13.3
- Node.js version: v14.17.3

### Prisma Version

```
prisma               : 2.28.0
@prisma/client       : 2.28.0
Current platform     : darwin
Query Engine         : query-engine 89facabd0366f63911d089156a7a70125bfbcd27 (at ../../../../../../../../usr/local/lib/node_modules/prisma/node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli 89facabd0366f63911d089156a7a70125bfbcd27 (at ../../../../../../../../usr/local/lib/node_modules/prisma/node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core 89facabd0366f63911d089156a7a70125bfbcd27 (at ../../../../../../../../usr/local/lib/node_modules/prisma/node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt 89facabd0366f63911d089156a7a70125bfbcd27 (at ../../../../../../../../usr/local/lib/node_modules/prisma/node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash : 89facabd0366f63911d089156a7a70125bfbcd27
Studio               : 0.417.0
```

**Comment by pantharshit00** [comment]
Hello @lucas-a-pelegrino 

Can you please share a reproduction inside of a git repo? 

Also, have a look here: https://github.com/millsp/prisma-serverless-stack. One of my team members created this example for serverless users.

**Comment by lucas-a-pelegrino** [comment]
> Hello @lucas-a-pelegrino 
> 
> 
> 
> Can you please share a reproduction inside of a git repo? 
> 
> 
> 
> Also, have a look here: https://github.com/millsp/prisma-serverless-stack. One of my team members created this example for serverless users. 

@pantharshit00 tried that solution on the repo and still no luck. ):


I've created a repo with a sample of the structure, let's hope you can track that down and help me out. 😄

https://github.com/lucas-a-pelegrino/sls-node-sample

**Comment by lucas-a-pelegrino** [comment]
cc: @pantharshit00 

Taking another look at the issue at hand and maybe this `log` might be useful?

```
Invalid `prisma.user.findMany()` invocation:


  Query engine binary for current platform "darwin" could not be found.
This probably happens, because you built Prisma Client on a different platform.
(Prisma Client looked in ".../sls-node-sample/lambdas/users/.webpack/service/query-engine-darwin")

Searched Locations:

  .../sls-node-sample/lambdas/.prisma/client
  .../sls-node-sample/node_modules/@prisma/client
  .../sls-node-sample/lambdas/users/.webpack
  .../sls-node-sample/lambdas/users/.webpack/service
  .../sls-node-sample/lambdas/users/.webpack/service
  /tmp/prisma-engines
  .../sls-node-sample/lambdas/users/.webpack/service
```

Not really familiar with `webpack` which is used by `serverless-bundle`, so I'm not sure about customizing it in a way that prevents this issue from happening.

**Comment by janpio** [comment]
Where are you testing that @lucas-a-pelegrino? `Darwin` indicates this is running on Mac, not on AWS Lambda with is a `rhel` environment.

**Comment by lucas-a-pelegrino** [comment]
> Where are you testing that @lucas-a-pelegrino? `Darwin` indicates this is running on Mac, not on AWS Lambda with is a `rhel` environment.

@janpio MacOS for local development, but it behaves the same when deployed to AWS.

**Comment by MGough** [comment]
This issue looks very similar to what we're seeing here: https://github.com/prisma/prisma/issues/8393

**Comment by lucas-a-pelegrino** [comment]
Has someone being able to replicate the issue with the repo I've provided and managed to come up with a solution? I have tried a few solutions on other issues, but although similar, they didn't actually work for me.

**Comment by bianpratama** [comment]
@lucas-a-pelegrino 

This is what I do as workaround:
- Manually copy the query engine file with serverless-bundle `copyFiles`.
- Switch between `darwin` and `rhel-openssl-1.0.x` based on serverless stage.
- I use `local` stage for developing locally using `serverless-offline`.

### Folder Structure
    .
    ├── ...
    ├── prisma
    │   └── schema.prisma
    ├── src
    ├── package.json
    ├── serverless.yml
    └── ...


### serverless.yml
```yaml
package:
  individually: true
  
 plugins:
  - serverless-bundle
  - serverless-dotenv-plugin
  - serverless-offline

custom:
  engine:
    local: 'node_modules/.prisma/client/query-engine-darwin'
    other: 'node_modules/.prisma/client/query-engine-rhel-openssl-1.0.x'
  serverless-offline:
    httpPort: 2000
    lambdaPort: 20000
    noPrependStageInUrl: true
    allowCache: true
    useWorkerThreads: true
    location: .webpack/service
  bundle:
    packager: yarn
    forceExclude:
      - '_http_common'
    copyFiles:
      - from: 'prisma/schema.prisma'
        to: './src'
      - from: ${self:custom.engine.${self:provider.stage}, self:custom.engine.other}
        to: './'
```

### package.json
```json
{
  "scripts": {
    "dev": "prisma generate && sls offline start --stage local",
    "deploy:test": "prisma generate && sls deploy --stage test",
  }
}
```
