### ISSUE TITLE
'DateTime?' does NOT create nullable field

### ISSUE THREAD

**Issue by scon-io** [prisma/prisma#9438]
### Bug description

`DateTime? @db.Timestamp` should generate `timestamp NULL DEFAULT NULL` field.
But not.

### How to reproduce

schema.prisma
```
datasource db {
  provider = "mysql"
  url      = env("DB_URL")
}

generator client {
  provider = "prisma-client-js"
}

model User {
  id       String    @id @default(uuid()) @db.VarChar(36)

  createdAt DateTime  @default(now()) @db.Timestamp
  updatedAt DateTime  @default(now()) @db.Timestamp
  deletedAt DateTime? @db.Timestamp
}
```

docker-compose.yml
```
version: "3"

services:
  db:
    image: mariadb:10.6
    restart: always
    volumes:
      - ./dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: local
      MYSQL_USER: local
      MYSQL_PASSWORD: local
      MYSQL_DATABASE: local
      TZ: Asia/Seoul
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
```

1. Run `npx prisma migrate dev --name init`
2. Check DDL for local.users with MySQL workbench

```
CREATE TABLE `User` (
  `id` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `createdAt ` timestamp NOT NULL DEFAULT current_timestamp(),
  `updatedAt ` timestamp NOT NULL DEFAULT current_timestamp(),
  `deletedAt ` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
```

### Expected behavior

DDL for local.users should be
```
CREATE TABLE `users` (
  `id` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `createdAt ` timestamp NOT NULL DEFAULT current_timestamp(),
  `updatedAt ` timestamp NOT NULL DEFAULT current_timestamp(),
  `deletedAt ` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
```

### Prisma information
```
datasource db {
  provider = "mysql"
  url      = env("DB_URL")
}

generator client {
  provider = "prisma-client-js"
}

model User {
  id       String    @id @default(uuid()) @db.VarChar(36)

  createdAt DateTime  @default(now()) @db.Timestamp
  updatedAt DateTime  @default(now()) @db.Timestamp
  deletedAt DateTime? @db.Timestamp
}
```

### Environment & setup

- OS: WSL2
- Database: MariaDB 10.6
- Node.js version: v14.17.0

### Prisma Version

```
prisma                  : 3.1.1
@prisma/client          : 3.1.1
Current platform        : debian-openssl-1.1.x
Query Engine (Node-API) : libquery-engine c22652b7e418506fab23052d569b85d3aec4883f (at node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node)
Migration Engine        : migration-engine-cli c22652b7e418506fab23052d569b85d3aec4883f (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine    : introspection-core c22652b7e418506fab23052d569b85d3aec4883f (at node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary           : prisma-fmt c22652b7e418506fab23052d569b85d3aec4883f (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Default Engines Hash    : c22652b7e418506fab23052d569b85d3aec4883f
Studio                  : 0.423.0
```
